### ISSUE TITLE
Can the libraries build for intel processors be used on AMD processor?

### ISSUE THREAD

**Issue by lithin-chandran** [oneapi-src/oneDNN#1000]
Can the libraries build for intel processors be used on AMD processor ?
Do we need to  build the libraries separately for AMD processors or can we use the same libraries which were built for intel?

**Comment by vpirogov** [comment]
Hi @lithin-chandran,

Modern Intel and AMD processors are based on the same [X86-64](https://en.wikipedia.org/wiki/X86-64) architecture and are highly compatible. There are differences in supported instruction set extensions similar to these between different generations of Intel processors. Compilers have flags to manage which ISA specific optimizations to use ([gcc](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html), [clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#x86)).

oneDNN default build [supports processors](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html) that have at least Intel SSE4.1 support and will run on pretty much any Intel or AMD processor produced in the last 10 years. oneDNN also detects ISA in runtime and dispatches the most optimized implementation available.
