### ISSUE TITLE
Correct spelling of AVX-VNNI

### ISSUE THREAD

**Issue by rscohn2** [oneapi-src/oneDNN#1004]
https://oneapi-src.github.io/oneDNN/dev_guide_cpu_dispatcher_control.html

It's AVX-VNNI, not AVX2-VNNI according to @markcharney

The env variable should accept both spellings, but just document the correct one.

**Comment by louie-tsai** [comment]
@vpirogov 
Should we have a PR to change the name from AVX2-VNNI to AVX-VNNI?

**Comment by vpirogov** [comment]
The name of this variable indicates that dispatched codepath will use Intel AVX2 instructions and VNNI instructions, so the name looks correct to me as it is. I understand that the proper name of VNNI ISA extension used in this case is AVX-VNNI, but this it not fully descriptive of actual codepath used.

**Comment by rscohn2** [comment]
Agreed. Thanks for the explanation.
