### ISSUE TITLE
How to compile Tensorflow using a custom-built oneDNN

### ISSUE THREAD

**Issue by rahulbera** [oneapi-src/oneDNN#1012]
I want to build Tensorflow v2.4.0 using a custom-build oneDNN. I have made some changes in the oneDNN verbose log, that I want to be printed while running TF model using DNNL_VERBOSE=2.

I have tried out setting TF_MKL_ROOT environment variable to supply the path of the custom-build oneDNN to bazel. But apparently, TF still downloaded oneDNN and got compiled against the downloaded version.

## System tested
* OS: Ubuntu 18.04.5
* GCC: 9.3.0
* Tensorflow: 2.4.0
* oneDNN: 1.6.4 
* bazel: 3.1.0
* Compilation flags: `--config=mkl -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mavx512f --copt=-mavx512cd`

**Comment by vpirogov** [comment]
Tagging @louie-tsai, @agramesh1.

**Comment by mgouicem** [comment]
Hi @rahulbera , you can try to use the [new_local_repository rule ](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository) in bazel.

You can for example change [these lines ](https://github.com/tensorflow/tensorflow/blob/583814b2d7c63e879d4a80c080f409c163ee793a/tensorflow/workspace2.bzl#L168-L177) into
```
native.new_local_repository(
    name = "mkl_dnn_v1",
    build_file = "//third_party/mkl_dnn:mkldnn_v1.BUILD",
    path = "path/to/your/local/oneDNN/source"
)
```

**Comment by rahulbera** [comment]
Hi @mgouicem, thanks for the pointer. It is working.
