### ISSUE TITLE
test_benchdnn_self_ci_cpu failure

### ISSUE THREAD

**Issue by nSircombe** [oneapi-src/oneDNN#1014]
# Summary
The master branch fails CI for both x86 and AArch64 builds.
The first failing commit is: https://github.com/oneapi-src/oneDNN/commit/1fc180396201e3fcd0cd244700e4150c14c92e93

# Version
oneDNN Master at https://github.com/oneapi-src/oneDNN/commit/80884f8c38b979d22454a059650dbe601ca69cb8

# Environment
Observed with:
- x86_64 (Intel Xeon E5-2407 v2)
-- RHEL  7.6.1810 
-- GCC 9.2
-- cmake 2.8.12.2
- AArch64 (Neoverse N1)
-- RHEL 8.3.2011
-- GCC 8.3.1
-- cmake 3.11.4

# Steps to reproduce
To reproduce:
```
git checkout 1fc180396201e3fcd0cd244700e4150c14c92e93
mkdir -p build
cd build
cmake -DDNNL_BUILD_FOR_CI=ON ../. && make -j 16
ctest -R test_benchdnn_self_ci_cpu  --verbose
```

# Observed behavior
```
113: @@@ error [int self::check_tags():258]: 'init_md(&md_from_str, ndims, dims, dnnl_f32, str_tag)' -> 1
1/1 Test #113: test_benchdnn_self_ci_cpu ........***Failed    0.02 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
	113 - test_benchdnn_self_ci_cpu (Failed)
Errors while running CTest
```

# Expected behaviour
`ctest` suite should pass without error.

**Comment by vpirogov** [comment]
Thank you for the analysis, @nSircombe. The defect reproduces in our internal valdiation as well.

**Comment by nSircombe** [comment]
Hi @vpirogov - thanks for confirming, I thought that might be the case.

**Comment by nSircombe** [comment]
@vamironov - just to confirm, our pipelines have all gone green again, thanks for your help.
