### ISSUE TITLE
Which software component should handle the addition of zero-padding to convolution tensors?

### ISSUE THREAD

**Issue by alexandrelimassantana** [oneapi-src/oneDNN#1016]
Hello,

I am building a custom direct convolution primitive.
Currently, I am handling the case where the SIMD length does not divide the feature map channel dimension, which is resolved by adding zero-padding.
However, it is unclear to me whether I should ask for a padded memory descriptor through the primitive descriptor, or add padding inside the execution method itself.
The developer's guide pages, [Understanding Memory Format](https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html), states the following.

> The actual zero-padding of oneDNN memory objects happen inside the primitive execution functions in order to minimize its performance impact. The current convention is that a primitive execution can assume its inputs are properly zero padded, and should guarantee its outputs are properly zero padded. If a user implements custom kernels on oneDNN blocked memory objects, then they should respect this convention. In particular, element-wise operations that are implemented in the user's code and directly operate on oneDNN blocked layout like this:
> ```c++
> for (int e = 0; e < phys_size; ++e)
>     x[e] = eltwise_op(x[e])
> ```
> are not safe if the data is padded with zeros and eltwise_op(0) != 0.

My question is, at which point do existing convolutions implementations add/request zero-padding?

**Comment by mgouicem** [comment]
Hi @alexandrelimassantana . The answer is both :-). 

You can "ask" for a padded memory **descriptor** by setting the default format in the init function. You can find an example [here](https://github.com/oneapi-src/oneDNN/blob/80884f8c38b979d22454a059650dbe601ca69cb8/src/cpu/x64/jit_avx512_core_bf16_1x1_convolution.hpp#L136-L144)). This will create an appropriate memory descriptor with the padded_dims field properly filled.

Now for the actual memory content and its padded area, you can find more details in this [RFC](https://github.com/oneapi-src/oneDNN/tree/rfcs/rfcs/20201119-change-memory-init-behavior#option-1-move-destination-zero-padding-to-primitive-execution-preferred) (the currently adopted behavior is option 1). In short, you can assume that the padded area of your inputs contains zero, and you have to ensure that the padded area of the output of your primitive contains zeros. This can happen in three ways:
- your computation propagates the zero from your inputs to your output naturally. This is typically the case for GEMM/Convolution
- your computation does not propagate zeros from inputs. In this case, you have to explicitely put zeros in the padded area of the outputs in your kernel.
- you kernel does not write zeros to the outputs padded area. You can simply call a kernel to zero pad(example [here](https://github.com/oneapi-src/oneDNN/blob/38283b3b2bdbaac169adf8e99b0e26c88dafc7d7/src/cpu/x64/jit_brgemm_conv.cpp#L591))

**Comment by alexandrelimassantana** [comment]
Thanks @mgouicem, this explanation was exactly what I was looking for!
