### ISSUE TITLE
Validation for Linux aarch64 conda-forge package fails with a segfault for oneDNN v2.1.2

### ISSUE THREAD

**Issue by vpirogov** [oneapi-src/oneDNN#1017]
# Summary
oneDNN packages were recently added to conda-forge. An attempt to validate a package for Linux/aarch64 configuration results in segfault in `cpu-cnn-inference-f32-cpp` test.

# Version
oneDNN v2.1.2

# Environment
* OS: CentOS 7
* Runtimes:
  * DNNL_CPU_RUNTIME=TBB
  * DNNL_GPU_RUNTIME=NONE

See also [Drone CI logs](https://cloud.drone.io/conda-forge/onednn-feedstock/1/1/2).

# Steps to reproduce
See [Drone CI logs](https://cloud.drone.io/conda-forge/onednn-feedstock/1/1/2).

# Observed behavior
```
                            Start   3: cpu-cnn-inference-f32-cpp
1168	  3/104 Test   #3: cpu-cnn-inference-f32-cpp .........................***Exception: SegFault  9.10 sec
```

**Comment by vpirogov** [comment]
@nSircombe, does this issue looks like something your team will be able to help with?

**Comment by igorsafo** [comment]
The build fails for oneDNN v2.2 as well

**Comment by nSircombe** [comment]
Hi @vpirogov,
I can take a look, but I've not looked at Conda packaging for oneDNN - it doesn't look like the failure should be specific to that though?
We don't build with `DNNL_CPU_RUNTIME=TBB`, I'm not sure if this is part of the problem - is there a reason for choosing TBB over OMP for these builds?

**Comment by vpirogov** [comment]
I would expect the issue to be reproducible with TBB threading in regular builds for Arm as well. The conda forge packages were created with TBB threading as this is the configuration that is important for the contributor who created these. We plan to extend support with other configurations supported by oneDNN as well.

**Comment by nSircombe** [comment]
Hi @vpirogov,

Sorry for the slow response, this slipped off my to-do list. I'm able to reproduce the failure with `DNNL_CPU_RUNTIME=TBB` builds, an a number of other segfaults including `test_eltwise` and `test_batch_normalization`.

We're not at present testing, or supporting, builds with TBB - we'll have to decide if this is something we can / should cover.

**Comment by vpirogov** [comment]
Thanks for investigation, @nSircombe! Keeping this defect open in case someone wants to jump in.

**Comment by vpirogov** [comment]
We recently found [a known limitation](https://github.com/oneapi-src/oneTBB/blob/master/RELEASE_NOTES.md#rotating_light-known-limitations) related to TBB that lead to crashes under ctest:

> oneTBB does not support fork(), to work-around the issue, consider using task_scheduler_handle to join oneTBB worker threads before using fork().


This is address in benchdnn, gtests and examples by the following changeset: b8ffe4847ea2cc190174bae869a2003917be144f, b8ffe4847ea2cc190174bae869a2003917be144f, fd4f76b19ebc5c0c785aada82e88a7634da37e3c, a2a4b5ec89db18fed9ad47745b2527d54baff2a3, c700a7dd132cb21d04d5cc790860f51e655f75a4, 2ea6ecc3c32099c5dc1128fd11203322ad7a711a.
