### ISSUE TITLE
Difference between jit_avx512_common_1x1_convolution and jit_avx512_common_convolution?

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [oneapi-src/oneDNN#1018]
Is there a high-level explanation of the difference between jit_avx512_common_1x1_convolution and jit_avx512_common_convolution? I can tell when the kw and kh equal to 1, mkl will use the jit_avx512_common_1x1_convolution implementation. It will be also helpful if you can point some tutorials/papers on the two algorithms. Thanks!

**Comment by mgouicem** [comment]
Hi @LiuXiaoxuanPKU , you got it exactly right.
The main difference between the two is that for 1x1 convolutions (so filter spatial size is 1), there is less data reuse (it looks more like a matrix multiplication), hence the implementation is a little different to accommodate for that.
[This paper](https://arxiv.org/pdf/1808.05567.pdf) slightly talks about that in section II.C. 

@kwiersch @nshustrov @ankalinin Would you know of any more thorough reference.

**Comment by kwiersch** [comment]
I am not aware of any good reference for the algorithms used in jit_avx512_common_1x1_convolution and jit_avx512_common_convolution, but as Mourad mentioned the main difference between the two implementations is that the 1x1 version is specialized to the case of 1x1 filters (ie kh = kw = 1). A few comments:

- For strided 1x1 convolutions, the needed parts of the src tensor are copied to a buffer, then that is used as the input to a non-strided 1x1 convolution
- For non-1x1 convolutions, so-called logical padding is used (ie, when the filter falls within the padded region, no calculation is needed, so we can skip those cases and save some work)
- For both, we unroll by spatial rows (often represented by the variable `ur` or `ur_w`)
- For both, we also unroll by output channel blocks (often called `nb_oc_blocking`). In general, we want the product `ur` * `nb_oc_blocking` to be as large as possible to optimize the amount of compute in a set of (vector) registers w.r.t. the amount of reads/writes to/from those registers.

Also, maybe [this answer to an earlier question](https://github.com/oneapi-src/oneDNN/issues/833#issuecomment-689124947) might be of use here.

**Comment by vpirogov** [comment]
Closing as the question is addressed.
