### ISSUE TITLE
quantization/reorder f32->u8 much slower than s8

### ISSUE THREAD

**Issue by rosspleban** [oneapi-src/oneDNN#1026]
# Summary
I see a large difference in execution time for a reorder primitive to convert f32 -> u8 or s8.  Is the disparity expected?

This is the initial reorder of the network that feeds into a convolution primitive.

reorder to u8: 0.583984
reorder to s8: 0.0078125

# Version
```
dnnl_verbose,info,oneDNN v2.1.0 (commit 1a15624e805f6ed113175480e6a88bcaa949cbc7)
dnnl_verbose,info,cpu,runtime:sequential
dnnl_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost
```

# Environment
The test program was run with 50 iterations through the network.

```
Linux 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

# Observed behavior
f32 -> u8:
```
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_u8::blocked:acdb:f0,oscale:0:43.6907;zero_points:'dst:0:129';,,1x6x2x640,0.583984
```

f32 -> s8:
```
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_s8::blocked:acdb:f0,oscale:0:43.6907;,,1x6x2x640,0.0078125
```

# Expected behavior
Difference of execution time not almost 2 orders of magnitude

**Comment by igorsafo** [comment]
Hi @rosspleban ,
The reason is that jit implementation of reorder doesn't support zero points. We are aware of this issue and have an internal feature request.

While the performance of reorder f32 -> u8 + zero points is sub-optimal there is an alternative way for implementing similar functionality: binary primitive with algorithm `binary_mul` and post-operation binary with algorithm `binary_add`. 
The only restriction is that zero points are float numbers in case of binary primitive.
Here is a modified binary example:
```cpp
#include <algorithm>
#include <cmath>
#include <iostream>
#include <string>
#include <vector>

#include "example_utils.hpp"
#include "oneapi/dnnl/dnnl.hpp"

using namespace dnnl;

using tag = memory::format_tag;
using dt = memory::data_type;

void binary_example(dnnl::engine::kind engine_kind) {

    // Create execution dnnl::engine.
    dnnl::engine engine(engine_kind, 0);

    // Create dnnl::stream.
    dnnl::stream engine_stream(engine);

    // Tensor dimensions.
    const memory::dim N = 3, // batch size
            IC = 3, // channels
            IH = 150, // tensor height
            IW = 150; // tensor width

    // Source (src) and destination (dst) tensors dimensions.
    memory::dims src_dims = {N, IC, IH, IW};

    // Allocate buffers.
    std::vector<float> src_data(product(src_dims));

    // Initialize src.
    std::generate(src_data.begin(), src_data.end(), []() {
        static int i = 0;
        return std::cos(i++ / 10.f);
    });

    // Create src and dst memory descriptors.
    auto src_md = memory::desc(src_dims, dt::f32, tag::nchw);
    auto scales_md = memory::desc({1, 1, 1, 1}, dt::f32, tag::nchw);
    auto zero_points_md = memory::desc({1, 1, 1, 1}, dt::f32, tag::nchw);
    auto dst_md = memory::desc(src_dims, dt::f32, tag::nchw);

    // Create src memory objects.
    auto src_mem = memory(src_md, engine);

    float user_scale = 2.0f;
    float user_zero_point = 25.0f;
    auto scales_mem = memory(scales_md, engine, &user_scale);
    auto zero_points_mem = memory(zero_points_md, engine, &user_zero_point);

    // Write data to memory object's handle.
    write_to_dnnl_memory(src_data.data(), src_mem);

    // Create operation descriptor.
    auto binary_d
            = binary::desc(algorithm::binary_mul, src_md, scales_md, dst_md);

    // Create primitive post-ops.
    post_ops binary_ops;
    binary_ops.append_binary(algorithm::binary_add, zero_points_md);
    primitive_attr binary_attr;
    binary_attr.set_post_ops(binary_ops);

    // Create primitive descriptor.
    auto binary_pd = binary::primitive_desc(binary_d, binary_attr, engine);

    // Create the primitive.
    auto binary_prim = binary(binary_pd);

    // Primitive arguments. Set up in-place execution by assigning src as DST.
    std::unordered_map<int, memory> binary_args;
    binary_args.insert({DNNL_ARG_SRC_0, src_mem});
    binary_args.insert({DNNL_ARG_SRC_1, scales_mem});
    binary_args.insert(
            {DNNL_ARG_ATTR_MULTIPLE_POST_OP(0) | DNNL_ARG_SRC_1, zero_points_mem});
    binary_args.insert({DNNL_ARG_DST, src_mem});

    // Primitive execution: binary with ReLU.
    binary_prim.execute(engine_stream, binary_args);

    // Wait for the computation to finalize.
    engine_stream.wait();

    // Read data from memory object's handle.
    read_from_dnnl_memory(src_data.data(), src_mem);
}

int main(int argc, char **argv) {
    return handle_example_errors(binary_example, parse_engine_kind(argc, argv));
}
```

Regards,
Igor Safonov

**Comment by rosspleban** [comment]
Thanks for the speedy and helpful response.  A couple followup questions:

1. Where should the clamp to u8 happen?
    a. Can the dst of binary be u8 or will it clamp too early in the primitive?
    b. Follow binary with reorder to clamp u8 and possibly change memory layout for convolution.

2. What is the dequantize u8 approach?  binary_add with a multiply post op ?

Thanks!

**Comment by igorsafo** [comment]
> Where should the clamp to u8 happen?
> a. Can the dst of binary be u8 or will it clamp too early in the primitive?

Yes, dst of binary can be u8. Clamping and rounding of dst values happens after all post ops, so it works fine.

>b. Follow binary with reorder to clamp u8 and possibly change memory layout for convolution.

Clamping can be done directly in binary primitive. Changing memory layout can be also done in binary operation, however it is not recommended due to performance implications, on the other side reorder is optimized for changing layouts, so it might be beneficial to change layout in a standalone reorder u8->u8.

>What is the dequantize u8 approach? binary_add with a multiply post op ?

Correct, until we have optimized reorder with zero points support. Another option to dequantize is to do it directly in a primitive. For example, binary_add and binary_mul can be 2 post-operations to some primitive, for example, convolution.
```cpp
    // Create primitive post-ops.
    post_ops conv_ops;
    conv_ops.append_binary(algorithm::binary_add, zero_points_md);
    conv_ops.append_binary(algorithm::binary_mul, scales_md);
    primitive_attr conv_attr;
    conv_attr.set_post_ops(conv_ops);

    ...

    conv_args.insert(
            {DNNL_ARG_ATTR_MULTIPLE_POST_OP(0) | DNNL_ARG_SRC_1, zero_points_mem});
    conv_args.insert(
            {DNNL_ARG_ATTR_MULTIPLE_POST_OP(1) | DNNL_ARG_SRC_1, scales_mem});

    ...
```

Regards,
Igor Safonov

**Comment by rosspleban** [comment]
Awesome.  Appreciate the help.
