### ISSUE TITLE
oneDNN speedup with ARM Compute Library?

### ISSUE THREAD

**Issue by kuldeepx** [oneapi-src/oneDNN#1027]
How much speed up should we expect by compiling it with ARM Compute Library?

**Comment by mgouicem** [comment]
@nSircombe @alenik01 , would you have some data to share?

**Comment by alenik01** [comment]
@mgouicem, before answering this question we have to check which results are under NDA and which can be shared. Also what should be considered as a baseline when measuring speedup?

**Comment by vpirogov** [comment]
@alenik01,

I think the question here is how faster oneDNN will be if you build it with ACL in comparison no-ACL baseline on the same system.

**Comment by vpirogov** [comment]
Looks like the only option is to do actual measurement. You can use [benchdnn](https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn#readme), oneDNN's comprehensive performance validation tool.
