### ISSUE TITLE
How to debug if core dump in code generated by JIT?

### ISSUE THREAD

**Issue by dazuozcy** [oneapi-src/oneDNN#1028]
If the core dump appears in the traditional code, I can use gdb to debug and analyze the call stack, but how to debug when core dumps in the code generated by the JIT?
For example, once line 1744 is executed, it will core dump, but I cannot step into with gdb(even with gdb command `step`).
![image](https://user-images.githubusercontent.com/4265418/114644517-3f2bc900-9d0a-11eb-80d0-f041dbf00dae.png)

**Comment by mgouicem** [comment]
Hi @dazuozcy , you can typically use gdb to step through instructions  (see stepi [here](https://sourceware.org/gdb/current/onlinedocs/gdb/Continuing-and-Stepping.html#Continuing-and-Stepping)).
When stepping in instructions, you can also print the assembly instructions that are being executed and the next ones with `x/10i $pc`.

**Comment by dazuozcy** [comment]
> Hi @dazuozcy , you can typically use gdb to step through instructions (see stepi [here](https://sourceware.org/gdb/current/onlinedocs/gdb/Continuing-and-Stepping.html#Continuing-and-Stepping)).
> When stepping in instructions, you can also print the assembly instructions that are being executed and the next ones with `x/10i $pc`.
> 
> Edit: if you have BTW, TUI enabled in your GDB, you can also use `layout asm` to see the assembly code.

**Comment by dazuozcy** [comment]
thanks very much ：）
