### ISSUE TITLE
Since the AMX support is not merged into Linux kernel, how can we profiling the performance of AMX in oneDNN?

### ISSUE THREAD

**Issue by zqcawzs** [oneapi-src/oneDNN#1039]
Hi,

I am curious about the performance of the AMX which will be added in the next generation Xeon processor and happy to see the oneDNN already provides some support of AMX. However, I found the AMX support patch hasn't been merged into Linux kernel yet. So is there anyway I can run the AMX feature in oneDNN right now? By Intel Software development emulator?

Thanks.

**Comment by vpirogov** [comment]
Hi @zqcawzs,

You can use [Intel SDE](https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator.html) with `-spr` option to execute oneDNN codepath relying on Intel AMX. Intel SDE is a functional emulation tool, so it will not provide you with performance information.

Note, that Intel AMX codepath currently is not dispatched by default in oneDNN and you'll also need to set an environment variable [`DNNL_MAX_CPU_ISA=AVX512_CORE_AMX`](https://oneapi-src.github.io/oneDNN/dev_guide_cpu_dispatcher_control.html).

**Comment by zqcawzs** [comment]
> Hi @zqcawzs,
> 
> You can use [Intel SDE](https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator.html) with `-spr` option to execute oneDNN codepath relying on Intel AMX. Intel SDE is a functional emulation tool, so it will not provide you with performance information.
> 
> Note, that Intel AMX codepath currently is not dispatched by default in oneDNN and you'll also need to set an environment variable [`DNNL_MAX_CPU_ISA=AVX512_CORE_AMX`](https://oneapi-src.github.io/oneDNN/dev_guide_cpu_dispatcher_control.html).

Thanks for your reply! One more question, have you ever test oneDNN on SPR platform? If yes, some clue about the performance improvements?

**Comment by vpirogov** [comment]
We use engineering samples for performance validation and optimizations. Unforutnately there's not public data at this point that I can share. Keep an eye on the annoucements :)

**Comment by zqcawzs** [comment]
> We use engineering samples for performance validation and optimizations. Unforutnately there's not public data at this point that I can share. Keep an eye on the annoucements :)

That's alright. Thanks a lot.
