### ISSUE TITLE
int8 conv optimize method or idea in avx2 platform

### ISSUE THREAD

**Issue by Daniel-NJ** [oneapi-src/oneDNN#1043]
i want to optimize jit_uni_x8s8s32x_conv_kernel.cpp in AMD platform， dose have some idea can share with the direct-conv optimize，thanks！

**Comment by mgouicem** [comment]
Hi @Daniel-NJ, could you clarify how much more performance are you expecting, or what kind of performance gap you are observing?
The current `jit_uni_x8s8s32_conv_kernel`  should work on AMD platform by using avx2 instructions. The avx2 instructions for int8 computations will generally yield much lower performance than using [avx512_VNNI](https://en.wikichip.org/wiki/x86/avx512_vnni) instructions though.

**Comment by Daniel-NJ** [comment]
Hi @mgouicem
i compute the theory gflops of my machine
the main instructions are  vpmaddubsw, vpmaddwd and vpaddd. And I test the latency of that three instructions is 2.56 cycles.
in 2GHz，the theory max gflops is  2*4*8 / (2.56*0.5*10^-9) = 46.3gflops

i choose some inputs, the result are below,  we can see that when ic or oc are  large(ic>=10 oc >=10), the gflops are above 30gflops, about 65% of theory gflops, this seems ok. but when ic or oc are small, this template is not good.

Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,jit_uni_int8:avx2,"01",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic3ih224oc16oh224kh3ph1n"01",0.0430944,0,1.29395,33.3047,1.29623,33.246
perf,cpu,jit_uni_int8:avx2,"02",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic3ih1080iw1920oc32oh540ow960kh3kw3sh2sw2ph1pw1n"02",0.894931,0,26.395,33.9053,26.5024,33.7679
perf,cpu,jit_uni_int8:avx2,"03",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic32ih270iw480oc64oh270ow480kh3kw3ph1pw1n"03",4.75916,0,102.901,46.2499,102.912,46.2448
perf,cpu,jit_uni_int8:avx2,"04",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic48ih270iw480oc64oh270ow480kh3kw3ph1pw1n"04",7.13874,0,154.105,46.3238,154.126,46.3175
perf,cpu,jit_uni_int8:avx2,"05",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic3ih299oc10oh149kh3sh2ph1n"05",0.011935,0,0.600586,19.8722,0.603321,19.7821
perf,cpu,jit_uni_int8:avx2,"06",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic10ih149oc19oh147kh3ph0n"06",0.0739028,0,2.47681,29.8379,2.47947,29.8058
perf,cpu,jit_uni_int8:avx2,"07",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic19ih147oc60oh147kh3ph1n"07",0.439404,0,10.9114,40.2703,10.9217,40.232
perf,cpu,jit_uni_int8:avx2,"08",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic19ih147oc65oh73kh3sh2ph1n"08",0.117384,0,3.05103,38.4737,3.05315,38.4469
perf,cpu,jit_uni_int8:avx2,"09",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic3ih384iw512oc64oh192ow256kh3kw3sh2sw2ph1pw1n"09",0.169354,0,5.15015,32.8833,5.1617,32.8097
perf,cpu,jit_uni_int8:avx2,"10",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic16ih96iw128oc32oh96ow128kh3kw3ph1pw1n"10",0.111874,0,2.44019,45.8465,2.44209,45.8108
perf,cpu,jit_uni_int8:avx2,"11",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic64ih135iw240oc80oh135ow240kh3kw3ph1pw1n"11",2.96298,0,64.0034,46.2942,64.0514,46.2595
perf,cpu,jit_uni_int8:avx2,"12",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic64ih135iw240oc144oh135ow240kh3kw3ph1pw1n"12",5.33337,0,115.811,46.0526,115.839,46.0412
perf,cpu,jit_uni_int8:avx2,"13",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic3ih96iw128oc64oh48ow64kh3kw3sh2sw2ph1pw1n"13",0.0104882,0,0.324951,32.2762,0.326795,32.0941

**Comment by mgouicem** [comment]
Hi @Daniel-NJ . From the log you share, I see two instances where average Gflops is below 30Gflops:
```
perf,cpu,jit_uni_int8:avx2,"06",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic10ih149oc19oh147kh3ph0n"06",0.0739028,0,2.47681,29.8379,2.47947,29.8058
perf,cpu,jit_uni_int8:avx2,"05",--conv --skip-impl="ref:gemm" --dir=FWD_I --cfg=u8s8f32 mb1ic3ih299oc10oh149kh3sh2ph1n"05",0.011935,0,0.600586,19.8722,0.603321,19.7821
```

Here are three elements that can impact the performance for those cases:
- For both cases, OC is not a multiple of the register width, so extra computation is needed for tail handling (either spurious computations with zero padding or proper tail handling).
- For both cases, the accumulation chain (`ic * kh * kw`) is rather small (90 for the first, 27 for the second). This means that the initial latency of loading weights/data (~40-50 cycles from L3) is not negligible overall.
- On top of the two above, the second case is a strided convolution (sh=sw=2). That requires to actually load the data, pack it so it is non strided in registers, and then compute the multiply-add sequence of instructions. This adds additional overhead.

Summoning @kwiersch @alokbakshi in case I am missing something else.

**Comment by kwiersch** [comment]
I agree with @mgouicem, the slower shapes are less compute-intense and have significant OC tails, so lower performance is to be expected.

**Comment by alokbakshi** [comment]
Hi @Daniel-NJ I think you can also do performance testing for `--cfg=u8s8s8` or `--cfg=s8s8s8` to make a comparison with maximum possible gflops.

**Comment by Daniel-NJ** [comment]
Hi @mgouicem, agree with first two cases, thanks a lot~
