### ISSUE TITLE
Transition to Sphinx/Breathe generated documentation to align with other OneAPI project documentation 

### ISSUE THREAD

**Issue by intelkevinputnam** [oneapi-src/oneDNN#1046]
# Summary
Move away from Doxygen output to Sphinx/Breathe to align with other
OneAPI projects and enable publishing to IDZ.

# URLs
- https://github.com/oneapi-src/oneDNN/blob/master/doc/Doxyfile.in
- https://github.com/oneapi-src/oneDNN/tree/master/doc

# Additional details
@jedippold and I will submit multiple PRs referencing this issue in roughly
 this order:
1. Update to ``doc/Doxyfile.in`` to enable generating XML output in addition
   to HTML until transition is complete.
2. Addition of ``.rst`` files for each of the ``.md`` files in the ``doc`` directory (``.md`` files
   can be removed after the transition is complete).
3. Addition of Sphinx support files (``conf.py``, ``index.rst``, ``requirements.txt``)
   in the ``doc`` directory.
4. Addition of custom Python scripts for pre-processing the Doxygen XML to
   mimic current API structure in Sphinx (``parse_doxygen_index.py`` and
   ``replace_string.py``). Each will be its own PR with an explanation of what is doing.
5. We could use some help once we are ready to deploy to GitHub pages.

**Comment by vpirogov** [comment]
@intelkevinputnam,

Typically we expect a PR to include an incremental piece of useful functionality, so that the change can be tested. With that I believe these changes should go as a single PR, unless there are reasons for this split that I don't see.

**Comment by intelkevinputnam** [comment]
@vpirogov That's fine if that is what you'd prefer.

**Comment by jedippold** [comment]
Our thought was that separate PRs might mitigate risk in the event of issues with some of the files, but that may have been an overabundance of caution. ;-)

**Comment by vpirogov** [comment]
@jedippold,

It may be reasonable to split larger PRs into several smaller ones to simplify review. If you choose to do so please make sure that every PR introduces a self-contained set of useful behaviors that can be validated. The #1047 does not seem to meet this criteria, as it adds output to Doxygen generator that is not used anywhere.

**Comment by intelkevinputnam** [comment]
I closed the original PR and submitted #1048, which includes all of the infrastructure needed to generate the Sphinx HTML locally.

**Comment by vpirogov** [comment]
Updated theme is merged into master and [deployed at Github pages](https://oneapi-src.github.io/oneDNN).
