### ISSUE TITLE
dump the jit kernel，cannot understand what this kernel‘s  function? 

### ISSUE THREAD

**Issue by Daniel-NJ** [oneapi-src/oneDNN#1052]
./benchdnn --engine=cpu --mode=p --conv --batch=inputs/conv/resnet50
 
generator these there bin file, what  dose the second one do? 
dnnl_dump_cpu_jit_avx2_conv_fwd_kernel_f32.0.bin
dnnl_dump_cpu_jit_single_blk_kernel.1.bin
dnnl_dump_cpu_jit_uni_reorder_kernel_f32.2.bin

**Comment by mgouicem** [comment]
Hi @Daniel-NJ , this is a particular kernel for [reorder](https://github.com/oneapi-src/oneDNN/blob/5ea99f5cfc70a60e003fb6274a92b93e7db75920/src/cpu/x64/jit_uni_reorder.cpp#L992).
