### ISSUE TITLE
AMD performance?

### ISSUE THREAD

**Issue by cowwoc** [oneapi-src/oneDNN#1056]
Following up on https://github.com/tensorflow/tensorflow/issues/49113 and https://github.com/oneapi-src/oneDNN/issues/1000 am I correct in assuming that the vast majority of this codebase will run the same optimizations on both Intel and AMD CPUs? Or will any optimizations get skipped unless an Intel CPU is detected?

**Comment by vpirogov** [comment]
Hi @cowwoc, 

On x86-64 platforms oneDNN detects processor instruction set (ISA) using `cpuid` instruction at runtime and dispatches the best available codepath based on this information. AMD with Intel AVX2 instruction set support will run Intel AVX2 codepath. You can find implmementation of the dispatching mechanism in [`mayiuse`](https://github.com/oneapi-src/oneDNN/blob/a9dc485dd11f554654fb75789830e5b8887021c4/src/cpu/x64/cpu_isa_traits.hpp#L285) function.

**Comment by cowwoc** [comment]
Nice. Thank you.
