### ISSUE TITLE
Example project "cnn-inference-f32-cpp" crashed on HD 630

### ISSUE THREAD

**Issue by laoniangjiu** [oneapi-src/oneDNN#1066]
# Summary
I tried to run the example project "cnn-inference-f32-cpp" on device Intel HD Graphics  630 with driver "23.20.16.4973", but it crashed when create primitive("dnnl_primitive_create"). The engine kind was set to "gpu".

# Version
oneDNN version: 2.2.2

# Environment
* CPU: i7-7700
* OS version: 20H2
* GPU: Intel HD Graphics  630
* GPU Driver Version: 23.20.16.4973

# Steps to reproduce
Set the engine kind to gpu, and run the example on this device with this version of driver.
 
# Observed behavior
Crash happened when create primitive.

**Comment by mgouicem** [comment]
Hi @laoniangjiu , thanks for the report.
To reproduce and debug the issue we need to know how the library was built or through which channel you downloaded the binary package.
We also would need a reproducer on how you ran the example, as your environment setup before running the example can impact the behavior of the run.

**Comment by laoniangjiu** [comment]
Hi @mgouicem ,I downloaded the binary package from the page [v2.2.2](https://github.com/oneapi-src/oneDNN/releases/tag/v2.2.2). And built the library follow the [developer guide](https://oneapi-src.github.io/oneDNN/dev_guide_build.html) with Visual Studio 2019, replaced the cmake cmd with "cmake -G "Visual Studio 16 2019" -A x64". And I also ran the example with Visual Studio2019 and only changed the engine kind to gpu.

**Comment by vpirogov** [comment]
@laoniangjiu,

By default oneDNN builds without GPU support. You need to set CMake option [`DNNL_GPU_RUNTIME=OCL`](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html) to enable it. Without GPU support oneDNN examples will throw an exception 'cannot create engine' when you try to execute them on GPU.

**Comment by laoniangjiu** [comment]
@vpirogov , I had enabled this option. And the exception threw was not 'cannot create engine'. Also the examples worked well on other device with different driver used the same library I built.

**Comment by vpirogov** [comment]
@laoniangjiu, the driver you cite is rather old, the latest version being 27.20.100.9466. If you still see the issues with the latest driver please provide specific command lines you are using to build and run the test, and output logs.

**Comment by vpirogov** [comment]
Closind due to lack of activity. Feel free to reopen with new data.
