### ISSUE TITLE
 According to what formula is tanh primitive implemented in aarch64 ？

### ISSUE THREAD

**Issue by gititgo** [oneapi-src/oneDNN#1067]
In the analysis of aarch64's JIT primitive tanh （in eltwise）, it is found that it is very complex and can't understand how to calculate. I can not understand the principle of calculating tanh with arm assembly.  Can we give tanh formula for floating point number ？

**Comment by kawakami-k** [comment]
At the moment, AArch64's JIT implementation of tanh (in eltwise) is almost as same as that for AVX512 implemented in `x64/injectors/jit_uni_eltwise_injector.cpp`. I hope the comment will help you understand (https://github.com/oneapi-src/oneDNN/blob/ed2f38147a5e79a03cb083f3749fc2cdd62dcfba/src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp#L512).

**Comment by kawakami-k** [comment]
If you want an approximation to the second order, there is an implementation in the repository that Fujitsu is forking.
https://github.com/fujitsu/oneDNN/blob/fj_rls-v2.1/src/cpu/aarch64/injectors/jit_uni_eltwise_injector.cpp#L450-L475

**Comment by gititgo** [comment]
Thanks.
