### ISSUE TITLE
Query: Latest convolution_direct also works with NHWC directly?

### ISSUE THREAD

**Issue by avinashcpandey** [oneapi-src/oneDNN#1068]
Hi,

I am using MKLDNN since sometime with TensorFlow. I see with TF1.15, for best performance NHWC buffer gets reordered to nChw8c and then convolution get performed. which I understand.  
Now I see with TF2.5, no reorder is being used, directly convolution is performed on NHWC buffer. I don't see any reorder for I/p buffers. MKLDNN_VERBOSE says this

**dnnl_verbose,exec,cpu,convolution,jit:avx2,forward_training,src_f32::blocked:acdb:f0 wei_f32::blocked:Acdb8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:acdb:f0,post_ops:'eltwise_relu;';,alg:convolution_direct,mb640_ic3oc64_ih224oh112kh7sh2dh0ph3_iw224ow112kw7sw2dw0pw3,126.77**

I have few question:
1.  What does  "blocked:acdb" means here? acbd is NHWC, what is the meaning of blocked here
2.  If convolution is directly performed on NHWC buffer, will it be optimal like last version?
3.  Or is it like, though src buffer is NHWC, internally it will read as blocked and convolution will be performance, instead of having separate reorder (which causes memory operation.)   

Thanks in Advance!!

**Comment by mgouicem** [comment]
Hi @avinashcpandey !
1. `blocked:acdb` means that the data is in NHWC layout here. The blocked refers to the [format kind](https://github.com/oneapi-src/oneDNN/blob/e93203a3be65838955430fe72a8cf01c2e38cf95/include/oneapi/dnnl/dnnl_types.h#L94) used in the [memory descriptor](https://github.com/oneapi-src/oneDNN/blob/e93203a3be65838955430fe72a8cf01c2e38cf95/include/oneapi/dnnl/dnnl_types.h#L1591)
2. Most of our optimizations currently target NHWC activations and "optimally blocked" weights. Technically, there is a slight overhead of manipulating NHWC vs "optimally blocked" activations. Even though this overhead could be measurable at the primitive level (though small in practice), using nhwc directly allows to remove the overheads of reordering activations and the topology level. So application-level performance should be better overall.
3.  Yes internally, we can either directly work on the NHWC data, or sometimes we have to reorder small blocks of activations in a "local scratchpad", and then use the best instructions available to compute on those blocks.

**Comment by avinashcpandey** [comment]
Thanks @mgouicem for the prompt reply!!

**Comment by mgouicem** [comment]
I am closing this issue since your questions seem answered. If you have follow up questions, feel free to reopen, or open a new issue. Thanks!

**Comment by avinashcpandey** [comment]
Hi @mgouicem 

I am running some experiments with NHWC, NCHW and Blocked format. 
For all three cases, I was expecting similar performance. #1 and #2 is matching, but #3 is taking 2x time.
For #3 Am I using the right tag for weight buffer to get the optimal performance? I see its calls GEMM based implementation. For NCHW, DNNL doesn't have convolution_direct implementation?

**Blocked Format::**  i/p, weight and dst all are blocked format 
dnnl_verbose,exec,cpu,convolution,jit:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,,alg:convolution_direct,mb1_ic480oc64_ih224oh109kh7sh2dh0ph0_iw224ow109kw7sw2dw0pw0,**21.1208**

**NHWC format::**  i/p is NHWC, weights in blocked and dst in NHWC
dnnl_verbose,exec,cpu,convolution,jit:avx2,forward_inference,src_f32::blocked:acdb:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:acdb:f0,,alg:convolution_direct,mb1_ic480oc64_ih224oh109kh7sh2dh0ph0_iw224ow109kw7sw2dw0pw0,**23.0579**

**NCHW Format::**  i/p is NCHW, weights in blocked and dst is NCHW
dnnl_verbose,exec,cpu,convolution,gemm:jit,forward_inference,src_f32::blocked:abcd:f0 wei_f32::blocked:abcd:f0 bia_f32::blocked:a:f0 dst_f32::blocked:abcd:f0,,alg:convolution_direct,mb1_ic480oc64_ih224oh109kh7sh2dh0ph0_iw224ow109kw7sw2dw0pw0,**53.345**9

**Comment by mgouicem** [comment]
Hi @avinashcpandey. This is to be expected.
Out of the 3, blocked format is the fastest, closely followed by NHWC. NCHW is generally much slower.

If you look at the dispatched implementations, blocked and NHWC can leverage a direct convolution implementations (jit:avx2). This is because having C (or a block of C) as inner dimension allows efficient vectorization.

However, we have to use a gemm based implementation for NCHW which involves an internal data transformation. This transformation is necessary to efficiently vectorize the computation in the case of NCHW.
