### ISSUE TITLE
Does DNNL support cross-compiling

### ISSUE THREAD

**Issue by laoniangjiu** [oneapi-src/oneDNN#1071]
Hi, I tried to build DNNL library for AArch64 on x86 platform. I changed the DNNL_TARGET_ARCH to  AARCH64, and run the cmake command "cmake -G "Visual Studio 16 2019" -A ARM64 ..". The solution and project file was generated successfully. But when I build the project in virtual studio 2019, there are many errors appeared. Does DNNL support be compiled and run on arm cpu with windows system?

**Comment by nSircombe** [comment]
Hi @laoniangjiu 

Thanks for your interest in oneDNN on AArch64 - at present, we're only targeting Linux builds, so there's currently no support for Windows.

**Comment by laoniangjiu** [comment]
Got it, Thanks.
