### ISSUE TITLE
logs of benchdnn show that MatMul and IP do not support postops like mul, add, relu...

### ISSUE THREAD

**Issue by wenhuanh** [oneapi-src/oneDNN#1073]
# Summary
When add postops to MatMul and inner produce and run benchdnn, logs show that MatMul and IP didn't support postop like mul, add and relu.

# Version
dnnl_verbose,info,oneDNN v2.3.0 (commit 748528a2d3204b5f401c14a9aacdec16accd5ead)

# Environment
* CPU make and model: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
* OS version:  4.18.0-193.28.1.el8_2.x86_64
* Compiler version: gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
* CMake version: 3.20.2
* git hash: 748528a2d3204b5f401c14a9aacdec16accd5ead

# Steps to reproduce
1. `OMP_NUM_THREADS=1 numactl -N 1 -l ./benchdnn --matmul --bia_dt=f32 --bia_mask=2 20x50:50x30 --attr-post-ops=mul:f32+add:f32+relu:6`
2. `OMP_NUM_THREADS=1 numactl -N 1 -l ./benchdnn --ip --dir=FWD_B --cfg=f32 mb20_ic50_oc30 --attr-post-ops=mul:f32+add:f32+relu:6`

# Observed behavior
1. command 1 shows:

> dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,,,20x50:50x30:20x30,29.436

2. command 2 shows:

> dnnl_verbose,exec,cpu,inner_product,brgemm:avx512_core,forward_training,src_f32::blocked:ab:f0 wei_f32:p:blocked:AB16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb20ic50oc30,0.026123

Neither of outputs show postops. 

# Expected behavior
When run conv with benchdnn, postops would show by logs while MatMul and ip are not. We wonder that whether Matmul and IP support these postops?

$ `DNNL_VERBOSE=1 DNNL_VERBOSE=1 OMP_NUM_THREADS=1 numactl -N 1 -l ./benchdnn --conv --attr-post-ops=add:f32+mul:f32+relu:6 ic16oc16ih4oh4kh1ph0`

> dnnl_verbose,exec,cpu,convolution,jit_1x1:avx512_common,forward_training,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,attr-post-ops:binary_add:f32:0+binary_mul:f32:0+eltwise_relu:6 ,alg:convolution_direct,mb2_ic16oc16_ih4oh4kh1sh1dh0ph0_iw4ow4kw1sw1dw0pw0,0.0141602

**Comment by vpirogov** [comment]
Hi @wenhuanh,

benchdnn is a state machine, so arguments order is important. The lines in issue description have shape signature (`20x50:50x30`) followed by post-ops knob (`--attr-post-ops=mul:f32+add:f32+relu:6`), which results in the test being executed without the post-ops. Moving the shape signature to the end of the command line results in expected behavior:
```
$ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --bia_mask=2 --attr-post-ops=mul:f32+add:f32+relu:6 20x50:50x30             
dnnl_verbose,info,oneDNN v2.3.0 (commit 748528a2d3204b5f401c14a9aacdec16accd5ead)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX2
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,20x50,0.0681152
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,50x30,0.013916
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,20x30,0.0129395
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,1x30,0.0151367
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,1x1,0.0180664
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,1x1,0.013916
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:binary_mul:f32:0+binary_add:f32:0+eltwise_relu:6 ,,20x50:50x30:20x30,29.5891
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,20x30,0.0170898
0:PASSED __REPRO: --matmul --bia_dt=f32 --attr-post-ops=mul:f32+add:f32+relu:6 20x50:50x30:20x30
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0

$ DNNL_VERBOSE=1 ./benchdnn --ip --dir=FWD_B --cfg=f32 --attr-post-ops=mul:f32+add:f32+relu:6 mb20_ic50_oc30                  
dnnl_verbose,info,oneDNN v2.3.0 (commit 748528a2d3204b5f401c14a9aacdec16accd5ead)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX2
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,1x1,4.27393
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,1x1,2.75513
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,20x50,0.0129395
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ba:f0,,,30x50,2.03784
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:a:f0 dst_f32::blocked:a:f0,,,30,1.92212
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,20x30,0.0131836
dnnl_verbose,exec,cpu,inner_product,gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ba:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,attr-post-ops:binary_mul:f32:0+binary_add:f32:0+eltwise_relu:6 ,,mb20ic50oc30,29.7319
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,20x30,1.97095
0:PASSED __REPRO: --ip --attr-post-ops=mul:f32+add:f32+relu:6 mb20ic50oc30
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
```

Hope this helps.

**Comment by wenhuanh** [comment]
Thanks for your kind answering!
