### ISSUE TITLE
A question about performance_profiling.cpp

### ISSUE THREAD

**Issue by leizheng1** [oneapi-src/oneDNN#1074]
performance_profiling.cpp shows how to accelerate conv + relu, and I write a program to accelerate matmul + relu using the same method, and the result is correct but shows bad performance.

My matmul+relu output: (Implementation tag is ref:any)
```
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:ba:f0 dst_f32::blocked:ab:f0,,,41x19,0.000976562
dnnl_verbose,exec,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask3 dst_f32::blocked:ab:f0,post_ops:'eltwise_bounded_relu:6;';,,15x41:41x19:15x19,0.253906
```   

Example conv+relu output: (Implementation tag is brgconv:avx512_core)
```
dnnl_verbose,exec,cpu,convolution,brgconv:avx512_core,forward_inference,src_f32::blocked:acdb:f0 wei_f32::blocked:Acdb48a:f0 bia_undef::undef::f0 dst_f32::blocked:acdb:f0,attr-post-ops:eltwise_relu ,alg:convolution_direct,mb128_ic3oc96_ih227oh55kh11sh4dh0ph0_iw227ow55kw11sw4dw0pw0,167.871
```

And my question is if I write a bad program or the optimization (such as conv + relu in the example) is supported backend and others (such as matmul + relu) cannot use this method to optimize. And how I can know which operations combination can be optimized using this method.

**Comment by vpirogov** [comment]
Hi @leizheng1,

Post-ops are supported for matmul primitive and expected to be faster than a combination of matmul and eltwise function. What I see from your verbose log is that matmul run reference implementation (`ref:any`) for your case, as optimized implementation does not support 2D bias (`f0_mask3`). Is there a specific reason you need 2D bias?

2D bias results in reference implementation:
```
$ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --bia_mask=3 15x41:41x19:15x19
dnnl_verbose,info,oneDNN v2.3.0 (commit df09bb832e2c1498c61d98e59998c159bbb40abd)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost
dnnl_verbose,info,gpu,runtime:none
<snip>
dnnl_verbose,exec,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask3 dst_f32::blocked:ab:f0,,,15x41:41x19:15x19,0.139893
<snip>
$ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --bia_mask=3 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19
<snip>
dnnl_verbose,exec,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask3 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,0.138916
<snip>
```

1D bias results in JIT implementation:
```
$ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 15x41:41x19:15x19
<snip>
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,,,15x41:41x19:15x19,41.9641
<snip>
$ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19
<snip>
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,40.4431
<snip>
```

**Comment by leizheng1** [comment]
Thanks for your help, but when I revised the dimension of bias from 2-D to 1-D, there will be an error in creating the matmul descriptor, and here is my implementation of adding a bias. 
```
//1-D will cause error
auto user_bias = memory({{n}, memory::data_type::f32,
                                   memory::format_tag::a},
            eng); 
//2-D will not cause error
//auto user_bias = memory({{m, n}, memory::data_type::f32,
//                                   memory::format_tag::ab},
//            eng);
init_data(user_bias, 0.1);
auto mat_bias_md = memory::desc(user_bias.get_desc());
auto mat_d = matmul::desc(
            mat_src_md, mat_wei_md,
            mat_bias_md, mat_dst_md); //Error happends here
```
Is there anything wrong when I creating the matmul descriptor with bias?

**Comment by vpirogov** [comment]
Bias is required to have the same number of dimensions as tensor, so for your case the shape should be {1,n}. See an [example for matmul](https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/matmul.cpp).

**Comment by leizheng1** [comment]
Yes, it really works, thank you so much and I still have a stupid question, where can I find the difference between implementation ref:any and brgemm:AVX512_core?

**Comment by changqi1** [comment]
@vpirogov  we know brgemm:AVX512_core to use avx512 instructions, but what instructions does the gemm:jit use ?

**Comment by changqi1** [comment]
> Hi @leizheng1,
> 
> Post-ops are supported for matmul primitive and expected to be faster than a combination of matmul and eltwise function. What I see from your verbose log is that matmul run reference implementation (`ref:any`) for your case, as optimized implementation does not support 2D bias (`f0_mask3`). Is there a specific reason you need 2D bias?
> 
> 2D bias results in reference implementation:
> 
> ```
> $ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --bia_mask=3 15x41:41x19:15x19
> dnnl_verbose,info,oneDNN v2.3.0 (commit df09bb832e2c1498c61d98e59998c159bbb40abd)
> dnnl_verbose,info,cpu,runtime:OpenMP
> dnnl_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost
> dnnl_verbose,info,gpu,runtime:none
> <snip>
> dnnl_verbose,exec,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask3 dst_f32::blocked:ab:f0,,,15x41:41x19:15x19,0.139893
> <snip>
> $ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --bia_mask=3 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19
> <snip>
> dnnl_verbose,exec,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask3 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,0.138916
> <snip>
> ```
> 
> 1D bias results in JIT implementation:
> 
> ```
> $ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 15x41:41x19:15x19
> <snip>
> dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,,,15x41:41x19:15x19,41.9641
> <snip>
> $ DNNL_VERBOSE=1 ./benchdnn --matmul --bia_dt=f32 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19
> <snip>
> dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,40.4431
> <snip>
> ```
why is the ref:any perf better than gemm:jit perf (0.138916 vs. 40.4431) ? 
The gemm:jit should use avx instructions and the ref:any only use pure cpu.

**Comment by vpirogov** [comment]
> Yes, it really works, thank you so much and I still have a stupid question, where can I find the reference about the difference between implementation ref:any and brgemm:AVX512_core?

This is a good question and it's not covered in the documentation. oneDNN has multiple implementations for every function targeting specific instruction sets (Intel AVX2, Intel AVX512, Intel DL Boost) and sometimes specific classes of problems (for instance, convolution filter size, or convolution with 3 input channels). The faster implementation is dispatched in runtime based on the processsor capabilities and problem parameters. 

Reference implementation (`ref:any`) is very general C implementation designed to support all classess of functions and all processors. As it's not specialized for particular processor it's the slowest implementation available, but the most general one. You can find reference implementation for convolution is in [cpu/ref_convolution.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_convolution.cpp).

BRGEMM-based convolution for Intel AVX512 instruction set (`brgemm:AVX512_core`) is a specialized implementation of direct convolution algorithm for processors with Intel AVX512 instruction set support. As it's specialized for particular ISA it performs significantly better. You can find this implementation in [src/cpu/x64/jit_bregemm_conv.hpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_brgemm_conv.cpp).

**Comment by vpirogov** [comment]
> @vpirogov we know brgemm:AVX512_core to use avx512 instructions, but what instructions does the gemm:jit use ?

@changqi1, `gemm:jit` dispatches the best available GEMM implementation based on processor capabilities. For processors with Intel AVX512 ISA support it will use Intel AVX512 instructions.

**Comment by vpirogov** [comment]
> why is the ref:any perf better than gemm:jit perf (0.138916 vs. 40.4431) ?
> The gemm:jit should use avx instructions and the ref:any only use pure cpu.

The problem size used in the example is tiny (15x41 by 41x19) and the run is not [configured for performance](https://oneapi-src.github.io/oneDNN/dev_guide_performance_settings.html). In this case I believe optimized implementation is trying hard to utilize all the cores across two sockets in the system. See the results from benchmark run below.

GEMM:
```
$ OMP_NUM_THREADS=1 ./benchdnn --matmul --mode=P --bia_dt=f32 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19                             
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,gemm:jit,,--matmul --mode=P --bia_dt=f32 --attr-post-ops=bounded_relu:6 15x41:41x19:15x19,2.337e-05,0,0.00170898,13.6748,0.00229664,10.1757
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):0.00170898 avg(ms):0.00229664
```

Reference:
```
$ OMP_NUM_THREADS=1 ./benchdnn --matmul --mode=P --bia_dt=f32 --bia_mask=3 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19                
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,ref:any,,--matmul --mode=P --bia_dt=f32 --bia_mask=3 --attr-post-ops=bounded_relu:6 15x41:41x19:15x19,2.337e-05,0,0.280273,0.0833829,0.282135,0.0828328
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):0.280273 avg(ms):0.282135
```

**Comment by leizheng1** [comment]
> > why is the ref:any perf better than gemm:jit perf (0.138916 vs. 40.4431) ?
> > The gemm:jit should use avx instructions and the ref:any only use pure cpu.
> 
> The problem size used in the example is tiny (15x41 by 41x19) and the run is not [configured for performance](https://oneapi-src.github.io/oneDNN/dev_guide_performance_settings.html). In this case I believe optimized implementation is trying hard to utilize all the cores across two sockets in the system. See the results from benchmark run below.
> 
> GEMM:
> 
> ```
> $ OMP_NUM_THREADS=1 ./benchdnn --matmul --mode=P --bia_dt=f32 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19                             
> Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
> perf,cpu,gemm:jit,,--matmul --mode=P --bia_dt=f32 --attr-post-ops=bounded_relu:6 15x41:41x19:15x19,2.337e-05,0,0.00170898,13.6748,0.00229664,10.1757
> tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
> total perf: min(ms):0.00170898 avg(ms):0.00229664
> ```
> 
> Reference:
> 
> ```
> $ OMP_NUM_THREADS=1 ./benchdnn --matmul --mode=P --bia_dt=f32 --bia_mask=3 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19                
> Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
> perf,cpu,ref:any,,--matmul --mode=P --bia_dt=f32 --bia_mask=3 --attr-post-ops=bounded_relu:6 15x41:41x19:15x19,2.337e-05,0,0.280273,0.0833829,0.282135,0.0828328
> tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
> total perf: min(ms):0.280273 avg(ms):0.282135
> ```

The result shows the avg(ms) of gemm:jit is 0.00229664, but the first time to run it will be costly. So you mean this is caused by optimized implementation's trying hard to utilize all the cores across two sockets in the system, is that right?

```
$ OMP_NUM_THREADS=1 ./benchdnn --matmul --mode=P --bia_dt=f32 --attr-post-ops=eltwise_bounded_relu:6 15x41:41x19:15x19
dnnl_verbose,info,oneDNN v2.3.0 (commit 748528a2d3204b5f401c14a9aacdec16accd5ead)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost and bfloat16 support
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,15x41,0.00195312
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,41x19,0.000976562
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,15x19,0
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,1x19,0
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,30.731
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,0.00512695
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,0.000976562
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,0.000976562
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0_mask2 dst_f32::blocked:ab:f0,attr-post-ops:eltwise_bounded_relu:6 ,,15x41:41x19:15x19,0.00195312
...
```

**Comment by vpirogov** [comment]
@leizheng1, this is good observation. Unlike other oneDNN primitives GEMM generates compute kernels during the first call resulting in significantly slower first run. Kernel generation will move to initialization stage once we move this code path to BRGEMM-based implementation.

**Comment by changqi1** [comment]
> @leizheng1, this is good observation. Unlike other oneDNN primitives GEMM generates compute kernels during the first call resulting in significantly slower first run. Kernel generation will move to initialization stage once we move this code path to BRGEMM-based implementation.

@vpirogov Thanks for you reply.  And what is the difference between BRGEMM implementation and GEMM implementation ?

**Comment by igorsafo** [comment]
Hi @changqi1 , They use different approaches for computing matmul operation. GEMM-based implementation calls single GEMM (if batch size is 1). On the other side BRGEMM (Batch-Reduce Matrix Multiplication) is a highly-optimized micro-kernel which is used as a building block and will be called multiple times.
Please refer the following article for more details about BRGEMM: [High-Performance Deep Learning via a Single Building Block](https://arxiv.org/pdf/1906.06440.pdf).
