### ISSUE TITLE
input and weight transform in winograd 4x3

### ISSUE THREAD

**Issue by llxingkongxia** [oneapi-src/oneDNN#1076]
In file jit_avx512_core_f32_wino_conv_4x3.cpp. [input_transform_data()](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_4x3.cpp#L168), I don't understand why G_size = 9, The values of G are as follows:
```
float G[] = {-2.25f, -0.390625f, 0.87890625f, -2.640625f, 0.625f, -0.625f,
           1.5f, -1.5f, -2.640625f};
```
not
```
float G[] = { 4.0f, 0.0f, -5.0f, 0.0f, 1.0f, 0.0f ,
                   0.0f,-4.0f, -4.0f, 1.0f, 1.0f, 0.0f,
                   0.0f, 4.0f, -4.0f,-1.0f, 1.0f, 0.0f,
                   0.0f,-2.0f, -1.0f, 2.0f, 1.0f, 0.0f,
                   0.0f, 2.0f, -1.0f,-2.0f, 1.0f, 0.0f,
                   0.0f, 4.0f,  0.0f,-5.0f, 0.0f, 1.0f };
```
Similarly, in [weight_transform_data](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_4x3.cpp#L46), G is 
``` 
float G[] = {0.26890756302521f, 0.688403361344538f, 0.119514472455649f,
            1.13777777777778f, 0.430252100840336f, 0.179271708683473f};
```
instead of 
```
float G[] = {1.0f/4,     0.0f,    0.0f,
                 -1.0f/6,  -1.0f/6, -1.0f/6,
                 -1.0f/6,   1.0f/6, -1.0f/6,
                  1.0f/24,  1.0f/12,  1.0f/6,
                 1.0f/24, -1.0f/12,  1.0f/6,
                 0.0f,     0.0f,    1.0f};
```

**Comment by densamoilov** [comment]
@kwiersch, can you please help with this question?

**Comment by kwiersch** [comment]
@llxingkongxia I am not exactly sure how these values are obtained, but I believe that when used in the transform kernels (see [here for weight](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_4x3_kernel.cpp#L397) and [here for input](https://github.com/oneapi-src/oneDNN/blob/89fbae89d0f0960c3822c08404f491260e37f95e/src/cpu/x64/jit_avx512_core_f32_wino_conv_4x3_kernel.cpp#L882) transform kernels), they have the same effect but with fewer operations.

**Comment by llxingkongxia** [comment]
Hi @kwiersch , may be more operations. 
in input transforms generate code,  for alpha=6 times , each fma4 have 1mult and 1add, in total, 6 * 12 = 72fma. but the original operations is much smaller.  
``` 
        for (int i = 0; i < alpha; i++) {
            for (int idx = 0; idx < alpha; idx++) {
                vmovups(zmm_I(idx), ...)
            }

            fma4(zmm_t(0), zmm_I(2), zmm_G(0), zmm_I(4));
            fma4(zmm_t(1), zmm_I(1), zmm_G(0), zmm_I(3));
            fma4(zmm_t(2), zmm_I(2), zmm_G(1), zmm_I(4));
            fma4(zmm_t(3), zmm_I(1), zmm_G(1), zmm_I(3));
            fma4(zmm_t(4), zmm_I(0), zmm_G(2), zmm_I(4));
            fma4(zmm_t(5), zmm_I(1), zmm_G(2), zmm_I(5));

            fma4(zmm_T(0), zmm_I(2), zmm_G(3), zmm_t(4));
            fma4(zmm_T(1), zmm_t(1), zmm_G(4), zmm_t(0));
            fma4(zmm_T(2), zmm_t(1), zmm_G(5), zmm_t(0));
            fma4(zmm_T(3), zmm_t(3), zmm_G(6), zmm_t(2));
            fma4(zmm_T(4), zmm_t(3), zmm_G(7), zmm_t(2));
            fma4(zmm_T(5), zmm_I(3), zmm_G(8), zmm_t(5));

            for (int idx = 0; idx < alpha; idx++) {
                vmovups(..., zmm_T(idx));
            }
        }
```

**Comment by llxingkongxia** [comment]
maybe toom-cook algorighm, G, B, A can be transform to new matrix.

**Comment by llxingkongxia** [comment]
https://github.com/oneapi-src/oneDNN/commit/5da3e356, The parameters are used to improve numerical accuracy. but these parameters don't look the best. In [paper](https://arxiv.org/pdf/1803.10986.pdf), polynomial interpolation points = {0,-1,1,1/2,-2} is the best for F(4,3). In oneDNN code, polynomial interpolation points = {0,-0.625,0.625,1.5,-1.5}, we can get matrix  A B G  from [tool](https://github.com/andravin/wincnn), and get the parameters as follow:
![image](https://user-images.githubusercontent.com/14210127/120949786-dbf16c80-c777-11eb-8825-c70b5ac1a1ce.png)
The same with oneDNN.
BT = float G[] = {-2.25f, -0.390625f, 0.87890625f, -2.640625f, 0.625f, -0.625f,  1.5f, -1.5f, -2.640625f}; //input transform
AT = float G[] = {0.625f, 1.5f, 0.390625f, 2.25f, 0.244140625f, 3.375f};  //output transform
G  = float G[] = {0.26890756302521f, 0.688403361344538f, 0.119514472455649f,
            1.13777777777778f, 0.430252100840336f, 0.179271708683473f};  //weight transform

**Comment by kwiersch** [comment]
@mgouicem Maybe you can shed some light on the above. Do you know why the Winograd transform parameters were changed in [5da3e35](https://github.com/oneapi-src/oneDNN/commit/5da3e356)? The commit message says "improve numerical accuracy" but it would be nice to know how that was determined.

**Comment by mgouicem** [comment]
@llxingkongxia got it right! We used the script provided by the original authors of the Winograd convolution algorithm to get transform matrices with better condition number. Though I don't remember what was the reasoning behind choosing those specific points, sorry.
