### ISSUE TITLE
Visualizing the net

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1077]
Hi,
Is there any function to visualize the network layers using this library (or just print the layers information)?

**Comment by densamoilov** [comment]
Hi @kokhazade, oneDNN doesn't provide ant tool to visualize a model but you can run oneDNN with enabled [verbose mode](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html) to get information about layers.

**Comment by kokhazade** [comment]
Thank you @densamoilov

**Comment by kokhazade** [comment]
@densamoilov, does the library contain any feature or function to get operations count and parameters count information?can I get these information in verbose mode?

**Comment by densamoilov** [comment]
@kokhazade , can you please give an example of the information you are trying to get? What are the operation and parameters counts?

**Comment by kokhazade** [comment]
Hi @densamoilov,
I attached a text file that gives the information I asked but using TensorFlow. Now I want to get these information via your library.
First part of attached file gives the number of floating point operations that will take place in the network. For example the answer for multiplying two matrices with dimension of 2*2 and floating point data type is 12 operation. As you do quantization for int8 data type, probably some middle operations will be added for int8 data type.
Second part returns the number of trainable parameters like weights and bias for each layer
[Code.txt](https://github.com/oneapi-src/oneDNN/files/6602209/Code.txt)

.
Third part gives a summary of network including layers and information related to each layer.

**Comment by louie-tsai** [comment]
@kokhazade 

We have a parser tool to get the operations count, JIT kernels count and also algorithm counts in below link.
https://github.com/oneapi-src/oneAPI-samples/tree/master/Libraries/oneDNN/tutorials/profiling

Here are some snapshots of the results from the parser.
![image](https://user-images.githubusercontent.com/21761437/122094973-a248e300-cdc1-11eb-9fd2-1a59aa2fe969.png)

![image](https://user-images.githubusercontent.com/21761437/122095027-b391ef80-cdc1-11eb-95aa-672a54be4605.png)

![image](https://user-images.githubusercontent.com/21761437/122095061-be4c8480-cdc1-11eb-9eea-f799d6ff382a.png)

Does it meet your need?

**Comment by miladdona** [comment]
Hi @louie-tsai ,
Thanks for the response. It's a very good tool. Just one point, As you mentioned in your response I need to get "**the operations count**" like FLOPs. But graphs show time percentage. Is it possible to get counts instead of time in `ondnn.breakdown` function? And, how can I use this function? Should I call it at the end of my application code?

**Comment by kokhazade** [comment]
Hi @louie-tsai ,
Thanks for your response. It's a very good tool. Just one point, as you mentioned in your response I need to get "**operations count**" like **FLOPs** but graphs show time percentage. Is it possible to use operation count instead of time in calling `onednn.breakdown` function? And how could I use this function? Should I call it at the end of my application code?

**Comment by louie-tsai** [comment]
Hi @kokhazade 
yes. you can look into operations count instead by changing input argument from "time" to "count".


`       

        from profiling.profile_utils import oneDNNLog  
        log = oneDNNLog()  
        log.load_log(**FILE_PATH**)  
        log.exec_data['count'] = log.exec_data['time'].astype(float)  
        onednn.breakdown(log.exec_data,"type","count")  
        onednn.breakdown(log.exec_data,"jit","count")
  `

You should be get below count bar charts instead.
Let us know whether it works for you or not.

![typeCount Breakdown](https://user-images.githubusercontent.com/21761437/123722328-039a9880-d83d-11eb-8610-574e5b8b517c.png)


![jitCount Breakdown](https://user-images.githubusercontent.com/21761437/123722345-09907980-d83d-11eb-9800-b4838216d6c9.png)

**Comment by vpirogov** [comment]
Closing as the question is addressed.
