### ISSUE TITLE
I want to transfer pytorch source code to c++, how do I use onednn? Is there a specific process?

### ISSUE THREAD

**Issue by Deep-learning999** [oneapi-src/oneDNN#1087]
For example, I want to transfer the pytorch source code and model of yolov5 to oneapi. How to implement the specific operation steps?

**Comment by igorsafo** [comment]
Hi @Deep-learning999 ,
oneDNN is a library which contains highly-optimized building blocks for DNNs. Comparing to frameworks like PyTorch it is pretty low-level (an example of convolution implemented using oneDNN [takes ](https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/convolution.cpp) around 200 lines of C++ code comparing to a single line of Python code in PyTorch) and contains only part of core functionality you might need to implement and deploy DNNs so the rest should be implemented on the application side. For example, oneDNN doesn't provide SGD functionality which is typically used on training, but it provides basic building block as binary primitive which can be used to implement SGD on application/framework side. Another example is oneDNN doesn't contain any functionality related to model conversion/creation from model description formats like ONNX. On the other side implementing a model using oneDNN directly allows user to have much more control over execution and memory management which might result in better end performance comparing to frameworks.

P. S. If your concern is performance of yolov5 in PyTorch on Intel CPU you might want to look into [Intel Extensions for PyTorch (IPEX)](https://software.intel.com/content/www/us/en/develop/articles/getting-started-with-intel-optimization-of-pytorch.html). This is an extension to PyTorch focused on performance on Intel processors and it uses oneDNN inside.

P. P. S. If your concern is Python interface there is a [C++ interface in PyTorch](https://pytorch.org/cppdocs/), however I don't know how complete it is comparing to the Python interface.

Regards,
Igor Safonov

**Comment by Deep-learning999** [comment]
Understood, thank you for your answer
