### ISSUE TITLE
The result of nchw_pooling is not correct when calculating max pooling in some case

### ISSUE THREAD

**Issue by NaNAGISaSA** [oneapi-src/oneDNN#1094]
# Steps to reproduce

- construct following pooling primitive_desc:

```c++
    int batch_size = 1, input_height = 2, input_weight = 2, input_channel = 1;
    int stride = 2, kernel = 2, height_padding = 1, weight_padding = 1;
    int output_height = (input_height - kernel + 2 * height_padding) / stride + 1;
    int output_weight = (input_weight - kernel + 2 * weight_padding) / stride + 1;

    auto pooling_prim_desc = dnnl::pooling_forward::primitive_desc(
        {dnnl::prop_kind::forward_inference,
         dnnl::algorithm::pooling_max,
         dnnl::memory::desc({batch_size, input_channel, input_height, input_weight},
                            dnnl::memory::data_type::f32,
                            dnnl::memory::format_tag::nchw),
         dnnl::memory::desc({batch_size, input_channel, output_height, output_weight},
                            dnnl::memory::data_type::f32,
                            dnnl::memory::format_tag::nchw),
         {stride, stride},
         {kernel, kernel},
         {height_padding, weight_padding},
         {height_padding, weight_padding}},
        engine);
```
- elements for input: `{-1.0F, -1.0F, -1.0F, -1.0F}`, so the padding matrix will be:

```c++
0 0 0 0
0 -1.0 -1.0 0
0 -1.0 -1.0 0
0 0 0 0
```

- execute the max pooling op above, you will get final result: `{-1.0F, -1.0F, -1.0F, -1.0F}`, which is not correct.

# Debug

I think this bug is from here:

https://github.com/oneapi-src/oneDNN/blob/65f9a23f8efc68bdd8e61a545352fae414ae8a87/src/cpu/nchw_pooling.cpp#L96-L98

the `continue` statement causes zero elements from padding are not compared with the elements in the input, which causes the wrong result above.

**Comment by dzarukin** [comment]
Hi @NaNAGISaSA, thank you for your sighting. Could you share, please, what do you expect to get as an output? With such input parameters, output values seem correct to me.

**Comment by NaNAGISaSA** [comment]
Hi @dzarukin, at first I think the output will be `0.0F, 0.0F, 0.0F, 0.0F` and the padding elements should be used to compare with the input elements. 
After you reply, I also tired this example in TensorFlow, and I know that the padding zeros should not be used when doing max, my understanding about max pooling is wrong.
I will close this issue. Thank you for you reply!
