### ISSUE TITLE
Is the library not optimized for other intel GPUs than mentioned in the documentation ?

### ISSUE THREAD

**Issue by SiddSS** [oneapi-src/oneDNN#1101]
Hi,

In the documentation  it is mentioned that the library is optimized for the following GPUs
Intel HD Graphics
Intel UHD Graphics
Intel Iris Plus Graphics
Xe architecture-based Graphics (code named DG1 and Tiger Lake)

Is the library optimized only for the above GPUs ?
Does it provide performance benefits when used for other intel GPUs (such as Iris pro)?

Thanks,
Siddharth

**Comment by igorsafo** [comment]
Hi @SiddSS ,
Yes, oneDNN provides optimizations for Intel Iris Pro GPUs as well.
In general oneDNN uses OpenCL or assembly level kernels and dispatches based on Intel Gen architecture and extensions available on a particular device. For example, Intel {HD,UHD,Iris Plus,Iris Pro} 5xx series GPUs are based on Intel Gen9 GPU architecture and are different in terms of number of EUs, frequency, power consumptions, etc. So oneDNN contains optimizations for all of them, but we validate performance on a subset of these SKUs.

Regards,
Igor Safonov

**Comment by SiddSS** [comment]
Thanks for the answer @igorsafo 
I still have some confusion. If I use the library for development, will it work on other generation architectures as well ? say Gen 8 or Gen 11. Can I find a list somewhere or know exactly which range of architectures and gpus is the library able to support and optimize ? 
Also in terms of gpu runtime, Is it not available for MacOS ?

**Comment by igorsafo** [comment]
This is a fair point, oneDNN was validated on Gen9+ configurations: Gen9, Gen9.5, Gen11, Gen12LP. It might work on pre Gen9 architectures, but those architectures were not validated by our internal testing. @echeresh Is it possible to list all supported Gen architectures in oneDNN documentation?
As far as I know there is no Intel GPU runtime available for MacOS.

Regards,
Igor Safonov

**Comment by echeresh** [comment]
@igorsafo @SiddSS oneDNN provides support for the following GPU architectures: Gen9, Gen9.5, Gen11 and Xe architecture. Other GPU architectures are not supported. We will update the documentation to reflect that clearly.

As for other questions:
- Iris Pro and generally all other series are supported
- No support for Gen8
- Gen11 is supported (all Gen9 and above architectures are supported)
- MacOS is not supported as there is no OpenCL driver support on MacOS
    - oneDNN is tested with Windows and Ubuntu

**Comment by Hari-MathWorks** [comment]
Hi @echeresh, @igorsafo,

I had one naive question. If we choose OpenCL runtime and target engine as GPU then does OneDNN kernels choose only GPU devices or it uses GPU also. Because, In general, OpenCL capable of choosing all the devices either CPU device or GPU Device that is connected to the machine, and shares the workload among all the devices. 

Below is some question:
1. By choosing OpenCL runtime, Is it possible to run on mixed devices at a time for the OneDNN kernels? (or) does OnceDNN pick the only device based on the target engine?

Regards,
Hari

**Comment by igorsafo** [comment]
Hi @Hari-MathWorks ,
OpenCL runtime is supported by GPU only. DPC++ runtime on the other side supports both CPU and GPU devices. Device type selection is explicit, so user has to specify CPU or GPU when they create an engine -- there is no auto-dispatching between CPU and GPU. Auto-dispatching can be implemented on application/framework side.

Regards,
Igor Safonov

**Comment by Hari-MathWorks** [comment]
Hi @igorsafo,

Thanks for your quick response.
Does OneDNN provide benchmark tools for GPU deployment time measurement?

Thanks,
Hari

**Comment by igorsafo** [comment]
DPCPP runtime supports Intel CPUs and GPUs and Nvidia GPUs (Nvidia GPUs support is community driven). OpenCL runtime supports Intel GPUs only. Underneath DPCPP and OpenCL reuse the same set of kernels for Intel GPUs, so they are similar in terms of performance. Aside from oneDNN DPCPP implementation[ can utilize OpenCL inside](https://software.intel.com/content/www/us/en/develop/articles/migrating-opencl-designs-to-dpcpp.html), so the performance of OpenCL vs DPCPP should be similar in that case.

oneDNN provides a tool called benchdnn which is used for both correctness and performance validations.
benchdnn and supporting documentation are located in `tests/benchdnn` directory.
A simple example measuring convolution performance using oneDNN on GPU:
```sh
$ ./build/tests/benchdnn/benchdnn --conv --engine=gpu --mode=P g1ic256ih5oc512oh5kh3ph1n"2d_conv"
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,gpu,cuda:cudnn:any,2d_conv,--conv --engine=gpu --mode=P g1ic256ih5oc512oh5kh3ph1n2d_conv,0.0886047,0,0.109442,809.603,0.110276,803.479
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):0.109442 avg(ms):0.110276
```

Please review [benchdnn documentation](https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn#benchdnn) for more details.

**Comment by Hari-MathWorks** [comment]
Thanks for your quick reply @igorsafo .
This information would be helpful for us to getting started with OneDNN for Intel GPUs.

**Comment by igorsafo** [comment]
@SiddSS  @Hari-MathWorks The list of supported GPUs was updated in 0847a5b3dbf0800d206bc4a110268b212d0edc38 to reflect Intel GPU generations supported by oneDNN. Closing the issue because the question seems to be addressed and documentation is updated. Feel free to open a new issue in case you have additional questions.
