### ISSUE TITLE
To support Nvidia GPUs with OpenCL runtime

### ISSUE THREAD

**Issue by kakulo** [oneapi-src/oneDNN#1104]
Hi again, 

I am trying to support Nvidia GPUs with OpenCL runtime myself. When I hit this function (reorder_primitive_desc_create in reorder.cpp), it returns "unimplemented" always. Could you please explain to me what this function does in detail and what pieces are missing for unimplemented? Thank you very much.

BTW, does oneDNN support Intel CPUs with OpenCL runtime?

-Lenny

**Comment by igorsafo** [comment]
Hi @kakulo ,
`reorder_primitive_desc_create` goes through all available reorder implementations and tries to create each of them until one of them returns success or end of list is reached. The reference OpenCL-based reorder lives in src/gpu/ocl/simple_reorder.{cpp,hpp} files. There is an `init()` method which determines whether hardware and reorder configurations are supported. There are at least 2 issues in case this reorder is created on Nvidia GPU:
1. Engine has [vendor_id check](https://github.com/oneapi-src/oneDNN/blob/8f40cd636b2ad278f6840dfbaa98ee6ff8405b17/src/gpu/ocl/ocl_utils.cpp#L72) which should be modified;
2. Reorder [checks](https://github.com/oneapi-src/oneDNN/blob/8f40cd636b2ad278f6840dfbaa98ee6ff8405b17/src/gpu/ocl/simple_reorder.hpp#L73) that intel_subgroups are supported.

The best way to debug such issues would be to build oneDNN with debug information and run it under debugger to understand how different parts of code work together.

There is no OpenCL runtime support on CPUs in oneDNN.

Regards,
Igor Safonov

**Comment by kakulo** [comment]
Thanks Igor! What "reorder implementation" means in this context? I don't quite understand.

**Comment by igorsafo** [comment]
oneDNN contains set of primitives, like convolution, reorder, polling, etc. Each of these primitives might have multiple implementations. For example, one implementation is optimized for ARM architecture, another one optimized for Intel AVX512 ISA, the third one is optimized for AVX512 ISA and integer data type, etc. Each implementation is defined as a C++ class inherited from `primitive_t`. Each implementation has its own implementation of methods `init()`, `execute()`, etc. because each of them might have unique set of restrictions of unique set of steps required to compute math operation. In my previous comment I meant particular reorder implementation called `dnnl::impl::gpu::ocl::simple_reorder_t`.

**Comment by kakulo** [comment]
Thank you very much. I understand better the code structure thanks to your help. 
Now I am hitting the point to fix the [compiler](https://github.com/oneapi-src/oneDNN/blob/8f40cd636b2ad278f6840dfbaa98ee6ff8405b17/src/gpu/ocl/ocl_gpu_engine.cpp#L201) and [link](https://github.com/oneapi-src/oneDNN/blob/8f40cd636b2ad278f6840dfbaa98ee6ff8405b17/src/gpu/ocl/ocl_gpu_engine.cpp#L208) options error for ocl_gpu_engine found in the ocl_gpu_engine.cpp file. All OpenCL GPU test cases fail at this error. The two functions clCompileProgram and clLinkProgram return error code -66 (CL_INVALID_COMPILER_OPTIONS) and -67 (CL_INVALID_LINKER_OPTIONS). This makes me realize the problem with options to those two functions. I have spent time trying to fix the options, but cannot figure out the correct one. Could you please have a look at it? Thank you very much!

**Comment by igorsafo** [comment]
@kakulo I think the issue is that in oneDNN we pass Intel-specific compiler options which cause error when are passed to Nvidia OpenCL runtime: https://github.com/oneapi-src/oneDNN/blob/8f40cd636b2ad278f6840dfbaa98ee6ff8405b17/src/gpu/ocl/ocl_gpu_engine.cpp#L150 

To fix the issue method `get_cl_ext_options()` should be modified if target device is Nvidia GPU. I would recommend to look into core classes responsible for interacting with OpenCL runtime ( ocl_gpu_device_info_t , ocl_gpu_engine_t, etc) and modify them to support Nvidia GPU device along with Intel GPUs. Once it is done, reference primitives should start working, because they all go through those core classes.

**Comment by kakulo** [comment]
Hi @igorsafo: I found out the error that causes [clBuildProgram](https://github.com/oneapi-src/oneDNN/blob/8f40cd636b2ad278f6840dfbaa98ee6ff8405b17/src/gpu/ocl/ocl_gpu_engine.cpp#L164) to fail using the verbose mode. The error is not caused by wrong compiler options. Instead, it is because the grammar is not recognized by OpenCL. I fixed part of them, for example change [0] to s0. But there are still some that I could not make it work. The error message is attached below. Please let me know if you have any idea about how to fix this. Thanks a lot 👍. 

Error during the build of OpenCL program.
Build log:
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:154:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:154:22>: implicit declaration of function 'intel_sub_group_block_read' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:155:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:155:23>: implicit declaration of function 'intel_sub_group_block_read2' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:156:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:156:23>: implicit declaration of function 'intel_sub_group_block_read4' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:157:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:157:23>: implicit declaration of function 'intel_sub_group_block_read8' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:158:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:158:23>: implicit declaration of function 'intel_sub_group_block_write' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:159:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:159:24>: implicit declaration of function 'intel_sub_group_block_write2' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:160:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:160:24>: implicit declaration of function 'intel_sub_group_block_write4' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:161:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:161:24>: implicit declaration of function 'intel_sub_group_block_write8' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:168:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:133:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:168:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:136:8>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:169:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:133:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:169:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:136:8>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:170:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:133:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:170:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:136:8>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:171:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:133:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:171:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:136:8>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:172:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:148:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:172:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:151:6>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:173:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:148:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:173:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:151:6>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:174:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:148:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:174:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:151:6>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:175:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:148:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:175:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:151:6>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:176:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:148:12>: implicit declaration of function 'get_sub_group_local_id' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:176:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:151:6>: implicit declaration of function 'get_max_sub_group_size' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:209:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:204:13>: implicit declaration of function 'sub_group_broadcast' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:210:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:204:13>: implicit declaration of function 'sub_group_broadcast' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:211:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:204:13>: implicit declaration of function 'sub_group_broadcast' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:212:1 <Spelling=/home/guol678/.cache/pocl/kcache/tempdir-d45aeb/gpu/ocl/ocl_math_utils.h:204:13>: implicit declaration of function 'sub_group_broadcast' is invalid in OpenCL
error: /home/guol678/.cache/pocl/kcache/tempfile-c6-22-df-e2-33.cl:26:25 <Spelling=<command line>:35:22>: expected ')'

**Comment by igorsafo** [comment]
Hi @kakulo ,
I see that the issues are related to sub_group extensions API:

- https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/cl_khr_subgroups.html
- https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_subgroups_short.html

Did you verify that Nvidia OpenCL supports those extensions? Usually it can be queried using command `clinfo`. 

(off topic) Is there any particular reason you want OpenCL instead of DPCPP? The reason I am asking is that Nvidia support is available with DPCPP. The backend allows to run CUDA kernels and the implementation is optimized by calls to cuDNN library.

**Comment by kakulo** [comment]
Hi @igorsafo I have checked the extensions using `clinfo`. I find Nvidia OpenCL does not support the sub_group extension. Is it only available for Intel OpenCL?  I am not sure. 

The reason that we want OpenCL is that we have a homemade runtime to support heterogeneous platforms built on top of OpenCL. We want to have oneDNN run on our homemade runtime. DPCPP cannot help in our case. 

Do you have any better ideas for us? Thank you.

**Comment by igorsafo** [comment]
> I have checked the extensions using clinfo. I find Nvidia OpenCL does not support the sub_group extension. Is it only available for Intel OpenCL? I am not sure.

I see, there is an alternative Khronos extension called [cl_khr_subgroups](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/cl_khr_subgroups.html) which is not specific to Intel GPUs. However I am not sure if Nvidia OpenCL supports it. If it is not supported the kernels should be updated by replacing subgroup calls with other alternatives or reimplemented on pure OpenCL C or disabled.

> The reason that we want OpenCL is that we have a homemade runtime to support heterogeneous platforms built on top of OpenCL. We want to have oneDNN run on our homemade runtime. DPCPP cannot help in our case.
> 
> Do you have any better ideas for us? Thank you.

Makes sense. DPCPP provides some level of interoperability with OpenCL so it is possible to mix OpenCL and DPCPP kernels. Please review the following article: https://software.intel.com/content/www/us/en/develop/articles/interoperability-dpcpp-sycl-opencl.html .

**Comment by kakulo** [comment]
@igorsafo thank you very much!
