### ISSUE TITLE
export TF_ENABLE_ONEDNN_OPTS=1 enable this option, but the inferance is slower

### ISSUE THREAD

**Issue by zhaohb** [oneapi-src/oneDNN#1112]
I installed TensorFlow 2.5.0 in the container. Using TensorFlow to inference a recommend model, the time for 100 pieces of data was about 2.7s. but when I set export TF_ENABLE_ONEDNN_OPTS=1, the inference time was 6.3s. Shouldn't it be faster?

instll command:
```shell
pip install intel-tensorflow==2.5.0 
```

I do not know why?

**Comment by dzarukin** [comment]
Hi @zhaohb, thank you for your question. It seems it's related to TensorFlow and oneDNN integration into it, so tagging responsible people to answer your question.

@agramesh1, @mdfaijul, could you assist @zhaohb from this point, please?

**Comment by agramesh1** [comment]
@zhaohb can you provide more information. The TF_ENABLE_ONEDNN_OPTS setting will only work with official tensorflow. (pip install tensorflow==2.5.0), was the 6.3s observed with this version and TF_ENABLE_ONEDNN_OPTS=1 set? 
Or did you see the lower performance with intel-tensorflow?

**Comment by zhaohb** [comment]
@agramesh1 yes, using intel-tensorFlow also results in a lot of performance degradation. if I need to set some environment variables like KMP_BLOCKTIME OMP_NUM_THREADS to get better performance?

**Comment by zhaohb** [comment]
@agramesh1  I did the test again today, and found that MKL has obvious effect on the optimization of CV model, but the performance of recommended model is not so good.

**Comment by vpirogov** [comment]
Closing the issue as stale. If you are experiencing issues with Tensorflow I suggest to open an issue on Tensorflow github with a reproducer.
