### ISSUE TITLE
Gtest Library Linking

### ISSUE THREAD

**Issue by Alok-Ranjan23** [oneapi-src/oneDNN#1116]
How are you linking the Googletest library?
How are they(static library of googletest) linked to the written gtest?

**Comment by igorsafo** [comment]
Hi @Alok-Ranjan23 , oneDNN has a [copy](https://github.com/oneapi-src/oneDNN/tree/master/tests/gtests/gtest) of gtests library which is [linked statically](https://github.com/oneapi-src/oneDNN/blob/3b28c5246290d97107bf7f8e8f40618825717ef6/tests/gtests/CMakeLists.txt#L178) to gtests-based oneDNN tests.

**Comment by Alok-Ranjan23** [comment]
@igorsafo There are only headers and src files of google test. Where is the static google test library(*.a files)? Do we need to build google test library?

**Comment by igorsafo** [comment]
It is a dependency for oneDNN tests and is built during oneDNN tests building process (libdnnl_gtest.a will be in ${BUILD_DIR}/tests/gtests/gtest). It is integrated into oneDNN build system, so users don't have to provide their own version of gtests.

**Comment by Alok-Ranjan23** [comment]
Thanks for the explanation.

**Comment by igorsafo** [comment]
Clothing the issue since the question seems to be addressed. Feel free to open another issue if you have any questions.
