### ISSUE TITLE
build fail using Xcode

### ISSUE THREAD

**Issue by shlowdy** [oneapi-src/oneDNN#1119]
with
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DDNNL_CPU_RUNTIME=TBB -DTBBROOT=/Users/macbookpro/Downloads/oneapi-tbb-2021.2.0 -G Xcode -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=xxxxxxxx

cmake --build . --config Release
```

I got the error
```
PhaseScriptExecution CMake\ PostBuild\ Rules /Users/macbookpro/Downloads/oneDNN-2.3/build/src/oneDNN.build/Release/dnnl.build/Script-4A2486C4081C3239C2CAA84D.sh (in target 'dnnl' from project 'oneDNN')
    cd /Users/macbookpro/Downloads/oneDNN-2.3
    /bin/sh -c /Users/macbookpro/Downloads/oneDNN-2.3/build/src/oneDNN.build/Release/dnnl.build/Script-4A2486C4081C3239C2CAA84D.sh
CMake Error: failed to create symbolic link '/Users/macbookpro/Downloads/oneDNN-2.3/build/src/Release/libdnnl.2.dylib': No such file or directory
CMake Error: cmake_symlink_library: System Error: No such file or directory
CMake Error: failed to create symbolic link '/Users/macbookpro/Downloads/oneDNN-2.3/build/src/Release/libdnnl.dylib': No such file or directory
CMake Error: cmake_symlink_library: System Error: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

** BUILD FAILED **
```
oneDNN version 2.3
macOS version 11.4
Xcode version 12.4

It is possible to build with -GXcode? (even build for iOS?)
need help
thanks so much.

**Comment by igorsafo** [comment]
Hi @shlowdy ,
thanks for you report. Did you look for `/Users/macbookpro/Downloads/oneDNN-2.3/build/src/Release/libdnnl.2.dylib`? Was the build successful before the issue appeared? It looks like there was an issue during `libdnnl` build and cmake wasn't able to create a sym link to non-existing file.

We definitely haven't tried to build oneDNN targeting iOS or using XCode. ARM architecture support is based on [ARM Compute Library](https://github.com/ARM-software/ComputeLibrary ), so to be able to build oneDNN for iOS ARM Compute Library should support it and target CPU architecture should be at least ARMv8-A. Casting @nSircombe for more details as one of contributors of ARM support in oneDNN.

Regards,
Igor Safonov

**Comment by shlowdy** [comment]
yes it's strange
there is no other error
and I try -DDNNL_CPU_RUNTIME=THREADPOOL
still the same

no idea what go wrong

**Comment by shlowdy** [comment]
I might have found the reason

[https://github.com/wjakob/nanogui/issues/267](url)

Xcode won't generate dylib if where is no source file
