### ISSUE TITLE
Use CMAKE_CXX_STANDARD to set C++ standards for compilation

### ISSUE THREAD

**Issue by pablorcum** [oneapi-src/oneDNN#1120]
# Summary
Use `CMAKE_CXX_STANDARD`, `CMAKE_CXX_STANDARD_REQUIRED `and `CMAKE_CXX_EXTENSIONS `to set C++ standards for compilation as documented in the CMake documentation.

# Version
* git hash 84954971808b7ae0656834cf8e68cabbf086ec28

# Environment
* OS version Windows 10 targeting QNX v7.1
* Compiler version QCC v8.3
* CMake version 3.20.2
* git hash 84954971808b7ae0656834cf8e68cabbf086ec28

# Steps to reproduce
Build for an UNIX target and check the compiler flags.

# Observed behavior
Compiler flags have been manually added at `CMAKE_CXX_FLAGS`.

# Expected behavior
Use `CMAKE_CXX_STANDARD`, `CMAKE_CXX_STANDARD_REQUIRED `and `CMAKE_CXX_EXTENSIONS `to set C++ standards for compilation as documented in the CMake documentation.

**Comment by igorsafo** [comment]
The issue is addressed with no required changes to oneDNN. Review #1121 for more details.
