### ISSUE TITLE
Suggestion to change the separator from ":" to "," in BenchDNN --skip-impl

### ISSUE THREAD

**Issue by alenik01** [oneapi-src/oneDNN#1129]
# Summary
At the moment benchdnn provides ` --skip-impl="str"` functionality to skip particular implementations, where "str" consists of several primitive names separated by ":". It would be nice to change the separator to "," to match the `DNNL_VERBOSE` logging style. 

# Problem statement
Current functionality example:
`benchdnn --conv --skip-impl="ref:gemm:any" ...`
Suggestion:
`benchdnn --conv --skip-impl="ref:gemm,ref:any" ...`
The problem here is that ":" is already used in primitive naming (e.g. here: [src/cpu/gemm/gemm.hpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/gemm/gemm.hpp#L55-L70)), thus it seems more convenient to introduce the format `--skip-impl="first_primitive_name,second_primitive_name,..."`. 

# Preferred solution
The solution may be to change ':' to ',' in [tests/benchdnn/common.cpp](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/common.cpp#L388) and check that primitive names are handled as declared in its `DECLARE_COMMON_PD_T` in primitive headers.

**Comment by dzarukin** [comment]
@alenik01, just a friendly follow up - we fixed a delimiter from `:` to `,` in `skip-impl` option. It means that `:` can be used in names now. In addition, we modified x64 GEMM names for `x64:gemm` and now refer to it everywhere. I believe this should be enough for ACL team to proceed with testing. In addition, I've created an internal item for the team to formalize the naming convention inside the library for implementation names and likely an RFC to be expected for a broader audience to come up with a solution. Thanks for letting us know about the issue and please share with us if everything works as expected on your side.

**Comment by alenik01** [comment]
@dzarukin, many thanks for the quick fix! It noticeably simplifies the things.
