### ISSUE TITLE
Regarding availability of interoperatibility functions for OpenCL in version 1.4 of the library

### ISSUE THREAD

**Issue by SiddSS** [oneapi-src/oneDNN#1134]
Hi,

While working with version 1.4 of the library I noticed that the header file "dnnl_ocl.hpp" is not available with OpenCL build. The header file seems to be necessary in order to use interoperability functions to get context, command queue etc. The same header file was available with the OpenCL build of the latest version of the library.  Do let me know if it is not possible to use interoperability functions with the older version. 
Also are there dependencies on OpenCL version for using specific versions of oneDNN library ?

Thanks
Siddharth

**Comment by dzarukin** [comment]
Hi @SiddSS, thank you for your question.
GPU support was a major feature of v2.0 release and this is the initial version where OpenCL and DPCPP support is available. All versions of oneDNN 1.x don't and won't have this support. Please consider updating oneDNN version to latest available in case GPU support is desired.

OpenCL requirements are described [in this section](https://github.com/oneapi-src/oneDNN#gpu-engine). Basically it says OpenCL 1.2 and OpenCL driver with Intel extensions support.

Hope it helps. Thank you.
