### ISSUE TITLE
No pre-built binaries available in releases

### ISSUE THREAD

**Issue by congkun-ck** [oneapi-src/oneDNN#1141]
https://github.com/oneapi-src/oneDNN#installation says "Pre-built binaries for Linux*, Windows*, and macOS* are available for download in the releases section. "
However there are only source code packages available for download, not any binaries.

**Comment by vpirogov** [comment]
Thank you for the report @congkun-ck. We stopped providing pre-build binaries on Github starting from v2.3, as the packages are now available in [conda-forge](https://github.com/conda-forge/onednn-feedstock). I'll update documentation accordingly.

**Comment by vpirogov** [comment]
Documentation updated accordingly.
