### ISSUE TITLE
Add support for the RISC-V architecture

### ISSUE THREAD

**Issue by aaronfranke** [oneapi-src/oneDNN#1146]
# Summary

This is a low-priority feature request, but one that would make sense to be done eventually.

Currently oneDNN supports many architectures, including x86, ARM, PPC, and IBMz S390X. RISC-V is a new open source ISA supported by several Linux distros, and it would be nice if oneDNN supported RISC-V.

# Problem statement

The problem is the lack of ability to compile software that depends on oneDNN for RISC-V.

# Preferred solution

The solution is to add support for RISC-V. Specifically, I am only interested in 64-bit RISC-V aka RV64 (32-bit and 128-bit exist too), and as for extensions, I recommend just supporting the general purpose extensions, so `-march=rv64g` (or `-march=rv64gc`). The abbreviation of RISC-V to just RV is very common and is the preferred option in some situations, so feel free to use that name.

**Comment by mgouicem** [comment]
Hi @aaronfranke , oneDNN has architecture specific code paths, but also contains some generic C++11 implementations.
You can compile oneDNN with only the latter implementations by using the `-DDNNL_TARGET_ARCH=ARCH_GENERIC` cmake option. Could you give it a try and let us know how it goes?

**Comment by aaronfranke** [comment]
@mgouicem Thanks for the reply. I discovered that oneDNN does successfully compile with the current master, so no changes are strictly necessary. I also opened #1148 to allow explicitly targeting it. 2 of the tests fail.
