### ISSUE TITLE
dynamic_cast failed

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1157]
i build intel/llvm with cuda backend, and onednn with gpu_run_time only.
i compiled the getting_started.cpp example with this command 
"clang++ -I$DNNLROOT/include -L$DNNLROOT/lib getting_started.cpp -ldnnl -lsycl"
then i tried to run the a.out file, this error came up:
```
oneDNN-master/src/common/utils.hpp:454: derived_type dnnl::impl::utils::downcast(base_type *) [derived_type = dnnl::impl::sycl::sycl_buffer_memory_storage_t *, base_type = dnnl::impl::memory_storage_t]: Assertion `dynamic_cast<derived_type>(base) == base' failed.
Aborted (core dumped)
```
i counldn't understand it, please help me.
 i'm tring to use gdb to find where the code goes wrong, but the function calling chain is complex, and i'm not sure it will leading me to solve this error. (T_T)

**Comment by dzarukin** [comment]
Hi @MOLOjl, thanks for your question. The thing is that cuda support is limited to buffer-type memory only. By default, memory objects in oneDNN are created using USM type. This mismatch and lack of USM support for cuda leads to an error you see. None of examples would work with Nvidia backend from the box. To make them work, one needs to change all calls to memory objects from default to specialized `sycl_interop::make_memory(...)` using buffer type of memory and proper initialization.

I will respond later with other suggestions in case you like to see invocations to cuda implementations.

**Comment by MOLOjl** [comment]
thanks very much!!
i followed your advice and change the 
```c++
auto src_mem = memory(src_md, eng);
```
to 
```c++ 
auto src_mem = sycl_interop::make_memory(src_md, eng,  sycl_interop::memory_kind::buffer);
```
(the dst_mem too)
and passed the getting_started example !
i don't know the underlying mechanism about why this limit happen and how sycl allocate memory on cuda device, i'm just learning about it, in fact, as a student. 
so if convenient, i would be appreciated to get your guidance.
thanks again!

**Comment by wangzy0327** [comment]
> Hi @MOLOjl, thanks for your question. The thing is that cuda support is limited to buffer-type memory only. By default, memory objects in oneDNN are created using USM type. This mismatch and lack of USM support for cuda leads to an error you see. None of examples would work with Nvidia backend from the box. To make them work, one needs to change all calls to memory objects from default to specialized `sycl_interop::make_memory(...)` using buffer type of memory and proper initialization.
> 
> I will respond later with other suggestions in case you like to see invocations to cuda implementations.

@dzarukin Was the `USM support for cuda` in new version ?

**Comment by dzarukin** [comment]
@mehdi-goli, could you, please, help answering the question when USM support will be added for Nvidia backend?
