### ISSUE TITLE
graph: support for dnnl_graph_thread_pool?

### ISSUE THREAD

**Issue by pinzhenx** [oneapi-src/oneDNN#1160]
onednn graph currently does not expose the [onednn threadpool interoperability](
https://oneapi-src.github.io/oneDNN/dev_guide_threadpool.html), with only a dummy `thread_pool` being set in `stream_attr`, which is never being used in kernel execution.

**Comment by igorsafo** [comment]
Seems like this is a question related to oneDNN graph API.
@TaoLv Could you please take a look at this issue?

**Comment by TaoLv** [comment]
Long time no see, @pinzhenx, and thank you for the request. Yes, external thread pool is not supported in graph API yet. Previously we had some internal discussion and planned to evaluate and enable the feature in Q4 this year. Will keep this issue updated if there is any progress.

**Comment by TaoLv** [comment]
Should have been fixed via 96ce136d01c2ccc4a63f72a5d85bf035c79b3fc4 and will be released as part of Graph preview4..

**Comment by pinzhenx** [comment]
@TaoLv @xinyu-intel Thanks for the patch. Closing this issue.
