### ISSUE TITLE
Difficulty in setting output_scales attribute for Convolution primitive .

### ISSUE THREAD

**Issue by eagledot** [oneapi-src/oneDNN#1170]
Hi,

I was trying to set the ``output_scales``  attribute for Convolution Primitive (Int8 inference), Since in  my case the value for output_scale/scales would be known at runtime only so i used  an array with single ``DNNL_RUNTIME_F32_VAL `` for ``scales`` parameter according to documentation. 

```
//Pseudo code

int mb = 1, oc = 8.
    oh = 14, ow = 14; // convolution output params


vector<float> scales = { DNNL_RUNTIME_F32_VAL };  //array with single value .

// construct a convolution descriptor
dnnl::convolution::desc conv_d;

dnnl::primitive_attr attr;
attr.set_output_scales(attr, 1, 0, scales); //mask is set to 0.

dnnl::primitive_desc conv_pd(conv_d, attr, engine);
``` 
It doesnot indicate any error  during any of the above steps,During execution of primitive it doesnot seem to care if i provide any argument with ``DNNL_ARG_ATTR_OUTPUT_SCALES`` index.
I always get the output filled with ``nan`` values which i guess is the interpreted value for ``DNNL_RUNTIME_F32_VAL``.

It makes me think that ``WILDCARD`` value is not being interpreted  as ``WIDCARD``  but as a value for ``scale`` itself. I observed the same behaviour when i tried to use ``runtime scaling`` for the ``reroder primitive `` as well.
I donot know what i am missing here? please let me know if you have some suggestions.

Thanks

DNNL_VERSION: 2.2.0.0 (intel openmp runtime)
OS: windows 10
Architecture: intel i5-8300H @2.30GHz

**Comment by dzarukin** [comment]
Hi @eagledot, could you try to use [binary_mul post-op](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html) instead? I believe it should work no worse than run-time output scale.

**Comment by dzarukin** [comment]
Closing as stale. Feel free to reopen with requested information.
