### ISSUE TITLE
Does TensorFlow have support for intel GPUs? 

### ISSUE THREAD

**Issue by karasjoh000** [oneapi-src/oneDNN#1176]
Wondering if there is support for intel GPUs on TensorFlow and if there is a step by step guide of how to set it up.

**Comment by tedliosu** [comment]
> Wondering if there is support for intel GPUs on TensorFlow and if there is a step by step guide of how to set it up.

@karasjoh000 it has happened! https://github.com/oneapi-src/oneDNN/issues/1465#issuecomment-1295229193
