### ISSUE TITLE
Creating a convolution descriptor by specifying the destination memory descriptor with strides.

### ISSUE THREAD

**Issue by phanicoder** [oneapi-src/oneDNN#1183]
Hi,
I am trying to create a convolution descriptor by specifying the destination memory descriptor with strides. With this, the convolution algorithm used by the descriptor is found be the reference algorithm. This has been impacting the performance. The following are the logs printed in the cases mentioned above:

-------------------- Convolution descriptor when destination memory descriptor with strides -------------------------
**dnnl_verbose,create:cache_miss,cpu,convolution,ref:any,forward_inference,src_f32::blocked:acdb:f0 wei_f32::blocked:abcd:f0 bia_f32::blocked:a:f0 dst_f32::blocked:abcd:f0,,alg:convolution_direct,mb1_ic3oc96_ih227oh55kh11sh4dh0ph0_iw227ow55kw11sw4dw0pw0,0.0100098**

-------------------- Convolution descriptor when destination memory descriptor without strides -------------------------
**dnnl_verbose,create:cache_miss,cpu,convolution,jit:avx2,forward_inference,src_f32::blocked:abcd:f0 wei_f32::blocked:Acdb8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,,alg:convolution_direct,mb1_ic3oc96_ih227oh55kh11sh4dh0ph0_iw227ow55kw11sw4dw0pw0,0.25293**

The following is the code snippet used to create the convolution descriptor:

    auto conv1_src_md = memory::desc({conv1_src_tz}, dt::f32, tag::any);
    auto conv1_bias_md = memory::desc({conv1_bias_tz}, dt::f32, tag::any);
    auto conv1_weights_md = memory::desc({conv1_weights_tz}, dt::f32, tag::any);
    auto conv1_dst_md = memory::desc({conv1_dst_tz}, dt::f32, tag::any);

    memory::dims ldims = {conv1_dst_tz};
    memory::dims lstrides;
   //Logic to calculate the strides.
    auto conv1_dst_md = memory::desc(ldims, dt::f32, lstrides);
    auto conv1_desc = convolution_forward::desc(prop_kind::forward_inference,
            algorithm::convolution_direct, conv1_src_md, conv1_weights_md,
            conv1_bias_md, conv1_dst_md, conv1_strides, conv1_padding,
            conv1_padding);

Kindly let us know if there is any way to create the convolution descriptor such that jit avx2 convolution algorithm is selected, even though destination memory descriptor with strides is specified. 

Thanks...

**Comment by kwiersch** [comment]
Hi @phanicoder,

One problem is that for the case of memory descriptors with strides it looks like your `dst` layout is `nchw` (or `abcd`), but as I recall the jit avx2 convolution algorithm only supports `nChw8c` and `nhwc` (or `acdb`) layouts. But even if you fix that by setting the strides to match `nhwc` layout, keep in mind that the weights will still need to be changed to something like `OIhw8i8o`. So it's probably best to always use `format_kind::any` for weights (as far as I know, all the jit implementations use blocked weights layouts).

More generally, the best practice is usually to create the convolution primitive with all memory descriptors initialized to `format_kind::any`, which allows the implementation to choose the best layout, then perform extra reorders as needed. See https://oneapi-src.github.io/oneDNN/page_memory_format_propagation_cpp.html for an example of how to do this.
