### ISSUE TITLE
Why onednn examples couldn't find GPU on ubuntu20.04 machine which have a intel igpu and nvidia gpu ?  These examples are built by DPCPP.

### ISSUE THREAD

**Issue by RobbertOnly** [oneapi-src/oneDNN#1189]

**Comment by igorsafo** [comment]
Hello @RobbertOnly ,
There are multiple reasons which might cause this behavior:
- User doesn't have group `render`
- There is no GPU runtime installed on the system

Please take a look at this article for more details: https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html

**Comment by RobbertOnly** [comment]
> Hello @RobbertOnly , There are multiple reasons which might cause this behavior:
> 
> * User doesn't have group `render`
> * There is no GPU runtime installed on the system
> 
> Please take a look at this article for more details: https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-focal.html

Thanks for your quick reply! @igorsafo 
According to the link address, I reinstalled the intel graphics driver and assigned group `render` permissions, but  the problem still exists.  And i accidentally found that putting any  executable onednn example  file in the directory `/usr/lib/x86_64-linux-gnu` which contains libOpenCL.so and intel-opencl subdirectory, the example can execute in  gpu engine. I do not know the reason .
Maybe you can give me some advice.

**Comment by vpirogov** [comment]
`libOpenCL.so` is [a runtime dependency](https://github.com/oneapi-src/oneDNN#linux) for oneDNN. Do you have path to it in your `LD_LIBRARY_PATH`?

**Comment by vpirogov** [comment]
You can check whether Linux dynamic loader can find the library by running `ldd ./libdnnl.so`
