### ISSUE TITLE
Why is the cpu_iomp library much larger than cpu_gomp?

### ISSUE THREAD

**Issue by guillaumekln** [oneapi-src/oneDNN#1193]
Hello,

I'm using the binary release of oneDNN included in the Intel oneAPI toolkit.

Why is the size of `libdnnl.so` much larger when compiled against Intel OpenMP compared to GNU OpenMP? Here are the reported sizes on Ubuntu 18.04:

```text
$ du -h /opt/intel/oneapi/dnnl/2021.4.0/cpu_gomp/lib/libdnnl.so.2.4 
50M	/opt/intel/oneapi/dnnl/2021.4.0/cpu_gomp/lib/libdnnl.so.2.4

$ du -h /opt/intel/oneapi/dnnl/2021.4.0/cpu_iomp/lib/libdnnl.so.2.4 
141M	/opt/intel/oneapi/dnnl/2021.4.0/cpu_iomp/lib/libdnnl.so.2.4
```

Thanks!

**Comment by vpirogov** [comment]
Hi @guillaumekln,

There's more difference than just OpenMP runtime. The library linked to Intel OpenMP is compiled with Intel C/C++ Compiler and includes compiler-generated code specializations for multiple instruction sets.

**Comment by guillaumekln** [comment]
Thanks for the quick reply @vpirogov. This answers my question.
