### ISSUE TITLE
Dense +Binary mul post-op got incorrect answer

### ISSUE THREAD

**Issue by mengceng15** [oneapi-src/oneDNN#1198]
Hi there. I tried to implement a simple 2D **Dense with bias + mul binary post-op** example (based on the inner_product.cpp from /example), but the result is incorrect. The script is attached. 
[dnnl_binary_mul_accuracy.txt](https://github.com/oneapi-src/oneDNN/files/7595229/dnnl_binary_mul_accuracy.txt)
Could you please have a look? Thanks

**Comment by igorsafo** [comment]
Hi @mengceng15 ,
I see in the example you provided it computes dst = **dst** * matmul(src, weights, bias). Is it a typo that you wanted to multiply previous dst and a result of a matmul operation?

Could you please provide verbose logs? To get verbose please use `DNNL_VERBOSE=1` env variable. This will help us to understand what implementation was used to validate it on our side.

Regards,
Igor

**Comment by mengceng15** [comment]
@igorsafo Hi Igor. I wanted to compute matmul(src, weight, bias) * dst, where dst contains the values of the multiplier. I expected the multiplication to be in-place (the result is stored in dst as well).

Below is the DNNL verbose log:
[dnn_verbose.txt](https://github.com/oneapi-src/oneDNN/files/7599116/dnn_verbose.txt)

**Comment by igorsafo** [comment]
@mengceng15 Unfortunately, binary post-op doesn't support in-place computations. This feature will restrict implementations from storing intermediate result into dst memory.

**Comment by mengceng15** [comment]
@igorsafo Many thanks for the clarification. So If I do not do it in-place, all what I need to do is to create some memory for the multiplier (we may call it mul_mem), and insert it to the args map like     inner_product_args.insert({DNNL_ARG_ATTR_MULTIPLE_POST_OP(0) | DNNL_ARG_SRC_1, mul_mem}); ?
I modified the code like above and got the correct answer.
