### ISSUE TITLE
Pooling primitive testing (Representation of -3.40282e+38 in Compute Library and Unsupported BWD)

### ISSUE THREAD

**Issue by cfRod** [oneapi-src/oneDNN#1205]
Hi, 

I am in the process of integrating the pooling function from Compute Library https://github.com/ARM-software/ComputeLibrary (ACL), as part of our AArch64 build. There are a few problems that we have for a small number of edge test cases including the representation of the value -3.40282e+38 and unsupported workspace tensor/BWD pass).

Problem 1: 
Certain test cases where kh==ph that return -Inf when using ACL when compared to the reference implementation. There are 4 test cases failing in test_pool_ci for example for e.g. Is it possible to change the representation of this value in the test harness for ACL only builds?
```
434:PASSED __REPRO: --pool --alg=avg_p ic16ih13oh14kh3ph3n"pool_2d_kh_equals_ph"
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:acdb:f0,,,2x16x13x13,0.273926
dnnl_verbose,exec,cpu,pooling_v2,acl,forward_training,src_f32::blocked:acdb:f0 dst_f32::blocked:acdb:f0 ws_u8::blocked:acdb:f0,,alg:pooling_max,mb2ic16_ih13oh14kh3sh1dh0ph3_iw13ow14kw3sw1dw0pw3,0.052002
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:acdb:f0 dst_f32::blocked:abcd:f0,,,2x16x14x14,0.269043
[   0][DST][0:0:0:0] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   1][DST][0:0:0:1] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   2][DST][0:0:0:2] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   3][DST][0:0:0:3] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   4][DST][0:0:0:4] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   5][DST][0:0:0:5] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   6][DST][0:0:0:6] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   7][DST][0:0:0:7] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
[   8][DST][0:0:0:8] exp_f32:-3.40282e+38 exp:-3.40282e+38 got:    -inf diff:     inf rdiff:     inf
@@@ error [int pool::doit(const pool::prb_t*, res_t*):313]: 'cmp.compare(dst_fp, dst_dt, prb->attr, res)' -> 1
435:FAILED (errors:864 total:6272) __REPRO: --pool --tag=axb ic16ih13oh14kh3ph3n"pool_2d_kh_equals_ph"
```

Problem 2:
ACL does not support BWD pass for any primitive. In the case of pooling there is information/indices passed from the FWD pass to the BWD pass via workspace tensor. This again has limited coverage in ACL (ACL only supports indices for 2x2 pooling windows https://github.com/ARM-software/ComputeLibrary/blob/91ee4d0a9ef128b16936921470a0e3ffef347536/src/cpu/kernels/CpuPool2dKernel.cpp#L229). Hence, the test_pooling_forward fails at  this line https://github.com/oneapi-src/oneDNN/blob/26a7c19e15dee8988cd35bd3c5db52c37aa9bd3c/tests/gtests/test_pooling_forward.cpp#L194 which basically checks the content of ws_data (https://github.com/oneapi-src/oneDNN/blob/26a7c19e15dee8988cd35bd3c5db52c37aa9bd3c/tests/gtests/test_pooling_forward.cpp#L120) which is the workspace tensor.  Is it possible to disable this test for ACL only builds (I see that it is skipped for cudnn builds, so can we do something similar for ACL) AND skip all BWD tests in benchdnn in pool.cpp?

```
dnnl_verbose,exec,cpu,pooling_v2,acl,forward_training,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0 ws_u8::blocked:abcd:f0,,alg:pooling_max,mb1ic16_ih10oh6kh5sh5dh0ph10_iw10ow6kw5sw5dw0pw10,2.09204
/home/ubuntu/pooling/oneDNN/tests/gtests/test_pooling_forward.cpp:194: Failure
Expected equality of these values:
  out_index
    Which is: 1
  out_ref_index
    Which is: 0
 n = 0 c = 1 od = 0 oh = 2 ow = 0
```

**Comment by dzarukin** [comment]
Hi @cfRod, thanks for your questions.

As for benchdnn: as long as returning infinity is documented behavior for ARM ACL library for such cases, I don't see any issues to update [pooling reference benchdnn code](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/pool/ref_pool.cpp) as this:
```cpp
float get_initial_min_value(const prb_t *prb) {
#if DNNL_AARCH64_USE_ACL
    return std::numeric_limits<float>::infinity();
#else
    return lowest_dt(prb->cfg[DST].dt);
#endif
}

...
        float max_value = get_initial_min_value(prb);
....
```

Skipping backward cases should be controlled by [this](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/pool/pool.cpp#L178) function. As long as you want it to be skipped, just update conditions there.

For gtest problem, the fix may be rather simpler - just to use such define somewhere after [this line](https://github.com/oneapi-src/oneDNN/blob/master/tests/gtests/test_pooling_forward.cpp#L341):
```cpp
// Since ACL supports only forward, to avoid triggering workspace check which is not available.
#if DNNL_AARCH64_USE_ACL
#define forward_training forward_inference
#endif
```

Cudnn testing is not completely switched off. All cases not supported by cudnn library or its integration into oneDNN are gracefully walked around.

Hope it helps. Thanks.

**Comment by cfRod** [comment]
Hi @dzarukin 
Thanks for your suggestions. For  get_initial_min_value() there is a small problem. It will cause the tests that fallback to oneDNN reference to fail because the tests return -3.40282e+38 instead of -Inf. I am finding a way to  resolve this.

**Comment by cfRod** [comment]
My very hacky/less elegant solution right now is to pass res->Impl_name to compute_ref_fwd(), so that we change representation only if the Impl is of type acl. Would that work? Also had to ensure that the representation is only change for float data type and not other types.
 
```
float get_initial_min_value(const prb_t *prb, const std::string impl) {
#if DNNL_AARCH64_USE_ACL
    if (prb->cfg[DST].dt == dnnl_f32 && impl == "acl")
        return -std::numeric_limits<float>::infinity();
    else
        return lowest_dt(prb->cfg[DST].dt);
#else
    return lowest_dt(prb->cfg[DST].dt);
#endif
}
```

**Comment by cfRod** [comment]
@dzarukin 

Is there a reason for testing cases when ph==kh? According to https://github.com/oneapi-src/oneDNN/blob/26a7c19e15dee8988cd35bd3c5db52c37aa9bd3c/tests/benchdnn/inputs/pool/shapes_2d#L66 it says these are corner cases but I wanted to understand if there is a use-case for testing this particular configuration.

**Comment by sicong-li-arm** [comment]
Thanks @cfRod  for posting the question. I just want to add that in ACL the behaviour when ph>=kh is currently undefined. We can't think of any real world case where such config would be required (other than the hypothetical case where we need to support dilation in padding).

If this config is simply for testing the corner cases in OneDNN, I think we shall prohibit such configs in ACL, and we can skip these tests.

**Comment by dzarukin** [comment]
Hi @cfRod, yeah, for some custom models, at least in past, users would use pooling to physically pad their output to make it bigger. It could be needed to align spatial in branches inside the model before concatenating the final output or something along the lines.
Anyway, if it wasn't needed, we wouldn't test it. :)
