### ISSUE TITLE
Performance degradation when running with OpenMP functions[Performance bug]

### ISSUE THREAD

**Issue by zheng-ningxin** [oneapi-src/oneDNN#1208]
# Summary
I call the onednn kernels and the openmp functions in the same program and I found that the performance of both onednn kernels and openmp function degrades significantly. When I call them separately, their performance returns to normal (onednn kernels 400ms total, openmp functions 600ms total). When I call them in a program at the same time (all kernels and functions are executed serially), the program will become 2000ms，which should be around 1000ms.
So I guess if the thread pools of onednn and openmp interfere with each other. Do you know how to solve this problem? Looking forward for your reply.

# Version
2.5.0

**Comment by dzarukin** [comment]
Hi @zheng-ningxin, thanks for your question. Could you attach a reproducer and some comments around so that team may get an understanding what's going on, please?
The way you build oneDNN and verbose output would help to understand your environment, too. Thanks.

**Comment by densamoilov** [comment]
@zheng-ningxin, quick question, do you specify a number of threads in your OpenMP functions? It might happen that oneDNN and your functions create parallel regions for different number of threads. When that happens OpenMP has to re-initialize a context during creation of the parallel regions, which may slow things down.

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional information.
