### ISSUE TITLE
CUDA backend: Application couldn't find GPU

### ISSUE THREAD

**Issue by vitduck** [oneapi-src/oneDNN#1216]
## Version
v2.5 

## Environment: 
cpu: Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
gpu: Tesla V100-PCIE-32GB
os: CentOS 7.9.2009
gcc: 8.3.0
cuda: 10.2
cmake: 3.16.3
clang: intel/llvm@8458fab
opencl runtime: oneapi_21.4

## Step to reproduce
Same as #1215  

## Test
```
$ cd build 
$ make test 
99% tests passed, 1 tests failed out of 118

Total Test time (real) = 396.53 sec

The following tests FAILED:
	 26 - test_deconvolution_buffer_gpu (Failed)
Errors while running CTest
make: *** [test] Error 8
```

## Examples
```
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda getting_started.cpp
$ ./a.out cpu 
Example passed on CPU.
$ ./a.out gpu
Application couldn't find GPU, please run with CPU instead.
```

## Issues
- I am getting conflicted result when running post-build tests and getting started example. The former passed all tests except the deconvolution one. Yet the later cannot initialize the GPU.  
- Since I cannot modify icd file located in ```/etc/OpenCL/vendors/```, I had to use the runtime from oneAPI 2021.4 release. This allows ```clinfo``` to 'see' both CPU and GPU platforms.
- I think explicit GPU selection is required for CUDA backend in `getting_started.cpp`. Could you give me some pointers ?

**Comment by densamoilov** [comment]
Do you use DPC++ compiler that was built with CUDA backend support?

Just in case, you can build it using the following script:
```bash
export CC=gcc
export CXX=g++

export DPCPPCOMPROOT=/path/to/intel-llvm

python3 $DPCPPCOMPROOT/buildbot/configure.py -s $DPCPPCOMPROOT -o $DPCPPCOMPROOT/build -t release --shared-libs --no-werror --cuda
python3 $DPCPPCOMPROOT/buildbot/compile.py -s $DPCPPCOMPROOT/llvm -o $DPCPPCOMPROOT/build
```
Please make sure you have CMake and ninja installed in the system.

Another important thing to mention is that oneDNN doesn't use OpenCL to support NVIDIA and we recently removed the dependency: fd51d4217bcf146678a90801615e2a3f1455cd6b. But if you use an older oneDNN then you will have to specify a location of OpenCL via `OPENCLROOT` CMake variable if OpenCL is installed in a non-default directory.

**Comment by vitduck** [comment]
Yes, I used CUDA-enabled intel-llvm to build v2.5. As shown in the original post, all ```test_*_gpu``` passed execpt one. 
If it helps, below is ```benchdnn``` output, following the dzarukin's instructions https://github.com/oneapi-src/oneDNN/issues/919#issuecomment-755135790
```
$  DNNL_VERBOSE=1 ./benchdnn --engine=gpu --binary 3x4x5:3x4x5

onednn_verbose,info,oneDNN v2.5.0 (commit 7e8dffa08d9f1706f3fa41efb6c35bc98ffca840)
onednn_verbose,info,cpu,runtime:DPC++
onednn_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost
onednn_verbose,info,gpu,runtime:DPC++
onednn_verbose,info,cpu,engine,0,backend:OpenCL,name:Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz,driver_version:2021.12.9
onednn_verbose,info,gpu,engine,0,backend:Nvidia,name:Tesla V100-PCIE-32GB,driver_version:0.0.0
onednn_verbose,info,gpu,engine,1,backend:Nvidia,name:Tesla V100-PCIE-32GB,driver_version:0.0.0
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.21582
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.0390625
onednn_verbose,exec,gpu:0,binary,cuda:cudnn:any,undef,src_f32::blocked:abc:f0 src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,alg:binary_add,3x4x5:3x4x5,1.79004
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.0419922
0:PASSED __REPRO: --binary --engine=gpu 3x4x5:3x4x5
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total compute_ref: sum(s):0.00
```
IMHO, intel-llvm and oneDNN were built correctly. Yet, I could not make ```getting_started.ccp``` to work with CUDA backend. 
The source code contains the follwoing device initialization: 
```
 engine eng(engine_kind, 0);
```
Here ```engine_kind``` accepts either ```cpu``` or ```gpu```. I think it should work out of the box.

**Comment by densamoilov** [comment]
@vitduck, sorry, I missed the fact that you are trying to use examples. oneDNN doesn't build examples for NVIDIA backend intentionally because the examples use runtime agnostic API to create `dnnl::memory` objects. The runtime agnostic API allocates underlying USM buffer, which is not currently supported by NVIDIA backend in oneDNN. We plan to add support for USM for NIVDIA soon.

Similar issues: #888, #1157

**Comment by vitduck** [comment]
Following the comments from #1157, changing ```dnnl::memory``` to ```sycl_interop::make_memory``` did solve the issue. 

I append the src build llvm and oneDNN to ```PATH``` and ```LD_LIBRARY_PATH```  after loading ```oneAPI 2021.4``` module. This is because I am under the impression that oneDNN always requires an intelocl CPU runtime to fully function. Before closing the issue, could you kindly comment on whether my current understanding is correct ?
- For Intel CPU/GPU, an intel ocl runtime is always requried. oneDNN is not a SYCL-based design, i.e no queue and submit.
- For NVIDIA, cuda backend is supported  only via SYCL interopt which doesn't require intel ocl runtime, i.e the build works even with ```-DDNNL_CPU_RUNTIME=NONE```

**Comment by densamoilov** [comment]
> For Intel CPU/GPU, an intel ocl runtime is always requried. oneDNN is not a SYCL-based design, i.e no queue and submit.

oneDNN supports different CPU and GPU runtimes via build options. When you build oneDNN with DPCPP runtime (CPU and GPU) it uses a SYCL-based programming model inside and provides an API to embed oneDNN into another SYCL based application. This means you can use API enclosed in `dnnl::sycl_interop` namespace to create an engine from `sycl::device` and `sycl::context`, stream from `sycl::queue` or memory from `sycl::buffer`. If a user uses runtime agnostic API then oneDNN creates all the sycl objects on its own.
Regarding OpenCL dependency for DPCPP runtime, the answer is yes, OpenCL is always required for CPU and GPU. For CPU this is a DPC++ compiler requirement. For GPU this is a DPC++ and oneDNN requirement. Please see the [backend concept](https://oneapi-src.github.io/oneDNN/dev_guide_dpcpp_backends.html) in DPC++.

> For NVIDIA, cuda backend is supported only via SYCL interopt which doesn't require intel ocl runtime, i.e the build works even with -DDNNL_CPU_RUNTIME=NONE

When you build oneDNN with NVIDIA support, you merely enable NVIDIA support (and disable Intel GPU support) for DPCPP runtime. The main difference is dependencies (the programming model stays the same). As I mentioned above we removed a dependency on OpenCL loader in fd51d4217bcf146678a90801615e2a3f1455cd6b. However, OpenCL for CPU will still be needed as DPC++ requires it to create a CPU SYCL device.
We do support so-called gpu only configurations (when you specify `-DDNNL_CPU_RUNTIME=NONE`). But we haven't tested it with NVIDIA so it may not work. But conceptually, I would expect that DPC++ + CUDA backend doesn't require OpenCL if CPU SYCL devices are not used.

**Comment by vitduck** [comment]
Thanks for detailed explanation, especially for the first question. 

Regarding  ```-DDNNL_CPU_RUNTIME=NONE``` in the second one, I was able to build v2.5 with this flag and passed most of the tests, excepting the following two: 
```
96% tests passed, 2 tests failed out of 48

Total Test time (real) = 272.77 sec

The following tests FAILED:
	 13 - test_deconvolution_buffer_gpu (Failed)
	 48 - test_api_sycl (Failed)
```
The result for ```benchdnn``` is follow. It seems to work with only CUDA backend. 
```
onednn_verbose,info,oneDNN v2.5.0 (commit 2597b4bf15a18619957f5f8ae2337fd0f0ec6a4b)
onednn_verbose,info,gpu,runtime:DPC++
onednn_verbose,info,gpu,engine,0,backend:Nvidia,name:Tesla V100-PCIE-32GB,driver_version:0.0.0
onednn_verbose,info,gpu,engine,1,backend:Nvidia,name:Tesla V100-PCIE-32GB,driver_version:0.0.0
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,gpu:0,reorder,cuda:cudnn:any,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,2.33691
onednn_verbose,exec,gpu:0,reorder,cuda:cudnn:any,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.238037
onednn_verbose,exec,gpu:0,binary,cuda:cudnn:any,undef,src_f32::blocked:abc:f0 src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,alg:binary_add,3x4x5:3x4x5,0.416992
onednn_verbose,exec,gpu:0,reorder,cuda:cudnn:any,undef,src_f32::blocked:abc:f0 dst_f32::blocked:abc:f0,,,3x4x5,0.210938
0:PASSED __REPRO: --binary --engine=gpu --fast-ref-gpu=false 3x4x5:3x4x5
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
```
In case of intel-llvm and oneMKL, the CUDA backend does not require CPU OpenCL runtime.  it would make sense conceptually that oneDNN doesn't require one as well. This will allow us to completely decouple oneAPI runtime from our build when migrating clients' code from CUDA to SYCL/oneMKL/oneDNN. 

I also tested https://github.com/oneapi-src/oneDNN/commit/fd51d4217bcf146678a90801615e2a3f1455cd6b commit. It is a welcome change that prevents OpenCL.so in CUDA modules from creeping in. 

Again thanks for your insights. Unless you have further comments, please close this issue.

**Comment by densamoilov** [comment]
Thanks for letting me know that GPU only configuration works for oneDNN with NVIDIA support. Also, thanks for sharing the testing results. We will look into that.

> This will allow us to completely decouple oneAPI runtime from our build when migrating clients' code from CUDA to SYCL/oneMKL/oneDNN.

Just to make sure I understand this. You have a CUDA based codebase that doesn't need the CPU OpenCL dependency (that is part of the oneAPI toolkit). You want to use some functionality from oneDNN with NVIDIA support without introducing the dependency on CPU OpenCL. Do I get it right?

**Comment by vitduck** [comment]
Yes. That is how we hope to be able do. 
As I recall with pre v2.4 release, ```benchdnn --engine=gpu``` would result in 'dnnl_engine_create()' error due to missing CPU runtime. Since the CUDA support is based on SYCL, our understanding has been that the creation of NVIDIA device queue does not depend on whether we can create a CPU queue or not.
 
In the end, we would like to just use Intel GPUs, but Xe HPC is nowhere on the horizon.  For now our focus is

- Confirmation of NVIDIA compatibility
- Performance comparison with native cuDNN since ```sycl_interop``` would introduce overhead from underlying creation and destruction of CUDA context per queue dispatch. At least we have seen the same issue with oneMKL. 
 
We will keep testing and report any found issues.

**Comment by densamoilov** [comment]
> As I recall with pre v2.4 release, benchdnn --engine=gpu would result in 'dnnl_engine_create()' error due to missing CPU runtime.

This is because we may create a CPU engine in `benchdnn` or `gtests` to use some CPU primitives to speed up testing. This is a test specific behavior. If you only use GPU engine in your code oneDNN won't create a CPU engine.
But if you need a oneDNN GPU only configuration with NVIDIA support (which is totally reasonable) then disabling a CPU runtime at the build time is the way to go.
> In the end, we would like to just use Intel GPUs, but Xe HPC is nowhere on the horizon.

While waiting for the Intel's GPU you can migrate your code to oneDNN with NVIDIA support. Once the GPU's are released you can simply enable them by using `DNNL_GPU_VENDOR=INTEL`. The programming model will stay the same (SYCL based) so no changes are expected in your code. But there will be a new set of dependencies (e.g. OpenCL for GPU).

> Performance comparison with native cuDNN since sycl_interop would introduce overhead from underlying creation and destruction of CUDA context per queue dispatch. 

That would be interesting to see some data for this. Feel free to report performance issues.

**Comment by AerialMantis** [comment]
> 96% tests passed, 2 tests failed out of 48
> 
> Total Test time (real) = 272.77 sec
> 
> The following tests FAILED:
> 	 13 - test_deconvolution_buffer_gpu (Failed)
> 	 48 - test_api_sycl (Failed)

We have also observed test_deconvolution_buffer_gpu failing on Nvidia GPU, we've been looking into this and we believe we may have a fix for it, once we confirm this we will prepare a PR.

**Comment by densamoilov** [comment]
@AerialMantis, thanks for letting us know, it would really nice if you could fix that.

I'm closing the issue as the original problem has been addressed.

**Comment by densamoilov** [comment]
@vitduck, JFYI, `test_api_sycl` failed due to an issue in the test which was fixed in aed66b1d9c5467a3a41dfb95321ef1b48d542e04.

**Comment by vitduck** [comment]
@densamoilov Sorry for late response. 
I would like to confirm that ```test_api_sycl``` passed after updating. Thanks for the notice !

**Comment by vitduck** [comment]
@densamoilov I've just tested the lastest commit. Thanks for adding USM support.

**Comment by vpirogov** [comment]
KUDOs go to @dylan-angus-codeplay, @hdelan, @t4c1, and @AidanBeltonS
