### ISSUE TITLE
[GPU] Is `cl_intel_subgroup_matrix_multiply_accumulate` extension used?

### ISSUE THREAD

**Issue by masahi** [oneapi-src/oneDNN#1217]
Hi, I'm exploring int8 capabilities on my tiger lake Xe LP. I found that int8 kernels uses `mmad8x8` macro defined at https://github.com/oneapi-src/oneDNN/blob/c7e18067cc5353f5ccbd63129dd7eb64fa4275c4/src/gpu/ocl/ocl_math_utils.h#L319-L323. I'm wondering if `cl_intel_subgroup_matrix_multiply_accumulate` is defined in the binary release of the driver. I couldn't find any public information of this extension, so any pointer would be appreciated.

**Comment by densamoilov** [comment]
+ @rjoursler

**Comment by vpirogov** [comment]
@masahi, this is an Intel OpenCL extension for DPAS instruction, which is not available on Xe-LP based GPUs like yours. It looks like the documentation or driver support for this extension was not yet published.

**Comment by masahi** [comment]
@vpirogov Thank you, then I assume that in my environment, the alternative code path is being used to emulate `mmad8x8`. Looking forward to learn about this extension and the mysterious DPAS instruction in particular!
