### ISSUE TITLE
about memory allocate and copy

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1219]
hello,
I'm testing onednn with cuda backend, when I use cudnn directly, I normally use `cudaMalloc()` and `cudaMemcpy()`,
when I use onednn, it seems the `sycl_interop::make_memory()` and `write_to_dnnl_memory()` (which is defined in the `example_utils.hpp`) do the similar function, am I thinking right?
I've tested the time cost of them, it's weird to find that sycl's memory allocation and copy are more efficient than cuda's original API. 
In the meanwhile, the total time to finish a single kernel (like a convolution forward) by onednn is less than using cuda language too.
does the result above true? if so, is it because sycl did some optimization on memory access?
I can provide my code if you'd like to check it.

**Comment by densamoilov** [comment]
Hi @MOLOjl,
`write_to_dnnl_memory()` uses `dnnl_memory_map_data`, which is implemented via host accessor for DPCPP runtime.
So basically, when you perform the code below DPCPP Runtime copies device memory to host.
```cpp
    sycl::buffer<int> buffer_a(10);
    auto acc_a = buffer_a.get_access<sycl::access::mode::write>();
    int *ptr = acc_a.get_pointer();
```

**Comment by MOLOjl** [comment]
sorry, I still don't understand, I remember in cuda you can only access device memory in kernel functions, like those with the `__device__`  prefix.
in the code you provided, does `ptr` a device pointer, if so why it can be accessed directly? if not, when will the data it pointed be copied to device memory? 

>DPCPP Runtime copies device memory to host.

I can't understand this sentence, I thought data were firstly assigned in the host and then copied to device memory to be used in the computation. why do I want to copy device memory to host?
I tried the code below, but honestly, I don't understand the mechanics of it, 
like why do I have to use `{}` in lines 4-10, and because of it the output `a` became a short logical address.
and what is a `buffer` ? a container encapsulates an array? does it exist in host memory? or in device memory?
and why do I have to use an `accessor` to write or read it? to synchronize threads? then, are these thread host threads? or device threads?
can you kindly recommend something like documentation or API reference about SYCL? please.
```c++ 
void test1(){
    cl::sycl::queue q;
    cl::sycl::buffer<int> buffer_a(10);
{
    auto acc_a = buffer_a.get_access<cl::sycl::access::mode::write>();
    int *a = acc_a.get_pointer();
    std::cout<<"a: "<<a<<"\n";
    for (int i = 0; i < 10; i++)
        a[i] = 10 - i;
}
    q.submit([&](cl::sycl::handler &cgh) {
        auto acc_a_read = buffer_a.get_access<cl::sycl::access::mode::read>(cgh);
        cgh.interop_task([=](const cl::sycl::interop_handler &ih) {
            int* da = (int* )ih.get_mem<cl::sycl::backend::cuda>(acc_a_read);
            std::cout<<"da: "<<da<<"\n";
        });
    });
    q.wait_and_throw();
}
```

**Comment by densamoilov** [comment]
Hi @MOLOjl, the questions you are asking are more about SYCL than oneDNN so answering those would require explaining basic SYCL abstractions (e.g. SYCL buffers, buffer accessors, etc.). There is a [SYCL specification](https://www.khronos.org/registry/SYCL/specs/sycl-2020/pdf/sycl-2020.pdf) that contains answers to your questions.

Some of your questions, such as when and where underlying memory is created is probably an implementation detail. If you are looking for clarifications from implementation perspective then you can ask a question in the [DPC++ compiler GitHub](https://github.com/intel/llvm/issues).

**Comment by densamoilov** [comment]
> DPCPP Runtime copies device memory to host.

By the way, here I was talking about SYCL Runtime, sorry for the confusion.

**Comment by MOLOjl** [comment]
thanks very much🙏
