### ISSUE TITLE
Runtime error with scalar kernel args.

### ISSUE THREAD

**Issue by Airbala** [oneapi-src/oneDNN#1222]
@igorsafo Here I am again. I asked you several questions in issue [#1174](https://github.com/oneapi-src/oneDNN/issues/1174), Thanks for you kind help, That really means a lot to me.  I'm still working on integarting oneDNN with my OpenCL device. A serious problem happend and I have nothing to do but ask for your help. I followed your instruction and  I started work with eltwise  primitive, when I was trying to  run eltwise primitive on my device 
![image](https://user-images.githubusercontent.com/39217135/146633046-a7fa5d4b-2736-40a8-8e99-f5acadc31453.png)
so I changed my device, I use NIVIDIA GPU's OpenCL interfaces, the error is the same. It's obvious that there is a problem on scalar kernel args. 
finally I use my intel gpu UHD, it worked.  I don't konw why. I checked file ref_eltwise.cpp and ref_eltwise.cl, I couldn't find anything  help.  Could you please tell me what to do with it? By the way,  I use oneDNN V1.4.. Thanks a lot

**Comment by vpirogov** [comment]
@igorsafo is out now, maybe @densamoilov would be able to help though.

**Comment by densamoilov** [comment]
Hi @Airbala, it's a llittle unclear from the description what the problem is about. The error message "could not execute a primitive" doesn't provide enough information. Can you please describe the problem in more details?

If you are asking about the OpenCL error message `KERNEL_ARG_INFO_NOT_AVAILABLE` then I suspect you didn't pass `-cl-kernel-arg-info` compiler option upon `clBuildProgram` call. From the [OpenCL documentation](https://www.khronos.org/registry/OpenCL/sdk/2.2/docs/man/html/clGetKernelArgInfo.html) for `clGetKernelArgInfo`:
> Kernel argument information is only available if the program object associated with kernel is created with clCreateProgramWithSource and the program executable is built with the -cl-kernel-arg-info option specified in options argument to clBuildProgram or clCompileProgram.

As far as I know Intel OpenCL always stores information about kernel arguments regardless of whether the `-cl-kernel-arg-info` is passed.

Also, please note that the ability to query information about kernel arguments is missing before OpenCL 1.2

**Comment by Airbala** [comment]
Thanks a lot. It really works when I follow you instructions. The runtime error is caused by OpenCL error, and if I change the argname to float instead of using clGetArgInfo, It works well. So if I pass the  -cl-kernel-arg-info compiler option upon clBuildProgram call, is it corrcet that I should  add "-cl-kernel-arg-info" after "const std::string &options = kernel_ctx.options();"    The official docs just tell me diffirent type of args without an useful example. The picture is form file ocl_gpu_engine.cpp. and my device support OpenCL 1.2, Is it able to query information about kernel arguments? 
![code](https://user-images.githubusercontent.com/39217135/146728535-87df9bd7-137a-4ac8-a39c-2abfc20748f5.png)

By the way. could you please offer me some advice to improve perfoemance with OpenCL. The performance is not good when I just work with ref_primitives. I would appreciate it if you give me some useful advice.

**Comment by densamoilov** [comment]
@Airbala, if I understand the problem correctly the error occurs here:
https://github.com/oneapi-src/oneDNN/blob/c95c03fce94ba0c0e9563b54c0516b8d5509f190/src/gpu/ocl/ocl_utils.cpp#L107-L137

The code above identifies and validates scalar data types for the given kernel. When OpenCL doesn't return any information about kernel data types then it's considered an error and `status::runtime_error` is returned.
OpenCL 1.2 should support querying information about kernel arguments. As you correctly assumed you just need to add `-cl-kernel-arg-info` to `options`. This should address the problem.

> By the way. could you please offer me some advice to improve performance with OpenCL. 

The OpenCL kernels can be optimized by using OpenCL extensions that can utilize the capabilities your device has, for example [subgroups](https://github.com/KhronosGroup/OpenCL-Docs/blob/master/ext/cl_khr_subgroups.asciidoc).
In the element-wise primitive implementation for Gen9 we check whether the device supports [Intel subgroups](https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_subgroups.html) of size 16 to use them for optimizing the kernel.
https://github.com/oneapi-src/oneDNN/blob/c95c03fce94ba0c0e9563b54c0516b8d5509f190/src/gpu/ocl/gen9_eltwise.hpp#L70-L75

The available extensions largely depends on OpenCL vendor and version.
