### ISSUE TITLE
Request for upsampling_linear support for align_corners=Ture

### ISSUE THREAD

**Issue by Semmer2** [oneapi-src/oneDNN#1223]
# Summary
We need the function upsampling_linear or related functions support for parameters align_corner=True

# Problem statement
Hi, We are using IPEX to enabling python inferring acceleration of BasicVSR model, which is vital to our current work. And the IPEX module need the feature we stated above. So we are wandering if you have any plan for supporting such feature? Any information would be appreciated.

# Preferred solution
Supporting parameters align_corner=True in upsampling_linear function.

**Comment by densamoilov** [comment]
Hi @Semmer2, oneDNN has a [resampling](https://oneapi-src.github.io/oneDNN/dev_guide_resampling.html) primitive that supports linear/bilinear/trilinear interpolation algorithms. Please take a look at [this ](https://github.com/oneapi-src/oneDNN/issues/653#issuecomment-589388546 )explanation of the resampling behavior.

**Comment by vpirogov** [comment]
Closing, as we currently have no plans to introduce additional interpolation modes.
