### ISSUE TITLE
How to make the Resampling support data tag nhwc

### ISSUE THREAD

**Issue by yinghu5** [oneapi-src/oneDNN#1224]
when I read the doc :  https://oneapi-src.github.io/oneDNN/dev_guide_resampling.html#doxid-dev-guide-resampling
Resampling implementation supports data with arbitrary data tag (nchw, **nhwc**, nChw16c, etc.) 

so try the "nhwc" by the example cpp code in  oneDNN/examples/primitives/resampling.cpp.  
Just change the src_dims and dst_dims as below : 

//resampling_nhwc.cpp
    // Source (src) and destination (dst) dimensions.
    memory::dims src_dims = {N, IH, IW, IC};
    memory::dims dst_dims = {N, OH, OW, IC};

    // Allocate buffers.
 ...

    // Create memory descriptors and memory objects for src and dst.
    auto src_md = memory::desc(src_dims, dt::f32, tag::nhwc);
    auto dst_md = memory::desc(dst_dims, dt::f32, tag::nhwc);

build it with the below command 
>source /opt/intel/oneapi/compiler/latest/env/vars.sh
>source /opt/intel/oneapi/dnnl/latest/env/vars.sh
>dpcpp resampling_nhwc.cpp -I$DNNLROOT/include -L$DNNLROOT/lib -ldnnl -o  resampling_nhwc

Run it and get the error 
$ ./resampling_nhwc
oneDNN error caught:
        Status: invalid_arguments
        Message: could not create a resampling forward descriptor
Example failed on CPU.

So want to know how to set right argements to make sure the  Resampling with data tag nhwc work. thank you!

**Comment by igorsafo** [comment]
Hi @yinghu5 ,
While physical data format can be `nchw`, `nwhc`, etc, the logical order of dimensions specified in memory descriptor should be almost always `nchw`. Here is correct way to create memory descriptor with `nhwc` memory format:
```cpp
// Source (src) and destination (dst) dimensions.
// Logical order of dimensions is always the same for each oneDNN primitive. For most of the primitives the order or dimensions is ncdhw
memory::dims src_dims = {N, IC, IH, IW}; 
memory::dims dst_dims = {N, IC, OH, OW};
// Create memory descriptors and memory objects for src and dst.
// Here we create memory descriptor with specified dimensions, but also passing information to the library that physical format is different from the logical one.
auto src_md = memory::desc(src_dims, dt::f32, tag::nhwc);
auto dst_md = memory::desc(dst_dims, dt::f32, tag::nhwc);
```

There are some exceptions for primitives like RNN, which don't use `nchw` notion, but `tnc` due to differences in target DNN models (Vision vs Sequential).

Regards,
Igor

**Comment by yinghu5** [comment]
@igorsafo , thank you much for the explanation. Got it. please close the issue now.
  
For who reads the question,  please note:  **physical data format vs. logical odata format**  
DNNL memory format distinguishes between logical and physical tensor representation:
-  Physical format of data and weights memory objects can be other  memory format like NHWC or NCHW
-  Logical format used in memory description for some primitive , in most of case, it should be fixed like NCHW
-
so the expected memory desc for common primitive like Conv, Resampling should be like: 
auto src_md = memory::desc(
        {N, C, H, W}, // logical dims, the order is **fixed** by a primitive
        memory::data_type::f32, // tensor's data type
        memory::format_tag::nhwc // phyical (**real**) memory format, NHWC in this case
);
refer to https://oneapi-src.github.io/oneDNN/page_getting_started_cpp.html
