### ISSUE TITLE
Harnessing Deep Learning via a Single Building Block

### ISSUE THREAD

**Issue by AnonymousYWL** [oneapi-src/oneDNN#1226]
Is the format of the input tensor in OneDNN NCHW or NHWC (Figure 7)?

**Comment by dzarukin** [comment]
Hi @AnonymousYWL, thanks for the question.
In oneDNN user is responsible for setting a format on any tensor, either inputs or output. There are two options:
* Use specific format available [here](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl.hpp#L1297).
* Pass the responsibility to the library by using `format_tag::any`.

Later would require a query from the library to get the format library set for specific memory descriptor to create memory object around this memory descriptor.
You may find some relevant information [here](https://oneapi-src.github.io/oneDNN/page_memory_format_propagation_cpp.html) and [here](https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html). Thank you.

**Comment by AnonymousYWL** [comment]
Thank you for your reply, which is very helpful to me.

**Comment by igorsafo** [comment]
Hi @AnonymousYWL ,
As I understand you are talking about a document "Harnessing Deep Learning via a Single Building Block". In that document oneDNN uses blocked layout nChwBc for fp32 computations, which is nChw16c (block size is 16). You can find it in Section III B. 1)  ("Direct convolution loops and prior art", algorithm 3).
As @dzarukin mentioned, user should create oneDNN convolution with `foramt_tag::any` and the library will decide what format is the best for a given problem and a target platform.
