### ISSUE TITLE
What are the fonts used for?

### ISSUE THREAD

**Issue by dnns92** [oneapi-src/oneDNN#1228]
What are the fonts "Font Awesome", "Front lato" and "Font roboto" used for? (v2.3 and prior). Am I right in the assumption that those are used for the documentation? So if I dont build the docs, I dont need the fotns? Are the fonts used anywhere else?

Cheers

**Comment by vpirogov** [comment]
Hi @dnns92, 

These fonts are used in documentation only. If you are not building documentation it's safe to drop `/doc` folder altogether.

These are removed in oneDNN v2.4 as you noticed.
