### ISSUE TITLE
defining int16 datatype 

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1229]
Hi,
I don't find s16 and u16 data types in oneDNN library. How can I define them and which functions and classes should be defined to support these data types?

**Comment by igorsafo** [comment]
Hi @kokhazade ,

The reason there is no s16/u16 is that there are s8/u8 which provide more performance on modern CPUs. So before adding these data types you should understand what are the benefits comparing to the existing s8/u8 and bf16/fp16 support.

To add a new data type you will need to make changes in the following parts of the library:
- Extend API with new data type (https://github.com/oneapi-src/oneDNN/tree/master/include/oneapi/dnnl)
- Update core to support new data type (https://github.com/oneapi-src/oneDNN/tree/master/src/common)
- Add an implementation that will support new data type (https://github.com/oneapi-src/oneDNN/tree/master/src/cpu)
- Extend tests to to test your implementation with new data type  (https://github.com/oneapi-src/oneDNN/tree/master/tests)

**Comment by kokhazade** [comment]
Hi @igorsafo,
Thanks for your response.
