### ISSUE TITLE
Using oneDNN kernels in other frameworks

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1230]
Hi,

Is there any way to use oneDNN or parts of it (like convolution kernels) as the base of a framework like TensorFlow or keras?

**Comment by igorsafo** [comment]
Hi @kokhazade ,
oneDNN is already used inside of popular DL frameworks like TensorFlow, Pytorch, etc.
Here is an RFC in TensorFlow to enable oneDNN by default for x86 systems: https://github.com/tensorflow/community/pull/400
Do you have any specific question?

Regards,
Igor

**Comment by vpirogov** [comment]
Specifically with Tensorflow you can enable oneDNN optimizations by setting environment variable `TF_ENABLE_ONEDNN_OPTS=1`. This feature is available in [Tensorflow 2.5](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0) and later.

**Comment by vpirogov** [comment]
And here's [a blog](https://medium.com/pytorch/accelerate-pytorch-with-ipex-and-onednn-using-intel-bf16-technology-dca5b8e6b58f) on oneDNN in Pytorch.

**Comment by kokhazade** [comment]
Hi @igorsafo and @vpirogov ,
Thanks for your responses.
I made a change (add a method) in oneDNN and build it again to test my method. What I want is introducing this changed oneDNN to a framework like TensorFlow to use and check my changes via that framework.

**Comment by vpirogov** [comment]
Tensorflow integrates oneDNN at the source code level, so you'll need to build the [framework from source](https://www.tensorflow.org/install/source) to incorporate your changes. As you are introducing new API you'll also need to integrate it into Tensorflow. You can find implementations for Tensorflow operations based on oneDNN [here](https://github.com/tensorflow/tensorflow/tree/57349603a546ab5a1c7041484854c79654f9ee36/tensorflow/core/kernels/mkl).

**Comment by kokhazade** [comment]
Thanks @vpirogov
