### ISSUE TITLE
Build failure in src/cpu/aarch64/jit_uni_softmax.hpp

### ISSUE THREAD

**Issue by nSircombe** [oneapi-src/oneDNN#1256]
# Summary
The recent changes to the Softmax primitive (https://github.com/oneapi-src/oneDNN/commit/2622509c9568259e32a9f4d8f83e2c0252efce2d) appear to have broken the build on AArch64, which now fails for both Clang and GCC.

# Version
Build failure observed with the current HEAD: https://github.com/oneapi-src/oneDNN/commit/2622509c9568259e32a9f4d8f83e2c0252efce2d
Previous commit is working fine: https://github.com/oneapi-src/oneDNN/commit/8b68d014abe8d8fb86c7a97e80cea0d4c24b6b8c

# Environment
* CPU make and model: Neoverse-N1 (AArch64)
* OS version: CentOS 8 and Ubuntu 20.04
* Compiler version: Clang 9, GCC 7, 8, 9 and 10
* CMake version: 3.20.1

# Steps to reproduce
- Checkout current HEAD of master
- `mkdir build && cd build`
- `cmake -DDNNL_CPU_RUNTIME=OMP -DDNNL_BUILD_FOR_CI=ON ../. && make -j`

# Observed behavior
The recent changes to the Softmax primitive (https://github.com/oneapi-src/oneDNN/commit/2622509c9568259e32a9f4d8f83e2c0252efce2d) appear to have broken the build on AArch64, which now fails for both Clang (v9) and GCC (v7, 8, 9 and 10), with an error of the form:

```
In file included from /code/oneDNN/src/cpu/aarch64/jit_uni_softmax.cpp:30:
/code/oneDNN/src/cpu/aarch64/jit_uni_softmax.hpp: In member function 'dnnl::impl::status_t dnnl::impl::cpu::aarch64::jit_uni_softmax_bwd_t<isa>::pd_t::init(dnnl::impl::engine_t*)':
/code/oneDNN/src/cpu/aarch64/jit_uni_softmax.hpp:135:44: error: there are no arguments to 'set_default_formats_common' that depend on a template parameter, so a declaration of 'set_default_formats_common' must be available [-fpermissive]
  135 |                     && mayiuse(sve_512) && set_default_formats_common()
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/code/oneDNN/src/cpu/aarch64/jit_uni_softmax.hpp:135:44: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
```

I think, looking at the x86 implementation, it should be sufficient to swap `set_default_formats_common()` for `set_default_formats() == status::success` in `src/cpu/aarch64/jit_uni_softmax.cpp`. With this change it builds OK, and `make test` passes on AArch64. But I'm not that familiar with the `aarch64/jit_uni_*` codebase.

# Expected behavior
`cmake -DDNNL_CPU_RUNTIME=OMP -DDNNL_BUILD_FOR_CI=ON ../. && make -j` should lead to a sucessfull build.

**Comment by nSircombe** [comment]
Hi @kawakami-k, we encountered the above build failure in our downstream pipelines over the weekend. I was wondering if you had seen the same issue, and if you have a resolution?

**Comment by kawakami-k** [comment]
@nSircombe I encountered the same issue. I'm making a patch for AArch64. Could you please wait a week?

**Comment by nSircombe** [comment]
Hi @kawakami-k, that's great to hear!
I'd be very happy to run the patch through our CI when it's ready (we test more compiler versions than the Drone CI covers).

**Comment by dzarukin** [comment]
Hi! This is introduced by me, I changed the name of the method to set formats for dst with tag::any and completely forgot to cover aarch64 build with validation. Sorry about it.
I'll prepare a patch to fix it and we also will investigate our options to cover aarch64 build internally to avoid such kind of things. Issues have popped up like mushrooms recently (reorders for three times, now this...).

**Comment by kawakami-k** [comment]
@dzarukin @nSircombe 

This is a patch I'm working on. I've tried to incorporate as much of the current x64 functionality as possible.
So far, gtests/test_softmax passes, but I'm fixing some failures with `./benchdnn --mode=C -v1 --engine=cpu --softmax --batch=test_softmax_ci`.

https://github.com/fujitsu/oneDNN/commits/softmax

**Comment by dzarukin** [comment]
Hi @kawakami-k, thanks for handling this. I couldn't guess you'd like to promote different data types for src and dst feature as well. Please let me know if help is needed. Thank you.

**Comment by kawakami-k** [comment]
@nSircombe @dzarukin 
Now, I'm making the patch 
https://github.com/kawakami-k/oneDNN/tree/issue1256

@nSircombe 
The CI results also look almost good, but it looks like Ubuntu16+ACL build is failing. Could you please check?
https://cloud.drone.io/kawakami-k/oneDNN/275

I'm currently trying to modify a few more instructions for performance tuning. Please wait a few more days for the pull request.

**Comment by nSircombe** [comment]
Hi @kawakami-k,
Humm, that failure is a little confusing as it shows up nowhere near to the ACL src. I suspect it's related to the C++ std being set to C++14, but I'm not sure why it's impacting only the Ubuntu 16 build. @dzarukin, do you have any idea?

Do you see this failure if you run you Ubuntu 16 pipeline without the new patch?

I'll try the patch on our internal CI and see if there are any problems there, but we're using Ubuntu 20.04 so I suspect it won't show up.

**Comment by kawakami-k** [comment]
@nSircombe 
> Do you see this failure if you run you Ubuntu 16 pipeline without the new patch?

CI pipeline without the patch is running here.
https://cloud.drone.io/kawakami-k/oneDNN/279

The buile error may also be reproducible with a cross compiler on x64 Ubuntu16.04.
  - apt-get update && apt-get install -y git build-essential cmake binutils-aarch64-linux-gnu crossbuild-essential-arm64 pkg-config-aarch64-linux-gnu python3 wget libglib2.0-dev
  - export CC=aarch64-linux-gnu-gcc
  - export CXX=aarch64-linux-gnu-g++
  - .github/automation/build_acl.sh  --version 21.11 --arch arm64-v8a --root-dir $(pwd)/ComputeLibrary

**Comment by nSircombe** [comment]
Hi @kawakami-k,

A bit more checking, and this build failure is down to the compiler version it appears. The issue can be resolved with a small change to the offending kernel in Compute Library, which move the build on, but it stops again at the next occurrence. It would be a while now, given where we are in the release cycle, before these changes would land in a released version of Compute Library, and given the limited impact (i.e. later versions of the GCC 7 family and all later versions of GCC are OK) I don't think there's much motivation to resolve this specific failure.

...for now, I would suggest that the reviewers ignore the Ubuntu16 failure when reviewing your PR to address the softmax issue - @dzarukin, @vpirogov, does that sound reasonable?

In fact, from my point of view, I'm not sure there's much impetus to have Ubuntu 16 validation on the AArch64 build. It would be much more valuable to have a DroneCI stage building with GCC 10.2+ on Ubuntu 20.04. @vpirogov - would it be acceptable for us to modify these pipelines to drop the Ubuntu 16 build and add an Ubuntu 20 + GCC10 stage?

**Comment by kawakami-k** [comment]
Hi @nSircombe 
I also agree that ubuntu16 should be removed from the CI and added to Ubuntu20. I think it's better to match the support to the x64 target.

**Comment by nSircombe** [comment]
> I also agree that ubuntu16 should be removed from the CI and added to Ubuntu20

I'm happy to get a patch together for review to make those changes - I should have a chance next week.

**Comment by nSircombe** [comment]
I have a PR up to change the DroneCI pipelines as discussed above - #1276.

At present these will fail due to the issue highlighted here, but the ACL failure that @kawakami-k will be avoided, and we'll have an Ubuntu 20.04 + GCC 10 build stage too.

@kawakami-k - perhaps you could try out these CI changes on your fork?

**Comment by kawakami-k** [comment]
@nSircombe 
Thank you for the patch. Now, the new CI pipes are running.
https://cloud.drone.io/kawakami-k/oneDNN/283

**Comment by nSircombe** [comment]
Oh dear, that's a silly mistake. I should have spotted that in my own Drone run (https://cloud.drone.io/nSircombe/mkl-dnn/74/1/2) but I think I stopped it once I'd seen the ACL stage build Compute Library without issue.

Thanks @kawakami-k - I'll get it fixed!

**Comment by nSircombe** [comment]
@kawakami-k - I've pushed that fix to https://github.com/oneapi-src/oneDNN/pull/1276 now, thanks for pointing the mistake out.
