### ISSUE TITLE
Reapply change from #428, "Add declarations of explicit specializations and instantiations"

### ISSUE THREAD

**Issue by tkoeppe** [oneapi-src/oneDNN#1257]
# Summary

Pull request #428 was applied, but later rolled back because of a bug in GCC (https://github.com/oneapi-src/oneDNN/pull/428#issuecomment-478878114) with which it was incompatible.

That bug as since been fixed, so I would like to ask for the change from #428 to be reapplied.

**Comment by dzarukin** [comment]
Hi @tkoeppe, thanks for reporting the issue. We see that this may cause issues in certain scenarios (luckily we haven't encountered them yet).
The plan is to add `Wundefined-func-template` compile option by default when building oneDNN with Clang compiler to make sure this won't regress in the future. We will likely target master branch only trying to fit oneDNN v2.6 release timeframe. Does it sound good for you? Thank you.

**Comment by tkoeppe** [comment]
@dzarukin That sounds great, thank you very much!

**Comment by tkoeppe** [comment]
Hello :-) Did you happen to get a chance to look at this?

**Comment by tkoeppe** [comment]
Sure thing, thanks!

**Comment by vpirogov** [comment]
The core team currently does not have bandwidth to work on this item. Feel free to rebase the changes on top of master and open a PR.

**Comment by tkoeppe** [comment]
OK, will do!

**Comment by tkoeppe** [comment]
Actually, this seems like quite an undertaking to rebase, so I might just leave it be.
