### ISSUE TITLE
ERROR of "No int8 convolution implementation is available for this platform."

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1270]
Hi,
Two questions:
1- I ran the cnn_inference_int8.cpp example and saw the output. But when I change the algorithm of "convolution_direct" to "convolution_winograd" I get the error of "No int8 convolution implementation is available for this platform.". It's the only change that I have made. Am I doing right to have int8 winograd convolution or I should change another part to fix this error?

When I change the algorithm of f32 inference to "convolution_winograd" I get the error of:
"oneDNN error caught: 
	Status: unimplemented
	Message: could not create a primitive descriptor iterator
"
2- How should I change the example to gemm?Which parts I have to change other than algorithm?

I am using oneDNN v2.2.0

**Comment by dzarukin** [comment]
Hi @kokhazade, thanks for the question. Int8 Winograd is highly specialized implementation for certain type of convolution problems. It has only coverage for AVX512 and for a very limited number of problems. It's highly likely that the problem in the example doesn't fit the range of accepted problem to solve with it. Certain limitations are described [here](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html) (search for "wino" keyword). Thanks.

**Comment by kokhazade** [comment]
Thank you @dzarukin 
I'll check the limitations.
What about the gemm? How should I implement gemm convolution example?

**Comment by dzarukin** [comment]
> What about the gemm? How should I implement gemm convolution example?

Do I get it right the desire is to trigger GeMM-based convolution implementation? If yes, the best option might be to use plain abcd-like layouts since none of jit-ted implementation supports it. Thanks.

**Comment by kokhazade** [comment]
Yes, you do. But there is no algorithm called convolution-gemm in the enum and probably I should create the example for int8 gemm in a way different from direct and winograd.

**Comment by kokhazade** [comment]
What is the difference between sgemm and matmul in this library?

**Comment by dzarukin** [comment]
These are terms we use to describe different type of API with different capabilities.
"Sgemm" is a standalone primitive-less kind of API which has a single stage of setup and execution. It mostly relies on kernels migrated from Intel MKL.
"Matmul" is one of primitives API that supports primitives extension feature such as attributes, which sgemm doesn't. This also implies two stage flow - creation and execution are separated. Matmul underneath may dispatch between different kernels - brgemm, sgemm kernel or reference, while sgemm API is tied to sgemm kernels only it's shipped with.
Thanks.

**Comment by kokhazade** [comment]
Thanks @dzarukin ,
If I use the matmul primitive, Does it change the shape of original input and kernel to the suitable shape for matrix multiplication convolution or I should reshape them out of primitive?

**Comment by dzarukin** [comment]
I'm sorry, I don't get the question.

Convolution primitive can be replaced with a direct call to matmul primitive in the only particular case - when kernel size is 1 (`kd = kh = kw = 1`). If `mb != 1`, then it's a batched matmul.

I'm not sure about the purpose of replacing convolution with matmul. The fact that gemm approach can be used to compute convolution, it doesn't mean it's a straightforward call. You may inspect [this file](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/gemm_convolution.cpp) to get the idea.

If this doesn't cover your question, please provide more details on what you are trying to achieve. Thank you.
