### ISSUE TITLE
Hard to understand how the file dispatch.cpp in ocl runtime works.

### ISSUE THREAD

**Issue by Airbala** [oneapi-src/oneDNN#1284]
Could anyone please help me understand how the file dispatch.cpp works? I've read about the file, I think it means to transform a memory descriptor to ocl group worksize and local work size. I don't understand what nesting_level means and how the functions in the file work, especially the generate() function.  Could you please give me an example of how  it compute the dims and the worksize? I would appreciate it if you help me. Thanks.

**Comment by echeresh** [comment]
`compute::dispatch_t` is used to assist mapping of problem dimensions to global work item IDs. Let's say we have 4 indices that are to be iterated by global IDs. The dispatch object is used to determine:
- Order of indices
    - This can be decided based on the provided memory descriptor. For better memory locality more inner dimensions should be iterated first. Here `nesting_level` works as a hint: dimensions with smaller levels are more outer and assigned to more outer iterm IDs.
- Mapping of indices to work item IDs. We may have up to 3 dimensions for work items so it means some dimensions are to be packed into one work item ID and then extracted with division/modulus operations

Unfortunately the underlying algorithm/implementation are quite complicated - for example it's heavily macro-based. In most cases it makes sense to directly initialize `compute::nd_range_t` and then manually unpack problem indices from global work item IDs using the same division/modulus operations.
