### ISSUE TITLE
how to build oneDNN with test?

### ISSUE THREAD

**Issue by wangzy0327** [oneapi-src/oneDNN#1286]
how to build oneDNN with test?

**Comment by wangzy0327** [comment]
> @wangzy0327, oneDNN [default build](https://oneapi-src.github.io/oneDNN/dev_guide_build.html) includes tests. You can run `ctest` to execute basic validation. Extended validation is done by [benchdnn](https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn#benchdnn).

When I want to run unittest(oneDNN/tests/gtests/main.cpp) to verify code by google test in directory(oneDNN/tests/bulid), the build process get error.
The error as follows
![image](https://user-images.githubusercontent.com/22990858/155636840-397a6d97-5749-4266-87e8-fe0b9d2e0ab6.png)

**Comment by densamoilov** [comment]
You don’t have to build gtest separately. Just build the library and the test will be built.

**Comment by wangzy0327** [comment]
> You don’t have to build gtest separately. Just build the library and the gtest will be built.

OK.If I want to make some extensions on the source code base, how to do unit test?

**Comment by densamoilov** [comment]
We don't have unit tests per se, but we have tests for [internals](https://github.com/intel-innersource/libraries.performance.math.onednn/tree/master/tests/gtests/internals). You can add new tests if you need. If the name of the test files starts with `test_` they will get picked up by [CMake](https://github.com/intel-innersource/libraries.performance.math.onednn/blob/66a82b5ada43ab5e6d4eee88042da88572395fb3/tests/gtests/internals/CMakeLists.txt#L24) and a common executable for all such tests can be found in `tests/gtests/internals/test_internals`.
If you want to have your tests in different executables then you register separate [targets](https://github.com/intel-innersource/libraries.performance.math.onednn/blob/66a82b5ada43ab5e6d4eee88042da88572395fb3/tests/gtests/internals/CMakeLists.txt#L43).

**Comment by wangzy0327** [comment]
> @wangzy0327, oneDNN [default build](https://oneapi-src.github.io/oneDNN/dev_guide_build.html) includes tests. You can run `ctest` to execute basic validation. Extended validation is done by [benchdnn](https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn#benchdnn).

When I build includes tests,the output is cannot find TBB(I set env variable but no work) at [TBBConfig.cmake](https://github.com/oneapi-src/oneDNN/blob/master/cmake/lnx/TBBConfig.cmake).how to sovle it?

![image](https://user-images.githubusercontent.com/22990858/155915683-3f47c523-9d19-4c37-bf28-a4800a38c82d.png)

**Comment by densamoilov** [comment]
@wangzy0327, the tests always need TBB even though `DNNL_CPU_RUNTIME` is `NONE`. I suspect `TBBROOT` points to a TBB directory whose layout is different from what [TBBConfig.cmake](https://github.com/oneapi-src/oneDNN/blob/210950486f13b2fb9c88d8c2b435a22cfa7d7562/cmake/lnx/TBBConfig.cmake#L76) expects.

**Comment by wangzy0327** [comment]
> @wangzy0327, the tests always need TBB even though `DNNL_CPU_RUNTIME` is `NONE`. I suspect `TBBROOT` points to a TBB directory whose layout is different from what [TBBConfig.cmake](https://github.com/oneapi-src/oneDNN/blob/210950486f13b2fb9c88d8c2b435a22cfa7d7562/cmake/lnx/TBBConfig.cmake#L76) expects.

OK，This is my own build oneTBB directory.
![image](https://user-images.githubusercontent.com/22990858/156089210-5df642f0-a845-46c2-8718-3eca9766dd72.png)

**Comment by densamoilov** [comment]
The layout is different.
Can you try to set `export CMAKE_PREFIX_PATH=~/sycl_workspace/oneTBB-debug/lib/cmake:$CMAKE_PREFIX_PATH`? This should allow to substitute `TBBConfig.cmake` with the config file from `lib/cmake`.

**Comment by wangzy0327** [comment]
> export CMAKE_PREFIX_PATH=~/sycl_workspace/oneTBB-debug/lib/cmake:$CMAKE_PREFIX_PATH
OK，Thx. It found TBBConfig.cmake by export CMAKE_PREFIX_PATH
![image](https://user-images.githubusercontent.com/22990858/156102671-264c5834-a464-48aa-ae56-bfcb24a5e518.png)
![image](https://user-images.githubusercontent.com/22990858/156102802-cf329f20-be83-4a48-9750-b60f463c4aec.png)
Can I run tests some extensions on the source code base in folders marked with red boxes？

**Comment by densamoilov** [comment]
Yes, I desribed it [here](https://github.com/oneapi-src/oneDNN/issues/1286#issuecomment-1052532249).
