### ISSUE TITLE
maxpool with nchw8c input data performance is poorer than nchw input data in avx2 machines

### ISSUE THREAD

**Issue by praveen0447** [oneapi-src/oneDNN#1289]
# Summary
MaxPool with input data format nchw8c on avx2 machine is performing poorer when compared with nchw data input 
Input parameters for maxpool are 
input -      1,256,20,20
kernel -     13,13
padding -  6,6
stride -      1,1

# Version
dnnl_verbose,info,oneDNN v1.4.0 (commit N/A)

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)

flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

* OS version (`uname -a`)
 Linux hyd-hnalla-l 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
* Compiler version (`gcc --version`)
gcc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE
* CMake version (`cmake --version`)
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
* CMake output log
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- GPU support is disabled
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen dot 
-- Found Git: /usr/bin/git (found version "2.20.1") 
fatal: not a git repository (or any parent up to mount point /mathworks/devel/sandbox)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Configuring done
-- Generating done
-- Build files have been written to: /sandbox/pgajula/Projects/DeepLearning/mkldnnLibs/Linux/oneDNN-1.4/build

* git hash (`git log -1 --format=%H`)
***
# Steps to reproduce
Below steps gives me performance numbers as for nchw data format. 

./tests/benchdnn/benchdnn --pool --mode=P mb1ic256_ih20iw20_oh20ow20_kh13kw13_sh1sw1_ph6pw6

**Output template: perf,%engine%,%name%,%prb%,%-time%,%0time%
perf,cpu,,--pool mb1ic256ih20oh20kh13ph6,9.27002,13.2069**

Attached is the standalone setup[Con+MaxPool.zip](https://github.com/oneapi-src/oneDNN/files/8155313/Con%2BMaxPool.zip) which reproduces the below-benchmarking numbers with nchw8c data format . 

Step to build and Run 
1. Copy the Makefile and sample_net.cpp to examples folder .
2. Change the MKLDNN_PATH to desired location in Makefile
3. do make in terminal window where Makefile is present 
4. It creates a sample_net_exe. Run this on the terminal by setting verbose to 2 . You will see the below numbers.

dnnl_verbose,exec,cpu,pooling,ref:any,forward_inference,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:aBcd8b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic256_ih20oh20kh13sh1ph6_iw20ow20kw13sw1pw6,**53.708**
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:abcd:f0,,,1x256x20x20,2.81396
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:aBcd8b:f0,,,1x256x20x20,4.69897
dnnl_verbose,exec,cpu,convolution,jit:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,,alg:convolution_direct,mb1_ic256oc256_ih20oh20kh3sh1dh0ph1_iw20ow20kw3sw1dw0pw1,3.01001
dnnl_verbose,exec,cpu,pooling,ref:any,forward_inference,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:aBcd8b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic256_ih20oh20kh13sh1ph6_iw20ow20kw13sw1pw6,**62.4092**
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:abcd:f0,,,1x256x20x20,0.027832
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:aBcd8b:f0,,,1x256x20x20,0.078125
dnnl_verbose,exec,cpu,convolution,jit:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,,alg:convolution_direct,mb1_ic256oc256_ih20oh20kh3sh1dh0ph1_iw20ow20kw3sw1dw0pw1,0.916016
dnnl_verbose,exec,cpu,pooling,ref:any,forward_inference,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:aBcd8b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic256_ih20oh20kh13sh1ph6_iw20ow20kw13sw1pw6,**53.7651**
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:aBcd8b:f0 dst_f32::blocked:abcd:f0,,,1x256x20x20,0.0180664
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:aBcd8b:f0,,,1x256x20x20,0.0258789
dnnl_verbose,exec,cpu,convolution,jit:avx2,forward_inference,src_f32::blocked:aBcd8b:f0 wei_f32::blocked:ABcd8b8a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd8b:f0,,alg:convolution_direct,mb1_ic256oc256_ih20oh20kh3sh1dh0ph1_iw20ow20kw3sw1dw0pw1,0.955078

Essentially max pool with nchw8c is performing poorer when compared with nchw input. This kind of scenario occurs when there are convolution layers before and the data is in nchw8c format to max pool. I tried to reproduce the same with a standalone setup.

This issue appears to be resolved with 2.5 . Could you let us know what is the exact version it is fixed? Is there a patch that i could apply in 1.4 for improving the performance

# Observed behavior
Poor performance with nchw8c

# Expected behavior
Better performance with nchw8c

**Comment by dzarukin** [comment]
Hi @praveen0447, thank you for the question. The particular commit that enables jit implementation for this particular problem seems to be `77c71e5`. The problem is between rls-v1.4 and rls-v2.5 there were multiple changes, and it will be quite hard to apply this particular one considering other changes could affect the code as well.

I strongly encourage to update to the latest oneDNN version to have latest available changes and get support if there are any issues on your side with oneDNN. Thanks.

**Comment by dzarukin** [comment]
Feel free to reopen if case of any questions. Thanks.
