### ISSUE TITLE
[benchdnn] Understanding data layout

### ISSUE THREAD

**Issue by TharinduRusira** [oneapi-src/oneDNN#1290]
Hi,
I'm running the `conv` benchmark and have trouble understanding how to derive `abcd`-type tags. Correct me if wrong but I think, in order to get transposed layouts, I have to be aware of the assumed initial layouts. 

My preferred data layouts for the three tensors are,

- input[mini batch][input height][input width][input feature map]
- weights[filter height][filter width][input feature map][output feature map]
- output[mini batch][output height][output width][output feature map]

What should be my `stag`, `wtag`, and `dtag` values? 

Thanks,

**Comment by dzarukin** [comment]
Hi @TharinduRusira, thank you for the question.
oneDNN supplies both versions of tags for most formats. They may be found [here](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_types.h#L164).
For input it will be `nhwc` or `acdb`.
For weights it will be `hwio` or `cdba`.
For output it will be `nhwc` or `acdb` (same as input).
Benchdnn supports both versions of tags. Checking for a first tag by regular notation in the header file will instantly give its `abcd`-like counterpart. Thank you.

**Comment by TharinduRusira** [comment]
Thanks @dzarukin!
