### ISSUE TITLE
gpu: cuda: Cuda matmul benchdnn failure cases

### ISSUE THREAD

**Issue by AidanBeltonS** [oneapi-src/oneDNN#1292]
# Summary
During the addition of USM support for the CUDA backend, #1285, some failing matmul tests were encountered.
These tests were set to unsupported. 
This issue is a follow up to track the limitations.

# Version
githash: 471efa1d5b4e03dd3cfa8a2181b1c50f8c75e08e
DPC++: 8ab136feb560bc6debc5557c67c3eeb8c1336c23
CUDA: 11.5
GPU:  Nvidia Titan RTX

# Descriptions

#### Transposed destination:
Transposed destination unsupported.
Benchdnn example: `./tests/benchdnn/benchdnn --matmul --engine=gpu --stag=ab --wtag=ab --dtag=ba --runtime_dims_masks=15:15 2048x13:13x512_n"DLRM:0*1"`

Failure error:
```
 ** On entry to GEMM_EX  parameter number 16 had an illegal value
terminate called after throwing an instance of 'dnnl::impl::gpu::nvidia::cublas_error'
  what():  At :/onednn/src/gpu/nvidia/cudnn_matmul_impl.hpp : 321cublasGemmEx : CUBLAS_STATUS_INVALID_VALUE
Aborted (core dumped)
```

#### s8 bias mismatch:
Using bias with s8 types for matmul fail due to a mismatch in the gemm output.
cudnnSGemmEx supports inputs of s8 with a fp32 output if a bias of s8 is provided then this creates an issue due to the mismatch between the s8 and fp32 values.

Benchdnn example:
Fails: `./tests/benchdnn/benchdnn --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 77x133:133x117`
Passes: `/tests/benchdnn/benchdnn --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 77x133:133x117`

Failure error:
```
terminate called after throwing an instance of 'dnnl::impl::gpu::nvidia::cudnn_error'
  what():  At :/home/aidanbelton/oneDNN/src/gpu/nvidia/cudnn_matmul_impl.hpp : 328cudnnAddTensor : CUDNN_STATUS_BAD_PARAM
```

#### Primitive output scaler:
Output scaler as primitive is not supported:
Results in invalid output.

Benchdnn example: 
Fails: `./tests/benchdnn/benchdnn --matmul --engine=gpu --attr-oscale=common:0.5* 2048x13:13x512_n"DLRM:0*1"`
Passes: `./tests/benchdnn/benchdnn --matmul --engine=gpu --attr-oscale=common:0.5 2048x13:13x512_n"DLRM:0*1"`

Failure error:
```
 [   0][DST][0:0] exp_f32:-0.0112762 exp:-0.0112762 got:8.55006e+29 diff:8.55006e+29 rdiff:7.58237e+31
 [   1][DST][0:1] exp_f32:0.0600739 exp:0.0600739 got:-4.55502e+30 diff:4.55502e+30 rdiff:7.58237e+31
 [   2][DST][0:2] exp_f32:-0.260422 exp:-0.260422 got:1.97461e+31 diff:1.97461e+31 rdiff:7.58237e+31
 [   3][DST][0:3] exp_f32:-0.0788269 exp:-0.0788269 got:5.97695e+30 diff:5.97695e+30 rdiff:7.58237e+31
 [   4][DST][0:4] exp_f32:0.0405579 exp:0.0405579 got:-3.07525e+30 diff:3.07525e+30 rdiff:7.58237e+31
 [   5][DST][0:5] exp_f32:-0.0200806 exp:-0.0200806 got:1.52258e+30 diff:1.52258e+30 rdiff:7.58237e+31
 [   6][DST][0:6] exp_f32:-0.117676 exp:-0.117676 got:8.92261e+30 diff:8.92261e+30 rdiff:7.58237e+31
 [   7][DST][0:7] exp_f32:0.106491 exp:0.106491 got:-8.07455e+30 diff:8.07455e+30 rdiff:7.58237e+31
 [   8][DST][0:8] exp_f32:-0.257797 exp:-0.257797 got:1.95471e+31 diff:1.95471e+31 rdiff:7.58237e+31
```

**Comment by densamoilov** [comment]
Even with changes in 471efa1d5b4e03dd3cfa8a2181b1c50f8c75e08e there are still some cases that are unimplemented though they should probably be skipped instead. 
<details>
<summary>Unimplemented cases</summary>
run: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x1x1:1x1x1_n"RNN-T:JointNet_Linear2*3"
1430:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x1x1:1x1x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 1x1x1:1x1x1_n"RNN-T:JointNet_Linear2*3"
1432:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 1x1x1:1x1x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x1x1:1x1x1_n"RNN-T:JointNet_Linear2*3"
1434:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x1x1:1x1x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
1446:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
1448:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
1450:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=acb --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
1452:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=acb --dtag=acb --runtime_dims_masks=15:15 2x10x30:2x30x1_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
1462:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
1464:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
1466:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=acb --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
1468:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=acb --dtag=acb --runtime_dims_masks=15:15 3x30x1:3x1x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
1478:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
1480:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=abc --wtag=acb --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
1482:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=abc --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --stag=acb --wtag=acb --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
1484:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --stag=acb --wtag=acb --dtag=acb --runtime_dims_masks=15:15 1x30x30:1x30x20_n"RNN-T:JointNet_Linear2*3"
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 77x133:133x117
1692:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 --bia_mask=3 77x133:133x117
1693:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 --bia_mask=3 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 77x133:133x117
1698:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 -ask=3 77x133:133x117
1699:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 --bia_mask=3 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 77x133:133x117
1714:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 --bia_mask=3 77x133:133x117
1715:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 --bia_mask=3 77x133:133x117
run: --matmul --enginecfg=s8s8s8 --bia_dt=s8 77x133:133x117
1720:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 --bia_mask=3 77x133:133x117
1721:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 --bia_mask=3 77x133:133x117
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 --bia_mask=4 15x24x16:15x16x32
1802:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 --bia_mask=4 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 --bia_mask=6 15x24x16:15x16x32
1803:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=f32 --bia_mask=6 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 --bia_mask=4 15x24x16:15x16x32
1808:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 --bia_mask=4 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 --bia_mask=6 15x24x16:15x16x32
1809:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8f32 --bia_dt=s8 --bia_mask=6 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 --bia_mask=4 15x24x16:15x16x32
1824:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 --bia_mask=4 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 --bia_mask=6 15x24x16:15x16x32
1825:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=f32 --bia_mask=6 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 --bia_mask=4 15x24x16:15x16x32
1830:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 --bia_mask=4 15x24x16:15x16x32
run: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 --bia_mask=6 15x24x16:15x16x32
1831:UNIMPLEMENTED __REPRO: --matmul --engine=gpu --cfg=s8s8s8 --bia_dt=s8 --bia_mask=6 15x24x16:15x16x32
</details>
