### ISSUE TITLE
test_iface_pd_iter hangs when built with ACL

### ISSUE THREAD

**Issue by jondea** [oneapi-src/oneDNN#1295]
# Summary
`test_iface_pd_iter` hangs when built with ACL, specifically `TestFreeOpdesc` which was added in b7fd832ace0d893fe44ea3688de75ff04747eae0. 

# Version

oneDNN v2.6.0 (commit b7fd832ace0d893fe44ea3688de75ff04747eae0). Currently the latest commit on master.

# Environment

CI environment which builds with ACL, for example https://cloud.drone.io/oneapi-src/oneDNN/1216.

# Steps to reproduce

Build with ACL and run `test_iface_pd_iter`.

# Observed behavior

Test hangs for hours after this output
```
./test_iface_pd_iter
Note: Google Test filter = *:-*_GPU*
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from pd_iter_test_t
[ RUN      ] pd_iter_test_t.TestReLUImpls
[       OK ] pd_iter_test_t.TestReLUImpls (10 ms)
[----------] 1 test from pd_iter_test_t (10 ms total)

[----------] 2 tests from pd_next_impl
[ RUN      ] pd_next_impl.TestEltwiseImpl
[       OK ] pd_next_impl.TestEltwiseImpl (0 ms)
[ RUN      ] pd_next_impl.TestFreeOpdesc
5976
15344

[WARNING] tests/gtests/gtest/src/gtest-death-test.cc:1121:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 2 threads. See https://github.com/google/googletest/blob/master/docs/advanced.md#death-tests-and-threads for more explanation and suggested solutions, especially if this is the last message you see before your test times out.
```

# Expected behavior

Test to pass

**Comment by jondea** [comment]
Great, thank you for the update!

**Comment by mgouicem** [comment]
Thanks for the report. This is due to a gtest issue with death tests default settings. The patch is under review internally and should make it shortly to master.

The issue can be worked around by either:
- passing the `--gtest_death_test_style=threadsafe` on the command line
- adding `::testing::GTEST_FLAG(death_test_style) = "threadsafe";` [here](https://github.com/oneapi-src/oneDNN/blob/b7fd832ace0d893fe44ea3688de75ff04747eae0/tests/gtests/test_iface_pd_iter.cpp#L96)

**Comment by mgouicem** [comment]
Hi @jondea , could you confirm if you still see the issue with the current head of master.

**Comment by jondea** [comment]
@mgouicem just tested the current head of master and the test passes, thank you!
