### ISSUE TITLE
support the lstm,dropout and Dence layer?

### ISSUE THREAD

**Issue by xinsuinizhuan** [oneapi-src/oneDNN#1327]

**Comment by vpirogov** [comment]
You can find information on supported primitives in [oneDNN Developer Guide](https://oneapi-src.github.io/oneDNN).

[LSTM](https://oneapi-src.github.io/oneDNN/dev_guide_rnn.html#lstm) cell is supported in RNN primitive. Dense layer corresponds to oneDNN [inner product primitive](https://oneapi-src.github.io/oneDNN/dev_guide_inner_product.html). Dropout is not supported currently, though you can use [binary primitive](https://oneapi-src.github.io/oneDNN/dev_guide_binary.html) to apply pre-computed mask to activation.
