### ISSUE TITLE
dnnl::post_ops::kind(0) returns garbage value

### ISSUE THREAD

**Issue by krzychut** [oneapi-src/oneDNN#1337]
# Summary
When querying the kind of a post-op with `dnnl::post_ops::kind(int index)`, the function returns an uninitialized value for the first post-op, i.e. for `my_post_ops.kind(0)`

# Version
oneDNN v2.6.0 (commit 52b5f107dd9cf10910aaa19cb47f3abf9b349815)

# Environment
* CPU make and model: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
* OS version: Linux 2377c2589780 4.15.0-162-generic (Docker container based off `ubuntu:bionic`)
* Compiler version: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
* CMake version: 3.23.0
* CMake output log:
```
$ cmake .. # completely default build
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: X64
-- DNNL_LIBRARY_NAME: dnnl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE) 
-- Found PythonInterp: /usr/bin/python (found suitable version "3.6.9", minimum required is "2.7") 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Primitive cache is enabled
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Configuring done
-- Generating done
-- Build files have been written to: /data/sources/oneAPI/oneDNN/build
```
* git hash: 52b5f107dd9cf10910aaa19cb47f3abf9b349815

# Steps to reproduce
The shortest repro program I could manage:
```c++
#include <iostream>

#include "oneapi/dnnl/dnnl.hpp"

using tag = dnnl::memory::format_tag;
using dt = dnnl::memory::data_type;

int main() {
    // Boilerplate to set up a primitive...

    dnnl::engine engine(dnnl::engine::kind::cpu, 0);
    dnnl::stream engine_stream(engine);

    dnnl::memory::desc src_md({1, 1}, dt::f32, tag::ab);
    dnnl::memory::desc weight_md({1, 1}, dt::f32, tag::ab);
    dnnl::memory::desc dst_md({1, 1}, dt::f32, tag::ab);

    dnnl::memory src_mem(src_md, engine);
    dnnl::memory weight_mem(weight_md, engine);
    dnnl::memory dst_mem(dst_md, engine);

    // Set up one or more post-ops.
    dnnl::primitive_attr attr;
    dnnl::post_ops post_ops_tmp;
    post_ops_tmp.append_sum();
    post_ops_tmp.append_sum();
    attr.set_post_ops(post_ops_tmp);

    dnnl::matmul::desc matmul_desc(src_md, weight_md, dst_md);
    // Assign the attrs to the primitive.
    dnnl::matmul::primitive_desc matmul_prim_desc(matmul_desc, attr, engine, true);
    dnnl::matmul::primitive matmul_prim(matmul_prim_desc);

    auto post_ops = matmul_prim_desc.get_primitive_attr().get_post_ops();
    std::cout << (int)post_ops.kind(0) << std::endl; // Prints random garbage values
    std::cout << (int)post_ops.kind(1) << std::endl; // Correctly prints "4"

    return 0;
}

```

# Observed behavior
The query for `post_ops.kind(0)` above returns a random uninitialized value most of the time. The sample above seems to work correctly if I add two `dnnl::eltwise` post-ops in a row like so, though I suspect it's by pure chance:
```c++
    dnnl::primitive_attr attr;
    dnnl::post_ops post_ops_tmp;
    post_ops_tmp.append_eltwise(1.f, dnnl::algorithm::eltwise_linear, 1.f, 0.f);
    post_ops_tmp.append_eltwise(1.f, dnnl::algorithm::eltwise_linear, 1.f, 0.f);
    attr.set_post_ops(post_ops_tmp);
```
In a larger program, the `post_ops.kind(0)` occasionally (very rarely) returns the correct value, so it looks like some behind-the-scenes race conditions.

# Expected behavior
The call to `inline dnnl::primitive::kind dnnl::post_ops::kind(int index) const` should work for every valid index, including `0`

**Comment by dzarukin** [comment]
Hi @krzychut, thank you for your report.
Unfortunately, I can't reproduce the issue on my side. Could you, please, share some more information with us?
If the reproducer you've shared fails on your side, could you run it with ONEDNN_VERBOSE=2 and share the output with us, please?
If it's reliably reproduced only in a bigger workload, it's fine to collect verbose there, too.
If this is failing in Debug mode as well (-DCMAKE_BUILD_TYPE=Debug), that will be even more helpful. Thank you.

**Comment by krzychut** [comment]
On v2.6.0 with -DCMAKE_BUILD_TYPE=Debug the issue persists:
```
onednn_verbose,info,oneDNN v2.6.0 (commit 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:8
onednn_verbose,info,cpu,isa:Intel AVX2
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,create:cache_miss,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,attr-post-ops:sum+sum ,,1x1:1x1:1x1,0.0900879
-1889185840
4
```
Same on current master (e908c7146e4efca4183fe0c5753e8db613749134) with -DCMAKE_BUILD_TYPE=Debug:
```
onednn_verbose,info,oneDNN v2.6.0 (commit e908c7146e4efca4183fe0c5753e8db613749134)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:8
onednn_verbose,info,cpu,isa:Intel AVX2
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,create:cache_miss,cpu,matmul,ref:any,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,attr-post-ops:sum+sum ,,1x1:1x1:1x1,0.0810547
1255345104
4
```
Could it be caused by hardware? The CPU is pretty old. I can also try this  on a Cascade Lake if that's any help.

**Comment by dzarukin** [comment]
Thanks @krzychut, I think we figured it out (thanks @densamoilov). The issue is in the chaining of C++ calls into a single call when getting `post_ops`.
In `matmul_prim_desc.get_primitive_attr().get_post_ops()`, the first call to query attributes will get the object from primitive descriptor and [clone](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl.hpp#L4020) it (this is important), which makes it a standalone temporary object. The second call will query post-ops from this object, but it doesn't clone post-ops. We save the pointer on stack and when get to the next line of code, cloned attributes, which were the source of post-ops, get destroyed and it invalidates all the content underneath, including a pointer to post-ops. That's most likely the reason you are seeing bad values. The fact the index of 1 shows the correct result is luck.

Our semantics seem to keep an object standalone (read copy or clone it) regardless of "parent" object lifetime. This is not happening for post-ops and this is the issue we need to fix.

The only work around I may propose is to separate calls and store attributes on stack, even if they are not used anywhere else. We also seem to miss the test which queries post-ops from primitive descriptor, but not from attributes, which is likely why we haven't caught it ourselves.

Thank you for reporting the problem to us.

**Comment by krzychut** [comment]
That makes sense, thanks for the quick feedback. Yes, the semantics are a bit misleading, mostly because `get_primitive_attr()` does clone the attributes.

I actually did encounter an issue where chaining `get_primitive_attr().get_post_ops()` together caused the memory descriptor for a binary post-op to have incorrect dimensions in code equivalent to this:
```c++
        // auto attr = prim_desc.get_primitive_attr(); // This works
        // auto post_ops = attr.get_post_ops();        // nice and dandy

        auto post_ops = prim_desc.get_primitive_attr().get_post_ops(); // This breaks
        dnnl::algorithm alg;
        dnnl::memory::desc desc;
        post_ops.get_params_binary(0, alg, desc); // the descriptor here will have incorrect dims
```
I was going to open a separate issue for this, but it seems to be caused by the same bug.
