### ISSUE TITLE
Is it possible to integrate MPI with oneDNN?

### ISSUE THREAD

**Issue by malixian** [oneapi-src/oneDNN#1339]
Is it possible to integrate MPI with oneDNN? And are there some examples if possible?

**Comment by igorsafo** [comment]
Hi @malixian ,
oneDNN is a building block targeting single node performance. Work distribution and relevant communication between nodes happens on higher level outside of oneDNN (application, framework). For example, [oneCCL](https://github.com/oneapi-src/oneCCL) can be used to implement that communication. In case of high-level framework like Tensorflow [Horovod](https://horovod.readthedocs.io/en/stable/tensorflow.html) can be used. 

Regards,
Igor

**Comment by malixian** [comment]
> 

So is it not feasible to use MPICH to call oneDNN directly? 
And the solution is to use oneCCL?

**Comment by igorsafo** [comment]
@malixian Could you please describe your use case?
oneDNN can't dispatch automatically across many processes, but if an application splits data and distributes parts of it between processes then it can use oneDNN on parts of the data. For example, application could:
1. Split data of size `[batch, c, h, w]` across `batch` dimension and distribute its parts across `batch` processes
3. Within each of processes compute a oneDNN convolution or a set of oneDNN primitives using data `[1, c, h, w]`
4. Gather the results together.

**Comment by malixian** [comment]
I will try it by your comment. Thanks for your reply and close this issue.
