### ISSUE TITLE
Please Ensure Your System Has Sufficient Memory

### ISSUE THREAD

**Issue by Tom-Mirowski** [oneapi-src/oneDNN#1341]
./vcpkg install onednn 

On a system with 16 GB of RAM, 120 GB of free Disk space.

How much memory does this need?

It will go for about an hour, eventually fail with the following error, then just crash outright.

Building package onednn[core]:x64-linux...
-- Downloading https://github.com/oneapi-src/oneDNN/archive/v2.4.3.tar.gz -> oneapi-src-oneDNN-v2.4.3.tar.gz...
-- Extracting source /home/tditek/vcpkg/downloads/oneapi-src-oneDNN-v2.4.3.tar.gz
-- Using source at /home/tditek/vcpkg/buildtrees/onednn/src/v2.4.3-57b34cb498.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Warning at scripts/cmake/vcpkg_execute_build_process.cmake:89 (message):
  Please ensure your system has sufficient memory.
Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:111 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/onednn/portfile.cmake:17 (vcpkg_cmake_install)
  scripts/ports.cmake:145 (include)

-- Restarting build without parallelism

**Comment by igorsafo** [comment]
Hi @Tom-Mirowski ,
Thanks for reporting the issue.

I checked oneDNN binary size and it is far below the available memory your environment provides:
- dnnl_lnx_2.4.3_cpu_gomp:   50M 
- dnnl_lnx_2.4.3_cpu_iomp:  122M
- dnnl_lnx_2.4.3_cpu_tbb:     121M 

I would suggest to discuss it with vcpkg developers, maybe there is a way to make vcpkg installation more verbose to understand the error better (what directory did it try to put oneDNN?). Is it possible that your environment has 120 GB of free disk space but a partition which onednn is being installed in is full?

Regards,
Igor

**Comment by vpirogov** [comment]
@Tom-Mirowski, the error message is emitted by vcpkg and indicates that the system runs out of RAM during oneDNN compilation from the source. Memory consumption depends on the compiler and the number of parallel compilation steps. See [relevant PR in vcpkg](https://github.com/microsoft/vcpkg/pull/22417).
