### ISSUE TITLE
Different properties of primitive

### ISSUE THREAD

**Issue by kokhazade** [oneapi-src/oneDNN#1342]
Hi,
Could you please give me some explanation and examples on below concepts:

1- mask (that used in setting scales and zero points), please give me some examples like mask value x is used for tensors of dimension y. I mean how we should use mask?

2- different values of first argument in set_zero_point

3-alpha and beta fields of post_ops.

**Comment by densamoilov** [comment]
1. You can find documentation on using output scales and mask [here](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_quantization.html?highlight=mask#output-scaling-attribute)
2. The values specifiy an execution argument the given zero points will be applied to. 
3. Alpha and beta are used in [elementwise post op](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html?highlight=relu#eltwise-post-op). You can find the formulas [here](https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html#doxid-dev-guide-eltwise).

**Comment by dzarukin** [comment]
Clothing the issue since the question seems to be addressed. Feel free to open another issue if you have any questions.
