### ISSUE TITLE
When I run getting_started.cpp by sycl-cuda toolchain,there is a exception

### ISSUE THREAD

**Issue by wangzy0327** [oneapi-src/oneDNN#1343]
![image](https://user-images.githubusercontent.com/22990858/164179785-8f9c85a7-a04f-4008-b3c1-919f3a1a5a84.png)

starter: /home/wzy/sycl_workspace/oneDNN/src/common/utils.hpp:480: derived_type dnnl::impl::utils::downcast(base_type *) [derived_type = dnnl::impl::sycl::sycl_buffer_memory_storage_t *, base_type = dnnl::impl::memory_storage_t]: Assertion `dynamic_cast<derived_type>(base) == base' failed.
Aborted

how to solve this problem?

**Comment by dzarukin** [comment]
Hi @wangzy0327, thank you for the question.

Could you share a commit used, please? I can't reproduce the problem on latest master with some source modifications to make it built. Thanks.

**Comment by wangzy0327** [comment]
This is my used commit : aed66b1d9c5467a3a41dfb95321ef1b48d542e04 gtest: sycl: fix a test for non-sycl cpu runtime.
![image](https://user-images.githubusercontent.com/22990858/164351926-9055ae5d-ce32-4f8f-8da5-3d5b7871dcfd.png)

**Comment by dzarukin** [comment]
This commit won't work to run examples. The default memory mode is usm, but usm support was added for cuda backend only [recently](https://github.com/oneapi-src/oneDNN/tree/5d6f198b11199334f1715f06847f46ed4dcdc887). Please at least this revision to run examples. Thank you.

**Comment by wangzy0327** [comment]
how to choose other memory mode to run example ?

> This commit won't work to run examples. The default memory mode is usm, but usm support was added for cuda backend only [recently](https://github.com/oneapi-src/oneDNN/tree/5d6f198b11199334f1715f06847f46ed4dcdc887). Please at least this revision to run examples. Thank you.

**Comment by dzarukin** [comment]
If the intention to make it run at revision pointed out, one may need to re-write the example using one of [this](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_sycl.hpp#L281) or [this](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_sycl.hpp#L300) calls. Here's an [example](https://github.com/oneapi-src/oneDNN/blob/master/tests/gtests/sycl/api/test_memory_buffer.cpp) how it works in the code.
Using buffered memory for the tutorial should resolve the issue. Thank you.

**Comment by wangzy0327** [comment]
> If the intention to make it run at revision pointed out, one may need to re-write the example using one of [this](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_sycl.hpp#L281) or [this](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_sycl.hpp#L300) calls. Here's an [example](https://github.com/oneapi-src/oneDNN/blob/master/tests/gtests/sycl/api/test_memory_buffer.cpp) how it works in the code. Using buffered memory for the tutorial should resolve the issue. Thank you.

OK，thank you for this reply. I have solved the problem.
![image](https://user-images.githubusercontent.com/22990858/164376099-0bea4536-1875-4b03-895d-1aee817ca10a.png)
