### ISSUE TITLE
Build failure on older versions of Android (fixed in upstream xbyak)

### ISSUE THREAD

**Issue by cota** [oneapi-src/oneDNN#1350]
The recent memfd changes can cause a build failure on Android, since `memfd_create(2)` was not exposed in Bionic (Android's libc) until much later (~5 years) than `MFD_CLOEXEC`, which is what xbyak used to look for.

Upstream xbyak is now fixed, see https://github.com/herumi/xbyak/pull/145#event-6475924308

We should either backport the fix or just upgrade xbyak in OneDNN to pick up the fix. Thanks!

**Comment by igorsafo** [comment]
Hi @cota ,
Thanks for reporting the issue. We will update xbyak to the latest version.

Just curious is there a use case of oneDNN on Android platfrom?

Regards,
Igor

**Comment by cota** [comment]
Thanks!
Tensorflow Lite runs on Android, and it can optionally use oneDNN.
