### ISSUE TITLE
I run the sgx_dnnl demo, there is a error.

### ISSUE THREAD

**Issue by acknowledgexiongdei** [oneapi-src/oneDNN#1364]
the error is:
```
terminate called after throwing an instance of 'dnnl::error'
what():could not initialize a memory descriptor by a tag
```
how to fix it.
the code is within many files and long,If you need I will post.

**Comment by vpirogov** [comment]
Hi @acknowledgexiongdei, 

This looks like an application error, so the root cause should be somewhere in the code calling oneDNN. If `sgx_dnnl` refers to [a demo app](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleDNNL) from Intel SGX repository please open an issue there.

**Comment by acknowledgexiongdei** [comment]
> Hi @acknowledgexiongdei,
> This looks like an application error, so the root cause should be somewhere in the code calling oneDNN. If `sgx_dnnl` refers to [a demo app](https://github.com/intel/linux-sgx/tree/master/SampleCode/SampleDNNL) from Intel SGX repository please open an issue there.

Thank you, I`ll try.
