### ISSUE TITLE
Compile library in Raspberry Pi 4 64 bits

### ISSUE THREAD

**Issue by i02fesea** [oneapi-src/oneDNN#1365]
Hi, 

is there any information or tutorial to compile and to run an example in the raspberry pi 4?

Thank you

**Comment by nSircombe** [comment]
On a pi4, with GCC, you should be able to build following the usual steps for building from source - https://oneapi-src.github.io/oneDNN/dev_guide_build.html

On an Armv8 platform like the Pi, this will use the reference kernels throughout.

You can also download and build Compute Library for the Arm Architecture (https://github.com/ARM-software/ComputeLibrary) and link against that (https://oneapi-src.github.io/oneDNN/dev_guide_build.html#gcc-with-arm-compute-library-acl-on-aarch64-host), which will provide more optimised kernels for key primitives.

**Comment by nSircombe** [comment]
You can use BenchDNN (https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md) to run variety of examples and check their accuracy and performance.
