### ISSUE TITLE
Add support for inference on Greco

### ISSUE THREAD

**Issue by WilliamTambellini** [oneapi-src/oneDNN#1369]
# Summary
Add support for at least inference on greco:
https://habana.ai/inference/greco/

# Problem statement
As today, there does nt seem to be any connection/wrappers between the synapseAI sdk and oneAPI/oneDNN: 
https://docs.habana.ai/en/latest/Gaudi_Overview/SynapseAI_Software_Suite.html

# Preferred solution
Add support in oneDNN to run at lest the forward ops on Greco.

**Comment by densamoilov** [comment]
Hi @WilliamTambellini, as far as I understand SynapseAI is already integrated in TensorFlow and PyTorch, which enables Habana kernels for Habana hardware. What benefits do you see in adding such kernels in oneDNN?

**Comment by vpirogov** [comment]
No immediate plans to implement support for Habana accelerators.
