### ISSUE TITLE
How to convert onnx and inference via oneDNN?

### ISSUE THREAD

**Issue by jinfagang** [oneapi-src/oneDNN#1370]
any example?

**Comment by dzarukin** [comment]
Hi @jinfagang, would you mind to clarify your question, please?

**Comment by jinfagang** [comment]
Hi, does oneDNN will replace OpenVINO eventually? If so, I'd better start using oneDNN from now. But I don't know how to start with, like I have my model trained and exported to onnx, how to convert to oneDNN format for inference?

**Comment by dzarukin** [comment]
oneDNN and OpenVINO target different AI niches: oneDNN provides highly optimized low level building blocks to support commonly used operations from different models while OpenVINO provides inference engine to optimize existing workloads by using their API.

In fact, oneDNN is used inside OpenVINO and will never replace OpenVINO as a product.

onnx in turn also has oneDNN [integration](https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html), you may check it out. Thanks.

**Comment by jinfagang** [comment]
@dzarukin Oh, thanks for your explaination, still, may I ask what's the main difference between oneDNN and OpenVINO here? I mean they all can using for inference engine, why we need both of them?

**Comment by jinfagang** [comment]
So oneDNN provides a unified lower level NN implementation covers as many hardware as possible, while OpenVINO has it's own IR and can using one DNN as one of it backend (or function calling for specific op operation)? Correct me if am wrong.

**Comment by dzarukin** [comment]
As a top-level description, sounds about right, yes.
