### ISSUE TITLE
gcc compiler arguments

### ISSUE THREAD

**Issue by dev2y** [oneapi-src/oneDNN#1373]
Hi, I am compiling oneDNN with gcc and wanted to print all the Program Instrumentation Options used for compiling. I am trying to figure it out in cmake files but please let me know if you already know it. Thanks

**Comment by dzarukin** [comment]
Hi @dev2y, thanks for the question. You may dump a full compile line for each source file built. One needs to pass `VERBOSE=1` if they use `make` generator, or `-v` if they use `ninja` generator, specified in Cmake command. If nothing is specified, `make` will be a default generator.

Note: a list of option varies depending on target platform, oneDNN build options and compiler.

Will it cover your needs? Thank you.

**Comment by dzarukin** [comment]
The question seems to be addressed. Feel free to open if needed.
