### ISSUE TITLE
benchdnn version

### ISSUE THREAD

**Issue by TharinduRusira** [oneapi-src/oneDNN#1374]
Hi,
Is there a versioning policy for benchdnn? My benchdnn was built from source (cloned from github) and I can use the commit hash. I'm wondering if there is a more organized way to reference a specific version of benchdnn build (E.g. something that responds to `--version` or `-v`-like argument). 
Thanks,

**Comment by dzarukin** [comment]
Hi @TharinduRusira, thanks for the question.
Benchdnn follows the versioning of oneDNN. Fine granularity is provided with a hash. What do you want to refer with this version? Thank you.

**Comment by TharinduRusira** [comment]
Hi @dzarukin, 
I'm using the oneDNN version that is provided by the cluster repository, but benchdnn was independently built, locally on the system. 
Since oneDNN core and benchdnn can change independently between official oneDNN releases, I'm not sure how to refer to the exact version of benchdnn I'm running.
Thanks,

**Comment by dzarukin** [comment]
I see.
General recommendation is to get the version of the library through ONEDNN_VERBOSE=1, checkout the correspondent branch and use benchdnn from there.
There's no guarantee mismatched versions of benchdnn and oneDNN will work together nicely. The most common problem may be using newer oneDNN symbols in benchdnn, which will result in linker error with older oneDNN.

Is there any issue with benchdnn on your side you'd like to report? Thank you.

**Comment by TharinduRusira** [comment]
> The most common problem may be using newer oneDNN symbols in benchdnn, which will result in linker error with older oneDNN.
> Is there any issue with benchdnn on your side you'd like to report?

This makes sense. The benchdnn drivers I'm currently running  are compatible with the oneDNN version. Thanks for pointing this out.

Tharindu
