### ISSUE TITLE
CNN Quantization Bag #Bug

### ISSUE THREAD

**Issue by Theologis** [oneapi-src/oneDNN#1375]
Hello.

I took the code provided by oneapi (cnn_inference_int8.cpp) to Quantize and perform CNN execution. I load CNN parameters from a NN without problem. The problem that I faced was when I quantize CNN's weights and bias. I saw that I was passing the correct values to the **weights reorder function** but the output was zeroes.  

Bellow we can see code I've wrote for the weights quantization routine. I also print a few CNN values before and after the Quantization (Weights debugging part).
![Screenshot from 2022-05-13 13-35-24](https://user-images.githubusercontent.com/36996704/168269105-bdc5bb09-d8d5-4fe5-8e69-1bdb38236d98.png)

The problem as we can see, in the above picture, is that  the quantizer took the correct Weights and return zeroes.
![Screenshot from 2022-05-13 13-36-38](https://user-images.githubusercontent.com/36996704/168269987-3a11f14c-3c5e-463e-9a1d-c5f9b90cff3e.png)

Any ideas were  bug might be ?

**Comment by dzarukin** [comment]
Hi @Theologis, thank you for the question. Could you share the full code sample you are running, please? Thanks.

**Comment by Theologis** [comment]
> Hi @Theologis, thank you for the question. Could you share the full code sample you are running, please? Thanks.

Hi @dzarukin,
 Thank you for your support and your time. Yes of course I've uploaded on a GitHub repository here : https://github.com/Theologis/OneDNN_INT8_CNN

**Comment by dzarukin** [comment]
The example seems to be fine.
Couple issues noticed:
* It's incorrect to use `int` data type to obtain values of `int8_t` data type for quantized weights. You may want to change it to see proper values and avoid a crash.
* Weights are using blocked format which converts a single point (for oc=1 and ic=1 case) into a 16x16 block tile. Second point will be always zero in such scenario. You may want to consider to extend the range of values for monitoring. It will be 16*[oc/16] * 16 *[ic /16] * kh * kw, where `[]` is division up.
* Be sure to use non-zero value for the very first point of f32 weights that are reordered.
Thank you.

**Comment by Theologis** [comment]
@dzarukin  thank you vary match for your early response!
To be sure that the very first point of f32 weights that are reordered has non-zero value I've used the first printf at the picture above (printf("First two CNN weigts: %f, %f\n", *handler,handler[1]) ). right ?

Because you said that weights are using blocked format, I've changed the second handler (handler2) with the above code to see the values of the quantises weights. 
![Screenshot from 2022-05-14 15-26-02](https://user-images.githubusercontent.com/36996704/168425823-ee8a6cf8-7acd-42ae-b335-b38ffc903e93.png)
I've used read_from_dnnl_memory to make all the appropriate memory allocations. And then I've print the first two quantised weights (A,B). This is the output in the picture.
![Screenshot from 2022-05-14 15-33-20](https://user-images.githubusercontent.com/36996704/168425907-9892f1bf-56ad-4838-b023-994559ad5136.png)

And again the first point of f32 weights that are reordered has correct value 54.5 and the quantised one (A) has 0.

**Comment by dzarukin** [comment]
The code from your repo works fine for me:
```
$ ./run.sh

Enter Input/Parameters filename:300
onednn_verbose,info,oneDNN v2.6.0 (commit N/A)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:56
onednn_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_u8::blocked:acdb:f0,attr-oscale:0:1.800000e+00 ,,1x1x300x300,38.938
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_s8:p:blocked:ABcd4b16a4b:f0,attr-oscale:0:2.000000e+00 ,,1x1x3x3,0.0290527
First two CNN weigts: 54.500000, 200.000000
First two CNN quantized weigts: 109, 0
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:a:f0 dst_s8::blocked:a:f0,,,1,0.000976562
onednn_verbose,exec,cpu,convolution,jit_int8:avx512_core,forward_training,src_u8::blocked:acdb:f0 wei_s8:p:blocked:ABcd4b16a4b:f0 bia_s8::blocked:a:f0 dst_u8::blocked:acdb:f0,attr-oscale:2 attr-post-ops:eltwise_relu ,alg:convolution_direct,mb1_ic1oc1_ih300oh149kh3sh2dh0ph0_iw300ow149kw3sw2dw0pw0,6.26196
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_u8::blocked:acdb:f0 dst_f32::blocked:abcd:f0,attr-oscale:0:5.500000e-01 ,,1x1x149x149,0.026123
Use time(int8): 1614 ms per iteration.
Example passed on CPU.
```

I'd check if all inputs are correct on your side. Thanks.

**Comment by Theologis** [comment]
That is very interesting. My outputs in the quantized weights are Null (second picture in my post). I can't think any good reason for that. Code will also create an output under the ../input_test_files/ref_output_300_300.txt. This also has not-null values?

**Comment by vpirogov** [comment]
@Theologis, did you manage to find the root cause?

**Comment by Theologis** [comment]
@vpirogov, Yes I found my mistake. I've checked my code and I saw that I was using a s8 memory descriptor for the output. I've changed it to s32 and fixed the problem. Thank you vary much for your support.
