### ISSUE TITLE
How can I use these dump files when use ONEDNN_JIT_DUMP

### ISSUE THREAD

**Issue by yangshuo0323** [oneapi-src/oneDNN#1376]
when I execute:
`./benchdnn --matmul --batch=inputs/matmul/shapes_2d`, there will genarate some files:
```
dnnl_dump_cpu_jit_avx2_f32_copy_an_kern.0.bin
dnnl_dump_cpu_jit_avx2_f32_copy_at_kern.2.bin
dnnl_dump_cpu_jit_avx2_f32_copy_bn_kern.1.bin
dnnl_dump_cpu_jit_avx2_f32_copy_bt_kern.3.bin
dnnl_dump_cpu_jit_avx2_kernel_sgemm_kern.4.bin
dnnl_dump_cpu_jit_avx2_kernel_sgemm_kern.5.bin

```
so, I want to use these `.bin` to compute `MatMul`. I see some function declaration in `gemm_info.hpp`, but which one is needed, and how to use them? thanks for you reply.

**Comment by louie-tsai** [comment]
@yangshuo0323 
Those files are JIT kernel dump and you could refer below page for detailed information.
https://oneapi-src.github.io/oneDNN/dev_guide_inspecting_jit.html
You indeed could disassemble the bin file into assemble codes for debugging, but it is not for execution.

If you don't want those JIT dump files, please disable it by ONEDNN_JIT_DUMP=0.
you could follow below command to disable it.
$ONEDNN_JIT_DUMP=0 ./benchdnn --matmul --batch=inputs/matmul/shapes_2d

regards

**Comment by yangshuo0323** [comment]
>

**Comment by yangshuo0323** [comment]
> @yangshuo0323 Those files are JIT kernel dump and you could refer below page for detailed information. https://oneapi-src.github.io/oneDNN/dev_guide_inspecting_jit.html You indeed could disassemble the bin file into assemble codes for debugging, but it is not for execution.
> 
> If you don't want those JIT dump files, please disable it by ONEDNN_JIT_DUMP=0. you could follow below command to disable it. $ONEDNN_JIT_DUMP=0 ./benchdnn --matmul --batch=inputs/matmul/shapes_2d
> 
> regards

many thanks
