### ISSUE TITLE
How to judge whether the CPU supports mkldnn

### ISSUE THREAD

**Issue by marsbzp** [oneapi-src/oneDNN#1386]
How to judge whether the CPU supports mkldnn

**Comment by dzarukin** [comment]
Hi @marsbzp, thanks for the question.
Please find on the main page [a list](https://github.com/oneapi-src/oneDNN/tree/rls-v2.6#system-requirements) of supported CPUs. Thank you.

**Comment by marsbzp** [comment]
> Hi @marsbzp, thanks for the question. Please find on the main page [a list](https://github.com/oneapi-src/oneDNN/tree/rls-v2.6#system-requirements) of supported CPUs. Thank you.

Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz is not in list but support mkldnn

**Comment by marsbzp** [comment]
> @marsbzp Intel(R) Xeon(R) Gold 5218R CPU is one of Intel Xeon Scalable processor, so it is supported. You could refer below page for more details of 5218R. https://ark.intel.com/content/www/us/en/ark/products/199342/intel-xeon-gold-5218r-processor-27-5m-cache-2-10-ghz.html
> 
> thanks

Is this Intel Xeon processor（SKylake，IBRS）cpu support mkldnn?

**Comment by louie-tsai** [comment]
@marsbzp 
mkldnn supports Skylake Intel(R) Xeon(R) Gold 5218R CPU as one of Intel Xeon Scalable processor.

thanks
