### ISSUE TITLE
oneDNN and TensorFlow/Pytorch and NVIDIA GPU

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1395]
Does TensorFlow or Pytorch support oneDNN that use a CUDA device as its compute device and cudnn's kernel as its primitive?

**Comment by densamoilov** [comment]
I don't think there is a TF or PyTorch versions with oneDNN support + CUDA backend.

**Comment by MOLOjl** [comment]
thank you.
