### ISSUE TITLE
how to solve linker cudnn error

### ISSUE THREAD

**Issue by wangzy0327** [oneapi-src/oneDNN#1396]
This is oneDNN build on intel/llvm cuda toolchain.
![b52aedd79a5bed66a30e2c2679e5f5f](https://user-images.githubusercontent.com/22990858/173357675-911db228-b27e-4d35-8e5a-b9fed9e3de35.png)

when I compile a oneDNN example case, it happens error.
![image](https://user-images.githubusercontent.com/22990858/173358047-d2d7099b-fab2-4bae-89ea-f65c99d2ce4f.png)

This is my oneDNN example cmakeLists.txt
![image](https://user-images.githubusercontent.com/22990858/173358350-5fea4d60-283f-4328-bd12-ec9c09e9bb8b.png)

how to solve the problem? Could you help me ?

**Comment by densamoilov** [comment]
Try to change this condition to `#if defined(CL_VERSION_2_1) && 0`.
https://github.com/oneapi-src/oneDNN/blob/c0c5582d671bf573a576f4e63b2edeb02fbd0f8a/src/gpu/ocl/ocl_utils.cpp#L337

**Comment by wangzy0327** [comment]
> Try to change this condition to `#if defined(CL_VERSION_2_1) && 0`.
> 
> https://github.com/oneapi-src/oneDNN/blob/c0c5582d671bf573a576f4e63b2edeb02fbd0f8a/src/gpu/ocl/ocl_utils.cpp#L337

Firstly,Thank you for last solution. But Another problem emerges, as follows (libsycl.so.5:cannot open shared object file: No such file or directory)
![image](https://user-images.githubusercontent.com/22990858/173494566-5b8d3d84-c7f5-45a6-bff9-9687ce9b2838.png)

![image](https://user-images.githubusercontent.com/22990858/173494618-7f194f1c-9710-42e1-8bb6-227e6e81d81f.png)
![image](https://user-images.githubusercontent.com/22990858/173494651-4fb0122d-4dd3-4e1c-8676-01ac8dbc4b71.png)

why cannot find shared object file?how to solve it?
