### ISSUE TITLE
Performance regression in concat primitive after updating from dnnl-1.2a to onednn-2.6

### ISSUE THREAD

**Issue by rfg-gh** [oneapi-src/oneDNN#1405]
We observed using the same source code a significant performance regression in the concat primitive after updating from dnnl-1.2a to onednn-2.6 (both compiled with the Intel compiler 1.190), but only for input tensor shapes with N=1, i.e. NCHW={1,C,H,W} which unfortunately is the most important use-case for us. See more details on the parameters we used below. Is this a known issue? Do you have any tips for us?

Consistent performance value:
dnnl-1.2a  -> dnnl_concat_primitive->execute: 0.114390 ms
onednn-2.6 -> dnnl_concat_primitive->execute: 0.546506 ms (aprox. 4-5x slower)

The following parameters and OS-setup were used to generate the supplied log-files:
1-) 2x input tensors with the same shape: N,C,H,W={1,64,56,56}
    Important remark: the only configuration here for which the regression was observed, is N=1 in the input shapes above. For other N=2,4,8,16,etc onednn-2.6 performs as well as dnnl-1.2a.
2-) The resulting output tensor shape: {1,128,56,56}
3-) Number of omp threads used: 1 (one)
4-) Hardware: Linux host with Intel processor: see attached cpuinfo.log below
5-) Log files with performance for both cases: see attached concat_primitive_dnnl-1.2a.log and concat_primitive_onednn-2.6.log below. Each one contains 100 iterations.

[cpuinfo.log](https://github.com/oneapi-src/oneDNN/files/9021232/cpuinfo.log)
[concat_primitive_dnnl-1.2a.log](https://github.com/oneapi-src/oneDNN/files/9021234/concat_primitive_dnnl-1.2a.log)
[concat_primitive_onednn-2.6.log](https://github.com/oneapi-src/oneDNN/files/9021235/concat_primitive_onednn-2.6.log)

**Comment by dzarukin** [comment]
Hi @rfg-gh, thank you for reporting the issue.
I reproduced the regression, and I think it is caused by `6bfbce3` commit. It seems that for a single thread std::function brings higher overhead and also I can't see it vectorizes a copy which is the real reason for 5x degradation.

I've come up with a dummy fix, could you, please try it on your side?
I need to check if other number of threads are affected, and, if yes, it probably will require a different fix but you may stick to this one for a while. With it the performance goes on par with v1.2.

```
diff --git a/src/cpu/simple_concat.cpp b/src/cpu/simple_concat.cpp
index e7b2ce8..d29628f 100644
--- a/src/cpu/simple_concat.cpp
+++ b/src/cpu/simple_concat.cpp
@@ -77,7 +77,10 @@ status_t simple_concat_t<data_type>::execute(const exec_ctx_t &ctx) const {
         for (int a = 0; a < num_arrs; ++a) {
             const data_t *i = &iptrs[a][0];
             data_t *o = &optrs[a][0];
-            parallel_nd(nelems_to_copy[a], [&](dim_t e) { o[e] = i[e]; });
+            if (dnnl_get_max_threads() == 1)
+                std::memcpy(o, i, nelems_to_copy[a] * sizeof(data_t));
+            else
+                parallel_nd(nelems_to_copy[a], [&](dim_t e) { o[e] = i[e]; });
         }
         return status::success;
     }
```

Thank you and sorry for a long wait.

**Comment by rfg-gh** [comment]
@dzarukin ,
we made further tests with your last patch and here the results: 
- during inference (forward pass) there are no anymore regression between onednn-2.6 with your patch and dnnl-1.2a.
- during training (backward pass) onednn-2.6 without the patch was faster than dnnl-1.2a. But with the patch onednn-2.6 is now similar to dnnl-1.2a, i.e. no slower than dnnl-1.2a but slower as it was before the patch:

training |   |   |   |   |   | dnnl | onednn |   | abs | % | RESULT
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cmpct |   |   |   |   |   | 44.683 | 42.065 |   | -2.618 | -5.86% | GOOD
enhcd |   |   |   |   |   | 317.129 | 295.295 |   | -21.834 | -6.88% | GOOD
resnt |   |   |   |   |   | 531.868 | 523.532 |   | -8.336 | -1.57% |  
mnet1 |   |   |   |   |   | 398.205 | 332.985 |   | -65.220 | -16.38% | GOOD
mnet2 |   |   |   |   |   | 190.627 | 114.179 |   | -76.447 | -40.10% | GOOD
alex |   |   |   |   |   | 874.167 | 739.952 |   | -134.215 | -15.35% | GOOD
