### ISSUE TITLE
Broadcasting plan to use oneDNN to build a Flashlight Tensor Backend

### ISSUE THREAD

**Issue by StrongerXi** [oneapi-src/oneDNN#1416]
Hi oneDNN community,

I'm currently working on using oneDNN to build a [Flashlight](https://github.com/flashlight/flashlight#readme) [Tensor Backend](https://github.com/flashlight/flashlight/tree/main/flashlight/fl/tensor#implementing-or-adding-a-tensor-backend). This would enable a high-performance tensor backend in flashlight, and allow us to profile & study performance on machine/deep learning workloads, which may identify potential upstream improvements in oneDNN.

With this post, I meant to (1). broadcast our interests and plan, and (2). establish a communication channel for questions regarding oneDNN. Please let me know if the community has any existing channel or preference on (2).

-- Ryan

cc @jacobkahn

**Comment by vpirogov** [comment]
@StrongerXi, thanks for letting us know. The best way to communicate with oneDNN team is opening an issue on Github. Questions that for some reason should not be public can be addressed to [dnnl.maintainers@intel.com](mailto:dnnl.maintainers@intel.com).

**Comment by StrongerXi** [comment]
Sounds good, thanks!
