### ISSUE TITLE
Does oneDNN support inputting an onnx model for fp32 and int8 inference?

### ISSUE THREAD

**Issue by royywang** [oneapi-src/oneDNN#1419]

**Comment by louie-tsai** [comment]
Hi,
no onnx model parser in oneDNN, but oneDNN is enabled in ONNX as a execution provider.

please refer to below article to enable oneDNN in ONNX.
https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html
Here are code snapshot to enable oneDNN in ONNX.
```
Ort::SessionOptions sf;
bool enable_cpu_mem_arena = true;
OrtSessionOptionsAppendExecutionProvider_Dnnl(sf, enable_cpu_mem_arena)
```

**Comment by royywang** [comment]
Ok thanks for your reply
