### ISSUE TITLE
Best practice for unsupported ops?

### ISSUE THREAD

**Issue by StrongerXi** [oneapi-src/oneDNN#1422]
What's the best practice to apply unsupported ops like element-wise sin/cos to onednn memory?

I have 2 candidates in mind:

1. Manually implement apply the desire op to the data blob, e.g.,
```c++
generic_eltwise_apply(sin, memory_desc.get_data_type(), memory_desc.get_size(), memory.get_data_handle());
```

2. Use [oneMKL](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/vector-mathematical-functions/vm-mathematical-functions/trigonometric-functions/sin.html), which seems to require sycl interoperability, but oneDNN [does provide that](https://oneapi-src.github.io/oneDNN/dev_guide_dpcpp_interoperability.html?highlight=sycl%20queue).

To us (2) would be the optimal approach, but could you guys share some pointers?

cc: @jacobkahn

**Comment by densamoilov** [comment]
Normally, if oneDNN doesn't provide desired functionality users are responsible for implementing it on their own. Using memory descriptor you can get information about how data is laid out in memory and implement missing functionality. This is widely used practice.
How you decide to implement is up to you, if having an additional dependency like oneMKL meets your requirements then it's perfectly fine to use it.

**Comment by StrongerXi** [comment]
Thanks for confirming!
