### ISSUE TITLE
Can we transfer/release device memory ownership?

### ISSUE THREAD

**Issue by StrongerXi** [oneapi-src/oneDNN#1423]
As title.

## Context
This example shows what we'd like to do:
```c++

// Assume `gpu_engine` is an ocl engine
auto gpu_engine =  dnnl::engine(dnnl::engine::kind::gpu, 0);
auto src_md = dnnl::memory::desc(...);
auto src_mem = dnnl::memory(src_md, gpu_engine);

void* device_ptr = ??? // e.g., src_mem.release_data_handle();
// use device_ptr for interoperability purposes, where `src_mem` might have been destroyed
```

## Question
What would be the best practice here?

cc: @jacobkahn

**Comment by densamoilov** [comment]
Current API doesn't allow to transfer ownership of the underlying buffer. You either have to manage allocated memory on your own or let the library do that. For interoperability you can use `get_data_handle()` but you are required to keep the associated memory object alive while using the returned buffer.

**Comment by StrongerXi** [comment]
I see, thanks for confirming!
