### ISSUE TITLE
Best practice for filling a tensor with a constant?

### ISSUE THREAD

**Issue by StrongerXi** [oneapi-src/oneDNN#1424]
As title.

## Candidate approaches I had in mind

1.
```c++
auto memory = dnnl::memory(...);
fill_with_constant<T>(memory.get_data_handle(), constant); // a loop, assign buffer elements 1 by 1
```

2. If newly created memory buffer is guaranteed to be zeroed-out, use `dnnl_eltwise_linear` with `alpha = 1`, `beta = constant`.

## Issues
(1) might not be optimal, and needs extra copy for device memory.

(2) has assumptions and may lose precision (if we want to init with a large integer instead of float).

Could you guys provide some pointers here?

cc: @jacobkahn

**Comment by densamoilov** [comment]
> If newly created memory buffer is guaranteed to be zeroed-out

oneDNN doesn't zero out allocated buffers. 

I think the best way would be getting underlying buffer and populating it with a value on your side.

oneDNN provides [map/unmap](https://github.com/oneapi-src/oneDNN/blob/e7f89e29992208891fc5ac574eed094fcecf053b/include/oneapi/dnnl/dnnl.hpp#L2850) API that could help you with that (especially for GPU), but it may not be efficient.

**Comment by StrongerXi** [comment]
Got it, thank you!
