### ISSUE TITLE
`dnnl::memory::desc::get_size()` returns 0 for submemory with non-zero offset

### ISSUE THREAD

**Issue by StrongerXi** [oneapi-src/oneDNN#1429]
The root cause seems to be [this commit](https://github.com/oneapi-src/oneDNN/commit/e0e46ccdaec02e8ed4b9606564a721c225f33960).

Is there any reason why this is the behavior? It came as a surprise to me because it wasn't specified in the [public API](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl.hpp#L2678-L2682).

cc: @jacobkahn

**Comment by dzarukin** [comment]
Hi @StrongerXi, the reason is that submemory_desc in general case doesn't provide full information on how much memory to provide for the end user. Thus, it provides nothing. Thank you.

**Comment by StrongerXi** [comment]
I see. Would you mind providing a quick example of such submemory_desc?

I can easily simulate `get_size` on my end, but I'm also using `submemory_desc` for tensor indexing (and eventually, in reorder primitive during indexed assignments) so I just want to make sure it's actually safe.
