### ISSUE TITLE
oneDNN is slower than pytorch on intel CPU

### ISSUE THREAD

**Issue by kwonbeomseok** [oneapi-src/oneDNN#1433]
Hi,

I did latency performance test between oneDNN vs Pytorch.

Each code is below

I think that each code has same forward graph(Linear -> ReLU) and input, weight, bias shape(I modified oneDNN example's input, weight, bias shape and value).
The test result shows that pytorch code is faster than oneDNN code.

||Pytorch|oneDNN|
|:--:|:--:|:--:|
|Latency|0.91 sec|1.14sec|

**  using same number of cpu core(1 core)

I wonder if it's supposed to be like this or if it's my fault

### Pytorch code
```python
import torch
import time

inputs = torch.rand(4096, 4096)
layer = torch.nn.Linear(4096, 4096)

t1_start = time.perf_counter()

# Forward         
output = layer(inputs)
torch.nn.functional.relu(output)

t1_stop = time.perf_counter()
    
print(f"Elapsed time  in seconds: {t1_stop-t1_start:.4f}")
```

### oneDNN example
https://oneapi-src.github.io/oneDNN/page_inner_product_example_cpp.html#doxid-inner-product-example-cpp

**Comment by dzarukin** [comment]
Hi @kwonbeomseok, are you measuring only a single execute call in both cases?

**Comment by kwonbeomseok** [comment]
Hi @dzarukin, 

I tested a single execute call and multiple execute call in both cases. However, Pytorch is faster than oneDNN in all experiments.

The result table which is in first comment is only a single execute call.

**Comment by dzarukin** [comment]
Well, single call execute doesn't work when it comes to performance number. It should be either an average number of ms per call once time per call become stable or just the minimum number between all calls, whatever suits your needs.

As for operations compared, it seems to me that Linear (eltwise) + ReLU is desired, but the example linked for oneDNN is Inner Product (which is GeMM in sort of way), which is a completely different operation.

I'm also not sure what kind of PyTorch are you comparing to oneDNN - stock (with only reference path available) or with oneDNN enabled inside? And what's the purpose of the experiment? Thank you.

**Comment by dzarukin** [comment]
> So I think that inner product is same operation of pytorch's linear layer.

It seems they are, the name though very ambiguous.

> I think oneDNN is faster than pytorch because simply pytorch is python code and oneDNN is c++ code.

PyTorch only gives python interfaces. All mathematics underneath is written in same C++ or by calling vendor libraries. oneDNN is the C++ library, yes, but optimizations are coming from programming on assembly without giving much details what kind of assembly it is.

> If model is same, which one is fast? pytorch or oneDNN?

This is not quite correct comparison. oneDNN provides building blocks but not model level support while PyTorch does. Only separate operations might be compared directly. Like Fully Connected op. If PyTorch falls back underneath into its reference version, I would expect oneDNN does better job in most cases, though it's always possible to find specific problem when it's not. But I don't expect PyTorch to fall back into reference path anyway.

To continue looking on performance comparison, [verbose](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html) output for oneDNN will be needed. Thank you.

**Comment by kwonbeomseok** [comment]
Thank you very much for the detailed explanation.

Thanks to you, I could understand many things and your explanation helped a lot.

I appreciate your kind reply, have a nice day
