### ISSUE TITLE
Error when compiling dnnh.h

### ISSUE THREAD

**Issue by Fatichti** [oneapi-src/oneDNN#1435]
# Summary
Error when compiling ``dnnh.h`` (the file is here : ```oneDNN/include/oneapi/dnnl/dnnl.h```) :
Include file not found :
- ``dnnl_config.h``
- ``dnnl_version.h``

But files with the same name can be found in ``oneDNN/include``  
 
# Version
All version (to last release v2.7-pc2)

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model : **AMD Ryzen Threadripper 2950X 16-Core Processor**
* OS version : **x86_64 x86_64 x86_64 GNU/Linux -  5.4.0-122-generic 138-Ubuntu SMP**
* Compiler version : **9.4.0**
* CMake version : **3.16.3**
* CMake output log : **see the summary**
* git hash : **52b5f107dd9cf10910aaa19cb47f3abf9b349815**

# Steps to reproduce
``oneDNN`` has been compiled with **Pytorch**.
Just compile ``oneDNN`` to see the problem

# Observed behavior
The compilation stops in error because the documents indicated in ``#include`` of the file  ```oneDNN/include/oneapi/dnnl/dnnl.h``` are not found (just dnnl_types.h).
![image](https://user-images.githubusercontent.com/74354655/184300537-874aaf77-49f5-4c6b-abff-b7af47206354.png)

# Expected behavior
The ``dnnl.h`` file includes files that are located in the indicated paths of ``#include``.

**Comment by igorsafo** [comment]
Hi @Fatichti , thanks for letting us know.

`dnnl_config.h` and `dnnl_vision.h` are generated during build proccess in the build directory. So once oneDNN is built, <build>/include/oneapi/dnnl contains these headers.

@Fatichti Could you please share logs? It is not clear what exactly is happening on your side. How do you build oneDNN?

Tagging some people from PyTorch @gujinghui @TaoLv

**Comment by Fatichti** [comment]
Hi,

I actually build oneDNN with pytorch from source.

I don't realy know how to get logs about it.

**Comment by TaoLv** [comment]
@chunyuan-w Do you have any idea?

**Comment by Fatichti** [comment]
I am using cudatoolkit 11.7.

But i think i may do it with cudatoolkit 11.6 since the [download page](https://pytorch.org/get-started/locally/) show compute platform up to CUDA 11.6

It's relevant ?

**Comment by jingxu10** [comment]
Hi @Fatichti , I would like to clarify some questions. Did this problem happen when you compile PyTorch with oneDNN? If so, could you share the compilation steps?
I don't quite follow this statement. Could you provide more details/explanations?
```
oneDNN has been compiled with Pytorch.
Just compile oneDNN to see the problem
```
Thank you.

**Comment by Fatichti** [comment]
Hi @jingxu10 

In fact, this problem happen when I compile PyTorch with oneDNN

I have downgrade CUDA version to 11.6 (instead 11.7), now i have other error wich are different each recompilation.

For the step, i just change directory to python folder and type ``python setup.py install``

**Comment by jingxu10** [comment]
Could you provide the following info?
1. Which PyTorch commit did you compile 
2. Which platform did you compile on
3. gcc version

Also, could you try compiling it with CUDA disabled (`USE_CUDA=0`)?

**Comment by Fatichti** [comment]
🎉 I reached !

When Pytorch are compiling from source, it doesn't compile oneDNN.

1️⃣ So i first do `cmake .` in the oneDNN folder and then compile Pytorch !

2️⃣ Furthemore, i has to disable ninja with `export USE_NINJA=0`

3️⃣ To conclude, i has also to modify a script : `cuda_nccl_gpu.cc` but it's outside oneDNN module.
🤜 The modification was to change `CHECK_NOTNULL` to `TORCH_CHECK_NOTNULL`


And i try compiling without CUDA @jingxu10 but i has same errors.

Thanks for the help !
