### ISSUE TITLE
How To Build from Source for GPU and CPU on ppc64le archictecture

### ISSUE THREAD

**Issue by FernandezR** [oneapi-src/oneDNN#1437]
Hello,

I'm trying to install the oneDNN library for GPU and CPU on a system with ppc64le architecture so that I can build pytorch with it. I don't see any explanation for building the package from scratch and adding the libraries to python. Can you help me with this?

Thanks

**Comment by FernandezR** [comment]
I tried using the conda-forge prebuilt binary but it through a bunch of conflicts

**Comment by dzarukin** [comment]
Hi @FernandezR, oneDNN should support PPC64 platform by default through [CMake](https://github.com/oneapi-src/oneDNN/blob/master/CMakeLists.txt#L92). If CMake binary you use supports `CMAKE_SYSTEM_PROCESSOR` variable and provides the proper value, the build will be configured to utilize PPC ISA.

Rest build options supported may be found [here](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html).

Feel free to reach in case of any errors. In latter case, please don't forget to supply CMake output. Thank you.

**Comment by igorsafo** [comment]
@FernandezR , In addition to @dzarukin comments -- only CPU runtime is supported on PPC64 (no GPU).
