### ISSUE TITLE
Is there any plan for oneDNN to support ACL-fp16?

### ISSUE THREAD

**Issue by lilh9598** [oneapi-src/oneDNN#1438]
I found that ACL's fp16 operator is not supported in oneDNN, but many arm-servers support fp16 ISA, so it is impossible to call ACL to accelerate fp16 through oneDNN. Is there any plan for oneDNN to support ACL-fp16?

**Comment by nSircombe** [comment]
Hi @lilh9598,

Our team at Arm implemented the current Compute Library based primitives and are working on expanding support, improving performance, and improving integration with key frameworks like TensorFlow.
However, at present there are no plans to integrate fp16 support from ACL into oneDNN. 
At present oneDNN does not, I believe, support fp16 for CPU targets (https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html), which precludes integration of ACL fp16 kernels to some extent. 
We have chosen to focus on fp32, and while we've implemented support for `ONEDNN_DEFAULT_FPMATH_MODE=BF16` in key GEMM based primitives we're not currently looking at `ONEDNN_DEFAULT_FPMATH_MODE=FP16`, which might be the most practical way to leverage the ISA's fp16 support.

...we would be happy to review & test any implementations for `ONEDNN_DEFAULT_FPMATH_MODE=FP16` from the community.

**Comment by igorsafo** [comment]
@nSircombe , actually f16 support on CPU was added recently. It is still work in progress, but most of work is done: common internals and tests are ready, some reference and optimized implementations are there (https://github.com/oneapi-src/oneDNN/search?q=f16&type=commits). However the documentation deployment is outdated, I will deploy the latest version.

**Comment by nSircombe** [comment]
thanks for the clarification @igorsafo - that's good to know.

**Comment by lilh9598** [comment]
> @nSircombe , actually f16 support on CPU was added recently. It is still work in progress, but most of work is done: common internals and tests are ready, some reference and optimized implementations are there (https://github.com/oneapi-src/oneDNN/search?q=f16&type=commits). However the documentation deployment is outdated, I will deploy the latest version.
@igorsafo @nSircombe Thx for your kindly reply！On x86, oneDNN can speed up the fp16 operator by avx512_fp16, and it looks almost ready. However, what I want to know most is the plan to integrate ACL-fp16 into oneDNN.

**Comment by nSircombe** [comment]
Hi @lilh9598,
 
> However, what I want to know most is the plan to integrate ACL-fp16 into oneDNN.

No plans at present.

**Comment by lilh9598** [comment]
> Hi @lilh9598,
> 
> > However, what I want to know most is the plan to integrate ACL-fp16 into oneDNN.
> 
> No plans at present.

I get it. Thank you for your answer.
