### ISSUE TITLE
What does `gemm_api` in `ONEDNN_VERBOSE` log mean?

### ISSUE THREAD

**Issue by nSircombe** [oneapi-src/oneDNN#1442]
Hi,

I've recently been using oneDNN's verbose output to check that some TensorFlow benchmarks are calling Compute Library primitives as expected. For my build I'm using TF2.10 rc0, and building with oneDNN taken from this commit - https://github.com/oneapi-src/oneDNN/commit/70d1198de554e61081147c199d661df049233279.

In the log generated when I run MatMul benchmarks (see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_matmul_op_benchmark.cc) I'm seeing output of the form:

```
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,1x512:512x512,0.359131
```

It looks like this verbose output from the top level APIs went in here: https://github.com/oneapi-src/oneDNN/commit/db84c2d755c13ea52cc832f63d589ad04289c2d9. But it doesn't tell me which matmul implementation is being picked up, it provides less detail than I was hoping for. If I supply the same problem parameters to benchdnn, I do get something more like the expected output:

```
onednn_verbose,exec,cpu,matmul,gemm:acl,undef,src_f32::blocked:ba:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0...
```

Could you explain what the `gemm_api` output in the verbose log is for, and why I'm seeing this rather than `...matmul, gemm:acl...` - or is this suggesting that the Compute Library kernels aren't being called at all?

I'd be very grateful for any explanations / hints / tips you can give.

**Comment by densamoilov** [comment]
Hi @nSircombe, oneDNN provide function like API for GEMM, which is different from Matmul primitive: https://github.com/oneapi-src/oneDNN/blob/23679763e28ce85451b68c238b279f77173e7a05/include/oneapi/dnnl/dnnl.hpp#L13119-L13124

So what you are observing is TF calling the function-like GEMM API instead of primitive-like Matmul API.

**Comment by densamoilov** [comment]
For the function-like GEMM primitive we don't have a list of implementations therefore we print only `gemm_api`.

**Comment by nSircombe** [comment]
Ah, so this benchmark is actually calling the BLAS-like SGEMM! It's been a while, but as I recall we added ArmPL support here, but not ACL, as Compute Library doesn't provide a BLAS interface, I don't think we're currently going to pick these up with ACL...
...I'll do a bit of digging.

**Comment by nSircombe** [comment]
Thanks @densamoilov, I think that's saved me some head-scratching...

**Comment by nSircombe** [comment]
Closing this as my original question is covered, thanks.
...will re-open if I have any follow-ups!
