### ISSUE TITLE
Does OneDNN guarantee deterministic result for floating numbers

### ISSUE THREAD

**Issue by zhaoflying** [oneapi-src/oneDNN#1443]
1. Does OneDNN guarantee deterministic result for matrix multiplication, convolution, pooling and batch normalization operations for floating numbers, in both single-thread and multi-thread environment? Especially for single-thread environment, does OneDNN guarantee that? 
2.  I observed that some other library like libeigen produces different result for matrix multiplication on Intel IceLake CPU vs. earlier generations CPU because of L1 cache size difference. Does OneDNN have the same problem? The reason I asked this because I found that jit_avx2_convolution_bwd_data_t::execute_backward_data() in https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx2_convolution.cpp queries L2 cache size. Does it mean it could produce different result when L2 cache size is different? I didn't observe result difference on my test dataset though.

**Comment by igorsafo** [comment]
Hi @zhaoflying ,
oneDNN doesn't guarantee the same answer between different implementations, CPU architectures, microarchitecture generations or devices. However oneDNN guarantees reproducibility betwwen runs in the same environment.

If you run the same oneDNN on the same CPU in single thread multiple times, it will return the same answer. However, if number of threads are changed or CPU is changed, there is no guarantee for the results to be the same.

Regards,
Igor

**Comment by zhaoflying** [comment]
Igor,

Thanks a lot for your response. Really appreciate it.

A follow up question: If I run the same oneDNN(avx2 enabled but not avx-512) on the Skylake and IceLake CPUs in single thread, they may generate different result. Is the difference only coming from different cache size or there are other factors as well?

Best Regards,

Tengfei

**Comment by igorsafo** [comment]
Hi Tengfei,

Yes, I would say that different cache size can result in different blocking/reduction sizes that might affect accumulation chain order. Tagging @kwiersch @msotoflo and @akharito for more insights on the implementation.

Regards,
Igor

**Comment by kwiersch** [comment]
Hi, if build is limited to avx2 instructions / kernels, and same build is run in single-threaded mode on Skylake and Icelake, then I agree that cache size is the only factor leading to different results. If you are interested in testing this, you can change the cache query routine to always use default values here: https://github.com/intel-innersource/libraries.performance.math.onednn/blob/master/src/cpu/platform.cpp#L135 (removing the x64-specific code path should do the trick).
