### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by magicse** [oneapi-src/oneDNN#1447]
Windows 7
Codeblocks
Mingw64 

During compiling I get next error.

oneDNN-master\tests\benchdnn\commo
n.cpp: In function 'std::string locate_batch_file(const std::string&)':
oneDNN-master\tests\benchdnn\commo
n.cpp:388:18: error: 'readlink' was not declared in this scope
  388 |     int length = readlink("/proc/self/exe", &fdir[0], PATH_MAX);
      |                  ^~~~~~~~

**Comment by dzarukin** [comment]
Hi @magicse, you may want to check [this](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/common.cpp#L313) piece of code to adjust it for Mingw64 to work properly.

The assumption is Linux always has it at `<unistd.h>`, but for Windows we wrap `GetModuleFileName(...)` call with readlink interface.

I guess fixing macro condition should resolve the issue. Could you check it, please?

**Comment by vpirogov** [comment]
Closing as stale.
