### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by leizhenyuan** [oneapi-src/oneDNN#1448]
## Env:
cmake 3.16.3
gcc 9.4.0
os unbuntu

## build oneDnn from source  Succeed
mkdir -p build

cd build

export CC=icx

export CXX=icpx

cmake .. -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP

make -j

sudo cmake --build . --target install

export DNNL_VERBOSE=1

## git branch 
16418c6b6

## error
I tried to run an sample benchdnn command as follow:
./benchdnn --mode=cp --binary --engine=gpu --sdt=bf16:bf16 --ddt=bf16 --attr-scratchpad=user --stag=ABcd32a16b:ABcd32a16b --alg=ADD --inplace=true 256x256x56x56:256x256x56x56

and got the following error

./benchdnn: symbol lookup error: ./benchdnn: undefined symbol: dnnl_post_ops_append_dw

any recommandation to slove ?

thanks a lot

**Comment by dzarukin** [comment]
Hi @leizhenyuan, have you tried a clean build by removing a `build` directory entirely and build everything from scratch? I can't reproduce an issue on a clean build. Thank you.
