### ISSUE TITLE
Nested parallelism with openMP

### ISSUE THREAD

**Issue by webepasc** [oneapi-src/oneDNN#1464]
We are planning an application with nested parallelism. After taking care that every thread has his own pipeline and oneDNN is compiled with ONEDNN_ENABLE_CONCURRENT_EXEC=on, I wanted to bring it to a test. Unfortunately, the approach did not yield the wished speedup, since nested parallelism is disabled by default (see https://github.com/oneapi-src/oneDNN/blob/master/src/common/dnnl_thread.hpp#L169). When trying to "hack" the wished behavior by modifying dnnl_in_parallel() (https://github.com/oneapi-src/oneDNN/blob/master/src/common/dnnl_thread.hpp#L71) to

```
inline int dnnl_in_parallel() {
    return 0;
}
```

did also not bring the wished nested parallelism. Is there any reason why nested parallelism is disabled and is there any way to enable it?

**Comment by webepasc** [comment]
Today I tried to condition the use of nested parallelism using an omp if. A pseudocode would read

```
#pragma omp parallel for if( condition )
for( outer loop )
{
   oneDNN_invoquation();
}
```

I found that even if condition == false, I still observe the slow-down due to the serialization of oneDNN. Why is this the case? Isn't the omp_in_parallel() call responsible for this behavior?

**Comment by dzarukin** [comment]
Hi @webepasc, thank you for the question.

In general, nested parallelism is a complex technology that requires deep understanding of hardware and where the performance benefits come from. This is not something that one enables and get speed ups right away.

> Is there any reason why nested parallelism is disabled and is there any way to enable it?

There are two:
1) scratchpad (additional internal memory) management. The library can't assume that user re-creates primitives if number of threads changes inside the region, thus, can't reliably use internal memory which is necessary in certain scenarios.
2) internal blocking logic is usually not general (targeting single socket most of times), and nested parallelism on specific number of threads will not bring performance on par with parallelization inside a primitive anyway.

My recommendation is to either avoid nested parallelism (this is from performance perspective), or use solutions that orchestrate with threads on their side (like TensorFlow threadpool technology). One more option would be to make non unified memory access control tool (numactl) to make magic happen but this is OS and environment specific.

Hope it helps, thanks.

**Comment by webepasc** [comment]
Hello @dzarukin,

thank you for the answer. 

Let me better explain my situation: I am working on the Lumi supercomputer, more concretely on the LUMI-C compute nodes, which are equipped with 2 AMD EPYC 7763 CPUs. These CPUs have so-called Core Complex Dies (CCD), which are 8 cores that share L3-cache. If I benchmark my application, which uses oneDNN for the neural networks, I see a significant drop in performance when using more than 8 cores. In order to avoid this, I restrict my application to only use 8 cores and use numactl to map the application to the respective CCDs. 

However, this is an unsatisfying solution in the case where I want to train multiple neural networks. Ideally, I would be able to train the networks in parallel by using nested parallelism. My idea was to use the environment variable OMP_NUM_THREADS=8 such that oneDNN is restricted to using 8 cores and then use an outer parallel for with proc_bind(spread) to make sure the nested threads to not overlap. I tested the setup using the following script 

```
#include <omp.h>
#include <cstdio>
#include <utmpx.h>
#include <sched.h>

int main(int argc, char **argv)
{
  const int numNetworks = 16;
  #pragma omp parallel for num_threads(numNetworks) proc_bind(spread) schedule(static)
  for( size_t i = 0; i<numNetworks; i++ )
  {
    int cpuBefore = sched_getcpu();
    int tidBefore = omp_get_thread_num();
    int numThreadsBefore = omp_get_num_threads();
    #pragma omp parallel
    {
        int tid = omp_get_thread_num();
        int numThreads = omp_get_num_threads();
        int cpu = sched_getcpu();
        printf("     Hello! I am cpu %d running omp thread %d/%d originating from cpu=%d and thread %d/%d\n", cpu, tid, numThreads, cpuBefore, tidBefore, numThreadsBefore);
    }
  }

  return 0;
}
```

If I compile this application with GCC 11.2.0 using `g++ -fopenmp main.cpp -o main.o`, I get the wished mapping to CCDs

```
paweber@uan03:~> OMP_NUM_THREADS=8 srun --cpus-per-task=128 oneDNNdiscussion.o
     Hello! I am cpu 72 running omp thread 0/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 32 running omp thread 0/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 38 running omp thread 6/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 34 running omp thread 2/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 73 running omp thread 1/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 78 running omp thread 6/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 76 running omp thread 4/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 80 running omp thread 0/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 74 running omp thread 2/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 39 running omp thread 7/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 33 running omp thread 1/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 35 running omp thread 3/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 37 running omp thread 5/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 36 running omp thread 4/8 originating from cpu=32 and thread 4/16
     Hello! I am cpu 77 running omp thread 5/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 79 running omp thread 7/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 81 running omp thread 1/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 87 running omp thread 7/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 83 running omp thread 3/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 84 running omp thread 4/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 82 running omp thread 2/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 86 running omp thread 6/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 85 running omp thread 5/8 originating from cpu=80 and thread 10/16
     Hello! I am cpu 75 running omp thread 3/8 originating from cpu=72 and thread 9/16
     Hello! I am cpu 108 running omp thread 4/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 114 running omp thread 2/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 113 running omp thread 1/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 99 running omp thread 3/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 90 running omp thread 2/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 103 running omp thread 7/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 88 running omp thread 0/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 91 running omp thread 3/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 94 running omp thread 6/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 92 running omp thread 4/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 104 running omp thread 0/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 65 running omp thread 1/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 7 running omp thread 7/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 23 running omp thread 7/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 105 running omp thread 1/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 0 running omp thread 0/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 117 running omp thread 5/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 109 running omp thread 5/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 25 running omp thread 1/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 2 running omp thread 2/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 115 running omp thread 3/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 5 running omp thread 5/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 45 running omp thread 5/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 96 running omp thread 0/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 100 running omp thread 4/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 95 running omp thread 7/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 112 running omp thread 0/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 102 running omp thread 6/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 97 running omp thread 1/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 89 running omp thread 1/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 93 running omp thread 5/8 originating from cpu=88 and thread 11/16
     Hello! I am cpu 71 running omp thread 7/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 69 running omp thread 5/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 67 running omp thread 3/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 66 running omp thread 2/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 111 running omp thread 7/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 106 running omp thread 2/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 116 running omp thread 4/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 118 running omp thread 6/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 119 running omp thread 7/8 originating from cpu=112 and thread 14/16
     Hello! I am cpu 110 running omp thread 6/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 31 running omp thread 7/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 24 running omp thread 0/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 28 running omp thread 4/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 26 running omp thread 2/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 3 running omp thread 3/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 1 running omp thread 1/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 6 running omp thread 6/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 30 running omp thread 6/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 4 running omp thread 4/8 originating from cpu=0 and thread 0/16
     Hello! I am cpu 22 running omp thread 6/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 18 running omp thread 2/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 20 running omp thread 4/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 16 running omp thread 0/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 21 running omp thread 5/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 46 running omp thread 6/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 41 running omp thread 1/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 40 running omp thread 0/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 42 running omp thread 2/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 43 running omp thread 3/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 44 running omp thread 4/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 29 running omp thread 5/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 19 running omp thread 3/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 17 running omp thread 1/8 originating from cpu=16 and thread 2/16
     Hello! I am cpu 47 running omp thread 7/8 originating from cpu=40 and thread 5/16
     Hello! I am cpu 56 running omp thread 0/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 98 running omp thread 2/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 126 running omp thread 6/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 58 running omp thread 2/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 121 running omp thread 1/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 64 running omp thread 0/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 101 running omp thread 5/8 originating from cpu=96 and thread 12/16
     Hello! I am cpu 68 running omp thread 4/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 27 running omp thread 3/8 originating from cpu=24 and thread 3/16
     Hello! I am cpu 127 running omp thread 7/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 62 running omp thread 6/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 60 running omp thread 4/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 59 running omp thread 3/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 61 running omp thread 5/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 120 running omp thread 0/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 122 running omp thread 2/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 123 running omp thread 3/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 124 running omp thread 4/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 125 running omp thread 5/8 originating from cpu=120 and thread 15/16
     Hello! I am cpu 8 running omp thread 0/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 9 running omp thread 1/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 10 running omp thread 2/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 15 running omp thread 7/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 14 running omp thread 6/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 12 running omp thread 4/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 13 running omp thread 5/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 11 running omp thread 3/8 originating from cpu=8 and thread 1/16
     Hello! I am cpu 107 running omp thread 3/8 originating from cpu=104 and thread 13/16
     Hello! I am cpu 70 running omp thread 6/8 originating from cpu=64 and thread 8/16
     Hello! I am cpu 63 running omp thread 7/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 57 running omp thread 1/8 originating from cpu=56 and thread 7/16
     Hello! I am cpu 51 running omp thread 3/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 48 running omp thread 0/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 55 running omp thread 7/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 52 running omp thread 4/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 54 running omp thread 6/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 50 running omp thread 2/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 53 running omp thread 5/8 originating from cpu=48 and thread 6/16
     Hello! I am cpu 49 running omp thread 1/8 originating from cpu=48 and thread 6/16
```
Is there any way to achieve this mapping by enabling nested parallelism in oneDNN?

**Comment by dzarukin** [comment]
Is there anything that prevents from using 1 socket as an instance with 2 instances enabled if 1 socket performance is acceptable? Why bothering with nesting which is uncontrollable?

**Comment by webepasc** [comment]
Please excuse me, I do not completely understand what you mean.

Let me show you the scaling for the function that forward the data, computes the loss,and backwards the data for 1,...,10 cores:

![image](https://user-images.githubusercontent.com/14875526/193923865-8471b2b5-fb80-46b5-a931-ef427646bda0.png)

The blue line shows the speedup I get, the dashed back line is ideal, and the orange one from Ahmdal's law with a 70% parallel code fraction. This leads me to not map the code to sockets, but to these 8 core CCDs (see the CPU architecture here: https://docs.lumi-supercomputer.eu/computing/systems/lumic/). For the case that I have described, there I want to train multiple networks, there is shared data, that all the networks need to access, so I can either process them sequentially, or use some shared memory paradigm - which is why I wanted to reside to the nested approach. 

Regarding the threadpool approach that you mentioned: Could I override the threadpool interface to an openMP interface that allows for nested parallelism? Or is there another, perhaps simpler way to enable nested parallelism in oneDNN? And could you further elaborate what are the reasons that nested parallelism is disabled? As far as I understand, with ONEDNN_ENABLE_CONCURRENT_EXEC=on, there should not be a problem with the scratchpad (https://oneapi-src.github.io/oneDNN/v2.5/dev_guide_attributes_scratchpad.html) and I do not understand the second argument, because in case of training multiple networks in parallel, the operation can not be rewritten in terms of a single primitive. 

Thanks a lot for your patience and time to answer my inquiry.

**Comment by mgouicem** [comment]
Hi @webepasc , the main reason we disabled nested parallelism on purpose is that it typically causes oversubscription of the system, and poor performance (we had several reports of that in the past).

It is particularly the case for applications that use libraries, without knowing that those libraries spawn threads. Think application A, linking to library B and to oneDNN. Now the user of application A will have to set openMP environment to have best performance for parallel regions, following the recommendations of library B and oneDNN. Those will typically conflict.

So in order to make things simpler for the end user, we safe guarded against oversubscription. Performance will be suboptimal when  nested parallelism is enabled, but at least it won't be catastrophic. Hope this helps explain our decision to disable nested parallelism with OMP.

As Dmitry mentioned, you can use TBB and [task_arena](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Guiding_Task_Scheduler_Execution.html) to achieve that. Here you would create one task arena per CCX, and then run your topology within each of these arenas. There is a good example in the link I referenced.

You could also use the oneDNN threapool backend and implement your own threadpool interface [here](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_threadpool_iface.hpp), which would behave the way you want it to.

**Comment by webepasc** [comment]
Hello @mgouicem,

thanks for your answer. I completely understand this decision, however, I am curious if there is no simple way to re-enable it (don't worry, I will properly test/benchmark that I get a performance benefit before putting it into the wild). Also, I am curious why my attempt to simply modify https://github.com/oneapi-src/oneDNN/blob/master/src/common/dnnl_thread.hpp from

```
#elif DNNL_CPU_THREADING_RUNTIME == DNNL_RUNTIME_OMP
#include "omp.h"
#define DNNL_THR_SYNC 1
inline int dnnl_get_max_threads() {
    return omp_get_max_threads();
}
inline int dnnl_in_parallel() {
    return omp_in_parallel();
}
inline void dnnl_thr_barrier() {
#pragma omp barrier
}
```

to 

```
#elif DNNL_CPU_THREADING_RUNTIME == DNNL_RUNTIME_OMP
#include "omp.h"
#define DNNL_THR_SYNC 1
inline int dnnl_get_max_threads() {
    return omp_get_max_threads();
}
inline int dnnl_in_parallel() {
    return 0;
}
inline void dnnl_thr_barrier() {
#pragma omp barrier
} 
```
did not work. Is this the wrong place for this kind of surgery?

Thanks for the link to control the TBB threads. Unfortunately, when I tried using TBB, I could not make it work. I installed oneDNN with the TBB runtime, and when running, I got worse runtimes than with openMP. The cause got clear when I tried checking whether the correct amount of treads are available and found `tbb::this_task_arena::max_concurrency()==2`. I tried to modify this value using `tbb::task_scheduler_init init(nthread)`, unfortunately without success. 

With threadpool I also failed. I understand that I have to override https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl_threadpool_iface.hpp#L38, i.e. the virtual functions defined here 

```
struct threadpool_iface {
    /// Returns the number of worker threads.
    virtual int get_num_threads() const = 0;

    /// Returns true if the calling thread belongs to this threadpool.
    virtual bool get_in_parallel() const = 0;

    /// Submits n instances of a closure for execution in parallel:
    ///
    /// for (int i = 0; i < n; i++) fn(i, n);
    ///
    virtual void parallel_for(int n, const std::function<void(int, int)> &fn)
            = 0;

    /// Returns threadpool behavior flags bit mask (see below).
    virtual uint64_t get_flags() const = 0;

    /// If set, parallel_for() returns immediately and oneDNN needs implement
    /// waiting for the submitted closures to finish execution on its own.
    static constexpr uint64_t ASYNCHRONOUS = 1;

    virtual ~threadpool_iface() {}
};
```
However, I do not understand how I can put them into action since I do not understand the comment 
```
/// Abstract threadpool interface. The users are expected to subclass this
/// interface and pass an object to the library during CPU stream creation or
/// directly in case of BLAS functions.
```
Also I was irritated that although I did not define these pure virtual functions, the compilation using 
```
CXXFLAGS=-O3 cmake .. \
     -DCMAKE_INSTALL_PREFIX=$HOME/.local \
     -DONEDNN_BUILD_EXAMPLES=OFF \
     -DONEDNN_BUILD_TESTS=OFF \
     -DONEDNN_ENABLE_CONCURRENT_EXEC=ON \
     -DONEDNN_CPU_RUNTIME=TBB \
     -DONEDNN_ARCH_OPT_FLAGS='-march=native -mtune=native' \
     -DBUILD_SHARED_LIBS=true; make -j8; make install
```
did work without warning/error.

**Comment by mgouicem** [comment]
> did not work. Is this the wrong place for this kind of surgery?

At first glance, this surgery seems proper. Could you clarify what "did not work" mean here? Did you see sequential execution, or too many threads used? Could you also provide which primitive you are testing (a verbose log would be ideal here).

> Thanks for the link to control the TBB threads. Unfortunately, when I tried using TBB, I could not make it work. I installed oneDNN with the TBB runtime, and when running, I got worse runtimes than with openMP. The cause got clear when I tried checking whether the correct amount of treads are available and found tbb::this_task_arena::max_concurrency()==2. I tried to modify this value using tbb::task_scheduler_init init(nthread), unfortunately without success.

Task scheduler is the older mecanism and it is typically recommend to move away from it (see [this article](https://oneapi-src.github.io/oneTBB/main/tbb_userguide/Migration_Guide/Task_Scheduler_Init.html)).
I would really encourage you to use task_arena, since oneDNN relies on this_task_arena() to determine how many threads it needs to use at creation time. Also it is much simpler/robust than relying on the task scheduler.
Just remember that task_group might also be needed to allow for asynchronous execution of the different tasks in the different arenas.

> However, I do not understand how I can put them into action since I do not understand the comment

You typically have to create a threadpool object of the class you defined. Then use that object to create a dnnl::stream object though [this function](https://github.com/oneapi-src/oneDNN/blob/bf73fa213504bd5849f5114f35ffaeec99531b40/include/oneapi/dnnl/dnnl_threadpool.hpp#L40-L55).
Using that stream for primitive execution will allow you to schedule work through these threadpools (one per CCX).
The issue you will face here is with thread pinning/binding... This can be achieved with hwloc but is typically not that straightforward.

Also, the threadpool model does not allow global functions for queries (e.g. maximum concurrency), ... So oneDNN has to implement imprecise heuristics for load balancing during primitive creation time (more on that [here](https://github.com/oneapi-src/oneDNN/pull/1466)). Until this is worked around, I would hence encourage you to use TBB instead.

**Comment by webepasc** [comment]
> Could you clarify what "did not work" mean here? Did you see sequential execution, or too many threads used?

I observed that the runtime does not improve and thus concluded that I still have sequential execution. The example uses the following primitives:

```
inner_product_forward
inner_product_backward_data
inner_product_backward_weights
eltwise_forward
eltwise_backward
```

(it is a neural network with two hidden layers). They are created and then called in a parallel region with static scheduling. Like this I make sure that the memory resides close to the thread that will call the primitive. Even when the number of threads in the parallel region is set to 1, or the parallel execution is avoided by adding an if(0) to the pragma, the execution is slowed down. Here the verbose log in a case without the parallel region:

```
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic8oc128,17.595
onednn_verbose,exec,cpu,eltwise,jit:avx2,forward_training,data_f32::blocked:ab:f0 diff_undef::undef::f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.032959
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc128,0.0759277
onednn_verbose,exec,cpu,eltwise,jit:avx2,forward_training,data_f32::blocked:ab:f0 diff_undef::undef::f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.0378418
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc5,0.019043
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_data,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_undef::undef::f0 dst_f32::blocked:ab:f0,,,mb256ic128oc5,0.052002
onednn_verbose,exec,cpu,eltwise,jit:avx2,backward_data,data_f32::blocked:ab:f0 diff_f32::blocked:ab:f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.0351562
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_data,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_undef::undef::f0 dst_f32::blocked:ab:f0,,,mb256ic128oc128,0.0629883
onednn_verbose,exec,cpu,eltwise,jit:avx2,backward_data,data_f32::blocked:ab:f0 diff_f32::blocked:ab:f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.0310059
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_data,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_undef::undef::f0 dst_f32::blocked:ab:f0,,,mb256ic8oc128,0.0148926
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_weights,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic8oc128,0.0539551
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_weights,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc128,0.0791016
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_weights,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc5,0.0151367
```

, and one with the parallel region:

```
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic8oc128,20.208
onednn_verbose,exec,cpu,eltwise,jit:avx2,forward_training,data_f32::blocked:ab:f0 diff_undef::undef::f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.246094
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc128,0.700928
onednn_verbose,exec,cpu,eltwise,jit:avx2,forward_training,data_f32::blocked:ab:f0 diff_undef::undef::f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.312012
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc5,0.679932
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_data,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_undef::undef::f0 dst_f32::blocked:ab:f0,,,mb256ic128oc5,0.318115
onednn_verbose,exec,cpu,eltwise,jit:avx2,backward_data,data_f32::blocked:ab:f0 diff_f32::blocked:ab:f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.302979
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_data,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_undef::undef::f0 dst_f32::blocked:ab:f0,,,mb256ic128oc128,0.319824
onednn_verbose,exec,cpu,eltwise,jit:avx2,backward_data,data_f32::blocked:ab:f0 diff_f32::blocked:ab:f0,,alg:eltwise_soft_relu alpha:1 beta:0,256x128,0.299072
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_data,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_undef::undef::f0 dst_f32::blocked:ab:f0,,,mb256ic8oc128,0.324951
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_weights,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic8oc128,0.685059
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_weights,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc128,0.677002
onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,backward_weights,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb256ic128oc5,0.585938
```

The only differences that I can spot is the runtimes...

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional information.
