### ISSUE TITLE
Integer overflow in src/cpu/x64/jit_brgemm_conv_utils.cpp

### ISSUE THREAD

**Issue by ShuaiShao93** [oneapi-src/oneDNN#1468]
# Summary
In src/cpu/x64/jit_brgemm_conv_utils.cpp, [dim_od = nb_oh * dim_oh;](https://github.com/oneapi-src/oneDNN/blob/52b5f107dd9cf10910aaa19cb47f3abf9b349815/src/cpu/x64/jit_brgemm_conv_utils.cpp#L1239) dim_od is an int32 and overflows in our use case when nb_oh*dim_oh is too large.

# Version
v2.6

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model (try `lscpu`; if your `lscpu` does not list CPU flags,
  try running `cat /proc/cpuinfo | grep flags | sort -u`)
  * Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          20
On-line CPU(s) list:             0-19
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) W-2255 CPU @ 3.70GHz
* OS version (`uname -a`)
  * Linux desktop 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Compiler version (`gcc --version`)
  * clang11
* git hash (`git log -1 --format=%H`)
  * 52b5f107dd9cf10910aaa19cb47f3abf9b349815

# Observed behavior
When nb_oh = 655360, dim_oh = 32768, I got dim_od = 0 because of overflow, thus causing `src/common/utils.hpp:294: typename remove_reference<T>::type dnnl::impl::utils::div_up(const T, const U) [T = int, U = int]: Assertion 'b' failed.`

# Expected behavior
Support int64 when it's needed.

**Comment by vpirogov** [comment]
+@tprimak, @kwiersch

**Comment by kwiersch** [comment]
Hi @ShuaiShao93, thanks for the bug report! Could you include some steps to reproduce this issue? A benchdnn command line would be the easiest for me to start from.

**Comment by vpirogov** [comment]
Fixed by deb5595a0f96b54f9106cb846e6fc4e0af49aadf. Targeting v2.6.3 patch release.
