### ISSUE TITLE
Using scaling on Inputs for binary primitive

### ISSUE THREAD

**Issue by ItayLasch** [oneapi-src/oneDNN#1472]
I was trying to set the input scales attribute for Binary Primitive, Since in my case the value for the scales would be known at runtime only. I couldn't find documentation on how exactly to do that and this is a simpler version that represents what I was trying to do:

...
binary_desc = binary::desc(algorithm::binary_add, src1_md, src2_md, dst_md);
binary_post_ops.append_binary(algorithm::binary_mul, shift_md_2);

attr.set_post_ops(binary_post_ops);

binary_args.insert({DNNL_ARG_SRC_0, src1});
binary_args.insert({DNNL_ARG_SRC_1, src2});
binary_args.insert({DNNL_ARG_DST, elem_wise_dst_memory});
binary_args.insert({DNNL_ARG_ATTR_INPUT_SCALES | DNNL_ARG_SRC_0,shifts_memory_1});
binary_args.insert({DNNL_ARG_ATTR_INPUT_SCALES | DNNL_ARG_SRC_1, shifts_memory_2};
binary_args.insert({DNNL_ARG_ATTR_MULTIPLE_POST_OP(0) | DNNL_ARG_SRC_1, shifts_memory_3});

m_oneDNNObj.binary_prim.execute(s, binary_args);
 s.wait();
..
Disclaimer: This is not exactly the code since it is much longer but it is the general idea of what I'm trying to do.

since it is obviously not working I would be happy if you could show me how to use it or alternatively refer me to documentation/example that covers this issue.

thank you in advance

**Comment by dzarukin** [comment]
Hi @ItayLasch, thank you for the question.
The code doesn't provide details how memories for scales are set and no information what the error is, I'll provide some general tips:
* `INPUT_SCALES` support only a single value (whether it's runtime or compile time). Make sure your memory descriptor contains a single element.
* There are certain limitations on binary post-op. Depending on what `shift_md_2` is it may or may not be supported.

Feel free to share the mistake with us, also DNNL_VERBOSE=2 output and if possible - a standalone cpp file no matter how big it is (as long as it can be compiled and linked). Thank you.

**Comment by densamoilov** [comment]
Hi @ItayLasch, I don't see that you configured attributes for runtime scales. Did you do the following:
`attr.set_scales(arg, mask, {DNNL_RUNTIME_F32_VAL});`?

There is [documentation for output scales](https://oneapi-src.github.io/oneDNN/struct_dnnl_primitive_attr-2.html#doxid-structdnnl-1-1primitive-attr-1a4b81acc8e48886313154f75c1708ae02). The part about `DNNL_RUNTIME_F32_VAL` is there but the part is missing for `set_scales` API.

**Comment by ItayLasch** [comment]
> Hi @ItayLasch, thank you for the question. The code doesn't provide details how memories for scales are set and no information what the error is, I'll provide some general tips:
> 
> * `INPUT_SCALES` support only a single value (whether it's runtime or compile time). Make sure your memory descriptor contains a single element.
> * There are certain limitations on binary post-op. Depending on what `shift_md_2` is it may or may not be supported.
> 
> Feel free to share the mistake with us, also DNNL_VERBOSE=2 output and if possible - a standalone cpp file no matter how big it is (as long as it can be compiled and linked). Thank you.

Hi thank you for the reply,
I have multiple scales and so I am creating the memories for the scales like so:

std::vector<memory::desc> shift_md;
std::vector<dnnl::memory> shifts_memory;

for (int i = 0; i < m_shiftsData.size(); i++){
        float* shiftsData = (float*)m_shiftsData[i].get(); 
       shifts_memory.push_back(memory({params_dims, dt::f32, tag::nhwc}, eng, shiftsData));  
        shift_md.push_back(memory::desc(params_dims, dt::f32, tag::nhwc));
}

So for each scale I am creating a memory descriptor and a memory object.

Does binary primitive supports output scales. And if you could show me a simple example on how to use scales in binary primitive that woulb be great because I'm not quite sure I understand completly.

Thank you

**Comment by densamoilov** [comment]
> Does binary primitive supports output scales?

No, but we may add it later.

> And if you could show me a simple example on how to use scales in binary primitive that would be great because I'm not quite sure I understand completely.

Have you tried to configure attributed properly - `attr.set_scales(arg, mask, {DNNL_RUNTIME_F32_VAL});`?

**Comment by ItayLasch** [comment]
> Have you tried to configure attributed properly - `attr.set_scales(arg, mask, {DNNL_RUNTIME_F32_VAL});`?

I did but for what I'm getting from the output it seems that the scaling part doesn't happening. Can you maybe write a short example on how things should look like for it to work?

**Comment by densamoilov** [comment]
Output of the code below: `res: 7.5`

```cpp
using tag = memory::format_tag;
using dt = memory::data_type;

int main() {

    // Create execution dnnl::engine.
    dnnl::engine engine(engine::kind::cpu, 0);

    // Create dnnl::stream.
    dnnl::stream engine_stream(engine);

    auto src_0_md = memory::desc({1}, dt::f32, tag::a);
    auto src_1_md = memory::desc({1}, dt::f32, tag::a);
    auto dst_md = memory::desc({1}, dt::f32, tag::a);

    // Create src memory objects.
    float src0 = 2.0f;
    float src1 = 3.0f;
    float scale = 1.5f;

    auto src_0_mem = memory(src_0_md, engine, &src0);
    auto src_1_mem = memory(src_1_md, engine, &src1);
    auto dst_mem = memory(dst_md, engine);
    auto scale_mem = memory(src_1_md, engine, &scale);

    primitive_attr attr;
    attr.set_scales(DNNL_ARG_SRC_0, 0, {DNNL_RUNTIME_F32_VAL});
    attr.set_scales(DNNL_ARG_SRC_1, 0, {DNNL_RUNTIME_F32_VAL});

    auto binary_d
            = binary::desc(algorithm::binary_add, src_0_md, src_1_md, dst_md);
    auto binary_pd = binary::primitive_desc(binary_d, attr, engine);
    auto binary_prim = binary(binary_pd);

    std::unordered_map<int, memory> binary_args;
    binary_args.insert({DNNL_ARG_SRC_0, src_0_mem});
    binary_args.insert({DNNL_ARG_SRC_1, src_1_mem});
    binary_args.insert({DNNL_ARG_DST, dst_mem});
    binary_args.insert({DNNL_ARG_ATTR_INPUT_SCALES | DNNL_ARG_SRC_0, scale_mem});
    binary_args.insert({DNNL_ARG_ATTR_INPUT_SCALES | DNNL_ARG_SRC_1, scale_mem});

    binary_prim.execute(engine_stream, binary_args);
    engine_stream.wait();
    float res = *(float *)dst_mem.get_data_handle();
    std::cout << "res: " << res << std::endl;

    return 0;
}

```

**Comment by ItayLasch** [comment]
> Output of the code below: `res: 7.5`
> 
> ```c++
> using tag = memory::format_tag;
> using dt = memory::data_type;
> 
> int main() {
>     dnnl::engine engine(engine::kind::cpu, 0);
>     dnnl::stream engine_stream(engine);
> 
>     auto src_0_md = memory::desc({1}, dt::f32, tag::a);
>     auto src_1_md = memory::desc({1}, dt::f32, tag::a);
>     auto dst_md = memory::desc({1}, dt::f32, tag::a);
> 
>     float src0 = 2.0f;
>     float src1 = 3.0f;
>     float scale = 1.5f;
> 
>     auto src_0_mem = memory(src_0_md, engine, &src0);
>     auto src_1_mem = memory(src_1_md, engine, &src1);
>     auto dst_mem = memory(dst_md, engine);
>     auto scale_mem = memory(src_1_md, engine, &scale);
> 
>     primitive_attr attr;
>     attr.set_scales(DNNL_ARG_SRC_0, 0, {DNNL_RUNTIME_F32_VAL});
>     attr.set_scales(DNNL_ARG_SRC_1, 0, {DNNL_RUNTIME_F32_VAL});
> 
>     auto binary_d
>             = binary::desc(algorithm::binary_add, src_0_md, src_1_md, dst_md);
>     auto binary_pd = binary::primitive_desc(binary_d, attr, engine);
>     auto binary_prim = binary(binary_pd);
> 
>     std::unordered_map<int, memory> binary_args;
>     binary_args.insert({DNNL_ARG_SRC_0, src_0_mem});
>     binary_args.insert({DNNL_ARG_SRC_1, src_1_mem});
>     binary_args.insert({DNNL_ARG_DST, dst_mem});
>     binary_args.insert({DNNL_ARG_ATTR_INPUT_SCALES | DNNL_ARG_SRC_0, scale_mem});
>     binary_args.insert({DNNL_ARG_ATTR_INPUT_SCALES | DNNL_ARG_SRC_1, scale_mem});
> 
>     binary_prim.execute(engine_stream, binary_args);
>     engine_stream.wait();
>     float res = *(float *)dst_mem.get_data_handle();
>     std::cout << "res: " << res << std::endl;
> 
>     return 0;
> }
> ```

thank you for the detailed example!!! unfortunately I still get an error from onednn saying: "could not execute a primitive" even though I wrote my code as you did.

**Comment by ItayLasch** [comment]
Hi I think I figured out my problem.
can we use a tensor for set_scales or is it accepting only a single element?

**Comment by densamoilov** [comment]
For now only mask 0 is supported, which means a scalar scale will be applied to the whole tensor. Non-scalar scale is not supported at this point.
