### ISSUE TITLE
No runtime scales in option_set_fwks_key_gpu

### ISSUE THREAD

**Issue by milpuz01** [oneapi-src/oneDNN#1478]
# Summary
When running `benchdnn` for convolution input from here https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/inputs/conv/option_set_fwks_key_gpu we get error parsing it because oscales is not defined as runtime. i.e. it us using `--attr-oscale=per_oc` but it should have value such us `--attr-oscale=per_oc:0.5*`

# Version
onednn_verbose,info,oneDNN v2.7.0 (commit 4358e67d480bd11baca94861a8b4b28db4be894f)

# Steps to reproduce

benchdnn --start=1070 --conv --batch=../tests/benchdnn/inputs/conv/option_set_fwks_key_gpu

# Observed behavior
@@@ error [dnnl_primitive_attr* create_dnnl_attr(const attr_t&, const attr_args_t&):906]: 'attr.oscale.runtime ? 0 : 1' -> 1

# Expected behavior
1071:PASSED __REPRO: --conv --allow-enum-tags-only=false --dir=FWD_I --cfg=s8s8u8 --stag=abcd --attr-oscale=per_oc:0.5* --attr-post-ops=add:f32:per_dim_0 mb1ic3ih224oc64oh112kh7sh2ph3n"resnet-50.inf.int8.ov.mb1*1"

**Comment by milpuz01** [comment]
CC: @kealan-barbieri

**Comment by dzarukin** [comment]
Hi @milpuz01, thank you for reporting this one. I can reproduce it and it will be fixed soon on master.

**Comment by dzarukin** [comment]
Resolved with 24617ca7d4d9d590cc517d1ba58abafcb939a413.
