### ISSUE TITLE
Relative install dir breaks installations from source

### ISSUE THREAD

**Issue by alejandrosame** [oneapi-src/oneDNN#1497]
I'm trying to use oneDNN as a dependency and trying to install it from source. The goal I'm trying to achieve is package [Flashlight](https://github.com/flashlight/flashlight)  (which has oneDNN as a dependency) via the [Nix package manager](https://nixos.org/).

The problem I'm facing is that I can't have `Flashlight` consume `oneDNN` as a source dependency due to having a relative install dir at
https://github.com/oneapi-src/oneDNN/blob/8859a1a0c17679799a1530dbc822f59100ef0721/src/CMakeLists.txt#L169.

The issue with this approach is explained with more detail in this [document](https://github.com/jtojnar/cmake-snips#assuming-cmake_install_dir-is-relative-path).

Could this problem be addressed, so the users downstream aren't forced to keep repatching?

**Comment by vpirogov** [comment]
Thanks for the report, @alejandrosame. I tried to find why `INSTALL_PREFIX` is necessary here, but it does not seem to be necessary even with CMake 2.8.12. Is this the only place that you have to patch?

**Comment by vpirogov** [comment]
Fixed by 55a6231aaab59080d797f6cc549ec272494f0aa3.

**Comment by vpirogov** [comment]
Backported to rls-v2.7 and rls-v3.0 branches.
