### ISSUE TITLE
What is the status of support for deconvolution in TensorFlow and PyTorch

### ISSUE THREAD

**Issue by annop-w** [oneapi-src/oneDNN#1502]
For TensorFlow I have tried running a simple script:
```
import tensorflow as tf
output_shape = [3, 8, 8, 128]
strides = [1, 2, 2, 1]
l = tf.constant(0.1, shape=[3, 4, 4, 4])
w = tf.constant(0.1, shape=[7, 7, 128, 4])
h1 = tf.nn.conv2d_transpose(l, w, output_shape=output_shape, strides=strides, padding='SAME')
```
and run with `ONEDNN_VERBOSE=1`. I have seen #193 and it looks like deconvolution is still currently
implemented as backward convolution in TF since I see
```
onednn_verbose,exec,cpu,convolution,gemm:ref,backward_data,src_f32::blocked:acdb:f0 wei_f32::blocked:cdba:f0 bia_undef::undef::f0 dst_f32::blocked:acdb:f0,,alg:convolution_direct,mb3_ic128oc4_ih8oh4kh7sh2dh0ph2_iw8ow4kw7sw2dw0pw2,0.666992
```

For PyTorch I have tried running
```
import torch
import torch.nn as nn
m = nn.ConvTranspose2d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50, 100)
output = m(input)
```
and see no message from oneDNN at all.

I have been trying to understand support for oneDNN deconvolution at the framework level.
Thank  you.

**Comment by agramesh1** [comment]
@annop-w we are working on adding support for deconvolution in Tensorflow and will be submitting a PR to TF.

**Comment by annop-w** [comment]
@agramesh1 Thank you for your reply. Is it something in the near future ? and is there also a plan for PyTorch ?

**Comment by gujinghui** [comment]
For PyTorch GPU, we are using oneDNN deconv primitive directly.
But your case is working on PyTorch CPU.

@jgong5 pls help.

```
import torch
import torch.nn as nn
m = nn.ConvTranspose2d(16, 33, 3, stride=2)
input = torch.randn(20, 16, 50, 100)
output = m(input)
```

**Comment by vpirogov** [comment]
Closing as stale.
