### ISSUE TITLE
Installation Issue during step: make -j

### ISSUE THREAD

**Issue by kaustubhroyvlabs** [oneapi-src/oneDNN#1507]
no member named sycl_interlop in namespace dnnl
no member named sycl in the global namespace and others...
![install_oneapi_error](https://user-images.githubusercontent.com/110053115/203773946-0b0556f4-2c1f-4fd1-8b44-04213a55c9bd.png)

**Comment by densamoilov** [comment]
Have you include "dnnl_sycl.hpp"?

**Comment by kaustubhroyvlabs** [comment]
I might not have done it properly. I’m trying to link the libraries
properly. I’ll get back to you in a few hours.

**Comment by kaustubhroyvlabs** [comment]
I am closing this issue. I think it was an issue with oneapi installation. Closing the issue. Thanks.
