### ISSUE TITLE
Fatal Error when trying to compile example/getting_started.cpp: fatal error: '/CL/sycl.hpp' file not found

### ISSUE THREAD

**Issue by kaustubhroyvlabs** [oneapi-src/oneDNN#1509]
![getting_started](https://user-images.githubusercontent.com/110053115/203977993-755f5a4f-b9d2-4d74-a019-1e2c953e55f6.png)
# Summary
Provide a short summary of the issue. Sections below provide guidance on what
factors are considered important to reproduce an issue.

# Version
I followed the Installation through package manager guide in the website
* CPU : AMD Ryzen 5700x 
* OS version : Ubuntu 20.04.5 LTS
* Compiler version icpx
* CMake version GNU Make 4.2.1

# Observed behavior
Upon executing the command:
~/MyComputer/OneDNN/oneDNN/examples$ icpx -I${DNNLROOT}/include -L${DNNLROOT}/lib test.cpp -ldnnl

the out put is:
In file included from test.cpp:30:
In file included from ./example_utils.hpp:36:
In file included from /opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/include/dnnl_sycl.hpp:20:
/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/include/oneapi/dnnl/dnnl_sycl.hpp:29:10: fatal error: '/CL/sycl.hpp' file not found

# Expected behavior
Compile the getting_started.cpp file

**Comment by kaustubhroyvlabs** [comment]
I have noticed that the referenced file, dnnl_sycl.hpp has include <CL/sycl.hpp> in it. but the folder for CL is not in the same directory. If I edit this header to include the full path of the file sycl.hpp, it proceeds to the next step but similarly fails at detecting other headers included in the linked files. This is creating a chain of "file not found" errors. I must be missing something here.

**Comment by densamoilov** [comment]
This is because you didn’t pass -fsycl compiler option.

Please note that the recommended way to build examples is to use CMake:
```bash
CC=icx
CXX=icpx
cmake ${PATH_TO_EXAMPLES}
make
```

**Comment by kaustubhroyvlabs** [comment]
I see…
I didn’t wish to compile the existing examples, made a new file which
copied the code from getting started.cpp and added a few lines.
I will give this a try and see if it works.

Thanks for the reply

**Comment by kaustubhroyvlabs** [comment]
passing -fsycl throws an interesting new error
![no matching constructor for relu example](https://user-images.githubusercontent.com/110053115/204530067-2b85956c-dbb0-49b0-9190-a9fc1aaa0c83.png)

**Comment by kaustubhroyvlabs** [comment]
The descriptor defined in the example passes 7 arguments: 
engine
propagation_kind
algorithm
source_desc
destination_desc
alpha
beta

but the primitive_desc constructor does not have a compatible function:
![primitive_desc](https://user-images.githubusercontent.com/110053115/204530967-771d14d1-9210-4d8c-9208-86e7c0fe2c89.png)
![primitive_desc](https://user-images.githubusercontent.com/110053115/204530987-b10c6aea-6213-4349-97ee-307b9763f47c.png)

**Comment by dzarukin** [comment]
[This](https://github.com/oneapi-src/oneDNN/blob/master/include/oneapi/dnnl/dnnl.hpp#L6404) is the constructor which should be found and used for compilation.
Please make sure you are using oneDNN and example from same repo/revision. Thanks.

**Comment by kaustubhroyvlabs** [comment]
/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/include/oneapi/dnnl/dnnl.hpp
You're right, it's not linking to the correct file. should i replace the ${DNNLROOT}/include with
"/home/user/OneDNN/oneDNN/include"
This is the where I cloned the current git repo. It contains the file you referenced.

I used the package manager to install oneapi-basekit. do you think this is the root of the cause; because the developer's guide seems to point out that it is required; but this only makes the DNNLROOT point to a wrong version (maybe?)

**Comment by vpirogov** [comment]
oneAPI Basekit includes a version of oneDNN and sets environment to use this specific version. oneDNN 2022.2 is not API compatible with the code in this repository master branch, as we are working towards future versions of oneDNN here.

**Comment by kaustubhroyvlabs** [comment]
Ok… this makes sense. So how do I fix it?
should I just not install oneAPI then?

**Comment by vpirogov** [comment]
Well, it actually depends on what your goal is. There are two options:
* If you want to work with oneAPI Basekit you should stick to [API available in oneDNN 2022.2](https://www.intel.com/content/www/us/en/develop/documentation/onednn-developer-guide-and-reference/top.html).
* If you want to build development version of oneDNN from source I'd suggest uninstalling oneDNN component from the oneAPI Basekit.

**Comment by kaustubhroyvlabs** [comment]
I’ll take the second route and see how that goes. Thanks!

**Comment by vpirogov** [comment]
Have fun!
