### ISSUE TITLE
Is bool type not supported in binary greater op?

### ISSUE THREAD

**Issue by lzwhard** [oneapi-src/oneDNN#1511]
> The source and destination tensors may have f32, bf16, f16 or s8/u8 data types. 

https://oneapi-src.github.io/oneDNN/dev_guide_binary.html

what type does `greater op` return?

**Comment by dzarukin** [comment]
Hi @lzwhard, binary primitive converts input data types to fp32, performs floating point comparison, converts and stores the output to destination data type requested by user.
oneDNN doesn't support `bool` data type. Minimal data types are s8 (`signed char`) or u8 (`unsigned char`), Thank you.

**Comment by vpirogov** [comment]
Irrespective of the data type return value can be interpreted as `bool`: `1` for true and `0` for false.
