### ISSUE TITLE
Does Binary OP support int32 data type?

### ISSUE THREAD

**Issue by lzwhard** [oneapi-src/oneDNN#1515]
> The source and destination tensors may have f32, bf16, f16 or s8/u8 data types. 

[doc](https://oneapi-src.github.io/oneDNN/dev_guide_binary.html#) says that it only supports above data types. But It works when I pass int32 tensor to Binary OP. I am not sure.

**Comment by dzarukin** [comment]
Hi @lzwhard, reference binary implementation does support, but optimized one does not, that's why it's not stated there. What's your use case for s32 binary op? Thank you.

**Comment by lzwhard** [comment]
We have some const data (int64) from onnx model, which datatype is not supported in our framework, so we need cast it to int32.

Thanks a lot! Maybe I should cast it to float32.
