### ISSUE TITLE
Interface for bfloat16 matrix multiplication function

### ISSUE THREAD

**Issue by CosimoRulli** [oneapi-src/oneDNN#1527]
Hello developers, 

thank you for your amazing library. I have my own c++ project which includes oneDNN and  I currently am using the ```dnnl_sgemm``` function for floating point 32matrix multiplication. To include it in my code, I simply use ```#include "dnnl.hpp"``` and everything works fine.

Now, I would like to use the bfloat16 version of matrix multiplication, namely the function ```dnnl_gemm_bf16bf16f32```, but when I try I get the following errors:

```
‘bfloat16_t’ was not declared in this scope
``` 

```
‘dnnl_gemm_bf16bf16f32’ was not declared in this scope
```

I took a look at the ```oneDNN/include/oneapi/dnnl/dnnl.h``` [file](https://github.com/oneapi-src/oneDNN/tree/master/include/oneapi/dnnl) and I realize that ```dnnl_gemm_bf16bf16f32``` is not included in that file. I tried to add the following lines to the ```dnnl.h``` file

```
dnnl_status_t dnnl_gemm_bf16bf16f32(char transa, char transb, dnnl_dim_t M,
        dnnl_dim_t N, dnnl_dim_t K, float alpha, const bfloat16_t *A,
        dnnl_dim_t lda, const bfloat16_t *B, dnnl_dim_t ldb, float beta,
        float *C, dnnl_dim_t ldc);
```

but the compiler still complains about bfloat16_t 

```
[..]/oneDNN/include/oneapi/dnnl/dnnl.h:3466:31: error: ‘bfloat16_t’ does not name a type; did you mean ‘float_t’?
```
Can you help me solve this problem?

**Comment by feng-intel** [comment]
Did you refer to ./tests/gtests/test_gemm_common.hpp  

```
// Declare bfloat16 GEMM interfaces for testing
extern "C" {
dnnl_status_t dnnl_gemm_bf16bf16f32(char transa, char transb, dnnl_dim_t M,
        dnnl_dim_t N, dnnl_dim_t K, float alpha, const bfloat16_t *A,
        dnnl_dim_t lda, const bfloat16_t *B, dnnl_dim_t ldb, float beta,
        float *C, dnnl_dim_t ldc);
}
```


this test can work,   tests/gtests/test_gemm_bf16bf16f32.cpp

**Comment by CosimoRulli** [comment]
I have included the snippet that you suggested in my code, but the compiler still complains about ```bfloat16_it```. I get the following error

```
error: 'bfloat16_t' does not name a type; did you mean 'float_t'?
```

**Comment by feng-intel** [comment]
Can you add this and check ?
```
#include "src/common/bfloat16.hpp"
using bfloat16_t = dnnl::impl::bfloat16_t;
```

**Comment by igorsafo** [comment]
Hi @CosimoRulli ,

We highly recommend using Matmul primitive API to implement gemm functionality. The reason is matmul provides more features like different data types support, CPU & GPU devices, post-operations, etc. Here is an example of implementing sgemm using matmul API: https://github.com/oneapi-src/oneDNN/blob/master/examples/tutorials/matmul/cpu_sgemm_and_matmul.cpp 


If you already have data in bfloat16 then it can be passed as a handle to oneDNN memory object with `data_type::bf16`:
```cpp
    memory A_m({{M, K}, memory::data_type::bf16, a_strides}, eng, (void *)A_bf16);
```
If data is in float, it can be converted to bfloat16 using Reorder primitive:
```cpp
    memory A_m_f32({{M, K}, memory::data_type::f32, a_strides}, eng, (void *)A_f32);
    memory A_m_bf16({{M, K}, memory::data_type::bf16, a_strides}, eng, (void *)A_bf16);
    reorder r(A_m_f32, A_m_bf16);
    r.execute(stream, A_m_f32, A_m_bf16);
```
Here is a reorder example: https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/reorder.cpp

**Comment by CosimoRulli** [comment]
The solution by @feng-intel solved my problem. Thanks also to @igorsafo for the cool suggestion. I am closing the issue.
