### ISSUE TITLE
doc/build/build_options.md uses ONEDNN_ prefix

### ISSUE THREAD

**Issue by plopresti** [oneapi-src/oneDNN#1528]
The settings documented in doc/build/build_options.md all start with ONEDNN_. Looking at the source code, these should all be DNNL_.

Over-aggressive search&replace? Or is there actually an intent to rename all of these from DNNL_ to ONEDNN_ ?

**Comment by vpirogov** [comment]
@plopresti, this is intended. oneDNN environment variables and CMake build options have `ONEDNN` prefix. `DNNL` prefix is currently supported for backward compatibility purposes.

**Comment by plopresti** [comment]
I see... All of the references in *.cmake and *.hpp still use the DNNL_ names. I was missing dnnl_compat.cmake.

Thanks.
