### ISSUE TITLE
How do I use a matmul_attr:scale properly?

### ISSUE THREAD

**Issue by kaustubhroyvlabs** [oneapi-src/oneDNN#1531]
I was trying to implement a layer that scales down the output of a matmul operation. I know it can be done with a separate scaling primitive, but I saw the fused OP possible with matmul in the scenario and it felt like a good place to optimize the code. 
I wasn't too clear on how to use it properly though since there is no corresponding example in the developer's guide... I tried this:

Here, A, W, O and scales are variable memory Objects from user input, for scales, I used a {1} size descriptor with one value.

It works perfectly if I don't try to use a scale and gives the correct matmul behaviour; can anyone suggest what might be going wrong?
the only error I get is Aborted (Core Dumped). So, I'm not sure... should I pass a vector scale? I tried passing a float value but it doesn't work.

void matrix_multiply(memory A, memory W, memory O, memory scales){
    engine eng = A.get_engine();
    stream engine_stream(eng);

    memory::desc A_md = A.get_desc();
    memory::desc W_md = W.get_desc();
    memory::desc O_md = O.get_desc();

    primitive_attr matmul_attr;
    
    matmul_attr.set_scales_mask(0, 0);
    auto matmul_pd = matmul::primitive_desc(eng, A_md, W_md, O_md, matmul_attr);
    auto matmul_prim = matmul(matmul_pd);

    std::unordered_map<int, memory> matmul_args;
    matmul_args.insert({DNNL_ARG_SRC, A});
    matmul_args.insert({DNNL_ARG_WEIGHTS, W});
    matmul_args.insert({DNNL_ARG_SCALE | 0, scales});
    matmul_args.insert({DNNL_ARG_DST, O});

    matmul_prim.execute(engine_stream, matmul_args);

    engine_stream.wait();
}

**Comment by kaustubhroyvlabs** [comment]
Should I mail you the file? Can I have your email ID?

**Comment by dzarukin** [comment]
Just attach it here or post it in GitHub Gists, whatever works for you.

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional informaiton.
