### ISSUE TITLE
windows build fails with undefined symbol: _intel_fast_memset

### ISSUE THREAD

**Issue by ashokei** [oneapi-src/oneDNN#1532]
# Summary
during windows build with DPCPP runtime, it fails at the end with **lld-link: error: undefined symbol: _intel_fast_memset, _intel_fast_memcpy**

<img width="977" alt="image" src="https://user-images.githubusercontent.com/29638935/212505114-bcf26438-ca78-4c95-b332-d07fdbb9baca.png">
 

# Version
d49bfbe6c2c0725902b43b3d15c72cb3303be55d

# Environment
Windows 10, build with DPCPP backend.

# Steps to reproduce
`
>cmake .. -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_WITH_LEVEL_ZERO=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=icpx -G Ninja
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- The C compiler identification is Clang 16.0.0 with GNU-like command-line
-- The CXX compiler identification is Clang 16.0.0 with GNU-like command-line
-- Check for working C compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/bin-llvm/clang.exe
-- Check for working C compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/bin-llvm/clang.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/bin/icpx.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/bin/icpx.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: X64
-- DNNL_LIBRARY_NAME: dnnl
-- Performing Test SYCL_FLAG_SUPPORTED
-- Performing Test SYCL_FLAG_SUPPORTED - Success
-- OpenCL runtime is found in the environment: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/windows/lib/OpenCL.lib
-- DPC++ support is enabled (OpenCL and Level Zero)
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- TBB: C:/Program Files (x86)/Intel/oneAPI/tbb/latest
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE) 
-- Found PythonInterp: D:/ipex/p39/python.exe (found suitable version "3.9.7", minimum required is "2.7") 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.36.1.windows.1") 
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Primitive cache is enabled
-- The ASM_MASM compiler identification is MSVC
-- Found assembler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/ml64.exe
-- Configuring done
-- Generating done
-- Build files have been written to: D:/ipex/oneDNN/build
`

**Comment by vpirogov** [comment]
@ashokei, I do not see any build issues in validation. One thing that jumps at me is use of deprecated `clang` driver. Do you see the same issue with `icx`?

**Comment by ashokei** [comment]
thanks @vpirogov  , where can i see the validation build log. I am interested in checking the "cmake" config command.  I used the below, it completed successfully but fails during linking phase after build.
`cmake .. -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_WITH_LEVEL_ZERO=1 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=icpx -G Ninja`

**Comment by vpirogov** [comment]
You can find documentation in the [Build from Source](https://oneapi-src.github.io/oneDNN/dev_guide_build.html#id1) section of the developer guide. The following works with Intel oneAPI Basekit 2023:
```
cmake .. -DDNNL_CPU_RUNTIME=DPCPP -DDNNL_GPU_RUNTIME=DPCPP -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icx -G Ninja
```

**Comment by ashokei** [comment]
build passes using latest cmake and above cmake args
