### ISSUE TITLE
Is there an implementation document for oneDNN GEMM?

### ISSUE THREAD

**Issue by huangmiumang** [oneapi-src/oneDNN#1544]
Is there an implementation document for oneDNN GEMM? Corresponding code is below:
https://github.com/oneapi-src/oneDNN/blob/v2.6/src/cpu/x64/gemm/f32/jit_avx_gemm_f32.cpp

**Comment by dzarukin** [comment]
Hi @huangmiumang, sorry, but we don't. This file implements the most internal logic to generate gemm blocks that are dispatched from a higher level driver. May I ask what's your interest in this file?

**Comment by huangmiumang** [comment]
> 
I am more interested in the implementation of oneDNN GEMM, so I would like to ask if there are any relevant documents for reference.

**Comment by dzarukin** [comment]
Depending on a backend of interest, there several different flavors for each.
CPU [has](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/matmul/cpu_matmul_list.cpp):
* [BRGeMM-based](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/matmul/brgemm_matmul.hpp) (batch-reduced GeMM);
* [JIT (just-in-time) kernels](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/matmul/gemm_f32_matmul.hpp)-based (the one you were asking initially about, and all related).
* [Reference](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/matmul/ref_matmul.hpp)

GPU [has](https://github.com/oneapi-src/oneDNN/blob/master/src/gpu/gpu_gemm_list.cpp):
* [nGen-based](https://github.com/oneapi-src/oneDNN/blob/master/src/gpu/ocl/gemm/xe_lp_gemm.hpp)
* Bunch of OpenCL-based

Feel free to get acknowledged with them.
oneDNN doesn't provide technical documentation for internals, mostly comments if any, doc exists only for API references and developer guide to navigate through operation specifics and their description.

**Comment by huangmiumang** [comment]
> Ok，I got it. Thanks very much!
