### ISSUE TITLE
Lots of undefined references with Arm Compute Library (ACL) on aarch64

### ISSUE THREAD

**Issue by 666easyfuture** [oneapi-src/oneDNN#1596]
# Summary
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- The C compiler identification is GNU 9.3.1
-- The CXX compiler identification is GNU 9.3.1
-- Check for working C compiler: /opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/gcc
-- Check for working C compiler: /opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/g++
-- Check for working CXX compiler: /opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: AARCH64
-- DNNL_LIBRARY_NAME: dnnl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found ACL: /home/xxxx/mkl_acl/ComputeLibrary  
-- Arm Compute Library: /home/xxxx/mkl_acl/ComputeLibrary/build/libarm_compute.so;/home/xxxx/mkl_acl/ComputeLibrary/build/libarm_compute_graph.so;/home/xxxx/mkl_acl/ComputeLibrary/build/libarm_compute_core.so
-- Arm Compute Library headers: /home/xxxx/mkl_acl/ComputeLibrary;/home/xxxx/mkl_acl/ComputeLibrary/include
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE) 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.18", minimum required is "2.7") 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Primitive cache is enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxxx/mkl_acl/oneDNN/build

part of undefined information:
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEFullyConnectedLayer::NEFullyConnectedLayer(std::shared_ptr<arm_compute::IMemoryManager>, arm_compute::IWeightsManager*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::INESimpleFunctionNoBorder::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPReluLayer::NEPReluLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPixelWiseMultiplication::NEPixelWiseMultiplication()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NETranspose::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMMConvolutionLayer::NEGEMMConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager> const&, arm_compute::IWeightsManager*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEElementwiseDivision::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEActivationLayer::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEElementwiseMax::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::INESimpleFunctionNoBorder::~INESimpleFunctionNoBorder()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEFullyConnectedLayer::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMMConv2d::NEGEMMConv2d(std::shared_ptr<arm_compute::IMemoryManager> const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEBatchNormalizationLayer::NEBatchNormalizationLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPoolingLayer::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::PoolingLayerInfo const&, arm_compute::ITensor*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEActivationLayer::NEActivationLayer(arm_compute::IRuntimeContext*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMMConv2d::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `vtable for arm_compute::NEMeanStdDevNormalizationLayer'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEMeanStdDevNormalizationLayer::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, float)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NETranspose::~NETranspose()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEBatchNormalizationLayer::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEBatchNormalizationLayer::~NEBatchNormalizationLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEDeconvolutionLayer::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEArithmeticSubtraction::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ConvertPolicy, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEArithmeticAddition::NEArithmeticAddition()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEConvolutionLayer::get_convolution_method(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&, arm_compute::Size2D const&, arm_compute::ActivationLayerInfo const&, bool)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPoolingLayer::NEPoolingLayer(std::shared_ptr<arm_compute::IMemoryManager>)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEElementwiseDivision::NEElementwiseDivision()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEDeconvolutionLayer::configure(arm_compute::ITensor*, arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::PadStrideInfo const&, bool)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPoolingLayer::~NEPoolingLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEActivationLayer::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEMeanStdDevNormalizationLayer::~NEMeanStdDevNormalizationLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NETranspose::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NESoftmaxLayerGeneric<true>::configure(arm_compute::ITensor*, arm_compute::ITensor*, float, int)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMMConv2d::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::Conv2dInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NESoftmaxLayerGeneric<false>::configure(arm_compute::ITensor*, arm_compute::ITensor*, float, int)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NESoftmaxLayerGeneric<false>::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, float, int)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEBatchNormalizationLayer::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, float, arm_compute::ActivationLayerInfo)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEArithmeticSubtraction::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::ConvertPolicy, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEElementwiseMax::NEElementwiseMax()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEElementwiseMax::configure(arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ITensor*, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEElementwiseMin::NEElementwiseMin()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEWinogradConvolutionLayer::NEWinogradConvolutionLayer(std::shared_ptr<arm_compute::IMemoryManager> const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMMConv2d::~NEGEMMConv2d()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NESoftmaxLayerGeneric<false>::NESoftmaxLayerGeneric(std::shared_ptr<arm_compute::IMemoryManager>)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPReluLayer::~NEPReluLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPReluLayer::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `typeinfo for arm_compute::INESimpleFunctionNoBorder'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEArithmeticAddition::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ConvertPolicy, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NETranspose::configure(arm_compute::ITensor const*, arm_compute::ITensor*)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEPReluLayer::run()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMMConvolutionLayer::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::PadStrideInfo const&, arm_compute::WeightsInfo const&, arm_compute::Size2D const&, arm_compute::ActivationLayerInfo const&, bool, unsigned int)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEFullyConnectedLayer::~NEFullyConnectedLayer()'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEArithmeticAddition::configure(arm_compute::ITensor const*, arm_compute::ITensor const*, arm_compute::ITensor*, arm_compute::ConvertPolicy, arm_compute::ActivationLayerInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NESoftmaxLayerGeneric<true>::NESoftmaxLayerGeneric(std::shared_ptr<arm_compute::IMemoryManager>)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMM::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, float, float, arm_compute::GEMMInfo const&)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NESoftmaxLayerGeneric<true>::validate(arm_compute::ITensorInfo const*, arm_compute::ITensorInfo const*, float, int)'
/opt/aarch64/compiler/gcc-9.3.1-2021.03-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/9.3.1/../../../../aarch64-linux-gnu/bin/ld: ../../src/libdnnl.so.3.1: undefined reference to `arm_compute::NEGEMM::~NEGEMM()'

# Version
mkl-dnn v3.0.1
acl 23.02.1

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
CPU make and model: aarch64
OS version (uname -a):Linux pod2p-arm-183 4.19.90-2112.8.0.0131.oe1.aarch64 #1 SMP Fri Dec 31 19:53:20 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
Compiler version (gcc --version) 9.3.1
CMake version (cmake --version) 3.16.5

# Steps to reproduce
Try to build against shared libraries of ACL.

# Observed behavior
I can see that mkldnn finds all the so files for ACL when cmake is done, but mkldnn still reports an error when compiling.
# Expected behavior
Link to ACL shared libraries should work.

**Comment by nSircombe** [comment]
Hi @666easyfuture,

Could you please share all the details of the other steps in your build process. How you're building ACL, which env. vars. you've set, the full `cmake` like you're using etc.

**Comment by 666easyfuture** [comment]
This is my problem. I do not understand the meaning of ACL-related parameters. When I install the ACL, the command is "scons Werror=0 -j8 debug=0 neon=0 opencl=1 arch=armv8a". However, I actually compile the ACL in a CPU environment. Therefore, I change the compilation parameter to "scons Werror=0 -j8 debug=0 neon=1 opencl=0 arch=armv8a build=native cppthreads=1 openmp=1" and compile PyTorch successfully.

**Comment by nSircombe** [comment]
> When I install the ACL, the command is "scons Werror=0 -j8 debug=0 neon=0 opencl=1 arch=armv8a".

As you've spotted, you need `neon=1` and `opencl=0` for CPU targets. You should not set both `openml` and `cppthreads` though - it's either/or. These are two different options for ACL's scheduler, I would recommend you pick OpenMP and turn off the pthreads scheduler. i.e. `cppthreads=0 openmp=1`.

 If you're compiling for a target that supports armv8.2a or newer, you should also set `multi_isa=1` this provides runtime support for the latest features, such as SVE and bf16, where HW supports. 

The automation scripts in this repo should help with getting a working stand-alone oneDNN build stood up:
https://github.com/oneapi-src/oneDNN/blob/master/.github/automation/build_acl.sh
https://github.com/oneapi-src/oneDNN/blob/master/.github/automation/build.sh

If you're building PyTorch from source, the upstream scripts in PyTorch/builder should give you all you need - https://github.com/pytorch/builder/blob/a007fbcc97b6f02a777104d6e0e94c80f3d2d41e/aarch64_linux/build_aarch64_wheel.py (see https://github.com/pytorch/builder/blob/a007fbcc97b6f02a777104d6e0e94c80f3d2d41e/aarch64_linux/build_aarch64_wheel.py#L234)
