### ISSUE TITLE
[benchdnn] `runtime_dims_masks` doesn't seem to work as expected?

### ISSUE THREAD

**Issue by dcaballe** [oneapi-src/oneDNN#1602]
The example provided in the matmul driver documentation doesn't seem to work for me:

```
benchdnn --matmul --runtime_dims_masks=3:3 10x30:30x20
0:SKIPPED (INVALID_CASE) __REPRO: --matmul --runtime_dims_masks=3:3 10x30:30x20
tests:1 passed:0 skipped:1 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:0 listed:0
total compute_ref: sum(s):0.00
```

I built oneDNN from source yesterday using the dpcpp-cpp-compiler_p_2023.0.0.25393 on Linux.

**Comment by igorsafo** [comment]
Hi @dcaballe , thanks for catching this issue.
Runtime dimensions require tags to be set. Originally benchdnn explicitly set it to `ab` but with this change https://github.com/oneapi-src/oneDNN/commit/5e78846cf4abc924b842a91ecb728580ecef6c2a it is no longer the case so benchdnn requires to set tags explicitly when runtime dimensions are used, but the documentation still states that they are set by default to `ab`:
https://github.com/oneapi-src/oneDNN/blob/c3c080b8e670fe756f10b104186ee87e7c6546d7/tests/benchdnn/doc/driver_matmul.md?plain=1#L14-L19

Here is a modification to make your test work:
```bash
$ ./build/tests/benchdnn/benchdnn  --matmul --runtime_dims_masks=3:3 --stag=ab --wtag=ab --dtag=ab 10x30:30x20
0:PASSED __REPRO: --matmul --stag=ab --wtag=ab --dtag=ab --runtime_dims_masks=3:3 10x30:30x20
```
