### ISSUE TITLE
Bench normalisation unit test failing

### ISSUE THREAD

**Issue by milpuz01** [oneapi-src/oneDNN#1614]
# Summary
This change https://github.com/oneapi-src/oneDNN/pull/1608 introduced `test_batch_normalization` to start failing. It looks like the reason is that this line: https://github.com/oneapi-src/oneDNN/blob/a1f314e101d9115a76f1f1a54bb4e05aa7725f4f/tests/gtests/test_batch_normalization.cpp#L108 has changed from `aa.po_eltwise = !is_amd_gpu(eng);` to `aa.po_eltwise = is_amd_gpu(eng);` so test is expecting to fail to create batch normalisation primitive on non-AMD GPU platform with post-op eltwise. 

# Version
oneDNN hash a1f314e101d9115a76f1f1a54bb4e05aa7725f4f

# Environment
* CPU make and model: AWS Graviton 3 (AArch64)
* OS version: Linux 78209d6b1396 5.15.0-1031-aws #35~20.04.1-Ubuntu SMP Sat Feb 11 16:19:53 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
* Compiler version: gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
* CMake version: cmake version 3.16.3

# Steps to reproduce
Run tests/gtests/test_batch_normalization

# Observed behavior
[==========] 38 tests from 5 test suites ran. (274 ms total)
[  PASSED  ] 22 tests.
[  FAILED  ] 16 tests, listed below:

One of the errors:
./oneDNN/tests/gtests/dnnl_test_common.hpp:887: Failure
Expected: pd_t pd(eng, prim_params..., attr_po_eltwise) throws an exception.
  Actual: it doesn't.

# Expected behavior
All tests to pass.

**Comment by densamoilov** [comment]
@milpuz01, should be fixed in 5aabea153825347afa92a2d9f69dd893246bea45.
