### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by jelmervdl** [oneapi-src/oneDNN#1615]
# Summary
The documentation and API reference links in the README are currently broken:
- https://oneapi-src.github.io/oneDNN
- https://oneapi-src.github.io/oneDNN/group_dnnl_api.html

In the meantime I've found https://www.intel.com/content/www/us/en/docs/onednn/developer-guide-reference/2023-0/onednn-api.html but the versioning there doesn't match the versioning here, so I'm not entirely clear how much behind those docs are to v3.0.1 or master.

# Version
The repository is at a1f314e at the time of writing. I don't know which commit broke the docs.

**Comment by igorsafo** [comment]
Hi @jelmervdl , thanks for reporting the issue. Indeed branch `gh-pages` contains broken documentation. We will notify you once it is fixed.
