### ISSUE TITLE
Fully fused MLP implementation

### ISSUE THREAD

**Issue by salykovaa** [oneapi-src/oneDNN#1618]
Dear all,

Developers from Nvidia have recently re-implemented MLP network and called it "Fully-Fused MLP", which is 5x-10x faster than the equivalent MLP implementation from PyTorch or TensorFlow. People currently use these fully-fused MLPs  to accelerate training and inference of ML applications, particularly they use them extensively in neural computer graphics to obtain high gains in speed. I would like to know do you maybe plan to implement it or do you have an equivalent implementation? 

I think it is a nice feature, which will enrich oneDNN library and make the library more attractive for machine learning / computer graphics researchers and engineers.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/63703454/229091825-8126ac7f-7c1e-4e46-b7dc-599696b5d030.png">

References:
[1] [Real-time Neural Radiance Caching for Path Tracing](https://arxiv.org/abs/2106.12372)
[2] [Technical Paper](https://www.nvidia.com/en-us/on-demand/session/gtcspring21-e31307/)
[3] [Fully fused MLP implementation](https://github.com/NVlabs/tiny-cuda-nn)

**Comment by vpirogov** [comment]
@salykovaa, there's indeed an optimization opportunity in complex subgraphs like MLP block, multi-head attention (MHA) block, or convolutional residual block. These creates two issues for a library:
* It's hard to provide stable API as there are many different variants of these blocks. This is addressed in oneDNN by recently introduced [Graph API](https://oneapi-src.github.io/oneDNN/graph_extension.html) which allows to express arbitrary subgraphs without breaking API.
* Performant implementation has to be highly specialized for particular shapes and sizes as you see mentioned in the paper. We are tackling this problem with [Graph Compiler backend](https://oneapi-src.github.io/oneDNN/dev_guide_graph_compiler.html). Current version is experimental, but it already provides optimized implementations of MHA, MLP, and convolution residual block.

**Comment by salykovaa** [comment]
@vpirogov Thanks for your reply. Very interesting! I will take a look into it
