### ISSUE TITLE
The test_convolution_eltwise_forward_f32 test never finishes

### ISSUE THREAD

**Issue by yurivict** [oneapi-src/oneDNN#1619]
# Summary
It didn't finish in 7 hours:
```
  PID USERNAME    THR PRI NICE   SIZE    RES STATE    C   TIME    WCPU COMMAND
49245 yuri          1 102    0    71M    60M CPU3     3 416:25 100.00% test_convolution_el
```

# Version
3.1

# Environment
oneDNN includes hardware-specific optimizations and may behave
differently on depending on the compiler and build environment. Include
the following information to help reproduce the issue:
* CPU make and model: Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz
* OS version: FreeBSD 13.1
* Compiler version: clang-14
* CMake version 3.25.1

# Steps to reproduce
regular build+test

**Comment by dzarukin** [comment]
Hi @yurivict, could you set ONEDNN_VERBOSE=1 to see if it executes primitives from the test, please?

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional information.
