### ISSUE TITLE
Error: could not create a primitive descriptor for an inner product forward propagation primitive

### ISSUE THREAD

**Issue by lzwhard** [oneapi-src/oneDNN#1629]
oneDNN version: v3.1
Reproduction code:
```cpp
int main(int argc, char **argv) {
    auto eng = engine(dnnl::engine::kind::cpu, 0);
    primitive_attr attr;
    attr.set_scales_mask(DNNL_ARG_SRC, /* mask */ 0);
    attr.set_zero_points_mask(DNNL_ARG_SRC, /* mask */ 0);
    attr.set_scales_mask(DNNL_ARG_WEIGHTS, /* mask */ 1);
    auto any_src0_md = memory::desc({3, 30}, dt::u8, memory::format_tag::any);
    auto any_src1_md = memory::desc({50, 30}, dt::s8, memory::format_tag::any);
    auto any_dst_md = memory::desc({3, 50}, dt::f32, memory::format_tag::any);
    auto inner_product_pd_ = dnnl::inner_product_forward::primitive_desc(eng,
                        prop_kind::forward_inference, any_src0_md, any_src1_md, any_dst_md, attr);

    std::cout << "success!\n";
    return 0;
}
```

error log:
`what():  could not create a primitive descriptor for an inner product forward propagation primitive`

May I ask if there is a problem with my usage?

**Comment by lzwhard** [comment]
By the way, there is no example for int8 innerproduct

**Comment by mgouicem** [comment]
Hi @lzwhard , it seems we don't support zero points for inner-product. (if you comment the zero point mask setting, this should work).

**Comment by vpirogov** [comment]
Right, according to oneDNN developer guide inner product [does not support zero points](https://oneapi-src.github.io/oneDNN/dev_guide_inner_product.html#post-ops-and-attributes). I wish we had this information in error message.

If you are trying to implement matrix multiplication then [matmul primitive](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html) would be the best choice. There are also [several examples](https://github.com/oneapi-src/oneDNN/tree/master/examples/tutorials/matmul) covering int8 support in matmul.

**Comment by lzwhard** [comment]
Thanks for reply. But how does it support u8*s8? @mgouicem @vpirogov

**Comment by lzwhard** [comment]
When I created an example of **u8s8->f32 innerproduct**, I encountered another calculation error. The correct output should be 20 elements with all 0.337262839, but I found that the following few outputs were clearly incorrect. (I print them in GDB because there is an error "`corrupted size vs. prev_size`" during runtime)

actual output:
```
(gdb) p out
$1 = std::vector of length 20, capacity 20 = {0.337262839, 0.337262839, 0.337262839, 0.337262839, 0.337262839, 0.337262839, 0.337262839, 0.337262839, 0.337262839, 0.337262839, 0, 0, 0, 0, 0, 0, 0, 0, 41.0634155, 0}
```

my code:
```cpp
#include <stdexcept>
#include "oneapi/dnnl/dnnl.hpp"
#include "example_utils.hpp"

using namespace dnnl;
using tag = memory::format_tag;
using dt = memory::data_type;


int main(int argc, char **argv) {
	auto eng = engine(dnnl::engine::kind::cpu, 0);
	primitive_attr attr;
	attr.set_scales_mask(DNNL_ARG_SRC, /* mask */ 0);
	attr.set_scales_mask(DNNL_ARG_WEIGHTS, /* mask */ 1);
	auto A_md = memory::desc({3, 30}, dt::u8, memory::format_tag::any);
	auto B_md = memory::desc({50, 30}, dt::s8, memory::format_tag::any);
	auto out_md = memory::desc({3, 50}, dt::f32, memory::format_tag::any);
	auto inner_product_pd_ = dnnl::inner_product_forward::primitive_desc(eng,
					prop_kind::forward_inference, A_md, B_md, out_md, attr);

	inner_product_forward ip_p(inner_product_pd_);


	memory A_u8_mem({{1, 2}, memory::data_type::u8, {2, 1}}, eng);
	memory B_s8_mem({{20, 2}, memory::data_type::s8, {2, 1}}, eng);
	memory sc_A_mem({{1}, memory::data_type::f32, {1}}, eng);
	memory sc_B_mem({{1}, memory::data_type::f32, {1}}, eng);
	memory out_mem({{1, 20}, memory::data_type::f32, {20, 1}}, eng);

	// prepare inputs
	std::vector<float> scales1{0.00419014481937184};
	std::vector<float> scales2{0.006097693142928477};
	write_to_dnnl_memory(scales1.data(), sc_A_mem);
	write_to_dnnl_memory(scales2.data(), sc_B_mem);

	std::vector<uint8_t> srcA;
	srcA.resize(2, 200);
	std::vector<int8_t> srcB;
	srcB.resize(40, 33);
	write_to_dnnl_memory(srcA.data(), A_u8_mem);
	write_to_dnnl_memory(srcB.data(), B_s8_mem);

	std::vector<float> out;
	out.resize(200, 0);
	write_to_dnnl_memory(out.data(), out_mem);

	// execute
	stream s(eng);
	std::unordered_map<int, memory> memory_args_;
	memory_args_[DNNL_ARG_ATTR_SCALES | DNNL_ARG_SRC] = sc_A_mem;
	memory_args_[DNNL_ARG_ATTR_SCALES | DNNL_ARG_WEIGHTS] = sc_B_mem;
	memory_args_[DNNL_ARG_SRC] = A_u8_mem;
	memory_args_[DNNL_ARG_WEIGHTS] = B_s8_mem;
	memory_args_[DNNL_ARG_DST] = out_mem;
	ip_p.execute(s, memory_args_);
	s.wait();

	read_from_dnnl_memory(out.data(), out_mem);
	for(int i = 0; i < 20; i++) {
		std::cout << out[i] << std::endl;
	}
       return 0;
}
```

**Comment by mgouicem** [comment]
> Thanks for reply. But how does it support u8*s8? @mgouicem @vpirogov

Support of u8 datatype without zero-point  is typically useful for CNNs where the relu activation is used. For those, the activations are unsigned by design.

> When I created an example of u8s8->f32 innerproduct, I encountered another calculation error. The correct output should be 20 elements with all 0.337262839, but I found that the following few outputs were clearly incorrect.

This is because when you created the primitive you have let the primitive choose what is the best memory layout to use

```c++
        auto A_md = memory::desc({1, 2}, dt::u8, memory::format_tag::any);
	auto B_md = memory::desc({20, 2}, dt::s8, memory::format_tag::any);
	auto out_md = memory::desc({1, 20}, dt::f32, memory::format_tag::any);
	auto inner_product_pd_ = dnnl::inner_product_forward::primitive_desc(eng,
					prop_kind::forward_inference, A_md, B_md, out_md, attr);
```

However, you created the memory objects with the data in specific memory layouts (what is called `memory::format_tag::ab`), which is different than what the primitive has chosen:

```c++
        memory A_u8_mem({{1, 2}, memory::data_type::u8, {2, 1}}, eng);
	memory B_s8_mem({{20, 2}, memory::data_type::s8, {2, 1}}, eng);
```

The simple fix that will make for your snippet work is to use `memory::format_tag::ab` when creating `A_md`, `B_md`, and `out_md`.

If you are interested in going further and getting more performance, you can use `memory::format_tag::any` and the reorder primitive as described in [this tutorial](https://oneapi-src.github.io/oneDNN/page_memory_format_propagation_cpp.html).

**Comment by lzwhard** [comment]
Thank @mgouicem for pointing out the error. The weight mask should be set to 0 in the case of per-tensor quantization. My problem has been solved, thanks a lot! @vpirogov
