### ISSUE TITLE
Compiler used in prebuilt mac onednn library 

### ISSUE THREAD

**Issue by praveen0447** [oneapi-src/oneDNN#1630]
Hi, 

We are using the prebuilt onednn library for mac.Specifically [dnnl_mac_1.4.0_cpu_iomp.tgz](https://github.com/oneapi-src/oneDNN/releases/download/v1.4/dnnl_mac_1.4.0_cpu_iomp.tgz). Could you tell me what is the compiler used for building this library? 

Is it Clang that comes by default with Xcode or any other compiler? Is there a way to get the compiler information from the libmkldnn.dylib? I tried to use _otool_ and _objdump_  but could not get the desired information.

Thanks,
Praveen

**Comment by vpirogov** [comment]
@praveen0447, oneDNN `cpu_iomp` packages rely on Intel OpenMP runtime and built with Intel C/C++ Compiler. This particular package used Intel C/C++ Compiler 19.0.

**Comment by vpirogov** [comment]
You can build oneDNN on macOS with Clang as well, the caveat is that Apple Clang does not support OpenMP, so you'll need to switch to TBB threading.
