### ISSUE TITLE
Examples of classic Deep Neural Network.

### ISSUE THREAD

**Issue by Airbala** [oneapi-src/oneDNN#1631]
Hi, I want to know that if there is other CNN example in oneDNN, such as VGG16 or YOLO. There is only one AlexNet exmaple in [cnn_inference_f32.cpp](https://github.com/oneapi-src/oneDNN/blob/master/examples/cnn_inference_f32.cpp) now.

**Comment by yehudaorel** [comment]
Hi @Airbala, for CNN workloads the only sample code provided by oneDNN is AlexNet implementation for inference and training. For building other/custom networks, follow the tutorials provided in the [oneDNN docs](https://github.com/oneapi-src/oneDNN#documentation) and use the AlexNet example as a guideline implementation.

Hope this helps, let us know if you have any other questions!

**Comment by vpirogov** [comment]
@feixuedudiao, you would need to implement corresponding code yourself. oneDNN is a performance library, not a framework or inference engine, so it does not provide everything necessary to run models. If you want to train or deploy models with oneDNN acceleration you should use OpenVINO, Pytorch, Tensorflow or one of [other applications](https://github.com/oneapi-src/oneDNN?tab=readme-ov-file#applications-enabled-with-onednn) offering oneDNN acceleration.

**Comment by feixuedudiao** [comment]
@vineelabhinav Thanks, Does the network inference operator of OpenVINO use the operator of the OneDNN framework?
