### ISSUE TITLE
Segmentation fault issues in CPU and GPU

### ISSUE THREAD

**Issue by dyedd** [oneapi-src/oneDNN#1635]
Hello, may I ask if I allow example CNN programs on the CPU and use Pytorch pre training weights for inference, but there may be segment errors on the CPU. I defined the problem as fc7, where there is a calculation error, but there is no problem on the GPU. May I ask if there are any testing and repair methods available?
The oneDNN version is 3.0.0, the latest oneAPI installation package, and the CPU is i5-13600KF, the GPU is arc A770
The segmentation fault occurred on the CPU and was not a problem during GPU testing.

**Comment by vpirogov** [comment]
@dyedd,

Segmentation fault indicates incorrect memory access. It may be caused by an application, for instance via incorrect use of oneDNN API, or a bug within oneDNN implementation. Are you using a framework to run the model or you have an implementation using oneDNN directly?

**Comment by vpirogov** [comment]
Here're some useful debug capabilities if you suspect a defect in oneDNN:
* [verbose mode](https://oneapi-src.github.io/oneDNN/v3.1/dev_guide_verbose.html) reports information about all the oneDNN calls in application.
* [benchnn](https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn#readme) can test any oneDNN function with any set of parameters for bugs.
* [verbose converter](https://github.com/oneapi-src/oneDNN/tree/master/scripts/verbose_converter#readme) converts oneDNN verbose output to benchdnn test cases.

**Comment by dyedd** [comment]
@vpirogov I use oneDNN directly.There is no problem with the program code. For AlexNet, since I started running normally with 48 convolutional kernels, a segmentation fault occurred with 64 kernels. When I annotated fc7, the program was able to run normally again. Therefore, I suspect it is due to issues such as CPU accuracy.

**Comment by dyedd** [comment]
verbose converter
```
prim_kind      shapes                                                     ncalls  time(ms)  overall%  agg_ncalls(avg)  agg_time(ms)  agg_overall%
inner_product  mb1ic256ih6iw6oc4096                                       100     260.74    36.43     100.00           260.74        36.43
inner_product  mb1ic4096oc4096                                            100     123.30    17.23     100.00           384.04        53.65
convolution    mb1_ic64oc192_ih27oh27kh5sh1dh0ph2_iw27ow27kw5sw1dw0pw2    100     59.72     8.34      100.00           443.76        62.00
convolution    mb1_ic384oc256_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1   100     46.41     6.48      100.00           490.17        68.48
convolution    mb1_ic3oc64_ih224oh55kh11sh4dh0ph2_iw224ow55kw11sw4dw0pw2  100     40.79     5.70      100.00           530.97        74.18
convolution    mb1_ic192oc384_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1   100     39.51     5.52      100.00           570.48        79.70
convolution    mb1_ic256oc256_ih13oh13kh3sh1dh0ph1_iw13ow13kw3sw1dw0pw1   100     35.54     4.96      100.00           606.01        84.67
lrn            mb1ic64ih55iw55ls5beta0.75                                 100     13.97     1.95      100.00           619.98        86.62
lrn            mb1ic192ih27iw27ls5beta0.75                                100     12.23     1.71      100.00           632.22        88.33
reorder        1x3x224x224                                                100     11.21     1.57      100.00           643.43        89.89
pooling        mb1ic64_ih55oh27kh3sh2dh0ph0_iw55ow27kw3sw2dw0pw0          100     10.88     1.52      100.00           654.31        91.41
inner_product  mb1ic4096oc3                                               100     10.70     1.49      100.00           665.01        92.91
pooling        mb1ic192_ih27oh13kh3sh2dh0ph0_iw27ow13kw3sw2dw0pw0         100     9.62      1.34      100.00           674.63        94.25
reorder        1x256x6x6                                                  100     8.65      1.21      100.00           683.28        95.46
pooling        mb1ic256_ih13oh6kh3sh2dh0ph0_iw13ow6kw3sw2dw0pw0           100     8.64      1.21      100.00           691.92        96.67
reorder        4096x4096                                                  1       6.82      0.95      93.81            698.74        97.62
reorder        192x64x5x5                                                 1       4.61      0.64      88.35            703.35        98.26
softmax        1x3                                                        100     4.46      0.62      89.00            707.81        98.89
reorder        1x3                                                        100     3.74      0.52      89.58            711.55        99.41
reorder        256x384x3x3                                                1       2.35      0.33      85.15            713.90        99.74
reorder        256x256x3x3                                                1       0.80      0.11      81.14            714.71        99.85
reorder        384x192x3x3                                                1       0.65      0.09      77.50            715.35        99.94
reorder        64x3x11x11                                                 1       0.23      0.03      74.17            715.58        99.97
reorder        3x4096                                                     1       0.19      0.03      71.13            715.77        100.00
```

**Comment by vpirogov** [comment]
This is weird, as accuracy issues are not known to cause segfaults. Could you please elaborate on what you mean by 'annotated fc7'?

Would you mind sharing a log for the crashing case collected with `ONEDNN_VERBOSE=2`? If the code available that I can play with it would be useful too.

**Comment by vpirogov** [comment]
One thing I see in the log is that you are using non-production version of oneDNN. I'd suggest you try rls-v3.1 branch head, which includes fixes to most known issues.

Other than that I need a way to reproduce behavior you report to investigate further.

**Comment by dyedd** [comment]
I have used the latest version of the community. Could you please take a look at the email? There seems to be an error reported, but I didn't understand it

> One thing I see in the log is that you are using non-production version of oneDNN. I'd suggest you try rls-v3.1 branch head, which includes fixes to most known issues.
> 
> Other than that I need a way to reproduce behavior you report to investigate further.

**Comment by dyedd** [comment]
@vpirogov 
I'm not sure if it's the CPU or oneDNN version. I'm currently working on oneDNN 2.7 and i7-9750H CPUs!!!! Therefore, there must be a problem with onednn3 at present.

**Comment by dyedd** [comment]
@vpirogov 
1. The email sent yesterday was about the latest version of oneDNN testing, which was all the information and stopped at the pool layer. Therefore, I feel that this is the error message

2. Later, I also sent a PTH weight file because I don't know how you extract weight data. Therefore, I sent this file and only need to provide the weight data to Conv1_ Weight, bias, etc., in the product function. In addition, I have also sent the shapes of each layer through PDF, and I believe that this program can achieve the same effect as mine. Of course, I also sent the approximate structure of the source code in the email.

3. Then run the program normally and an error will occur

4. I will not report errors when using onednn2.7 version, but when using oneDNN3, it may be due to an API error.

**Comment by vpirogov** [comment]
The issue in your version is likely in incorrect size of buffers allocated for weights and biases. In particular this snippet allocates memory buffers using `load_net_data` function which does not guarantee that resulting buffer is enough for `{48, 3, 11, 11}` shape:
```
memory::dims conv1_weights_tz = {48, 3, 11, 11};
        memory::dims conv1_bias_tz = {48};

        std::vector<float> conv1_weights = load_net_data("conv1-weight");
        std::vector<float> conv1_bias = load_net_data("conv1-bias");

        auto user_weights_memory = memory({{conv1_weights_tz}, dt::f32, tag::oihw}, eng);
        write_to_dnnl_memory(conv1_weights.data(), user_weights_memory);
        auto conv1_user_bias_memory = memory({{conv1_bias_tz}, dt::f32, tag::x}, eng);
        write_to_dnnl_memory(conv1_bias.data(), conv1_user_bias_memory);
```

Here's [working version of the model](https://gist.github.com/vpirogov/7aca44e561d16e37f2434264bc3b80c4) for reference.

**Comment by dyedd** [comment]
@vpirogov The length assigned to my function after printing is the same as the cumulative product implemented by product. Additionally, if using product, how should I transfer weights?

**Comment by vpirogov** [comment]
@dyedd, in that case something else is going on in the application. The fact that stripped down version of the code runs without segfaults indicates that there's something wrong with the remaining code. Please try to narrow issue down to something reproducible with simple C++ program or oneDNN tests. Here's a couple of ideas:
* [Debugging a segfault with gdb](https://www.cprogramming.com/debugging/segfaults.html#:~:text=The%20strategy%20for%20debugging%20all,that%20caused%20the%20segmentation%20fault.&text=This%20just%20loads%20the%20program,core%20file%20called%20%22core%22.)
* Testing suspected functions with benchdnn
  * Collect log with [verbose mode](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html)
  * Convert the log with [verbose converter](https://github.com/oneapi-src/oneDNN/tree/master/scripts/verbose_converter) to benchdnn commands
  * Run [benchdnn](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md)

**Comment by dyedd** [comment]
> @dyedd, in that case something else is going on in the application. The fact that stripped down version of the code runs without segfaults indicates that there's something wrong with the remaining code. Please try to narrow issue down to something reproducible with simple C++ program or oneDNN tests. Here's a couple of ideas:
> 
> * [Debugging a segfault with gdb](https://www.cprogramming.com/debugging/segfaults.html#:~:text=The%20strategy%20for%20debugging%20all,that%20caused%20the%20segmentation%20fault.&text=This%20just%20loads%20the%20program,core%20file%20called%20%22core%22.)
> * Testing suspected functions with benchdnn
>   
>   * Collect log with [verbose mode](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html)
>   * Convert the log with [verbose converter](https://github.com/oneapi-src/oneDNN/tree/master/scripts/verbose_converter) to benchdnn commands
>   * Run [benchdnn](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md)

Thank you very much for the information about segmentation errors. I have finally found the root cause! It's a pointer problem.
But it's curious why these issues were not discovered during the compilation of onednn2.7. Is it because the compiler has been upgraded?

**Comment by vpirogov** [comment]
It seems to be just luck. Depending on how the bad pointer is used you may see various symptoms including memory corruption, incorrect results, and segfaults. Likely changes in oneDNN memory descriptors between v2.7 and v3.0 resulted in different symptom.
