### ISSUE TITLE
About default dilation in convolution

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1652]
https://github.com/oneapi-src/oneDNN/blob/5dc0698b11f6f02ddd5566ab5d5b0a27622d5199/src/common/convolution.cpp#L122
Why the default dilation is 0 but 1?

**Comment by vpirogov** [comment]
I tried to dig up history, but the reason we use 0 seems to be lost.

**Comment by MOLOjl** [comment]
All right, thanks anyway.
