### ISSUE TITLE
How to understand this code in brgemm 1x1 calc_block_1x1()

### ISSUE THREAD

**Issue by llxingkongxia** [oneapi-src/oneDNN#1656]
In code[ jit_brgemm_conv_utils.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_brgemm_conv_utils.cpp):1687，automatic tuning of appropriate block parameters via calc_blocks_1x1().

    if (is_os_blocking) { 
        ow_block = 0;
        const auto max_os_block_thr 
                = (src_dsz * ic >= 1024 && src_dsz * ic < 4096)
                ? nstl::max(nstl::min(16, os),
                        div_up(os, div_up(nthr, mb * div_up(oc, oc_block))))
                : nstl::max(div_up(2048, oc_block),
                        static_cast<int>(div_up(mb * ngroups * os, nthr))); 
        const auto max_os_block_L2 = max_sp_block_L2;
        auto max_os_block_aliasing = 1000000 / nthr;
        if ((oc_without_padding * os * dst_dsz) % P4K == 0) {
            max_os_block_aliasing /= 1;
            for (auto cur_oc = oc_without_padding;
                    max_os_block_aliasing * dst_dsz > 400 && cur_oc % 2 == 0
                    && cur_oc * os * dst_dsz >= P4K;
                    cur_oc /= 2) {
                max_os_block_aliasing /= 2;
            }
            max_os_block_aliasing += max_os_block_aliasing % 2 ? 0 : 1;
        }
        max_os_block_aliasing
                = nstl::min(div_up(1001, dst_dsz), max_os_block_aliasing);

        start_sp_block = utils::saturate(1, os,
                nstl::min(nstl::min(max_os_block_thr, max_os_block_L2),
                        max_os_block_aliasing));

    } 

I can't understand this code.

- max_os_block_thr
   - If ic belongs to [1024/src_dsz ,  4096/src_dsz),  choose :  nstl::max(nstl::min(16, os), div_up(os, div_up(nthr, mb * div_up(oc, oc_block)))); otherwise choose:  nstl::max(div_up(2048, oc_block), static_cast<int>(div_up(mb * ngroups * os, nthr))).
   - I don't understand how to get this formula

- if ((oc_without_padding * os * dst_dsz) % P4K == 0)
   - Does the output size require page alignment? 

- for (auto cur_oc = oc_without_padding; max_os_block_aliasing * dst_dsz > 400 && cur_oc % 2 == 0 && cur_oc * os * dst_dsz >= P4K; cur_oc /= 2) 
   - Why the judgment condition is  **max_os_block_aliasing * dst_dsz > 400 && cur_oc % 2 == 0 && cur_oc * os * dst_dsz >= P4K**; 
   - What does max_os_block_aliasing mean？ (max_os_block_aliasing = nstl::min(div_up(1001, dst_dsz), max_os_block_aliasing);)

Read this code to find the importance of choosing ow_block, but don't understand the meaning of these parameters? Please help analyze it, thank you

**Comment by kwiersch** [comment]
Hi @llxingkongxia, you are not alone -- even the author may have trouble understanding 😆 . Still, I will try to help.

1. `max_os_block_thr`: this variable represents the maximum `os` block size per thread. If there is not enough threading along `mb` and `oc` dimensions, we want to thread along `os` as well. If `oc_block` is under this limit than there should be enough work per thread.

1. No, output does not require any special alignment (though typical performance considerations apply, for example in our benchmarking I believe we align buffers to 128-byte boundary by default).

1. The general idea here is to avoid aliasing between blocks of input and output. Aliasing can happen for strides that are a large power of 2, and reduce the size of an input or output block that can fit in cache. But the specific conditions here are unclear to me. I think `max_os_block_aliasing` should be the maximum block size that still avoids an aliasing issue.
