### ISSUE TITLE
Debug reorder can't go deeper

### ISSUE THREAD

**Issue by mahuichao** [oneapi-src/oneDNN#1671]
Hello guys, recently I was looking the source code of oneDNN, my enviroments is as blow:
**system: Mac M1 
tools:     VScode
compiler: clang13.0 arm64-apple-darwin**
I run the program in "**examples/cnn_inference_int8.cpp**" . I start debugging from "**src_reorder.execute()**", because I want to know how oneDNN implement reorder.I stuck in "**jit_generator.hpp:693**":
`   void operator()(kernel_args_t... args) const {
        using jit_kernel_func_t = void (*)(const kernel_args_t... args);
        auto *fptr = (jit_kernel_func_t)jit_ker_;
        (*fptr)(std::forward<kernel_args_t>(args)...);
    }`
it seems **fptr** is an address to some function.I can't step into,and I don't know what function it invoked, can anyone help me with this?   
thanks in advance.

**Comment by igorsafo** [comment]
Hi @mahuichao ,
The reason you don't see the code is it is generated at execution (JIT compilation) using XByak library. The result of JIT is a function implemented in assembly and located in memory. **fptr** points to the start of this function.
The sources for reorder implementation on ARM platform is located here: https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/aarch64/jit_uni_reorder.cpp.
Generated asm code can be dumped into file for inspection. Please refer to this page in the documentation: https://oneapi-src.github.io/oneDNN/dev_guide_inspecting_jit.html

**Comment by mahuichao** [comment]
@igorsafo  Thank you so much, it helps me a lot, I will look the source code and documentation.
