### ISSUE TITLE
What is the scale mask of weight in conv per-channel case?

### ISSUE THREAD

**Issue by zhenwei-intel** [oneapi-src/oneDNN#1678]
[Doc](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html). says only about zero point and 2 for per channel case:
```
The following masks are supported by the primitive:

0, which applies one zero point value to an entire tensor, and

2, which applies a zero point value per each element in a IC or OC dimension for DNNL_ARG_SRC or DNNL_ARG_DST arguments respectively.
```

**Comment by igorsafo** [comment]
Hi @zhenwei-intel ,

The mask specifies across what dimension there are multiple scales/zero points.

For weights which have logical dimensions order [OC, IC, KH, KW] if user wants to have a per-channel scale mask should be set to `1 << OC_dim_idx`   or   `1 << 0` or `1`. If weights have groups then their logical dimensions order is [G, OC, IC, KH, KW]
and the mask for per-channel scales should be `(1 << G_dim_idx) + (1 << OC_dim_idx)` or `(1 << 0) + (1 << 1)` or `3`.

For src and dst logical dimensions order is  [N, C, H, W], C is the 1-th dimension, so to specify per-channel scales user will need to set mask to `1 << 1` or `2`.

Please be aware of the following oneDNN limitations:
- Only Weights support per-channel scales
- Src and Dst support common scales
- Only Src and Dst support zero points
- Different primitives might have different support coverege of zero points and scales.

Regards,
Igor

**Comment by zhenwei-intel** [comment]
Thank a lot! @igorsafo
