### ISSUE TITLE
Can you provide a complete training example , such as training MNIST.

### ISSUE THREAD

**Issue by w1005444804** [oneapi-src/oneDNN#1683]
It's difficult to find a complete example，Provide a complete example of training MNIST to enable more people to use OneDNN， thanks

**Comment by vpirogov** [comment]
@w1005444804, a sample application illustrating MNIST training with SYCL and oneDNN is coming. I'll let you know once it's published.

Note though, that oneDNN is a performance library, not a full blown solution for deep learning training. Here're deep learning frameworks enabled with oneDNN that you can use for training:
* [PyTorch\*](https://pytorch.org). Intel GPU support and additional optimizations are available with [Intel Extension for PyTorch](https://github.com/intel/intel-extension-for-pytorch).
* [Tensorflow\*](https://www.tensorflow.org). Intel GPU support and additional optimizations are available with [Intel Extension for Tensorflow](https://github.com/intel/intel-extension-for-tensorflow).
* [PaddlePaddle\*](http://www.paddlepaddle.org)
* [Apache\* MXNet](https://mxnet.apache.org)

**Comment by w1005444804** [comment]
@vpirogov thanks
