### ISSUE TITLE
break change of some api include `post_ops_t::append_eltwise`

### ISSUE THREAD

**Issue by dc3671** [oneapi-src/oneDNN#1684]
# Summary

some apis like:
- `post_ops_t::append_eltwise(alg_kind_t alg, float alpha, float beta)` -> `post_ops_t::append_eltwise(float scale, alg_kind_t alg, float alpha, float beta)`
- `attr.set_scales_mask` -> removed
- `dnnl::matmul::primitive_desc(engine, src_md, wgt_md, dst_md, attr)` -> `dnnl::matmul::primitive_desc(engine, src_md, wgt_md, dst_md)`

# URLs

https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html

# Additional details
Provide detailed description of the expected changes in documentation
and suggestions you have.

**Comment by vpirogov** [comment]
oneDNN v3.0 is a major release incompatible with oneDNN v2.x releases. You can find the list of breaking changes for this release in [the release notes](https://github.com/oneapi-src/oneDNN/releases/tag/v3.0).

Documentation in [the default location](https://oneapi-src.github.io/oneDNN) tracks main development branch. Documentation for specific releases is available in versioned folders:
* oneDNN v2.7: https://oneapi-src.github.io/oneDNN/v2.7
* oneDNN v3.2: https://oneapi-src.github.io/oneDNN/v3.2

**Comment by vpirogov** [comment]
Feel free to reopen with further questions.
