### ISSUE TITLE
undefined TBB function when building examples

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDNN#1685]
I got many errors about undefined TBB functions when building oneDNN with the CUDA backend

``` 
/usr/bin/ld: /tmp/cnn_inference_f32-869fbb.o: in function `handle_example_errors(std::initializer_list<dnnl::engine::kind>, std::function<void ()>)':
cnn_inference_f32-9757f5.cpp:(.text._Z21handle_example_errorsSt16initializer_listIN4dnnl6engine4kindEESt8functionIFvvEE[_Z21handle_example_errorsSt16initializer_listIN4dnnl6engine4kindEESt8functionIFvvEE]+0x236): undefined reference to `tbb::detail::r1::get(tbb::detail::d1::task_scheduler_handle&)'
/usr/bin/ld: cnn_inference_f32-9757f5.cpp:(.text._Z21handle_example_errorsSt16initializer_listIN4dnnl6engine4kindEESt8functionIFvvEE[_Z21handle_example_errorsSt16initializer_listIN4dnnl6engine4kindEESt8functionIFvvEE]+0x24d): undefined reference to `tbb::detail::r1::finalize(tbb::detail::d1::task_scheduler_handle&, long)'
/usr/bin/ld: cnn_inference_f32-9757f5.cpp:(.text._Z21handle_example_errorsSt16initializer_listIN4dnnl6engine4kindEESt8functionIFvvEE[_Z21handle_example_errorsSt16initializer_listIN4dnnl6engine4kindEESt8functionIFvvEE]+0x261): undefined reference to `tbb::detail::r1::finalize(tbb::detail::d1::task_scheduler_handle&, long)'
/usr/bin/ld: ../src/libdnnl.so.3.2: undefined reference to `tbb::detail::r1::spawn(tbb::detail::d1::task&, tbb::detail::d1::task_group_context&)'
/usr/bin/ld: ../src/libdnnl.so.3.2: undefined reference to `tbb::detail::r1::allocate(tbb::detail::d1::small_object_pool*&, unsigned long)'
/usr/bin/ld: ../src/libdnnl.so.3.2: undefined reference to `tbb::detail::r1::deallocate(tbb::detail::d1::small_object_pool&, void*, unsigned long, tbb::detail::d1::execution_data const&)'
```

I installed TBB from source, and specify the TBB_ROOT in cmake.  The verbose mode does not seem to show that TBB is included for building the examples.

cd /path/oneDNN/build/examples && /auto/software/swtree/ubuntu22.04/x86_64/cmake/3.26.3/bin/cmake -E cmake_link_script CMakeFiles/cnn-inference-f32-cpp.dir/link.txt --verbose=1

clang++  -Wno-c++20-extensions -idirafter/path/cublas -idirafter/path/22.11/cuda/11.8/include -idirafter/path/cudnn/include -Wno-#pragma-messages -fsycl -fvisibility-inlines-hidden  -ffp-model=precise -fno-reciprocal-math -Wall -Wno-unknown-pragmas -fvisibility=internal -msse4.1  -fPIC -Wformat -Wformat-security -fstack-protector-all  -fsycl-targets=nvptx64-nvidia-cuda -Wno-linker-warnings   -Wno-pass-failed -Wno-tautological-compare -Wno-pass-failed -Wno-pass-failed -O3 -DNDEBUG -D_FORTIFY_SOURCE=2  -Wl,--as-needed -pie -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now "CMakeFiles/cnn-inference-f32-cpp.dir/cnn_inference_f32.cpp.o" -o cnn-inference-f32-cpp  -Wl,-rpath,/path/oneDNN/build/src ../src/libdnnl.so.3.2 -lOpenCL -lm -ldl

**Comment by densamoilov** [comment]
Can you please share the command you used to build oneDNN library?

**Comment by jinz2014** [comment]
May you add a full cmake command to allow users to build oneDNN with CUDA or other backend in a simple and clear way ?  

cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DDNNL_CPU_RUNTIME=SYCL -DDNNL_GPU_RUNTIME=SYCL -DDNNL_GPU_VENDOR=NVIDIA -DCMAKE_INSTALL_PREFIX=(…) -DCUBLAS_INCLUDE_DIR=/path/include/cublas -DCUBLAS_LIBRARY=/path/lib64/libcublas.so -DCUDNN_INCLUDE_DIR=/path/cudnn/include/ -DCUDNN_LIBRARY=/path/lib/libcudnn.so -DONEDNN_BUILD_GRAPH=OFF -DTBB_ROOT=/path/oneTBB-install/

**Comment by vpirogov** [comment]
@jinz2014, you can find information related to CUDA backend, including build commands, [here](https://github.com/oneapi-src/oneDNN/blob/master/src/gpu/nvidia/README.md).

**Comment by jinz2014** [comment]
Thank you for the link. Please update the build command if needed. Thanks.

**Comment by densamoilov** [comment]
TBB_ROOT is not the correct name. If your TBB package comes with a environment script then run it before you run CMake. If it doesn’t then set an environment variable TBBROOT yourself and then run CMake.
