### ISSUE TITLE
how can  I get riscv_vector.h?

### ISSUE THREAD

**Issue by TONG369** [oneapi-src/oneDNN#1692]
hello

I want to cross compile this code, set DNNL_TARGET_ARCH=RV64  DDNNL_RISCV_USE_RVV DNNL_ARCH_OPT_FLAGS=-march=rv64gcv. But I can't find riscv_vector.h this file?

I clone https://github.com/riscv-collab/riscv-gnu-toolchain  and install it。 But still can't find riscv_vector.h

how can I get?

I am looking forward your reply.

@aaronjohnson @indie @jmenon @WilliamTambellini @cota 

thks!

**Comment by igorsafo** [comment]
Hello @TONG369 ,

It seems gnu toolchain doesn't support vector extention or was built with it disabled.
Could you please make sure gnu toolchain was built with `rv64gcv` architecture?
Installation guide: https://github.com/riscv-collab/riscv-gnu-toolchain#installation-linux 
Also it would be easier to try to compile a small C program (without dependencies on oneDNN) with vector extensions to make sure the toolchain works correctly.

**Comment by TONG369** [comment]
> Hello @TONG369 ,
> 
> It seems gnu toolchain doesn't support vector extention or was built with it disabled. Could you please make sure gnu toolchain was built with `rv64gcv` architecture? Installation guide: https://github.com/riscv-collab/riscv-gnu-toolchain#installation-linux Also it would be easier to try to compile a small C program (without dependencies on oneDNN) with vector extensions to make sure the toolchain works correctly.

**Comment by TONG369** [comment]
@igorsafo 

Sorry, I still have some doubts.   

https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/rv64/rvv_nchw_pooling.cpp#L20

this file use  riscv_vector.h . I want to cross compile on target RV64.  how can I get  riscv_vector.h?

**Comment by igorsafo** [comment]
@TONG369 This header is a part of a compiler, it is not oneDNN code. Please check the following discussion: https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/O9tnaaFgKYc 
According to the discussion RVV support is not available on the `master` branch of https://github.com/riscv-collab/riscv-gnu-toolchain , so the repository should be switched to the branch `riscv-gcc-rvv-next`: https://github.com/riscv-collab/riscv-gcc/tree/riscv-gcc-rvv-next
This branch contains `riscv_vector.h`: https://github.com/riscv-collab/riscv-gcc/blob/riscv-gcc-rvv-next/gcc/config/riscv/riscv-vector.h

**Comment by TONG369** [comment]
thks, I will try it.  wait few days

@igorsafo

**Comment by TONG369** [comment]
@igorsafo 

the question is solved.  thanks very much

**Comment by TONG369** [comment]
@igorsafo 

sorry ,I have a new question. Following your method, can find riscv_vector.h . But , met some errors.

![image](https://github.com/oneapi-src/oneDNN/assets/29472117/c350abee-a816-477b-bc9d-80ca8d6a1610)
