### ISSUE TITLE
Installing oneDNN using binary dist for use with NVIDIA plugin

### ISSUE THREAD

**Issue by sanchit-grover-intel** [oneapi-src/oneDNN#1706]
Hi,

I am trying to use oneDNN with the NVIDIA plugin to use with NVIDIA GPUs. However, I am seeing an issue when I use the binary distribution of oneDNN vs when I build oneDNN from source.

- Spec:
SLES SP3 host
openSUSE Leap 15.4 container (used to run the app)
NVIDIA RTX A4000

- Software Stack for both setups:
oneAPI Base Toolkit 2023.2.0
dpcpp compiler installed via `intel-oneapi-compiler-dpcpp-cpp-2023.2.0`
CUDA SDK 12.0
oneDNN v3.1 (for building with source)
To initialise: `source /opt/intel/oneapi/setvars.sh --include-intel-llvm`

I am able to see the correct out of `sycl-ls`:
```
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2023.16.6.0.22_223734]
[opencl:cpu:1] Intel(R) OpenCL, Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz 3.0 [2023.16.6.0.22_223734]
[ext_oneapi_cuda:gpu:0] NVIDIA CUDA BACKEND, NVIDIA RTX A4000 8.8 [CUDA 12.0]
```

Command to build oneDNN from source:
```
cmake -B build \
        -DDNNL_LIBRARY_TYPE=SHARED \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=<path> \
        -DDNNL_CPU_RUNTIME=DPCPP \
        -DDNNL_GPU_RUNTIME=DPCPP \
        -DDNNL_BUILD_EXAMPLES=OFF \
        -DDNNL_BUILD_TESTS=OFF \
        -DCMAKE_C_COMPILER=icx \
        -DCMAKE_CXX_COMPILER=icpx \
        -DOpenCL_LIBRARY=<path> \
        -DDNNL_SYCL_CUDA=ON \
        -DONEDNN_BUILD_GRAPH=OFF \
        -DDNNL_GPU_VENDOR=NVIDIA \
        -DCUDA_DRIVER_LIBRARY=<path> \
        -DCUBLAS_INCLUDE_DIR=<path> \
        -DCUBLAS_LIBRARY=<path> \
        -DCUDNN_INCLUDE_DIR=<path> \
        -DCUDNN_LIBRARY=<path> && \
cd build && \
         make -j `nproc` && \
         make install
```

Installing oneDNN using binary dist:
```
zypper install intel-oneapi-dnnl-devel=2023.2.0-49516
```

This is the simple app I am running:
```
int main()
{
    device dev = device (gpu_selector_v);
    context ctx(dev);
    eng = std::make_shared<dnnl::engine>(sycl_interop::make_engine(dev, ctx));
    std::cout << "Done" << std::endl;
}
```
To build: `icpx -fsycl -O3  -Wno-undefined-var-template -I/opt/intel/oneapi/dnnl/latest/cpu_dpcpp_gpu_dpcpp/include -I/opt/intel/oneapi/compiler/latest/linux/include/sycl -ldnnl -Xsycl-target-backend --cuda-gpu-arch=sm_86 app.cpp -o app`
Run: `SYCL_PI_TRACE=1 DNNL_VERBOSE=1 ./app`

When I run in the setup where oneDNN is built from source, I see no errors:
```
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_opencl.so [ PluginVersion: 12.27.1 ]
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_cuda.so [ PluginVersion: 12.27.1 ]
SYCL_PI_TRACE[all]: Requested device_type: info::device_type::gpu
SYCL_PI_TRACE[all]: Requested device_type: info::device_type::gpu
SYCL_PI_TRACE[all]: Selected device: -> final score = 2000
SYCL_PI_TRACE[all]:   platform: NVIDIA CUDA BACKEND
SYCL_PI_TRACE[all]:   device: NVIDIA RTX A4000
Done
```
However, in the setup where I have just installed the binaries, I get this error:
```
SYCL_PI_TRACE[basic]: Plugin found and successfully loaded: libpi_cuda.so [ PluginVersion: 12.27.1 ]
SYCL_PI_TRACE[all]: Requested device_type: info::device_type::gpu
SYCL_PI_TRACE[all]: Selected device: -> final score = 1000
SYCL_PI_TRACE[all]:   platform: NVIDIA CUDA BACKEND
SYCL_PI_TRACE[all]:   device: NVIDIA RTX A4000
terminate called after throwing an instance of 'dnnl::error'
  what():  could not create an engine
Aborted (core dumped)
```

Is there a missing configuration that is required for the building the code or installing the `dnnl` package? Perhaps an option I am missing to `setvars.sh`? Or is this the expected behaviour? Thank you.

**Comment by vpirogov** [comment]
Intel oneDNN binary distribution supports Intel GPUs only. The only option to get NVIDIA support now is building oneDNN from source just as you deed.

+@mehdi-goli

**Comment by sanchit-grover-intel** [comment]
Hi @vpirogov, thank you for the clarification!
