### ISSUE TITLE
Compatibility with Apple Silicon GPUs

### ISSUE THREAD

**Issue by Yusepp** [oneapi-src/oneDNN#1711]
I've seen that oneDNN is compatible with different GPUs and also macos which made me think about the possibility of accelerating M1/M2 GPUs using oneDNN/oneAPI (I.E in pytorch).

Is it possible to use M2 GPU with oneAPI backend in pytorch?

**Comment by johnnynunez** [comment]
> @Yusepp, currently there's no backend in oneDNN capable to run on Apple M2 GPUs.

And in M1? How to install it?

**Comment by vpirogov** [comment]
oneDNN does not support any Apple GPUs.
