### ISSUE TITLE
"could not create a primitive descriptor for an eltwise forward propagation primitive" error

### ISSUE THREAD

**Issue by lucasalavapena** [oneapi-src/oneDNN#1715]
Thanks for adding the graph examples recently. I was trying to do my own even simpler example, however I am running into an error: 

```
root@6ed408b42351:/experiments/oneDNN-exp/simple_relu# ./simple_relu
Patitions count : 1
terminate called after throwing an instance of 'dnnl::error'
  what():  could not create a primitive descriptor for an eltwise forward propagation primitive
Aborted (core dumped)
```

Here is the source:

```c++

#include <iostream>
#include "oneapi/dnnl/dnnl_graph.hpp"

using namespace dnnl::graph;
using data_type = logical_tensor::data_type;
using layout_type = logical_tensor::layout_type;
using dim = logical_tensor::dim;
using dims = logical_tensor::dims;

int main(void) {
    dnnl::engine eng {dnnl::engine::kind::cpu, 0};
    dnnl::stream strm {eng};
    graph g(dnnl::engine::kind::cpu);

    logical_tensor input_lt {0, data_type::f32, layout_type::any};
    logical_tensor output_lt {1, data_type::f32, layout_type::any};
    op relu1(0, op::kind::ReLU, {input_lt}, {output_lt}, "relu1");

    g.add_op(relu1);
    g.finalize();

    auto partitions = g.get_partitions();

    std::cout
            << "Patitions count : " << partitions.size()
            << std::endl;
    const auto part = partitions[0];
    if (!part.is_supported()) {
        std::cout
                << "cpu_get_started: Got unsupported partition, users need "
                    "handle the operators by themselves."
                << std::endl;
    }
    // adding the dim, similar to in the cpu_getting_started.cpp, I also tried to create one set of logical tensors and use them in both places but I had the same error.

    dim major_axis = 5;
    dims in_dim {major_axis};
    dims out_dim {major_axis};

    auto input = logical_tensor {0, data_type::f32,
                    in_dim, layout_type::any}; 
    auto output = logical_tensor {1, data_type::f32,
                    out_dim, layout_type::any};

    std::vector<logical_tensor> inputs_c = {input};
    std::vector<logical_tensor> outputs_c = {output};
    compiled_partition cp = part.compile(inputs_c, outputs_c, eng);

}

```

I have spent a significant time trying to figure out the source of the error, but it is not clear to me at least. I also had the same error modifying cpu_getting_started.cpp to just include the relu op.

It is most likely me misunderstanding of how to use the library... Could it be related to the memory layouts being too unrestricted? Perhaps there is a possibility to add a useful error message somewhere if what I am doing is not too wrong.

I compiled it with `root@6ed408b42351:/experiments/oneDNN-exp/simple_relu# icpx -I/oneDNN/build/include/ -o simple_relu simple_graph_relu.cpp -L/oneDNN/build/src -ldnnl -lgomp`

**Comment by TaoLv** [comment]
Hi @lucasalavapena , thank you for the question! 

Yes, the failure here is caused by the memory layout used for partition compile. In particular, the layout used to create the input logical tensor:

```cpp
    auto input = logical_tensor {0, data_type::f32,
                    in_dim, layout_type::any}; 
```

`any` layout typically means the layout is unknown and the library may decide it. Layout is not critical for building graph. But if it's used as an input logical tensor for partition compilation, the library will not know how to generate the kernel code for the partition. For this example, changing input logical tensor from any to strided can address the issue. The output logical tensor can still be any layout.

```cpp
    auto input = logical_tensor {0, data_type::f32,
                    in_dim, layout_type::strided}; 
```

> Perhaps there is a possibility to add a useful error message somewhere if what I am doing is not too wrong.

Thanks for the suggestion. We are improving the library verbose mode for graph API to provide more diagnostic information to users.

**Comment by lucasalavapena** [comment]
Thanks for the help @TaoLv, that worked. I think another (silly) mistake I initially made but only later realised was that I was supposed to use the same logical tensors IDs. I think I was doing that wrongly initially because I did have a strided layout at that at the start point.

 The [docs](
https://oneapi-src.github.io/oneDNN/group_dnnl_graph_api_logical_tensor.html#detailed-documentation) has all the answers I was looking for, but I must have skipped it (you could argue it is a bit hidden) before because I checked only [this](https://oneapi-src.github.io/oneDNN/dev_guide_graph_basic_concepts.html#logical-tensor) and the linked provided there which goes one level deeper. Does it make sense to either to move some of the detailed docs to the graph extension section of the docs or at least have a sort of copy? I think these three lines (reworded) would be good to have in the graph extension section: "But shape information of input logical tensor will be required at partition compilation stage. Logical tensor is not mutable. Users must create a new logical tensor with the same ID to pass any new additional information to oneDNN Graph API." I think explicitly mentioned that it cannot be any would be good.

**Comment by TaoLv** [comment]
The document has been updated as suggested: https://github.com/oneapi-src/oneDNN/commit/0ac885adb4f4801a4ecbf924162492d79b44ab22 .

**Comment by lucasalavapena** [comment]
> The document has been updated as suggested: [0ac885a](https://github.com/oneapi-src/oneDNN/commit/0ac885adb4f4801a4ecbf924162492d79b44ab22) .

Great!
