### ISSUE TITLE
Problem with creating descriptor for pooling primitive

### ISSUE THREAD

**Issue by ItayLasch** [oneapi-src/oneDNN#1721]
# Summary
I am trying to produce a pooling primitive descriptor, forward_inference. each time I get the error "could not create a descriptor for a pooling forward propagation primitive"

# Environment
CPU 

A snippet of the code:
```
memory::dims src_dims = {1, 64, 1, 64};
memory::dims dst_dims = {1, 64, 1, 1};
memory::dims stride_dims = {1, 1};
memory::dims kernel_dims = { 64, 1};
memory::dims padding_dims_l = { 0, 0};
memory::dims padding_dims_r = { 0, 0};

// create tensors memory descriptors
dt src_dt = dnnl::memory::data_type::u8

//set src to nhwc - we require it in the configure
memory::desc src_md = memory::desc({src_dims}, src_dt, tag::nhwc);
memory::desc dst_md = memory::desc({dst_dims}, src_dt, tag::any);

// Create operation descriptor.
auto pooling_desc = pooling_forward::desc(
        prop_kind::forward_inference,
        algorithm::pooling_max,
        src_md,
        dst_md,
        stride_dims,
        kernel_dims,
        padding_dims_l,
        padding_dims_r);
```
* I replaced some of the variables with constants to show the case that cause this issue.

Is there a reason for this kind of behavior that I'm missing?

thank you in advance

**Comment by dzarukin** [comment]
Hi @ItayLasch, with oneDNN v3.2 and above the user may specify ONEDNN_VERBOSE=all and the error would be described with an exact place in the source code the error was triggered.

From the code it looks like the kernel dims are incorrect - `iw` was specified as `64` but `kh` was set to `64` instead of `kw`. Those must be aligned.

**Comment by ItayLasch** [comment]
> Hi @ItayLasch, with oneDNN v3.2 and above the user may specify ONEDNN_VERBOSE=all and the error would be described with an exact place in the source code the error was triggered.

Hi, I did that but except for the error I provided, I didn't receive any other information.

> From the code it looks like the kernel dims are incorrect - `iw` was specified as `64` but `kh` was set to `64` instead of `kw`. Those must be aligned.

also, I switched the dimensions as you suggested and the problem still reoccurs.

**Comment by dzarukin** [comment]
Based on the code you attach, it seems you are on v2.7 or below. No wonder there's no reports from oneDNN verbose as it's not enabled there.

Tried the code on my side. After switching from `memory::dims kernel_dims = { 64, 1};` to `memory::dims kernel_dims = {1, 64 };` the case started working for me. Same happens if changing `memory::dims src_dims = {1, 64, 1, 64};` to `memory::dims src_dims = {1, 64, 64, 1};` in the original code.

Other than that I don't see what else may go wrong.

**Comment by ItayLasch** [comment]
I'm trying to debug the code and in the following function I've highlighted the line I think fails my code:

`template <typename pooling_desc_type>
status_t pooling_desc_init(pooling_desc_type *pool_desc, prop_kind_t prop_kind,
        alg_kind_t alg_kind, const memory_desc_t *src_desc,
        const memory_desc_t *dst_desc, const dims_t strides,
        const dims_t kernel, const dims_t dilation, const dims_t padding_l,
        const dims_t padding_r) {
    bool args_ok = !any_null(pool_desc, src_desc, dst_desc, strides, kernel,
                           padding_l)
            && one_of(alg_kind, pooling_max, pooling_avg_include_padding,
                    pooling_avg_exclude_padding)
            && IMPLICATION(
                    one_of(prop_kind, forward_training, forward_inference),
                    !memory_desc_wrapper(src_desc).format_any());
    if (!args_ok) return invalid_arguments;

    if (padding_r == nullptr) padding_r = padding_l;

    auto pd = pooling_desc_type();
    pd.primitive_kind = std::is_same<pooling_desc_type, pooling_desc_t>::value
            ? primitive_kind::pooling
            : primitive_kind::pooling_v2;
    pd.prop_kind = prop_kind;
    pd.alg_kind = alg_kind;
    pd.src_desc.ndims = src_desc->ndims;

    const bool is_fwd = one_of(prop_kind, forward_training, forward_inference);

    bool runtime_dims_or_strides
            = memory_desc_wrapper(src_desc).has_runtime_dims_or_strides()
            || memory_desc_wrapper(dst_desc).has_runtime_dims_or_strides();
    if (runtime_dims_or_strides) return unimplemented;

    pd.diff_src_desc = pd.src_desc = zero_md();
    pd.diff_dst_desc = pd.dst_desc = zero_md();

    (is_fwd ? pd.src_desc : pd.diff_src_desc) = *src_desc;
    (is_fwd ? pd.dst_desc : pd.diff_dst_desc) = *dst_desc;

    int sp_dims = src_desc->ndims - 2;
    utils::array_copy(pd.strides, strides, sp_dims);
    utils::array_copy(pd.kernel, kernel, sp_dims);
    utils::array_copy(pd.padding[0], padding_l, sp_dims);
    utils::array_copy(pd.padding[1], padding_r, sp_dims);
    copy_dilation(pd, dilation, sp_dims);

    if (one_of(alg_kind, pooling_max, pooling_avg_include_padding,
                pooling_avg_exclude_padding)) {
        pd.accum_data_type = types::default_accum_data_type(
                src_desc->data_type, dst_desc->data_type);
        if (pd.accum_data_type == data_type::undef) return invalid_arguments;
    } else {
        pd.accum_data_type = dst_desc->data_type;
    }

    if (!utils::one_of(src_desc->ndims, 3, 4, 5)
            || !utils::one_of(dst_desc->ndims, 3, 4, 5)
            || src_desc->dims[0] != dst_desc->dims[0]
            || src_desc->dims[1] != dst_desc->dims[1])
        return invalid_arguments;

    for (int i = 2; i < src_desc->ndims; ++i) {
        const int src = src_desc->dims[i];
        const int dst = dst_desc->dims[i];
        const int ker = kernel[i - 2];
        const int dil = dilation ? dilation[i - 2] : 0;
        const int pad_l = padding_l[i - 2];
        const int pad_r = padding_r[i - 2];
        const int str = strides[i - 2];
        const int ker_range = 1 + (ker - 1) * (dil + 1);

        if (str < 1 || dil < 0 || pad_l < 0 || pad_r + str < 0)
            return invalid_arguments;

        **if ((src - ker_range + pad_l + pad_r) / str + 1 != dst)
            return invalid_arguments;**

        // It's not allowed for pooling window to be totally placed outside
        // of real source domain for pooling_avg_exclude_padding algorithm
        // due to 0 / 0 ambiguity
        if (alg_kind == pooling_avg_exclude_padding
                && !(pad_l < ker_range && pad_r < ker_range && dil < src))
            return invalid_arguments;
    }

    *pool_desc = pd;
    return success;
}`

for i=3 we would get that (src - ker_range + pad_l + pad_r) / str + 1 = (64-64+0+0)/1 + 1 = 1 != 64 = dst

maybe I'm missing something (and I hope I do) because it doesn't make sense to me.

**Comment by dzarukin** [comment]
Do you have any idea why `dst` is `64`? On the code above it supposed to be `1`.
