### ISSUE TITLE
[nvidia] pooling primitive fails correctness check 

### ISSUE THREAD

**Issue by dzarukin** [oneapi-src/oneDNN#1727]
# Summary
oneDNN validation for Nvidia backend hits a correctness issue on backward pooling when input dimension and kernel size are identical (thus, output dimension becomes 1) under benchdnn.

# Version
Latest master.

# Environment
## Hardware:
NVIDIA A100 80GB PCIe
(A10 should also work for most cases).

## Software
SYCL Compiler with Nvidia support.
    Any version that compiles without issues, preferable no later than April.
[Optional] TBB
    Any version.
[Optional] OpenCL CPU
    Latest version is preferable.
* Optional means that CPU backend can be enabled if dependency is satisfied. Otherwise, should be switched off.

# Steps to reproduce
## Build
mkdir -p build
cd build
cmake .. -DCMAKE_BUILD_TYPE=release (or debug) -DDNNL_CPU_RUNTIME=DPCPP (or NONE) -DDNNL_GPU_RUNTIME=DPCPP -DDNNL_GPU_VENDOR=NVIDIA -DONEDNN_BUILD_GRAPH=OFF
cmake --build . --target benchdnn

## Run
Important to use both tags in a single line since primitive cache plays a role here.

<env_vars> ./build/tests/benchdnn/benchdnn --pool --engine=gpu --dir=BWD_D --tag=abx,axb mb4ic32ih32oh1kh32sh32ph0

For a full suite validation, use `--batch=test_pool_gpu` instead of a specific test case.

## Helper env vars:
CUDA_LOGINFO_DBG=1 CUDA_LOGDEST_DBG=stdout -- enables cuda API dump
CUDNN_LOGINFO_DBG=1 CUDNN_LOGDEST_DBG=stdout -- enables cudnn API dump
DNNL_VERBOSE=all (or desired level) -- enables oneDNN execution information

## Helper tips:
benchdnn supports verbosity through -vX. Most info is available at v6. It's possible to dump destination with -v99 when really needed.
benchdnn documentation is here: https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn (scroll down). Reorder doc and others may be found through links.
benchdnn binary also supports `--help` command, which will tip to use `--bnorm --help` to dump all supported options.

# Observed behavior
Failures are reproducible within a single run, there are total of 15 failures of similar nature.

```
create: --pool --engine=gpu --dir=BWD_D mb4ic32ih32oh1kh32sh32ph0
run: --pool --engine=gpu --dir=BWD_D mb4ic32ih32oh1kh32sh32ph0
0:PASSED __REPRO: --pool --engine=gpu --dir=BWD_D mb4ic32ih32oh1kh32sh32ph0
create: --pool --engine=gpu --dir=BWD_D --tag=axb mb4ic32ih32oh1kh32sh32ph0
run: --pool --engine=gpu --dir=BWD_D --tag=axb mb4ic32ih32oh1kh32sh32ph0
[ 318][SRC][0:0:9:30] exp_f32:           0 exp:           0 got:         973 diff:     973 rdiff:     973
[ 736][SRC][0:0:23:0] exp_f32:         973 exp:         973 got:           0 diff:     973 rdiff:       1
[1491][SRC][0:1:14:19] exp_f32:           0 exp:           0 got:          85 diff:      85 rdiff:      85
[1934][SRC][0:1:28:14] exp_f32:          85 exp:          85 got:           0 diff:      85 rdiff:       1
[2304][SRC][0:2:8:0] exp_f32:        -941 exp:        -941 got:           0 diff:     941 rdiff:       1
[2979][SRC][0:2:29:3] exp_f32:           0 exp:           0 got:        -941 diff:     941 rdiff:     941
[3463][SRC][0:3:12:7] exp_f32:           0 exp:           0 got:         668 diff:     668 rdiff:     668
[3547][SRC][0:3:14:27] exp_f32:         668 exp:         668 got:           0 diff:     668 rdiff:       1
[4484][SRC][0:4:12:4] exp_f32:       -1923 exp:       -1923 got:           0 diff:    1923 rdiff:       1
1:FAILED (errors:256 total:131072) __REPRO: --pool --engine=gpu --dir=BWD_D --tag=axb mb4ic32ih32oh1kh32sh32ph0
```

The issue affects max pooling on backward for shapes with 1 in destination (e.g. when dimension and kernel sizes coincide: ih32kh32oh1). Then, cache gets into play. Since abx and axb formats are identical for such shapes, cache picks up backward primitive descriptor for abx format. It picks up a workspace used for abx (or re-computes with abx strides, I didn't check properly), and applies it to axb. Considering that both formats are same except strides (which, though, shouldn't affect anything), abx workspace doesn't work for axb. This is the source of results mismatch though values computed correctly.

# Expected behavior
The issue is not appearing during the single run validation nor under full batch.

**Comment by kala855** [comment]
As discussed in https://github.com/oneapi-src/oneDNN/pull/1730#discussion_r1364744010 @dzarukin offered to create a PR fixing the 2 issues he found. Is there any further work on this ticket or can we close it?

**Comment by dzarukin** [comment]
@kala855, I'll close the ticket once the solution gets into the repository. Thank you.
