### ISSUE TITLE
gemm_api and Reorder in HuggingFace OPT model

### ISSUE THREAD

**Issue by SriAlavandar** [oneapi-src/oneDNN#1729]
I am running Hugging Face OPT-350M model With Intel TensorFlow 2.12.

**_Reorder:_**

I am observing logs as follows:

> onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,36864x1024:1024x1024,35.502
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:**abcd**:f0 dst_f32::blocked:**acbd**:f0,,,96x384x16x64,1.83911

> onednn_verbose,exec,cpu,matmul,brg:avx512_core,undef,src_f32::blocked:abc:f0 wei_f32::blocked:acb:f0 dst_f32::blocked:abc:f0,attr-scratchpad:user ,,1536x384x64:1536x64x384:1536x384x384,10.8359

After every MatMul we are observing a reorder from src:**abcd** to dst:**acbd**

Is the reorder done on Input Matrix or Weight Matrix?. Can u let me know what is the importance of this reorder here to tag **acbd** ?

**_gemm_api vs gemm::jit/brg::avx512:_**

When I am running on Hardware which has AVX512 support
1. For Intel Bert we are observing Algo control goes to either **gemm::jit or brg::avx512_core**. ([Ref](https://github.com/IntelAI/models/tree/master/benchmarks/language_modeling/tensorflow/bert_large/inference))

> onednn_verbose,exec,cpu,inner_product,x64:gemm:jit,forward_training,src_f32::blocked:ab:f0 wei_f32::blocked:ba:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,attr-scratchpad:user ,,mb36864ic768oc768,22.5781
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:acbd:f0,,,96x384x12x64,1.83813

> onednn_verbose,exec,cpu,matmul,brg:avx512_core,undef,src_f32::blocked:abcd:f0 wei_f32::blocked:abdc:f0 dst_f32::blocked:abcd:f0,attr-scratchpad:user attr-post-ops:binary_mul:f32:0+binary_add:f32:13:abcd ,,96x12x384x64:96x12x64x384:96x12x384x384,8.51904

2. For Hugging Face OPT Model we are observing  ALGO control goes to **gemm_api**. ([Ref](https://huggingface.co/facebook/opt-350m))
> onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,36864x1024:1024x1024,35.502
onednn_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:**abcd**:f0 dst_f32::blocked:**acbd**:f0,,,96x384x16x64,1.83911

> onednn_verbose,exec,cpu,matmul,brg:avx512_core,undef,src_f32::blocked:abc:f0 wei_f32::blocked:acb:f0 dst_f32::blocked:abc:f0,attr-scratchpad:user ,,1536x384x64:1536x64x384:1536x384x384,10.8359

Why is it invoking gemm_api when it has support for brg::AVX512 ?

**Comment by vpirogov** [comment]
@SriAlavandar, verbose logs specifies a function called by the application as the fourth parameter. In your case Tensorflow calls 3 different functions: [inner product](https://oneapi-src.github.io/oneDNN/group_dnnl_api_inner_product.html#doxid-group-dnnl-api-inner-product), [matmul](https://oneapi-src.github.io/oneDNN/group_dnnl_api_matmul.html#doxid-group-dnnl-api-matmul), and [dnnl_gemm](https://oneapi-src.github.io/oneDNN/group_dnnl_api_blas.html). The fifth parameter indicates underlying implementation name (like brg_avx512_core).

Adding @agramesh1 to cover Tensorflow implementation decisions.

**Comment by vpirogov** [comment]
+@orelyehuda

**Comment by SriAlavandar** [comment]
Hi @yehudaorel, @agramesh1 Did you get any chance to have a look into the above issue. what is the importance of reorder to tag::abcd to tag::acbd? is reorder done on Matrix B?

**Comment by yehudaorel** [comment]
Hi @SriAlavandar, I believe your assumption here is correct, the reorder is taken place before matmul operation to reorder weight matrix to optimal memory format dictated by tensorflow implementation. In this case, the verbose output shows reorder from NCHW (channels first) to NHWC (channels last).

**Comment by SriAlavandar** [comment]
Thanks @yehudaorel. I noticed only for few MatMul's reorder on weight matrix is being triggered. 
![image](https://github.com/oneapi-src/oneDNN/assets/40352419/c2b8db00-3ce6-4845-b762-c9c932008ad9)
Can you please let me know on what basis are we deciding here whether reorder needs to be triggered or not?

**Comment by yehudaorel** [comment]
Hi @SriAlavandar, there are many reasons for a reorder primitive to be executed, one of them being matrix transposition which seems to be the case here. Without full context to the model implementation I don't have a definitive answer but I would recommend to run tensorboard profiler and verify tensorflow-onednn operation mapping. 

e.g
![image](https://github.com/oneapi-src/oneDNN/assets/111955825/99333a24-d4aa-4af8-b65e-2cecc02f1b24)
