### ISSUE TITLE
oneDNN does not build with Intel oneMKL as BLAS Vendor

### ISSUE THREAD

**Issue by vraghavulu** [oneapi-src/oneDNN#1733]
# Summary
When Intel oneMKL is used as BLAS vendor, then cmake fails.
When OpenBLAS is used as BLAS vendor, cmake succeeds.

I want to use oneMKL as BLAS lib.
This is being used by AnTuTu which is a Benchmark tool and used by our customer for KPI measurement. The KPI has to report the Single GEMM and MultiGEMM capabilities and hence we need to use Intel MKL as it is optimised for Intel platforms.

# Version
oneDNN V: master
githash: ee9674af13990f3e6bd6bc3201d6b91b2b960fa1

# Environment
* CPU make : Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (Skylake SOC)
* OS version (Linux vraghavu-ubuntu-dt 6.0.12-76060012-generic #202212290932~1674066459~20.04~3cd2bf3-Ubuntu SMP PREEMPT_DYNAMI x86_64 x86_64 x86_64 GNU/Linux)
* Compiler version (`gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0`)
* CMake version (3.16.3)
* CMake output log
* git hash (`git log -1 --format=%H`)

# Steps to reproduce
I am facing build issues when using Intel MKL with oneDNN. The following are the steps

1. git clone https://github.com/oneapi-src/oneDNN
2. mkdir build && cd build
3. cmake .. -DDNNL_BLAS_VENDOR=MKL -DBLAS_LIBRARIES=/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so
I get error and cmake stops. Logs have been attached.
-----------
.
.
.
-- DNNL_LIBRARY_NAME: dnnl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found BLAS: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so  
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - not found
CMake Error at cmake/blas.cmake:86 (message):
  BLAS library does not support CBLAS interface.
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)

-- Configuring incomplete, errors occurred!
See also "/media/venkat/local_disk/for_antutu/onemlk_src/oneDNN/build/CMakeFiles/CMakeOutput.log".
See also "/media/venkat/local_disk/for_antutu/onemlk_src/oneDNN/build/CMakeFiles/CMakeError.log".
---------------
4. When I use the below command (after deleting the build dir), there is no issues:
cmake .. -DDNNL_BLAS_VENDOR=OPENBLAS -DBLAS_LIBRARIES=/usr/lib/x86_64-linux-gnu/libblas.so

cmake completes

# Observed behavior
Error in running CMAKE when using oneMKL as BLAS Vendor

# Expected behavior
Complete Cmake.
[CMakeOutput.log](https://github.com/oneapi-src/oneDNN/files/12799592/CMakeOutput.log)
[CMakeError.log](https://github.com/oneapi-src/oneDNN/files/12799594/CMakeError.log)

**Comment by densamoilov** [comment]
Hi @vraghavulu, you should use `/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_rt.so` instead of `/opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_core.so` because `libmkl_core.so` is as you can tell by the name is a core library and doesn't have public interfaces.

**Comment by vraghavulu** [comment]
Hi @densamoilov Thanks! This worked - built and executed.
If DNNL_BLAS_VENDOR=NONE, then how does the GEMM operations take place. What is the optimisation when it is NONE.

Also in the page https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html along side description of "ONEDNN_BLAS_VENDOR" there can be a note regarding this option -DBLAS_LIBRARIES. It took lot of time to discover this variable and provide the correct item.

**Comment by densamoilov** [comment]
@vraghavulu, to be precise, the only officially supported BLAS vendor is ARMPL and now, probably, Apple Accelerate BLAS. Other BLAS libraries may or may not work but we try not to break it.

**Comment by densamoilov** [comment]
> What is the optimisation when it is NONE.

oneDNN has its own highly optimized kernels for GEMM functionality that are expected to be on par or faster than the kernels in oneMKL. The vast majority of our customers use oneDNN without oneMKL.

**Comment by vraghavulu** [comment]
Thanks you for the response! Closing the issue.
