### ISSUE TITLE
Meet a erro in building process about dnnl

### ISSUE THREAD

**Issue by unswimmingduck** [oneapi-src/oneDNN#1742]
The report of erro is below:

   CMake Error in src/CMakeLists.txt:
         Exporting the target "dnnl" is not allowed since its linker language cannot be determined

I really donot why this report occur, hope someone could help me to sovle it

**Comment by igorsafo** [comment]
Hi @unswimmingduck , could you please share the line used to build oneDNN?

**Comment by vpirogov** [comment]
Closing as there's no way to reproduce the issue. Feel free to reopen with requested information.
