### ISSUE TITLE
benchdnn matmul failing tests on aarch64

### ISSUE THREAD

**Issue by renato-arantes** [oneapi-src/oneDNN#1744]
# Summary
Benchdnn matmul tests are failing in inputs/matmul/test_matmul_all

# Version
The error is introduced by commit 578fb8b9b722a69f00a2f9005c263d3f3f706949

# Steps to reproduce
./benchdnn --matmul --batch=inputs/matmul/test_matmul_all

The cause is line '--batch=shapes_3d' being added to the file 'tests/benchdnn/inputs/matmul/test_matmul_all' at line 20.

# Observed behavior
Error: Fuction 'init_md' at (/home/renara01/tmp/oneDNN/tests/benchdnn/dnnl_memory.cpp:439) returned 'invalid_arguments'

**Comment by vpirogov** [comment]
Fixed by 7664e4184e520d26e82c60732d46ff3237cd15fa
