### ISSUE TITLE
Wrongly handling of inf when the post-op operation is mul.

### ISSUE THREAD

**Issue by renato-arantes** [oneapi-src/oneDNN#1747]
# Summary
This error occurs when oneDNN is compiled with ACL, although the ACL is not reached and the reference is called. It can also be reproduced on standalone oneDNN as described below.

# Version
The error is introduced by the commit 302102639c4931af062eac80eb90cfbe1a4e8ae9. 

# Steps to reproduce

To reproduce the error in standalone oneDNN it is needed to change to `true` this line [here](https://github.com/oneapi-src/oneDNN/blob/692b655f14eff430c16e1e287c214aedb513aa98/src/cpu/platform.cpp#L130C14-L130C14). I believe that this line returning `false` is an error as oneDNN can correctly handle data type F16. Otherwise, oneDNN can be compiled with any ACL version, as the version is irrelevant to reproduce the issue once ACL is not reached for this operation.

Commands to reproduce the issue:

`ctest -R test_benchdnn_softmax_ci_cpu`

or

`benchdnn --softmax --dir=FWD_I --sdt=s8 --ddt=f16 --stag=axb --alg=LOGSOFTMAX --attr-scales=src:common:64 --attr-post-ops=mul:f32:per_tensor 1x16x2x12_n"softmax_ci_2d:1"`

The error is caused by adding the test `mul:f32:per_tensor` at line 25 in file `tests/benchdnn/inputs/softmax/test_softmax_ci`.

# Observed behavior

The test fails as oneDNN post-op operations are not properly handling inf values.

`[DST][L1] exp:     inf got:     inf diff:    -nan rel_diff:    -nan`

**Comment by vpirogov** [comment]
Thank you for the report, @renato-arantes. We are working on the fix for this one.

**Comment by vpirogov** [comment]
Fixed by e8759ad76227849b4f01923a69b3221c74f5e432.
