### ISSUE TITLE
Matmul - tensor size effect on performance

### ISSUE THREAD

**Issue by ItayLasch** [oneapi-src/oneDNN#1748]
I'm testing out different input tensor's sizes in order to see their effect on the primitive creation performance.

Is there any thumb rule to decide whether or not it is preferable to use this primitive regarding the tensor's sizes?
I noticed that the output's dimension perhaps affects the performance more than the input's sizes.

For example If I run with tensor 1: [8,36,8] and tensor 2: [8,8,1] this is the average output:
`
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,create:cache_miss,cpu,matmul,brg:avx512_core_vnni,undef,src_s8::blocked:abc:f0 wei_s8::blocked:abc:f0 dst_s32::blocked:abc:f0,attr-scratchpad:user ,,8x1x8:8x8x1:8x1x1,3.84595
`
![image](https://github.com/oneapi-src/oneDNN/assets/81741607/56be168a-fc91-452a-8924-d553df6014b5)

and when I run with tensor 1: [8,1,8] and tensor 2: [8,8,1] this is the average output:
`
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,create:cache_miss,cpu,matmul,brg:avx512_core_vnni,undef,src_s8::blocked:abc:f0 wei_s8::blocked:abc:f0 dst_s32::blocked:abc:f0,attr-scratchpad:user ,,8x36x8:8x8x1:8x36x1,0.366943
`
![image](https://github.com/oneapi-src/oneDNN/assets/81741607/e1a33bf7-d747-4d3c-aedf-78660e5db795)

both cases were run multiple times under the same conditions where the only difference is the tensor's sizes.
If there is anything I should consider as a size boundary when using this primitive it would be helpful.

Thanks in advance.

**Comment by vpirogov** [comment]
@ItayLasch, oneDNN programming model assumes that primitives are created once and reused during the model execution (either explicitly of via [oneDNN primitive cache](https://oneapi-src.github.io/oneDNN/dev_guide_primitive_cache.html)), so we do not provide any guarantees around creation time. If you need the creation time to be zero there are two options:
* Using matmul with runtime dimensions. See example [here](https://github.com/oneapi-src/oneDNN/blob/master/examples/tutorials/matmul/cpu_sgemm_and_matmul.cpp#L120)
* Using [`dnnl_?gemm` API](https://oneapi-src.github.io/oneDNN/group_dnnl_api_blas.html)

While the creation time will be zero for these cases, the execution time will suffer in comparison to fully specialized matmul primitive.

Hope this helps!

**Comment by ItayLasch** [comment]
I don't want creation time to be zero. I wanted to know if there are certain cases with the inputs dimensions where the performance is worse the usual or better. The only variable I'm trying to look at right now is the dimension sizes of the inputs and output.

**Comment by mgouicem** [comment]
Adding @msotoflo @ankalinin 

> Is there any thumb rule to decide whether or not it is preferable to use this primitive regarding the tensor's sizes?
> I noticed that the output's dimension perhaps affects the performance more than the input's sizes.

It is really implementation dependent and architecture dependent. In general, here are some guidelines, though their impact on final performance will vary:
- use multiples of hardware vector length, so that you avoid tail handling (e.g. 64 should be ok for most instruction sets and datatypes)
- use multiples of the number of cores if you are targeting a particular platform. This allows perfect load balancing.
- Try to avoid large powers of 2 to maximize cache usage. This is because CPU caches are typically N-way associative, and for L1 cache, strided accesses prevent from using all the cache effectively (see [here](https://en.wikipedia.org/wiki/Cache_placement_policies#Set-associative_cache)) 

Hope that helps.
