### ISSUE TITLE
Integration of default in-order stream behaviour to release candidate

### ISSUE THREAD

**Issue by sanchit-grover-intel** [oneapi-src/oneDNN#1753]
Hello,

For one of our applications, we need the default stream behaviour to be in-order. There is a commit by @dzarukin that works for us: https://github.com/oneapi-src/oneDNN/commit/615236ce07261b622c5fe10de91e2832c4c4e985. I see that this is merged into the master branch, but it wasn't included in v3.3 release. I was wondering if there is a plan to include this change in the next release? Thank you.

**Comment by vpirogov** [comment]
This change is now available in [oneDNN v3.3.1](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3.1).
