### ISSUE TITLE
oneDNN build with ACL support on ARM machine gives wrong output for matrix multiplication operator

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#1755]
# Summary
oneDNN build with ACL support for MatMul operator on ARM:
1.  Basic build does not go inside ACL. So some changes are made in code so that oneDNN goes into ACL on ARM.
2.  MatMul operator gives wrong output w.r.t gemm_ref output.

# Version
Report oneDNN version and githash. Version information is printed to stdout
oneDNN Version: v3.2.0
(commit 010b6bcfb3bb5a9310b6d6403d3ca2b3e29900b7)

# Environment
CPU:  aarch64
OS:  22.04.1-Ubuntu
Compiler version (`gcc --version`): 11.4.0
CMake version (`cmake --version`): 3.22.7
git hash (`git log -1 --format=%H`): 010b6bcfb3bb5a9310b6d6403d3ca2b3e29900b7

# Steps to reproduce
1. clone oneDNN v3.2.0
2.  Make changes to following files in order to make onednn to go into acl for matmul operator:
     copy matmul.cpp to examples folder.
     In examples/matmul.cpp:
         o Comment all the bias data
         o Change weights format tag to any (ln.no : 88)
         o For weights we have to set data handles instead of gettting data handle (ln.no : 99)
            write_to_dnnl_memory(weights_data.data(), weights_mem); ->
            change to ->
            weights_mem.set_data_handle(weights_data.data())
        o Remove bais from arguments passes to create primitive desc. (ln.no : 113)
             auto matmul_pd = matmul::primitive_desc(engine, src_md, weights_md, bias_md, dst_md, matmul_attr); ->
            change to ->
            auto matmul_pd = matmul::primitive_desc(engine, src_md, weights_md, dst_md, matmul_attr)
     In src/cpu/aarch64/matmul/acl_matmul_utils.cpp:
        o Skip check for weight format (ln.no : 108) comment them
     In src/common/memory.cpp:
       o Comment the check for any format (ln.no : 146)
      In examples/matmul.cpp: use the following matrix shape
                // Tensor dimensions.
                const memory::dim MB = 3, // batch size
                            one=1, M = 128, K = 256, N =510;
                
                auto tg=tag::abc;
                memory::dims src_dims = {one,M,K};
                memory::dims weights_dims = {one,K,N};
                memory::dims dst_dims = {one,M,N};

3. mkdir build; cd build
4. cmake .. -DDNNL_AARCH64_USE_ACL=ON
5. make -j
6. cp ../build/include/oneapi/dnnl/* ../include/oneapi/dnnl/
7. export LD_LIBRARY_PATH= onednn_path/build/src
8. g++ -I onednn_path/include -L   /onednn_path/build/src matmul.cpp -ldnnl
9. ./a.out  (print matrix multiplication output)

# Observed behavior
output log for gemm ref:
![image](https://github.com/oneapi-src/oneDNN/assets/16516666/f9240129-23a7-4460-a72a-8ecdb13c64ef)
output log for gemm acl:
![image](https://github.com/oneapi-src/oneDNN/assets/16516666/229fe889-93ec-46e5-a0fc-c8ba3b59c50d)

**There is mismatch in matrix multiplication output between gemm ref and gemm acl implementations**

# Expected behavior
 The expected behaviour is that outputs of matrix multiplication between gemm ref and gemm acl implementations should match.

**Comment by jondea** [comment]
Hi @vineel96, thanks for your report. These 4 lines are necessary for the ACL kernel to correctly compute the matrix multiplication https://github.com/oneapi-src/oneDNN/blob/010b6bcfb3bb5a9310b6d6403d3ca2b3e29900b7/src/cpu/aarch64/matmul/acl_matmul_utils.cpp#L105-L111
As the comment says, the kernel will expect the user to have reordered the weights to be in that format. If the weights aren't in that form, then I would expect it to return the incorrect result. Why is it you commented these out?

So that I can reproduce your issue, can you tell me where to find that commit? When I click it, it says:
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
It might make sense for you to push the changes you describe in your issue to a branch on a private fork of oneDNN, that way we are working from the same source.

Also, would be able to tell me what version of ACL you are using?

**Comment by vpirogov** [comment]
Closing as stale. Feel free to reopen with additional information.
