### ISSUE TITLE
The test cases are not compatible with the new version of DNN

### ISSUE THREAD

**Issue by martyGong** [oneapi-src/oneDNN#1771]
The new version of DNN has been moved to https://github.com/oneapi-src/oneDNN. This location does not contain any mkldnn related headers or namespaces.
![image](https://github.com/oneapi-src/oneDNN/assets/97139887/9774621d-d512-451a-9c52-68b25ce01efb)

**Comment by vpirogov** [comment]
Hi @martyGong,

These errors have nothing to do with repository location change. oneDNN follows [semantic versioning scheme](https://semver.org/) and guarantees API compatibility between minor releases or patch releases as long as major version is the same. The code in your screenshot seems to be developed against oneDNN [v1.x](https://github.com/oneapi-src/oneDNN/tree/rls-v1.8) or [v2.x](https://github.com/oneapi-src/oneDNN/tree/rls-v2.7). Current version, [v3.x](https://github.com/oneapi-src/oneDNN/tree/rls-v3.3) does not include mfdnn headers or namespaces.

Please refer to [Intel MKL-DNN to oneDNN transition guide](https://oneapi-src.github.io/oneDNN/dev_guide_transition_to_dnnl.html) if you want to migrate your code to newer version.
