### ISSUE TITLE
Convolution not utilizing Eigen Implementation in TensorFlow v2.14.0, Defaults to OneDNN

### ISSUE THREAD

**Issue by rpushkarr** [oneapi-src/oneDNN#1774]
**Convolution not utilizing Eigen Implementation in TensorFlow v2.14.0, Defaults to OneDNN**

**Environment**:
  -   TensorFlow Version: 2.14.0
  -   Operating System and distribution: Ubuntu version 22.04 on aarch64

I have observed that the convolution operation in TensorFlow v2.14.0 is not utilizing the Eigen implementation.  Instead, it defaults to the OneDNN (Intel Math Kernel Library) implementation.  However, when I tried forcefully to redirect it to execute convolution through eigen implementation using following changes in mkl_layout_pass.cc (file path: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/mkl_layout_pass.cc):
```
rinfothr_.push_back(
        {csinfo_.conv2d, mkl_op_registry::GetMklOpName(csinfo_.conv2d),
          CopyAttrsConvCheckConstFilter,
          RewriteIfX86, 
          GetRewriteCause()}); 
    rinfo_.push_back({csinfo_.conv2d_with_bias,
                      native_fmt ? csinfo_.mkl_native_conv2d_with_bias
                                 : csinfo_.mkl_conv2d_with_bias,
                      CopyAttrsConvCheckConstFilter, RewriteIfX86, 
                      GetRewriteCause()});
    rinfo_.push_back({csinfo_.conv2d_grad_filter,
                      mkl_op_registry::GetMklOpName(csinfo_.conv2d_grad_filter),
                      CopyAttrsConvCheckConstFilter, RewriteIfX86, GetRewriteCause()}); 
                      native_fmt
                          ? csinfo_.mkl_native_conv2d_grad_filter_with_bias
                          : csinfo_.mkl_conv2d_grad_filter_with_bias,
                      CopyAttrsConvCheckConstFilter, RewriteIfX86, GetRewriteCause()}); 
    rinfo_.push_back({csinfo_.conv2d_grad_input,
                      mkl_op_registry::GetMklOpName(csinfo_.conv2d_grad_input),
                      CopyAttrsConvCheckConstFilter, RewriteIfX86, GetRewriteCause()});
```

Following the compilation of the customized TensorFlow build, I executed a sample Python code to perform convolution.

**Expected Behavior**:
The convolution operation should utilize the Eigen implementation by default in TensorFlow v2.14.0.

**Actual Behavior**:
The convolution operation defaults to using the OneDNN implementation, bypassing the expected Eigen implementation.

**Comment by vpirogov** [comment]
Tensorflow uses [oneDNN by default on x64 CPUs](https://github.com/tensorflow/community/blob/master/rfcs/20210930-enable-onednn-ops.md) starting from [Tensorflow 2.9](https://github.com/tensorflow/tensorflow/releases/tag/v2.9.0). You can disable oneDNN operations in Tensorflow with [TF_ENABLE_ONEDNN_OPTS=0](https://github.com/tensorflow/tensorflow/releases/tag/v2.15.0) environment variable.

**Comment by rpushkarr** [comment]
Hi @vpirogov,
I am using Ubuntu 22.04.1 on aarch64 architecture as my OS platform and distribution. 
Currently, I am in the process of building TensorFlow from source to forcefully execute convolution through eigen implementation. How to forcefully run convolution using eigen on aarch64 architecture machine?

**Comment by vpirogov** [comment]
Sorry, I missed the fact that you are runnning on AArch64. Same environment variable (TF_ENABLE_ONEDNN_OPTS=0) [should disable oneDNN on AArch64](https://github.com/tensorflow/tensorflow/releases/tag/v2.10.0). If it does not then it's a Tensorflow bug.

+@milpuz01, @jondea
