### ISSUE TITLE
how can i finish the operator of AdaptiveAvgPool in onednn

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1775]
i'm a new leanring for onednn, when building a network with onednn, i found that there is no such op，only avgpool。How to implement AdaptiveAvgPool in oneDnn。Thanks.

**Comment by chaoyu3** [comment]
Pytorch has AdaptivePooling implementation here: 

https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/AdaptivePooling.h
https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cpu/AdaptiveAvgPoolKernel.cpp

If the input size is an integer multiple of the output for your case, the adaptive max pooling can be replaced by max pooling from oneDNN. 
the stride and kernel size can be pre-calculated from input and output size, like: 
stride = kernel =  input size/ output size. 

but, if the input size is not an integer multiple of the output, the current oneDNN max pooling can not product the exactly the same output with AdaptivePooling:


See the bellow code which is similar with Pytorch on steps/kernel computation for adaptive pooling, 
```
inline int start_index(int a, int b, int c) {
        return (a / b) * c + ((a % b) * c) / b;
}
inline int end_index(int a, int b, int c) {
        return 1 + ((a + 1) * c - 1) / b;
}

int main() {
    int osize = 6;
    int isize = 10;
    for (int oh = 0; oh < osize; ++oh) {
        int istart = start_index(oh, osize, isize);
        int iend   = end_index(oh, osize, isize);
        int k = iend - istart;
        std::cout << "oh: " << oh << ", istart: " << istart << ", iend: " << iend << ", kernel: " << k << std::endl;
    }
    return 0;
}
```

the stride and kernel change when input size is not an integer multiple of ouput in some cases. 
For example, when input size is 10, output is 6: 
oh: 0, istart: 0, iend: 2, kernel: 2
oh: 1, istart: 1, iend: 4, kernel: 3
oh: 2, istart: 3, iend: 5, kernel: 2
oh: 3, istart: 5, iend: 7, kernel: 2
oh: 4, istart: 6, iend: 9, kernel: 3
oh: 5, istart: 8, iend: 10, kernel: 2

**Comment by feixuedudiao** [comment]
ths
