### ISSUE TITLE
Add official support for sparse memory and sparse-dense matmul

### ISSUE THREAD

**Issue by WilliamTambellini** [oneapi-src/oneDNN#1778]
# Summary
Add official support for sparse memory and sparse-dense matmul

# Problem statement
Atm sparse support is an optional exp build option:
https://github.com/oneapi-src/oneDNN/blob/cec7b41fc4686272a8dec123cb0c871093da3d9c/cmake/options.cmake#L197

# Preferred solution
Just enable sparse support by default.

**Comment by vpirogov** [comment]
@WilliamTambellini, sparsity is officially supported by oneDNN. Experimental status indicates that we do not guarantee API compatibility for this functionality at the moment, as we may need to make adjustments to API based on users feedback.

Can you elaborate on why you need this functionality enabled by default?

**Comment by vpirogov** [comment]
Feel free to reopen with additional information.

**Comment by vpirogov** [comment]
Current plan is to enable sparsity by default once it gets adopted by Tensorflow in upstream.

**Comment by vpirogov** [comment]
Tensorflow PR is up: https://github.com/tensorflow/tensorflow/pull/62883
