### ISSUE TITLE
Branching and release scheme

### ISSUE THREAD

**Issue by jondea** [oneapi-src/oneDNN#1779]
I was looking at the [branches page](https://github.com/oneapi-src/oneDNN/branches) and noticed that there is an [rls-3.4-pc](https://github.com/oneapi-src/oneDNN/tree/rls-v3.4-pc) branch. I assume that `rc` tags are release candidates, but what does the `pc` mean here? I couldn't find any definitions for it.

More generally I managed to find [this comment](https://github.com/oneapi-src/oneDNN/issues/580#issuecomment-547661841)

> Here's the branching scheme that we use:
> - `master` is used for ongoing development for stable major version (v1 now). No releases are done from the master.
> - `mnt-vX `is for support of previous major version (v0 now). No releases are done from mnt-vX branches either.
> - `rls-vX.Y` branch is created for each minor release at code freeze. The release candidate, vX.Y release, and vX.Y.Z patch releases are done from this branch.

But things have changed since. What's the current branching scheme?

Thanks!

**Comment by yehudaorel** [comment]
Hi @jondea, 

- `pc` stands for "preview candidate", which is used as an **engineering drop release** not to use for final production. 
- `master` branch has been renamed to `main`, purpose remains the same.

Hope this helped, let us know if you have any other questions/clarifications!

**Comment by jondea** [comment]
Hi @yehudaorel, thank you for the quick reply. Just to clarify, what's the purpose/difference between `rls-v3.3-pc` and the future `rls-v3.3` branch? Will `rls-v3.3` branch off `rls-v3.3-pc` when it's considered stable in some way?

**Comment by vpirogov** [comment]
@jondea,

rls-v3.3-pc is a release branch created from main to support [v3.3-pc](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3-pc) pre-production release. This branch is not used for any other purposes. This pre-production release is intended to support certain GPU related deliverables and does not meet full set of quality requirements.

rls-v3.3 is a release branch created from main to support [v3.3](https://github.com/oneapi-src/oneDNN/releases/tag/v3.3) production release and subsequent patch releases.

**Comment by jondea** [comment]
That clears things up, thank you both!
