### ISSUE TITLE
Why dnnl_gemm_bf16bf16f32 is much slower than dnnl_sgemm？

### ISSUE THREAD

**Issue by wells-wei-wei** [oneapi-src/oneDNN#1780]
My project has to use gemm with bfloat16 data, but dnnl_gemm_bf16bf16f32 is not in dnnl.h and I can't use it directly. So I write a function like this in src/common/gemm.cpp:

_dnnl_status_t gemm_bf16bf16f32(char transa, char transb, dim_t M, dim_t N, dim_t K, float alpha, const void *A, dim_t lda, const void *B, dim_t ldb, float beta, float *C, dim_t ldc) {
    // convert float to bf16
    bfloat16_t *A_bf16 = new bfloat16_t[M * K];
    bfloat16_t *B_bf16 = new bfloat16_t[N * K];
    for(size_t i = 0; i < (M * K); i++) {
        A_bf16[i] = ((float*)A)[i];
    }
    for(size_t i = 0; i < (N * K); i++) {
        B_bf16[i] = ((float*)B)[i];
    } 
    dnnl_gemm_bf16bf16f32(transa, transb, M, N, K, alpha, A_bf16, lda, B_bf16, ldb, beta, C, ldc);
    delete A_bf16;
    delete B_bf16;
    return dnnl_success;
}_

and add it in dnnl.h:

_dnnl_status_t DNNL_API gemm_bf16bf16f32(char transa,
        char transb, dnnl_dim_t M, dnnl_dim_t N, dnnl_dim_t K, float alpha,
        const void *A, dnnl_dim_t lda, const void *B, dnnl_dim_t ldb,
        float beta, float *C, dnnl_dim_t ldc);_

But when I use it, I find dnnl_gemm_bf16bf16f32 is much slower than dnnl_sgemm, why is that? I'm sure the host cpu support avx512_bf16, is this because I didn't add some options during build time?

**Comment by yehudaorel** [comment]
Hi @wells-wei-wei,

Regarding implementation of `dnnl_gemm_bf16bf16f32`, the [recommended interface](https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/matmul/cpu_matmul_list.cpp#L81) for this internal GEMM API call is via a [MatMul ](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html) primitive. 

Please reference the solution provided[ here](https://gist.github.com/emfomenk/4bdc70908cc5c30ad2a97e5030a22eaf), as well as [this example](https://oneapi-src.github.io/oneDNN/page_cpu_sgemm_and_matmul_cpp.html#doxid-cpu-sgemm-and-matmul-cpp) demonstrating MatMul as a replacement for sGEMM functions for additional details.

> But when I use it, I find dnnl_gemm_bf16bf16f32 is much slower than dnnl_sgemm, why is that? I'm sure the host cpu support avx512_bf16, is this because I didn't add some options during build time?

In general without Intel AMX support, bf16 gemm based ops have little to no performance gain depending on problem shape/HW/etc., which might explain your results.

Could you run the workload with the following environment variable: `ONEDNN_VERBOSE=all` and share the output? this will tell you specific supported ISA's and primitive dispatch information. 

Additional information such as problem size/shape, CPU, OS will be helpful!

**Comment by vpirogov** [comment]
@wells-wei-wei, in addition to what @yehudaorel shared there's [an example](https://github.com/oneapi-src/oneDNN/blob/main/examples/matmul_perf.cpp) that benchmarks and reports matmul primitive performance with various data types.
