### ISSUE TITLE
Request for Explanation of values set to some variables in jit_avx512_common_conv_kernel.cpp

### ISSUE THREAD

**Issue by kasturedeeksha** [oneapi-src/oneDNN#1782]
In the file `oneDNN/src/cpu/x64/jit_avx512_common_conv_kernel.cpp`, at line 1025, the values of `jcp.nb_ic_blocking` and `jcp.nb_oc_blocking` are set to 1:

“jcp.nb_ic_blocking = jcp.nb_oc_blocking = 1;”

I am seeking clarification on why these specific values are chosen.

Also if possible, I would appreciate guidance on how to experiment with different values for `jcp.nb_ic_blocking` and `jcp.nb_oc_blocking` to assess their impact on performance. Additionally, any information on the trade-offs associated with adjusting these parameters would be valuable.

Thank you for your time and assistance in addressing this query.

**Comment by shu1chen** [comment]
@kasturedeeksha From my understanding, the number of blocks ``jcp.nb_ic_blocking`` and ``jcp.nb_oc_blocking`` are initialized with value ``1``, meaning the data is initially not blocked. The values can be updated in some conditions, e.g. ``jcp.nb_ic_blocking`` can be updated with value ``i`` in [line 2104](https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/jit_avx512_common_conv_kernel.cpp#L2104) and ``jcp.nb_oc_blocking`` can be updated with value ``best_nb_oc_blocking`` in [line 1197](https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/jit_avx512_common_conv_kernel.cpp#L1197).

@msotoflo I see in the commit history that you updated the heuristic for nb_oc_blocking 4 years ago. Do you possibly have any suggestions for manually adjusting the values of ``jcp.nb_ic_blocking`` and ``jcp.nb_oc_blocking``?

**Comment by msotoflo** [comment]
Hello @kasturedeeksha 

There might be multiple reasons why these params were set to 1. Although primarily, depending on which direction the convolution is executed (e.g. forward vs backward propagation) is what kind of impact nb_ic_blocking or nb_oc_blocking will have. For forward direction, `nb_oc_blocking` will allow loop unrolling on the output elements. The best value for this param is chosen in [src/cpu/x64/jit_avx512_common_conv_kernel.cpp#L1197](https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/jit_avx512_common_conv_kernel.cpp#L1197) while taking into account other factors. `jcp.nb_ic_blocking` will do the same for backward propagation.

Additionally, I would like to point out that these are somewhat legacy JIT kernels. We now mostly depend on BRGeMM JIT Implementations to support the convolution primitive and give better performance.

Might I ask what is your interest in this specific implementation and what your approach is to running these primitives? We expect users to execute OneDNN primitives through the API and let OneDNN choose the best primitive implementation (as well as its internal parameters).
