### ISSUE TITLE
How to print out Memory Descriptors and other stuff?

### ISSUE THREAD

**Issue by Devjiu** [oneapi-src/oneDNN#1787]
I was working with an almost first example: 
https://github.com/oneapi-src/oneDNN/blob/b19f6875b1a27097aede9e8de1b632e3b1ae4d72/examples/primitives/convolution.cpp

1. 
I faced with several reorder operations were inserted due to mismatch of Memory Descriptors: 
```cpp
if (conv_pd.weights_desc() != user_weights_mem.get_desc()) {
```
I figured out, that difference were at format_tag, but is there option to print out memory descriptors, primitives and so on? 
There are some stuff in `dnnl/src/dnnl/src/src/common/verbose.hpp` but I can't include it. 
Also `info_with_runtime_dims()` and similar calls are not available for external user because when you are trying to do 
```cpp
user_src_mem.get_desc().get()->info_with_runtime_dims()
```
you get `dnnl_memory_desc_t is incomplete type` as this struct is predeclared. And defenition is at `dnnl/src/dnnl/src/src/common/memory_desc.hpp` which also cannot be included. 

Please tell me how to print these structures? 

2. 
In the example there are 2 utility functions: `write_to_dnnl_memory` and `read_from_dnnl_memory`
that actually copy the data (CPU case): 
```cpp
  size_t size = user_src_mem.get_desc().get_size();
  for (size_t i = 0; i < size; ++i)
    dst[i] = ((uint8_t *)in)[i];
```

Is it required to copy data? There are `set_data_handle()` method, but it breaks the code. Can I somehow pass the pointer to data without copying?

**Comment by yehudaorel** [comment]
Hi @Devjiu, as for the first question, oneDNN provides API execution tracing with primitive information via the environment variable `ONEDNN_VERBOSE`. Please refer to the [verbose mode documentation](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html) for more detail.

As for the second question, indeed you can use set_data_handle() for example in [examples/primitives/convolution.cpp](https://github.com/oneapi-src/oneDNN/blob/b19f6875b1a27097aede9e8de1b632e3b1ae4d72/examples/primitives/convolution.cpp) you can replace the the following lines:
```
write_to_dnnl_memory(src_data.data(), user_src_mem);
write_to_dnnl_memory(weights_data.data(), user_weights_mem);
write_to_dnnl_memory(bias_data.data(), user_bias_mem);
```
with
```
user_src_mem.set_data_handle(src_data.data());
user_weights_mem.set_data_handle(weights_data.data());
user_bias_mem.set_data_handle(bias_data.data());
```
Another option is to pass data during memory creation:
`auto user_src_mem = memory({src_dims, dt::f32, tag::nchw}, engine, src_data.data());`

Hope this helps, let us know if you run to any other issues!

**Comment by Devjiu** [comment]
@yehudaorel 
Thanks, for quick response) 
I was sure, that already set this variable - but there left `dnnl_set_verbose(0);`  in my code. Thanks for the hint. 
Setting data pointer in c-tor also helped, much better.

Sorry for noob questions, my questions are resolved.
