### ISSUE TITLE
Understand oneDNN graph compiler

### ISSUE THREAD

**Issue by akote123** [oneapi-src/oneDNN#1797]
Hi,
 I wanted to understand from framework like Tensorflow or Pytorch how we can enable graph compiler.

cc:@ZhennanQin 

Thank you

**Comment by ZhennanQin** [comment]
Hi Aruna,

The framework integration is WIP, you may check the status from [framework RFC](https://github.com/pytorch/pytorch/issues/105582). Currently, the recommended way to try graph compiler with pytorch, is to use [IPEX](https://github.com/intel/intel-extension-for-pytorch). Graph compiler is enabled by default in its INT8 path, for other data types like float32 or bfloat16, you need to manually turn on oneDNN graph by inserting the below line in the beginning of your model script:
```
ipex._C.set_llga_fp32_bf16_enabled(True)
```

**Comment by akote123** [comment]
@ZhennanQin Thank you

**Comment by ZhennanQin** [comment]
The brgemm interface location: https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/brgemm/brgemm.hpp

**Comment by akote123** [comment]
@ZhennanQin ,Graph compiler calls microkernel from primitive APIs?
How Tensor IR is connected to this?

**Comment by ZhennanQin** [comment]
Graph compiler shares the same microkernel implementation with primitive. The brgemm abstraction in graph compiler can be found at: https://github.com/oneapi-src/oneDNN/blob/main/src/graph/backend/graph_compiler/core/src/runtime/microkernel/cpu/microkernel.hpp

**Comment by akote123** [comment]
@ZhennanQin , Thank you. If we are using the same kernel from primitive then benefit of using graph compiler is only fusion?
if yes then primitives also support fusion , that is post op will be there right
So when we prefer graph compiler over primitives

**Comment by akote123** [comment]
@ZhennanQin ,How the fusion patterns in oneDNN graph api and  pytorch inductor are different
