### ISSUE TITLE
Difference between BRGEMM in oneDNN and GEMM in openBLAS

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#1799]
Hello team, 
I have following doubts:
1. How does BRGEMM in oneDNN, batched GEMM and GEMM in openBLAS differ? 
2. Can you provide intel's research paper links for BRGEMM? Also if there any recent variant of algorithm with performance boost can you share them? ( I found this paper https://arxiv.org/pdf/1906.06440.pdf, apart from this, any paper that I might have missed referring please share)

**Comment by yehudaorel** [comment]
Hi @vineel96 
In general, oneDNN supports various popular tensor formats used in deep learning workloads, such as plain formats - `NCHW` (batch size, channels, height, width) and blocked formats. oneDNN supports low optimizations, and is highly optimized for these types of memory/tensor formats. oneDNN `brgemm` kernel also provided functionality for [post-op fusion](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html) to benefit from additional performance gain. While OpenBLAS may also support different memory layouts, its implementation may not be as tailored to deep learning-specific tensor formats on Intel architecture, where oneDNN is.

Another advantage of `brgemm` internal implementation in oneDNN, is that weights tensors can be prepacked, reducing mem copy overhead for additional performance as mentioned in the [paper](https://arxiv.org/pdf/1906.06440.pdf). 

A more appropriate compression would be to [Intel Math Kernel Library](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html#gs.4qwffh) (oneMKL) which also provides general BLAS functions not specific to DL workloads. 

May I ask what are your specific doubts/concerns?

**Comment by vpirogov** [comment]
@vineel96, research paper on BRGEMM you found is the right one. oneDNN uses approach described in this paper to implement [convolution](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html), [matmul](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html), [inner product](https://oneapi-src.github.io/oneDNN/dev_guide_inner_product.html), and [RNN](https://oneapi-src.github.io/oneDNN/dev_guide_rnn.html) primitives. BRGEMM itself is an implementation detail for oneDNN, not a user-visible function.

OpenBLAS's GEMM is a general purpose matrix multiplication function with ]NETLIB CBLAS API](https://www.netlib.org/blas/#_cblas):
```
void cblas_sgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
		 OPENBLAS_CONST float alpha, OPENBLAS_CONST float *A, OPENBLAS_CONST blasint lda, OPENBLAS_CONST float *B, OPENBLAS_CONST blasint ldb, OPENBLAS_CONST float beta, float *C, OPENBLAS_CONST blasint ldc);
void cblas_dgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
		 OPENBLAS_CONST double alpha, OPENBLAS_CONST double *A, OPENBLAS_CONST blasint lda, OPENBLAS_CONST double *B, OPENBLAS_CONST blasint ldb, OPENBLAS_CONST double beta, double *C, OPENBLAS_CONST blasint ldc);
void cblas_cgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
		 OPENBLAS_CONST void *alpha, OPENBLAS_CONST void *A, OPENBLAS_CONST blasint lda, OPENBLAS_CONST void *B, OPENBLAS_CONST blasint ldb, OPENBLAS_CONST void *beta, void *C, OPENBLAS_CONST blasint ldc);
void cblas_zgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
		 OPENBLAS_CONST void *alpha, OPENBLAS_CONST void *A, OPENBLAS_CONST blasint lda, OPENBLAS_CONST void *B, OPENBLAS_CONST blasint ldb, OPENBLAS_CONST void *beta, void *C, OPENBLAS_CONST blasint ldc);
void   cblas_sbgemm(OPENBLAS_CONST enum CBLAS_ORDER Order, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransA, OPENBLAS_CONST enum CBLAS_TRANSPOSE TransB, OPENBLAS_CONST blasint M, OPENBLAS_CONST blasint N, OPENBLAS_CONST blasint K,
		    OPENBLAS_CONST float alpha, OPENBLAS_CONST bfloat16 *A, OPENBLAS_CONST blasint lda, OPENBLAS_CONST bfloat16 *B, OPENBLAS_CONST blasint ldb, OPENBLAS_CONST float beta, float *C, OPENBLAS_CONST blasint ldc);
```

This functionality may be compared to oneDNN's [matmul](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html). @yehudaorel above nicely covered how matmul is tailored to AI cases.

**Comment by vineel96** [comment]
Hi @vpirogov , @yehudaorel 
Thank you for the comments.
I wanted to know the exact difference between gemm and bgremm. I assume the following:
1. they differ in the division of matrix A and matrix B for multiplication.
2. The internal microkernel for actual multiplication is different. In BRGEMM it uses outer product gemm microkernel which actually multiplies the A's column with broadcasting of B's row  values.
Also what are the advantages of broadcasting the B row values? Is it for parallelization of computation only?

**Comment by yehudaorel** [comment]
@vineel96, Yes that understanding is correct, in the oneDNN brgemm internal kernel, the outer product microkernel is utilized to multiply the column of matrix A with a row of matrix B, essentially performing an outer product operation. This operation involves broadcasting the values of the row of matrix B to be multiplied with each element of the column of matrix A. The benefits  of the brgemm approach is 

Along with the benefits of parallelization, using the broadcasting approach will allow in more efficient vectorization, for example by broadcasting the elements across multiple elements of matrix A's cols, SIMD (single instruction, multiple data) instructions can be utilized to perform the multiplication in parallel, improving computational efficiency.

Another inherent advantage of the brgemm approach is reduced memory accesses during computation; as the same row values of matrix B are reused for multiple multiplications with different elements of matrix A's column.


![image](https://github.com/oneapi-src/oneDNN/assets/111955825/716793fb-2091-4dac-8900-ef789189e3ed)
_https://arxiv.org/pdf/1906.06440.pdf_

**Comment by vineel96** [comment]
Hi @yehudaorel,
Thank you for the explanation. One other question, the reference GEMM (GEMM ref) implementation uses which algorithm?it uses openBLAS kernels only as i see in the code? or any other kernel it uses?

**Comment by yehudaorel** [comment]
@vineel96, I am not an expert in openBLAS, so I cannot comment on their specific implementations/algorithms. I would suggest you take a look at the following documentation: https://github.com/OpenMathLib/OpenBLAS/wiki/Developer-manual#optimizing-gemm-for-a-given-hardware and get insight from maintainers.

**Comment by vineel96** [comment]
@yehudaorel  Thanks for the information.
