### ISSUE TITLE
cblass_gemm incorrect output

### ISSUE THREAD

**Issue by maktukmak** [oneapi-src/oneDNN#1805]
I am trying to use cblas_gemm_s8u8s32 in a torch program for int8 matrix multiplication. From this doc (https://oneapi-src.github.io/oneDNN/dev_guide_int8_computations.html), I am aware that it is better to use 7-bit data for the first or second input to avoid potential saturation. Here is my test code that passes 8-bit uint for the second input:  

Test code:
```
#include <vector>
#include <torch/extension.h>
#include "mkl.h"
#include "cpu_mm_mkl.cpp"

int main(int argc, char *argv[])
{
    int m = 32;
    int n = 32;
    int k = 32;

    torch::Tensor self = torch::ones({m, k}, torch::kInt8);
    torch::Tensor mat2 = 128 + torch::ones({k, n}, torch::kUInt8);

    auto result = _int_mm_cpu(self, mat2);

    std::cout << result << std::endl;

}
```

with kernel code:
```
#include <vector>
#include <torch/extension.h>
#include "mkl.h"


torch::Tensor& _int_mm_out_cpu(const torch::Tensor& self, const torch::Tensor& mat2, torch::Tensor& result) {
   
    TORCH_CHECK(self.dim() == 2, "Expected self to be of dimension 2 but got ", self.dim());
    TORCH_CHECK(mat2.dim() == 2, "Expected mat2 to be of dimension 2 but got ", mat2.dim());
    TORCH_CHECK(self.size(0) > 16, "self.size(0) needs to be greater than 16, but got ", self.size(0));
    TORCH_CHECK(self.size(1) > 0 && self.size(1) % 8 == 0, "self.size(1) needs to be greater than 0 and a multiple of 8, but got ", self.size(1));
    TORCH_CHECK(self.size(1) == mat2.size(0), "self.size(1) needs to match mat2.size(0) but got ", self.size(1), " and ", mat2.size(0));
    TORCH_CHECK(mat2.size(1) > 0 && mat2.size(1) % 8 == 0, "mat2.size(1) needs to be greater than 0 and a multiple of 8, but got ", mat2.size(1));

    TORCH_CHECK(result.dtype() == at::kInt, "Expected result dtype to be of type kInt but got ", result.dtype());
    TORCH_CHECK(result.size(0) == self.size(0), "Expected result.size(0) to be ", self.size(0), " but got ", result.size(0));
    TORCH_CHECK(result.size(1) == mat2.size(1), "Expected result.size(1) to be ", mat2.size(1), " but got ", result.size(1));

    TORCH_CHECK(result.dim() == 2, "Expected result to be of dimension 2 but got ", result.dim());

    TORCH_CHECK(result.is_contiguous(), "Expected result to be contiguous.");

    MKL_INT         m=self.size(0), n=mat2.size(0), k=self.size(1);
    MKL_INT         lda=self.size(1), ldb=mat2.size(1), ldc=result.size(1);
    float           alpha=1.0f, beta=0.0f;

    const MKL_INT8 ao = 0;
    const MKL_INT8 bo = 0;
    MKL_INT32 co = 0;
    CBLAS_OFFSET    offsetc=CblasFixOffset;

    cblas_gemm_s8u8s32(CblasRowMajor, CblasNoTrans, CblasNoTrans, offsetc,
                      m, n, k, alpha, self.data_ptr<int8_t>(), lda, ao, mat2.data_ptr<uint8_t>(), ldb, bo, beta, result.data_ptr<int32_t>(), ldc, &co);

  return result;
}


torch::Tensor _int_mm_cpu(const torch::Tensor& self, const torch::Tensor& mat2) {
  torch::Tensor result = torch::empty({self.size(0), mat2.size(1)}, self.options().dtype(torch::kInt32));
  return _int_mm_out_cpu(self, mat2, result);
}
```

The resulting matrix is full of -4064, which is apparently wrong. I could not figure out what I am missing here. Any help is appreciated.

Seemingly, cblas_gemm_s8u8s32 does not work when the second input is larger than 127. My first input (all 1s) is already less than 8 bits. According to the doc I referred to above, cblas_gemm_s8u8s32 should work when the first input is 7bit and the second input is 8bit. In my setup, it does not work. 

Here is CPU specs:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          96
On-line CPU(s) list:             0-95
Thread(s) per core:              2
Core(s) per socket:              24
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           85
Model name:                      Intel(R) Xeon(R) Platinum 8260M CPU @ 2.40GHz
Stepping:                        7
CPU MHz:                         2400.000
CPU max MHz:                     3900.0000
CPU min MHz:                     1000.0000
BogoMIPS:                        4800.00
Virtualization:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1.5 MiB
L2 cache:                        48 MiB
L3 cache:                        71.5 MiB
NUMA node0 CPU(s):               0-23,48-71
NUMA node1 CPU(s):               24-47,72-95
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; Enhanced IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_c
                                 pl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shad
                                 ow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_lo
                                 cal dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

**Comment by maktukmak** [comment]
I solved this issue. cblas_gemm_s8u8s32 seems to expect the first input to be unsigned int and the second input to be signed int. That is kind of confusing though. From the naming convention s8u8s32, I would expect the opposite. Anyway, I can move forward with this solution.

**Comment by vpirogov** [comment]
This functionality is a part of oneMKL library, not oneDNN.

You can find relevant documentation in [oneMKL Developer Reference](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2024-0/cblas-gemm-002.html). Apparently data type of A and B matrices changes depending on the layout chosen.
