### ISSUE TITLE
test_shuffle fails on aarch64 when BF16 data type is enabled.

### ISSUE THREAD

**Issue by renato-arantes** [oneapi-src/oneDNN#1806]
# Summary
By enabling BF16 data type on aarch64 [here](https://github.com/renato-arantes/oneDNN/blob/2136e1597be32bc56cd8244ec282a7908d8c9a9f/src/cpu/platform.cpp#L121), `test_shuffle` fails [here](https://github.com/oneapi-src/oneDNN/blob/561d996658ea151cbbf38385a837615e75662939/src/cpu/aarch64/shuffle/jit_uni_shuffle_kernel.cpp#L71). 

# Version
main, commit 0c2ea8b by @kawakami-k 

# Steps to reproduce
The code [here](https://github.com/renato-arantes/oneDNN/blob/2136e1597be32bc56cd8244ec282a7908d8c9a9f/src/cpu/platform.cpp#L121) checks if [ACL](https://github.com/ARM-software/ComputeLibrary) is present. But the issue also happens without ACL. By replacing the lines 120 and 121 with:

```
#elif DNNL_AARCH64
            return true;
```

Someone can enable BF16 on aarch64 by default, and reproduce the issue without ACL.

**Comment by kawakami-k** [comment]
Hi, @renato-arantes 

I reproduced `test_shuffle` of 67012a53d4c009923af034ec3917b2456d84b75c on Ubuntu22.04 AWS Graviton3.

```
.github/automation/build_acl.sh  --version 23.11 --arch armv8a --multi_isa --root-dir $(pwd)/ComputeLibrary
.github/automation/build.sh --threading omp --mode Release --source-dir $(pwd) --build-dir $(pwd)/build --acl-dir $(pwd)/ComputeLibrary
cd build/tests/gtests
./test_shuffle --gtest_filter="ShuffleSimpleBF16/shuffle_test_t.TestsShuffle/4"
```
This error message is as same as yours?
```
Note: Google Test filter = ShuffleSimpleBF16/shuffle_test_t.TestsShuffle/4:-*_GPU*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ShuffleSimpleBF16/shuffle_test_t
[ RUN      ] ShuffleSimpleBF16/shuffle_test_t.TestsShuffle/4
free(): invalid pointer
zsh: abort (core dumped)  ./test_shuffle 
```

**Comment by renato-arantes** [comment]
Hi @kawakami-k,

Sorry for the delay in responding to you.

It is similar:

```
./test_shuffle --gtest_filter="ShuffleSimpleBF16/shuffle_test_t.TestsShuffle/4"

Note: Google Test filter = ShuffleSimpleBF16/shuffle_test_t.TestsShuffle/4:-*_GPU*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ShuffleSimpleBF16/shuffle_test_t
[ RUN      ] ShuffleSimpleBF16/shuffle_test_t.TestsShuffle/4
test_shuffle: /home/renara01/desenv/oncpuml_1480/github/oneDNN/src/cpu/aarch64/shuffle/jit_uni_shuffle_kernel.cpp:77: void dnnl::impl::cpu::aarch64::jit_uni_shuffle_kernel_t<isa>::gather_data(const Xbyak_aarch64::XReg&, int, int, bool) [with dnnl::impl::cpu::aarch64::cpu_isa_t isa = dnnl::impl::cpu::aarch64::sve_256]: Assertion `!"unsupported emu_gather_data"' failed.
Aborted (core dumped)
```

**Comment by kawakami-k** [comment]
I'll fix the bug.
