### ISSUE TITLE
oneDNN 'Build from Source' doesn't work

### ISSUE THREAD

**Issue by jketreno** [oneapi-src/oneDNN#1809]
# Summary

I am attempting to follow the [Build from Source](https://oneapi-src.github.io/oneDNN/v2/dev_guide_build.html) instructions to build oneDNN in a Ubuntu 22.04 container:

![image](https://github.com/oneapi-src/oneDNN/assets/742584/6e3a0c8b-519f-4c6b-afc3-c3fb08a35dbf)
...
![image](https://github.com/oneapi-src/oneDNN/assets/742584/74f87072-1ce8-452c-aa20-aee635eef619)

**Setup system w/ oneAPI repo, and install DPC++ and necessary build dependencies**
```
sudo wget -qO - https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | \
    gpg --dearmor --output /usr/share/keyrings/oneapi-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | \
    sudo tee /etc/apt/sources.list.d/oneAPI.list
sudo apt-get update
sudo apt-get install --no-install-recommends -y \
    intel-oneapi-dpcpp-cpp-2024.0 \
    build-essential \
    clang \
    cmake
```

Following the instructions, the first error occurs here:

**NOTE**: The instructions in 'Build from Source' are missing a trailing slash after the `-DDNNL_CPU_RUNTIME=DPCPP`. Corrected in my execution below.

```
source /opt/intel/oneapi/setvars.sh
mkdir -p build
cd build
export CC=clang
export CXX=clang++
cmake .. \
          -DDNNL_CPU_RUNTIME=DPCPP \
          -DDNNL_GPU_RUNTIME=DPCPP
...
2.724 -- Found OpenCL headers: OpenCL_INCLUDE_DIR-NOTFOUND
2.732 CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
2.732   Could NOT find OpenCL (missing: OpenCL_LIBRARY OpenCL_INCLUDE_DIR)
...
```

The instructions don't call out that you need the OpenCL headers.  Adding those:

```
sudo apt-get install \
    opencl-headers \
    ocl-icd-opencl-dev
```

Then re-running the cmake results in it complaining that it can't find TBB, even though I did not select TBB for either runtime ([Build Options](https://oneapi-src.github.io/oneDNN/v2/dev_guide_build_options.html) implies TBB is only required if -DDNNL_CPU_RUNTIME=TBB is used. I am using -DDNNL_CPU_RUNTIME=DPCPP):

```
3.299 -- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
3.300 -- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
3.301 -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
3.306 -- TBB-provided CMake config either failed or was not found. Trying to use a custom one.
3.315 CMake Error at cmake/lnx/TBBConfig.cmake:104 (message):
3.315   Cannot find TBB
```

I went ahead and install libtbb-dev:

```
sudo apt-get install \
  libtbb-dev
```

And cmake completes. However, attempting to build fails:

```
make -j$(($(nproc)/2))
0.479 Scanning dependencies of target dnnl_common
0.487 [  0%] Building CXX object src/gpu/CMakeFiles/dnnl_gpu.dir/block_structure.cpp.o
0.487 [  0%] Building CXX object src/graph/utils/CMakeFiles/dnnl_graph_utils.dir/debug.cpp.o
0.487 [  0%] Building CXX object src/gpu/compute/CMakeFiles/dnnl_gpu_compute.dir/block_manipulation.cpp.o
0.489 [  0%] Building CXX object src/common/CMakeFiles/dnnl_common.dir/batch_normalization.cpp.o
0.493 [  0%] Building CXX object src/cpu/CMakeFiles/dnnl_cpu.dir/bfloat16.cpp.o
0.502 [  0%] Building CXX object src/cpu/x64/CMakeFiles/dnnl_cpu_x64.dir/amx_tile_configure.cpp.o
0.506 clang: error: unknown argument: '-fno-sycl-id-queries-fit-in-int'
0.506 clang: error: unknown argument: '-fno-sycl-id-queries-fit-in-int'
0.506 clang: error: unknown argument: '-fno-sycl-id-queries-fit-in-int'
0.507 clang: error: unknown argument: '-fno-sycl-id-queries-fit-in-int'
0.509 make[2]: *** [src/common/CMakeFiles/dnnl_common.dir/build.make:76: src/common/CMakeFiles/dnnl_common.dir/batch_normalization.cpp.o] Error 1
0.509 make[1]: *** [CMakeFiles/Makefile2:1197: src/common/CMakeFiles/dnnl_common.dir/all] Error 2
0.509 make[1]: *** Waiting for unfinished jobs....
...
```

# URLs

* [Build from Source](https://oneapi-src.github.io/oneDNN/v2/dev_guide_build.html)
* [Build Options](https://oneapi-src.github.io/oneDNN/v2/dev_guide_build_options.html)
 
# Additional details

Below is the full Dockerfile to reproduce the above failure:

```
mkdir tmp
cd tmp
cat << EOF > Dockerfile
FROM ubuntu:jammy

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y \
  gpg \
  wget \
  git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log}

# Install oneAPI DPC++
#
# oneAPI only has one stream end point
#
# https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2024-0/apt.html
RUN wget -qO - https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | \
    gpg --dearmor --output /usr/share/keyrings/oneapi-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | \
    tee /etc/apt/sources.list.d/oneAPI.list
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    intel-oneapi-dpcpp-cpp-2024.0 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log}

WORKDIR /home/user

# Build oneDNN from source
#
# https://oneapi-src.github.io/oneDNN/v2/dev_guide_build.html
RUN git clone https://github.com/oneapi-src/oneDNN.git
WORKDIR /home/user/oneDNN/build

# Install dependencies needed to build oneDNN
#
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    build-essential \
    clang \
    cmake \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log}

# cmake will fail as it can't find the OpenCL SDK headers. Install them...
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    opencl-headers \
    ocl-icd-opencl-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log}

# cmake will fail as it can't find TBB (even though DPCPP is being used). Install
# libtbb-dev...
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    libtbb-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log}

SHELL [ "/bin/bash", "-c" ]
RUN source /opt/intel/oneapi/setvars.sh

ENV CC=clang
ENV CXX=clang++
RUN cmake \
  .. \
  -DDNNL_CPU_RUNTIME=DPCPP \
  -DDNNL_GPU_RUNTIME=DPCPP

# Using all jobs kills my system, so limit to half
# the CPUs
RUN make -j$(($(nproc)/2))
# ^^^ build fails while running make

RUN cmake --build . --target install

ENTRYPOINT [ "/bin/bash" ]
EOF
docker build .

```

Documentation on [oneDNN](https://github.com/oneapi-src/oneDNN) indicates it was tested with `Clang 3.8.1, 7.1, 8.0, and 9.0`, however the version of clang on Ubuntu 22.04 is v14. Changing the FROM to 'ubuntu:focal' instead of 'ubuntu:jammy' result in the clang v10, and the following error during cmake:

```
0.789 -- Performing Test SYCL_FLAG_SUPPORTED
0.819 -- Performing Test SYCL_FLAG_SUPPORTED - Failed
0.819 CMake Error at cmake/dpcpp_driver_check.cmake:36 (message):
0.819   Clang doesn't support -fsycl flag.
```

**Comment by igorsafo** [comment]
Hi @jketreno ,
Thanks for reporting an issue.
Did you try to follow the latest version of the documentation? https://oneapi-src.github.io/oneDNN/dev_guide_build.html#intel-oneapi-dpc-c-compiler-with-sycl-runtime 
For DPCPP runtime the current way to build is to use `icx` and `icpx` drivers instead of `clang`. It seems like the wrong `clang` (not from oneAPI toolkit was found and it is not aware of DPCPP at all. TBB is required for DPCPP CPU runtime and is a part of oneAPI toolkit, so `setvars.sh` should set it for you.

**Comment by yehudaorel** [comment]
@jketreno seems like you are using old documentation, but building latest oneDNN. Please refer to the up-to-date docs https://oneapi-src.github.io/oneDNN/dev_guide_build.html

**Comment by jketreno** [comment]
Old build instructions were the culprit; bit-rot + Interweb links. Not sure how I landed on the v2 page instead of latest.

There was also a problem with how I had the Dockerfile was sourcing setvars.sh -- since the environment isn't persisted across multiple RUN lines, the values set the first time weren't being used in subsequent lines. I've updated my Dockerfile to use icx and icpx, and call `source /opt/intel/oneapi/setvars.sh` before each cmake and make call and it is now building.

Thank you.

Any chance the old documentation could have an indicator that it is not the latest documentation and point the user to that so others don't fall into the same pit?

**Comment by jketreno** [comment]
> Run some oneDNN examples:
> 
> ```
> time examples/matmul-perf-cpp cpu
> time examples/matmul-perf-cpp gpu
> ```

Well, CPU running works. GPU running is showing me:

```
# export ONEAPI_DEVICE_SELECTOR=level_zero:*
# sycl-ls 2>/dev/null
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Arc(TM) A770M Graphics 1.3 [1.3.27642]
[ext_oneapi_level_zero:gpu:1] Intel(R) Level-Zero, Intel(R) Iris(R) Xe Graphics 1.3 [1.3.27642]
# examples/matmul-perf-cpp gpu
oneDNN error caught:
        Status: invalid_arguments
        Message: could not create an engine
Example failed on GPU.
```

Any ideas?

**Comment by vpirogov** [comment]
Looks like something is missing in GPU software stack. You may want to check [client GPU driver installation](https://dgpu-docs.intel.com/driver/client/overview.html) instructions. One thing that seems to be missing from your docker file is Intel OpenCL GPU package.

Running the test with `DNNL_VERBOSE=all` may also yield some hints.

**Comment by jketreno** [comment]
Hmmm. Installing intel-opencl-icd did enable the application to run, so that unblocked me. Thank you. However, that seems really odd. If I'm using a level-zero device, why is OpenCL required? I had installed all the packages required for level-zero to operate.

For the debug env., I set `ONEDNN_VERBOSE=debuginfo=10` to get debug output (although that only started giving debug output after it had successfully identified a GPU context.)

**Comment by vpirogov** [comment]
This is good question. oneDNN has non-trivial amount of OpenCL C code, which is compiled at runtime for the target device. Compiled binaries are executed via SYCL runtime and Level Zero. This is effectively an implementation detail of oneDNN that has nothing to do with SYCL.

OpenCL dependency will go away once we switch to [SYCL Online Compilation extension](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/experimental/sycl_ext_intel_online_compiler.asciidoc) or reimplement this code in SYCL.

**Comment by jketreno** [comment]
@vpirogov Thank you for the explanation. I updated the final Dockerfile comment I put above to include the install of intel-opencl-icd.
