### ISSUE TITLE
How to disable USM feature for GPU plugin 

### ISSUE THREAD

**Issue by zhangnju** [oneapi-src/oneDNN#1811]
HI 

When I tried oneDNN on AMD GPU, I met the below issue: 
Device does not support shared USM allocations!

how did I disable USM feature when building OneDNN/SYCL AMD GPU? 

Thanks

**Comment by shu1chen** [comment]
@zhangnju Could you please try using buffer-based memory by setting the value for [`sycl_interop::memory_kind`](https://oneapi-src.github.io/oneDNN/enum_dnnl_sycl_interop_memory_kind.html#enum-dnnl-sycl-interop-memory-kind) to `buffer` when calling `sycl_interop::make_memory()` function? The is more introduction to oneDNN object Memory in [DPC++ Interoperability](https://oneapi-src.github.io/oneDNN/dev_guide_dpcpp_interoperability.html) and an example for it is [here](https://github.com/oneapi-src/oneDNN/blob/main/examples/sycl_interop_buffer.cpp#L134-L135).

**Comment by zhangnju** [comment]
@shu1chen Thanks for your info. I have been able to run oneDNN on AMD GPU successfully

**Comment by shu1chen** [comment]
@vpirogov I think it might be the test device specific and some devices don't support shared USM allocation. There is an assertion `DevImpl->has(sycl::aspect::usm_shared_allocations)` in line 148 in [usm_impl.cpp](https://intel.github.io/llvm-docs/doxygen/usm__impl_8cpp_source.html) and it throws the error "Device does not support shared USM allocations!" when it's not supported by the device. 
```
   if (Kind == alloc::device &&
       !DevImpl->has(sycl::aspect::usm_device_allocations)) {
     throw sycl::exception(sycl::errc::feature_not_supported,
                           "Device does not support USM device allocations!");
   }
   if (Kind == alloc::shared &&
       !DevImpl->has(sycl::aspect::usm_shared_allocations)) {
     throw sycl::exception(sycl::errc::feature_not_supported,
                           "Device does not support shared USM allocations!");
   }
```
There is an [issue #11747 in intel llvm repo](https://github.com/intel/llvm/issues/11747) also mentioning a device which does not have the `usm_shared_allocations` aspect.
Do you think it's necessary to add some assertions in oneDNN and advise users to switch to buffer-based memory in the doc when the usm allocations are not available?

**Comment by densamoilov** [comment]
@shu1chen, we could do that but I would prefer not to because using oneDNN with SYCL runtime requires users to be familiar with both SYCL and oneDNN programming models. Because of that, I would expect the users to know how to work with memory on different devices because it is not a oneDNN specific thing.

**Comment by shu1chen** [comment]
> We could extend verbose capabilities to share more details on why oneDNN API for creating a memory object failed.

@densamoilov Great idea! Thanks! I have created an internal feature request for this verbose capability

**Comment by feixuedudiao** [comment]
@shu1chen when used the sycl at oneDnn, can i only see how to use the memery with sycl?

**Comment by shu1chen** [comment]
> when used the sycl at oneDnn, can i only see how to use the memery with sycl?

@feixuedudiao I didn't understand this question, could you please provide a more detailed explanation? Or, please provide an example to better explain your question.
In addition, if your question is not related to this closed issue, could you please submit a new issue so that we can better track it?

**Comment by feixuedudiao** [comment]
@shu1chen Thanks, I will submit a new issue.
