### ISSUE TITLE
why the result of eltwise_hardswish is zero?

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1816]
Hi, When i test the active function with eltwise_hardswish for eltwise.cpp, the values are zero. The principle of the official document is consistent with that of pytorch, but the results are different. The code of test see above:
void eltwise_example(dnnl::engine::kind engine_kind) {

    // Create execution dnnl::engine.
    dnnl::engine engine(engine_kind, 0);

    // Create dnnl::stream.
    dnnl::stream engine_stream(engine);

    // Tensor dimensions.
    const memory::dim N = 3, // batch size
            IC = 3, // channels
            IH = 227, // tensor height
            IW = 227; // tensor width

    // Source (src) and destination (dst) tensors dimensions.
    memory::dims src_dims = {N, IC, IH, IW};
    memory::dims dst_dims = {N, IC, IH, IW};

    // Allocate buffers. In this example, out-of-place primitive execution is
    // demonstrated since both src and dst are required for later backward
    // propagation.
    std::vector<float> src_data(product(src_dims));
    std::vector<float> dst_data(product(dst_dims));

    // Initialize src tensor.
    std::generate(src_data.begin(), src_data.end(), []() {
        static int i = 0;
        return std::cos(i++ / 10.f);
    });

    // Create src and dst memory descriptors and memory objects.
    auto src_md = memory::desc(src_dims, dt::f32, tag::nchw);
    auto dst_md = memory::desc(dst_dims, dt::f32, tag::nchw);

    auto src_mem = memory(src_md, engine);
    auto dst_mem = memory(dst_md, engine);

    // Write data to memory object's handle.
    write_to_dnnl_memory(src_data.data(), src_mem);

    // Create primitive descriptor.
    auto eltwise_pd = eltwise_forward::primitive_desc(engine,
            prop_kind::forward_inference, algorithm::eltwise_hardswish, src_md,
            dst_md, 0.f, 0.f);

    // Create the primitive.
    auto eltwise_prim = eltwise_forward(eltwise_pd);

    // Primitive arguments.
    std::unordered_map<int, memory> eltwise_args;
    eltwise_args.insert({DNNL_ARG_SRC, src_mem});
    eltwise_args.insert({DNNL_ARG_DST, dst_mem});

    // Primitive execution: element-wise (ReLU).
    eltwise_prim.execute(engine_stream, eltwise_args);

    // Wait for the computation to finalize.
    engine_stream.wait();

    // Read data from memory object's handle.
    read_from_dnnl_memory(dst_data.data(), dst_mem);
}
the input data :
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/c462afac-66ca-459f-8f92-4d81a51dd163)

the output data:
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/73e9574b-681f-4919-a336-2b8b294e3c9e)

**Comment by feixuedudiao** [comment]
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/f1f32b01-233c-49b0-a066-6de54bfbe4f9)
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/7d484a8a-2f3b-4bd1-9956-1c59c1583ab9)

**Comment by feixuedudiao** [comment]
When alpha is set to 1.0 and beta is set to 0.0, the result is as follows. How to understand the use of beta and alpha parameters? What are the maximum and minimum values? That is, the upper and lower limits of the two parameters.
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/d4be1be8-1638-4400-b28b-cb0de1503af4)
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/dbffdabb-3438-4007-a3ea-c5a31fb14ca0)

**Comment by dzarukin** [comment]
> ![图片](https://private-user-images.githubusercontent.com/1230847/309162153-f1f32b01-233c-49b0-a066-6de54bfbe4f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTc5MjcsIm5iZiI6MTcwOTMxNzYyNywicGF0aCI6Ii8xMjMwODQ3LzMwOTE2MjE1My1mMWYzMmIwMS0yMzNjLTQ5YjAtYTA2Ni02ZGU1NGJmYmU0ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTgyNzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWEzYjAxZWEwOTY2NGRiN2YzZTJiMjU4YjgyMGY5OWE2M2U4ODNkZDAwNTY4OTIxOTg4ZDRiYTcxNTY3MzA1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gq6ojLe66jEBkMCCrIg9L7bOmR4GUX3TAPYcAjqNIt8) ![图片](https://private-user-images.githubusercontent.com/1230847/309162357-7d484a8a-2f3b-4bd1-9956-1c59c1583ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTc5MjcsIm5iZiI6MTcwOTMxNzYyNywicGF0aCI6Ii8xMjMwODQ3LzMwOTE2MjM1Ny03ZDQ4NGE4YS0yZjNiLTRiZDEtOTk1Ni0xYzU5YzE1ODNhYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTgyNzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDYwOTJjMDVmNjkxOTkwNDJhZmM5OGVkZGQwMzFiNjZhMTE5N2EyMzFmMjRiOWFmYzFkYWIzMDkzYWQ2NjllMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nn3yMvLQyN37QN5v9_kAOrsGOMP9BmW4uylSWV2Zm_o)

This refers to Graph API page, not the primitive one, and it has a different definition from what the primitive provides.
Here's the doc page for eltwise primitive: https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html

You'll see the proper formula for hardswish algorithm which relies on alpha and beta.

**Comment by feixuedudiao** [comment]
thank very much to answer, but i can not see the result of picture for Graph API.

**Comment by shu1chen** [comment]
@feixuedudiao Graph APIs have different usage models. If you are interested in calling Graph APIs, please refer to the example [Getting started on CPU with Graph API](https://oneapi-src.github.io/oneDNN/page_graph_cpu_getting_started_cpp.html#doxid-graph-cpu-getting-started-cpp) for details. For Hardswish usage in Graph API, there is also unit test example in [test_eltwise.cpp](https://github.com/oneapi-src/oneDNN/blob/main/tests/gtests/graph/unit/backend/dnnl/test_eltwise.cpp#L387-#L396).

**Comment by shu1chen** [comment]
@feixuedudiao Has your question been resolved? I will close this issue in 7 days if there is no more update.

**Comment by feixuedudiao** [comment]
tks，it had been resolved, it is the problem that the value of alpha should be 0.166667, and the value of beta should be 0.5。

**Comment by shu1chen** [comment]
Great! Thanks for the update and confirmation.
