### ISSUE TITLE
test_benchdnn_modeC_softmax_ci_cpu fails due to F16 accumulation

### ISSUE THREAD

**Issue by jondea** [oneapi-src/oneDNN#1819]
# Summary
`test_benchdnn_modeC_softmax_ci_cpu` is failing since 6727bbe8fe4217c8ec8982a9c1e975a6b75f81fb due to the F16 softmax threshold now being set to 0. ACL uses F16 accumulation in its F16 softmax (and most other F16 kernels) so this causes a failure. There's a couple of potential fixes for this:

1. Relax threshold for AArch64 until https://github.com/oneapi-src/oneDNN/pull/1540 goes in and we can properly specify the accumulation behavior
2. Disable the ACL softmax impl. This is obviously less preferable because it would cause a regression for end users. As far as I know, the only users of this implementation are people doing inference, where accumulating with F16 is less of a problem.

# Version
oneDNN v3.5. First bad commit: 6727bbe8fe4217c8ec8982a9c1e975a6b75f81fb, still failing on current main: 376c1792089273d5435ce767208dfdc452bf0607

# Environment
* CPU make and model: Graviton 3 (C7g). Crucially it is an AArch64 CPU with F16 support
* Built with ACL main (306a8a9fb0dacd2c1e5d65f76420c12162203986) although failure is present when built with v23.11 too. `ACL_ROOT_DIR=../ComputeLibrary/ cmake .. -DCMAKE_BUILD_TYPE=Release -DDNNL_AARCH64_USE_ACL=1 -DDNNL_BUILD_FOR_CI=ON -DONEDNN_BUILD_GRAPH=0 -DDNNL_ENABLE_JIT_PROFILING=0`

# Steps to reproduce
```
ACL_ROOT_DIR=../ComputeLibrary/ cmake .. -DCMAKE_BUILD_TYPE=Release -DDNNL_AARCH64_USE_ACL=1 -DDNNL_BUILD_FOR_CI=ON -DONEDNN_BUILD_GRAPH=0 -DDNNL_ENABLE_JIT_PROFILING=0
make -j`nproc`
ctest -R test_benchdnn_modeC_softmax_ci_cpu
```

# Observed behavior
Test fails (16 failures)
```
123: 752:FAILED (errors:41 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --axis=0 --inplace=true 255x10_n"softmax_ci_0d:1"
123: 753:FAILED (errors:41 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --axis=0 255x10_n"softmax_ci_0d:1"
123: 756:FAILED (errors:26 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --alg=LOGSOFTMAX --axis=0 --inplace=true 255x10_n"softmax_ci_0d:1"
123: 757:FAILED (errors:26 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --alg=LOGSOFTMAX --axis=0 255x10_n"softmax_ci_0d:1"
123: 760:FAILED (errors:41 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --stag=axb --axis=0 --inplace=true 255x10_n"softmax_ci_0d:1"
123: 761:FAILED (errors:41 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --stag=axb --axis=0 255x10_n"softmax_ci_0d:1"
123: 764:FAILED (errors:26 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --stag=axb --alg=LOGSOFTMAX --axis=0 --inplace=true 255x10_n"softmax_ci_0d:1"
123: 765:FAILED (errors:26 total:2550) __REPRO: --softmax --sdt=f16 --ddt=f16 --stag=axb --alg=LOGSOFTMAX --axis=0 255x10_n"softmax_ci_0d:1"
123: 1266:FAILED (errors:2046 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --inplace=true 2x19x17x13_n"softmax_ci_2d:0"
123: 1267:FAILED (errors:2046 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 2x19x17x13_n"softmax_ci_2d:0"
123: 1268:FAILED (errors:2096 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --alg=LOGSOFTMAX --axis=0 --inplace=true 2x19x17x13_n"softmax_ci_2d:0"
123: 1269:FAILED (errors:2096 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --alg=LOGSOFTMAX --axis=0 2x19x17x13_n"softmax_ci_2d:0"
123: 1270:FAILED (errors:993 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --alg=LOGSOFTMAX --inplace=true 2x19x17x13_n"softmax_ci_2d:0"
123: 1271:FAILED (errors:993 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --alg=LOGSOFTMAX 2x19x17x13_n"softmax_ci_2d:0"
123: 1276:FAILED (errors:2096 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --stag=axb --alg=LOGSOFTMAX --axis=0 --inplace=true 2x19x17x13_n"softmax_ci_2d:0"
123: 1277:FAILED (errors:2096 total:8398) __REPRO: --softmax --sdt=f16 --ddt=f16 --stag=axb --alg=LOGSOFTMAX --axis=0 2x19x17x13_n"softmax_ci_2d:0"
```

**Comment by dzarukin** [comment]
Hi @jondea, relaxing condition for Aarch64 is fine with me. Disabling softmax is not a good deal for Aarch64 users. Could you raise a PR for it, please?

**Comment by vpirogov** [comment]
I believe in long term option (1) suggested by @jondea makes the most sense. Support for accumulation data type [is available](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_accumulation_mode.html) in oneDNN v3.4.
