### ISSUE TITLE
Check timings of assembly level instructions 

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#1820]
Hello,
How to check timing of JITed assembly level instructions at execution time? Since JITed code have generation phase and execution phase, how to check time at execution phase?

**Comment by dzarukin** [comment]
Hi @vineel96, ONEDNN_VERBOSE=1 ([doc page](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html)) would should the execution time of the primitive. It will contain the kernel time execution plus some small preparation overhead to call the kernel.

**Comment by vineel96** [comment]
Hi @dzarukin , Thanks for the reply. But i wanted to know the timings of each jited assembly instructions that are present inside primitive. For example, MOV instruction and such.

**Comment by dzarukin** [comment]
Those are documented in the Intel Optimization Guide, each instruction with latency and throughput. oneDNN doesn't provide that information.

**Comment by shu1chen** [comment]
@vineel96 You may use some profiling tools like [Intel® VTune™ Profiler](https://www.intel.com/content/www/us/en/developer/tools/oneapi/vtune-profiler.html) for the assembly level analysis, e.g. in [Source Code Analysis](https://www.intel.com/content/www/us/en/docs/vtune-profiler/user-guide/2024-0/viewing-source.html).

**Comment by vineel96** [comment]
Thanks @shu1chen. Any such tool for arm machines?

**Comment by shu1chen** [comment]
> Any such tool for arm machines?
@vineel96 Sorry, I have no experience using similar tools on arm machines

**Comment by igorsafo** [comment]
> Thanks @shu1chen. Any such tool for arm machines?

@jondea @cfRod Could you help please?

**Comment by shu1chen** [comment]
@jondea @cfRod Do you perhaps have any suggestions for assembly level profiling tools on arm machines?

**Comment by cfRod** [comment]
Hi, there are a couple of options to get the latency per assembly: 

1. using perf + using a software optimisation guide for e.g https://developer.arm.com/documentation/pjdoc466751330-9685/latest/ 
2. llvm-mca, this is an external tool https://www.llvm.org/docs/CommandGuide/llvm-mca.html. @jondea for more info on this.
3. Streamline performance analyser https://developer.arm.com/Tools%20and%20Software/Streamline%20Performance%20Analyzer 
Can you give us some background about what you are trying to do? Thanks!

**Comment by jondea** [comment]
Once you have a small assembly snippet of your hot loop, llvm-mca will give information about latency/throughput bottlenecks of the different instruction pipelines (as detailed in the software optimisation guide). It is a simplification that mostly just considers latency and throughput of instructions (so will not model cache levels or branch predictors), so it won't be 100% correct, but it may be able to give you some insights. It also only has models for a few Arm CPUs.
