### ISSUE TITLE
How to use coverage.cmake file

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#1826]
How to use coverage.cmake file (https://github.com/oneapi-src/oneDNN/blob/main/cmake/coverage.cmake) to remove any unused steps in onednn code?

**Comment by shu1chen** [comment]
@vineel96 I'm not sure if I understand your question correctly. Are you trying to exclude some source files from ctest coverage output, like the macro [CTEST_CUSTOM_COVERAGE_EXCLUDE](https://cmake.org/cmake/help/latest/variable/CTEST_CUSTOM_COVERAGE_EXCLUDE.html) supported by cmake?

**Comment by vineel96** [comment]
@shu1chen, Yes similar to gcov tool. I wanted to remove any unused codes when we run a primitive. Example if I run oneDNN's matmul code, it should identify out of all oneDNN's matmul code which functions or code files are not used for any kind of input. So coverage.cmake file is used for this purpose ?

**Comment by shu1chen** [comment]
@vineel96 No, I think it's not for the purpose you mentioned. As seen in the [source code](https://github.com/oneapi-src/oneDNN/blob/main/cmake/coverage.cmake), coverage.cmake gets gcov tool involved, which helps to report the test code coverage.
There are some cross-dependencies in the source code and usually the oneDNN library is used as a full library. Can you explain why you want to remove the unused code? Is it to reduce the size of the binary?
I'm not aware of any tool/script that can automatically delete unused code. To reduce the code, it usually relies on developers who have a thorough understanding of the entire code base. Copy @vpirogov to see if there is any tool for this purpose

**Comment by vpirogov** [comment]
oneDNN has [build options](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html) to disable unused functionality:
* `ONEDNN_ENABLE_WORKLOAD` allows to disable training functionality for inference cases
* `ONEDNN_ENABLE_PRIMITIVE` allows to choose specific primitives (functions) and disable the rest
* `ONEDNN_ENABLE_PRIMITIVE_CPU_ISA` and `ONEDNN_ENABLE_PRIMITIVE_GPU_ISA` allow to drop unused targets
* `ONEDNN_ENABLE_GEMM_KERNELS_ISA` allows to drop legacy JIT GEMM kernels

**Comment by shu1chen** [comment]
No updates for a week and no open questions in this thread. Closing this issue as completed
