### ISSUE TITLE
Add option to disable python 2.7 finding via docs

### ISSUE THREAD

**Issue by ilya-lavrenov** [oneapi-src/oneDNN#1829]
See https://github.com/conda-forge/openvino-feedstock/issues/83

Currently, oneDNN unconditionally finds python 2.7 as exampled above:
https://github.com/oneapi-src/oneDNN/blob/6f8a5480516cf0380137f2f89984e0e4bab81127/cmake/Sphinx.cmake#L25

Let's add something similar to 
https://github.com/oneapi-src/oneDNN/blob/6f8a5480516cf0380137f2f89984e0e4bab81127/cmake/Doxygen.cmake#L20-L27
To disable python search. Good projects even provide special option `BUILD_DOCS` to control such behavior.

**Comment by vpirogov** [comment]
Yeah, an option to disable building documentation makes sense.

Could you please elaborate on how oneDNN finding Python 2.7 breaks OpenVINO?

**Comment by vpirogov** [comment]
+@igorsafo

**Comment by ilya-lavrenov** [comment]
> Could you please elaborate on how oneDNN finding Python 2.7 breaks OpenVINO?

It does not break, just one of our open source users noted that non-required dependency was found.

**Comment by vpirogov** [comment]
Got it, thanks!

**Comment by igorsafo** [comment]
@ilya-lavrenov The changes landed into the repository with the documentation disabled when oneDNN is a sub-project (34cc579).
