### ISSUE TITLE
why the result shape of conv  is not same with input 

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1833]
The convolution input parameters of onednn and porch are the same, and the data fed to the convolution is also the same. However, the shape of the result inferred by onednn convolution is different from that of pytorch. The input format is nchw, but the data format of the result inferred by onednn is nhwc, why. The onednn convolution code is as follows:
void convolution_example(dnnl::engine::kind engine_kind) {

    // Create execution dnnl::engine.
    dnnl::engine engine(engine_kind, 0);

    // Create dnnl::stream.
    dnnl::stream engine_stream(engine);

    // Tensor dimensions.

    // Source (src), weights, bias, and destination (dst) tensors
    // dimensions.

    memory::dims src_dims = {1, 4, 224, 384};
    memory::dims weights_dims = {32, 4, 3, 3};
    memory::dims bias_dims = {32};
    memory::dims dst_dims = {1, 32, 112, 192};

    // Strides, padding dimensions.
    memory::dims strides_dims = {2, 2};
    memory::dims padding_dims_l = {1, 1};
    memory::dims padding_dims_r = {1, 1};

    // Allocate buffers.
    std::vector<float> src_data(product(src_dims));
    std::vector<float> weights_data(product(weights_dims));
    std::vector<float> bias_data(product(bias_dims));
    std::vector<float> dst_data(product(dst_dims));
	// Initialize src, weights, and dst tensors.
    std::generate(src_data.begin(), src_data.end(), []() {
        static int i = 0;
        return std::cos(i++ / 10.f);
    });
    std::generate(weights_data.begin(), weights_data.end(), []() {
        static int i = 0;
        return std::sin(i++ * 2.f);
    });
    std::generate(bias_data.begin(), bias_data.end(), []() {
        static int i = 0;
        return std::tanh(float(i++));
    });

    //memset(&src_data[0], 0, src_data.size() / 3 * sizeof(float));

    // Create memory objects for tensor data (src, weights, dst). In this
    // example, NCHW layout is assumed for src and dst, and OIHW for weights.
    auto user_src_mem = memory({src_dims, dt::f32, tag::nchw}, engine);
    auto user_weights_mem = memory({weights_dims, dt::f32, tag::oihw}, engine);
    auto user_dst_mem = memory({dst_dims, dt::f32, tag::nchw}, engine);

    std::vector<std::unordered_map<int, memory>> conv_args;
    std::vector<primitive> convs;

    // Create memory descriptors with format_tag::any for the primitive. This
    // enables the convolution primitive to choose memory layouts for an
    // optimized primitive implementation, and these layouts may differ from the
    // ones provided by the user.
    auto conv_src_md = memory::desc(src_dims, dt::f32, tag::any);
    auto conv_weights_md = memory::desc(weights_dims, dt::f32, tag::any);
    auto conv_dst_md = memory::desc(dst_dims, dt::f32, tag::any);

    // Create memory descriptor and memory object for input bias.
    auto user_bias_md = memory::desc(bias_dims, dt::f32, tag::a);
    auto user_bias_mem = memory(user_bias_md, engine);

    // Write data to memory object's handle.
    write_to_dnnl_memory(src_data.data(), user_src_mem);
    write_to_dnnl_memory(weights_data.data(), user_weights_mem);
    write_to_dnnl_memory(bias_data.data(), user_bias_mem);

    // Create primitive post-ops (ReLU).
    const float alpha = 0.166667f;
    const float beta = 0.5f;
    post_ops conv_ops;
    //conv_ops.append_eltwise(algorithm::eltwise_hardswish, alpha, beta);
    primitive_attr conv_attr;
    conv_attr.set_post_ops(conv_ops);

    // Create primitive descriptor.
 
  
   auto conv_pd = convolution_forward::primitive_desc(engine,
        prop_kind::forward_inference, algorithm::convolution_direct,
        conv_src_md, conv_weights_md, user_bias_md, conv_dst_md,
        strides_dims, padding_dims_l, padding_dims_r, conv_attr);

    // For now, assume that the src, weights, and dst memory layouts generated
    // by the primitive and the ones provided by the user are identical.
    auto conv_src_mem = user_src_mem;
    auto conv_weights_mem = user_weights_mem;
    auto conv_dst_mem = user_dst_mem;

    // Reorder the data in case the src and weights memory layouts generated by
    // the primitive and the ones provided by the user are different. In this
    // case, we create additional memory objects with internal buffers that will
    // contain the reordered data. The data in dst will be reordered after the
    // convolution computation has finalized.
	
    if (conv_pd.src_desc() != user_src_mem.get_desc()) {
        conv_src_mem = memory(conv_pd.src_desc(), engine);
        auto rd = reorder(user_src_mem, conv_src_mem);
        convs.push_back(rd);
        conv_args.push_back({{DNNL_ARG_FROM, user_src_mem},
                           {DNNL_ARG_TO,  conv_src_mem}});
                //.execute(engine_stream, user_src_mem, conv_src_mem);
    }
	
	

    if (conv_pd.weights_desc() != user_weights_mem.get_desc()) {
        conv_weights_mem = memory(conv_pd.weights_desc(), engine);
        reorder(user_weights_mem, conv_weights_mem)
                .execute(engine_stream, user_weights_mem, conv_weights_mem);
    }

    if (conv_pd.dst_desc() != user_dst_mem.get_desc()) {
        conv_dst_mem = memory(conv_pd.dst_desc(), engine);
    }

    // Create the primitive.
    auto conv_prim = convolution_forward(conv_pd);

    // Primitive arguments.
    conv_args.push_back({{DNNL_ARG_SRC, conv_src_mem},
                        {DNNL_ARG_WEIGHTS, conv_weights_mem},
                     { DNNL_ARG_BIAS, user_bias_mem},
                    { DNNL_ARG_DST, conv_dst_mem}});
    // Primitive execution: convolution with ReLU.
    //conv_prim.execute(engine_stream, conv_args);
    convs.push_back(conv_prim);

    auto hd_swish_pd
            = eltwise_forward::primitive_desc(engine, prop_kind::forward_inference,
                    algorithm::eltwise_hardswish, conv_dst_mem.get_desc(),
                    conv_dst_mem.get_desc(), alpha, beta);

    convs.push_back(eltwise_forward(hd_swish_pd));
    conv_args.push_back({{DNNL_ARG_SRC, conv_dst_mem},
            {DNNL_ARG_DST, conv_dst_mem}});
	
    for(int i = 0; i < convs.size(); i++)
    {
		convs.at(i).execute(engine_stream, conv_args.at(i));
		std::unordered_map<int,memory> dstVecMem = conv_args.at(i);
        std::string resPath = "conv_result_";
         resPath += std::to_string(i);
		 
        resPath += std::to_string(i) + "_";
		int j = 0 ;
        for(auto it = dstVecMem.begin(); it != dstVecMem.end(); it++)
        {
           j = it->first;
           memory dst_mem = it->second;
           std::string fnlResPath = resPath   + std::to_string(j);

           std::ofstream resStream(fnlResPath + ".txt", std::ios::binary);
           int flag = resStream.is_open();
           if (!flag)
           {
               std::cout <<"failed to open file !"<< std::endl;
           }

           const_dnnl_memory_desc_t md;
           dnnl_memory_get_memory_desc(dnnl_memory_t(dst_mem), &md);
           size_t memSz = dnnl_memory_desc_get_size(md);
           std::vector<float> resVecF(memSz / sizeof(float));
           read_from_dnnl_memory(resVecF.data(), dst_mem);

           for (auto v : resVecF) {
            resStream << v << std::endl;
           }
           resStream.close();

        }

    }
    // Reorder the data in case the dst memory descriptor generated by the
    // primitive and the one provided by the user are different.
    if (conv_pd.dst_desc() != user_dst_mem.get_desc()) {
        reorder(conv_dst_mem, user_dst_mem)
                .execute(engine_stream, conv_dst_mem, user_dst_mem);
    } else
        user_dst_mem = conv_dst_mem;

    // Wait for the computation to finalize.
    engine_stream.wait();

    // Read data from memory object's handle.
    read_from_dnnl_memory(dst_data.data(), conv_dst_mem);
}

the result of conv inference with onednn is :
[test_infer_result_2_0_17.txt](https://github.com/oneapi-src/oneDNN/files/14599071/test_infer_result_2_0_17.txt)
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/532429f1-d779-4436-9fd6-19da2cbc8e49)
the result of conv with pytorch is:
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/c246e417-3f1b-40fa-9f99-faed46bf3a63)

**Comment by yehudaorel** [comment]
Hi @feixuedudiao, given that you are doing a reorder check at the end, the output memory format should be aligned with user_dst mem format (NCHW in this case). Could you provide a [oneDNN verbose log](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html) by running the workload using the following: 

`$ ONEDNN_VERBOSE=all ./convolution > verbose_log.txt`

Please attach the full verbose log, if you could also get the verbose log from the pytorch workload as well it will be helpful.
Thank you!

**Comment by shu1chen** [comment]
@feixuedudiao I took a look at your code and found that ``dst_data`` was read from ``conv_dst_mem``, instead of ``user_dst_mem`` at the code line ``read_from_dnnl_memory(dst_data.data(), conv_dst_mem);``. That might be the reason.
Also, as @yehudaorel suggested, it's usually easier to identify the problem by comparing the oneDNN verbose log. Please provide the verbose log if you need our assistance.

**Comment by shu1chen** [comment]
Closing due to no updates for a week and no open questions in this thread. Please feel free to add a new issue or reopen it if further assistance is needed
