### ISSUE TITLE
how to link the dnnl library from a git submodule build

### ISSUE THREAD

**Issue by Ravenwater** [oneapi-src/oneDNN#1837]
I am pulling oneDNN source code as a git submodule but I am unable to pull in the library asset.

In the CMakeList.txt configuration for the executable that depends on the dnnl library, I have a simple matmul performance test with a CMakeList.txt segment to create the library and link the result:

```
add_subdirectory(${WLC_ROOT_DIR}/ext/intel/oneapi-src/oneDNN build)
add_executable(onednn_matmul performance/matmul_perf.cpp)
target_link_libraries(onednn_matmul PRIVATE ${DNNL_LIBRARY_NAME})
```
The dnnl is built, but it is not associated correctly by the target_link_libraries() call.

I tried to explicitly move the built asset to a known location that is already linked into the build configuration defined by the variable ${WLC_INSTALL_LIB_DIR}.
```
add_subdirectory(${WLC_ROOT_DIR}/ext/intel/oneapi-src/oneDNN build)
message(STATUS "Installing ${DNNL_LIBRARY_NAME} library to ${WLC_INSTALL_LIB_DIR}")
install(TARGETS ${DNNL_LIBRARY_NAME} DESTINATION ${WLC_INSTALL_LIB_DIR})

add_executable(onednn_matmul performance/matmul_perf.cpp)
target_link_libraries(onednn_matmul PRIVATE ${DNNL_LIBRARY_NAME})
```
that didn't work either as the intended copy didn't happen.

What is the cmake pattern that I need to use to link the built dnnl library?

**Comment by shu1chen** [comment]
@Ravenwater ``add_subdirectory`` is supposed to work. A possible reason might be in ``${DNNL_LIBRARY_NAME}``. The dynamic oneDNN library name is ``libdnnl.so``. Could you please try to replace ``${DNNL_LIBRARY_NAME}`` with ``dnnl``?
I have a project which also adds oneDNN source code as a git submodule and the [CMakeList.txt](https://github.com/shu1chen/gemmBench/blob/cpu_gemm_matmul/CMakeLists.txt) there works well for me. You may refer to it.

**Comment by Ravenwater** [comment]
@shu1chen I see that the location where the dnnl library gets build is not where it is expected:

![image](https://github.com/oneapi-src/oneDNN/assets/466641/a5ecb224-7899-4074-a794-1701590ed5d7)

It is linked to `build/src/Release/dnnl.lib`, but it is produced in `build/src/dnn/onednn/build/src/Release/dnnl.lib`. The prefix `build/src/dnn/onednn` is the project that contains the project that we are building.

**Comment by Ravenwater** [comment]
not feeling much love from oneAPI here:

The CMakeList.txt file to build the executable and the dnnl lib:
```
add_subdirectory(${WLC_ROOT_DIR}/ext/intel/oneapi-src/oneDNN dnnlbuild)

add_executable(onednn_matmul performance/matmul_perf.cpp)
target_link_libraries(onednn_matmul PUBLIC dnnl)
```

The linker config generated is:
![image](https://github.com/oneapi-src/oneDNN/assets/466641/20a6b963-d41a-4809-9972-5d7e1c45f805)

And the dnnl project generated is:
![image](https://github.com/oneapi-src/oneDNN/assets/466641/3388f2e3-56fc-406f-bfdf-04d81e95ee13)

![image](https://github.com/oneapi-src/oneDNN/assets/466641/e73a8f0e-f3e1-4d58-824d-6dfd51f89a1f)


The target_link_libraries invoked in the executable cmake file seems to ignore the fact that the lib is built relative to the executable. It is looking for the lib `dnnlbuild\src\Release\dnnl.lib` whereas the lib is built at `${WLC_ROOT_DIR}\build\src\dnn\onednn\dnnlbuild\src\Release\dnnl.lib`

Is that a configuration issue, or is that a variable propagation issue?

**Comment by vpirogov** [comment]
Hi @Ravenwater, 

CMake's MSVS project generator is a bit finnicky and behavior you see ay depend on MSVS and CMake versions. I managed to build and link oneDNN as subproject succesfully with MSVS 2019 using [CMakefile from our subproject test](https://github.com/oneapi-src/oneDNN/blob/main/tests/other/subproject/CMakeLists.txt):
```
>cmake ..
<snip>
>cmake --build .
<snip>
>dir Debug
 Volume in drive C is OSDisk
 Volume Serial Number is F0AB-57AB

 Directory of c:\work\oneDNN\tests\other\subproject\build\Debug

03/22/2024  05:13 PM    <DIR>          .
03/22/2024  05:13 PM    <DIR>          ..
03/22/2024  05:13 PM            53,760 project_app.exe
03/22/2024  05:13 PM           995,328 project_app.pdb
               2 File(s)      1,049,088 bytes
               2 Dir(s)  237,280,186,368 bytes free

>dir oneDNN\src\Debug
 Volume in drive C is OSDisk
 Volume Serial Number is F0AB-57AB

 Directory of c:\work\oneDNN\tests\other\subproject\build\oneDNN\src\Debug

03/22/2024  05:13 PM    <DIR>          .
03/22/2024  05:13 PM    <DIR>          ..
03/22/2024  05:13 PM        83,203,584 dnnl.dll
03/22/2024  05:13 PM            60,472 dnnl.exp
03/22/2024  05:13 PM            99,380 dnnl.lib
03/22/2024  05:13 PM       286,961,664 dnnl.pdb
               4 File(s)    370,325,100 bytes
               2 Dir(s)  237,273,784,320 bytes free
```

I would recommend using Ninja generator (`-G Ninja`) unless MSVS project is absolutely necessary.

**Comment by Ravenwater** [comment]
@shu1chen this is not closed, as the example that @vpirogov provides only works inside the oneDNN tree. 

The issue reported is a bug in the oneDNN cmake design that prohibits integrating the oneDNN library in other cmake projects that pull the source via git submodules.

**Comment by vpirogov** [comment]
@Ravenwater, I cannot reproduce behavior you describe in any shape or form. If you believe there's a defect in oneDNN build system please provide `CMakefile.txt` you use and exact steps to reproduce.

**Comment by shu1chen** [comment]
@Ravenwater Since you insisted this is an issue in oneDNN, I tested with VS2022 Version 17.2.4 but still cannot reproduce the issue based on the info you provided. Do you have some special configuration that might cause the path to change?
Here are my steps:
1. In `CMakeLists.txt`:

```
# include oneDNN
set(DNNL_DIR "oneDNN")
add_subdirectory(${DNNL_DIR} dnnlbuild)
include_directories(${DNNL_DIR}/include)

add_executable(onednn_matmul main.cpp)
target_link_libraries(onednn_matmul PUBLIC dnnl)
```

2. Generate VS project:

```
cmake -G "Visual Studio 17 2022" ..
```
3. Compare the generated path:
![image](https://github.com/oneapi-src/oneDNN/assets/106653580/658448a5-73d1-430e-a876-4ca1ba14ff3f)
![image](https://github.com/oneapi-src/oneDNN/assets/106653580/7a19e8f6-7208-43d6-a6d9-6e950df45ad4)
It is looking for the lib `dnnlbuild\src\Release\dnnl.lib` and the lib is also built at `dnnlbuild\src\Release\dnnl.lib`.
