### ISSUE TITLE
'ONEDNN_VERBOSE' is not recognized at the windows cmd

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1842]
when i input "ONEDNN_VERBOSE=all ./convolution > verbose_log.txt" on the cmd of windows, it reports "'ONEDNN_VERBOSE' is not recognized as an internal or external command, operable program or batch file." why and how to solve it ? thanks.
![图片](https://github.com/oneapi-src/oneDNN/assets/1230847/5a22b963-9e67-48f4-87a9-af91759c4f62)

**Comment by vpirogov** [comment]
The command line you are using is for Linux. Windows syntax is a bit different:
```
set ONEDNN_VERBOSE=all
convolution.exe > verbose_log.txt
```

**Comment by feixuedudiao** [comment]
@vpirogov thanks
