### ISSUE TITLE
Core utilization on heterogeneous architectures

### ISSUE THREAD

**Issue by karlbnapf** [oneapi-src/oneDNN#1844]
I'm wondering how well oneDNN performs on Intel's hybrid processors with both performance and efficiency cores (e.g., Alder / Raptor Lake). Background: When distributing a workload among multiple cores, the data is typically partitioned into chunks of equal size. However, processing n chunks on n cores, where some of them are faster than others, will result in poor utilization. When using a work stealing scheduler, it would be better to make the chunks smaller, so that idle times of the performance cores are reduced. Does oneDNN partition tensors on its own or does it rely on TBB's / OpenMP's partitioning? Are there any experimental results or recommendations w.r.t. hybrid processors? Thanks!

**Comment by shu1chen** [comment]
By default, oneDNN relies OpenMP thrading on CPU. TBB or user-defined threading can be set through [`ONEDNN_CPU_RUNTIME`](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html#runtimes) when building oneDNN.
For hybrid processors, the decision on what cores to use is handled between threading runtime and OS, not by oneDNN itself. So please choose appropriate core type using methods provided by OS and threading runtime. The specific method varies between threading runtimes and operating systems. Some details are provided in [Configuring oneDNN for Benchmarking](https://oneapi-src.github.io/oneDNN/dev_guide_performance_settings.html) section of oneDNN developer guide.

**Comment by yehudaorel** [comment]
Hi @karlbnapf, in addition to what @shu1chen noted, for best performance in inferencing workload it is generally recommended to stick with one type of core, i.e either P or E cores per instance. You can do so with [numactl](https://linux.die.net/man/8/numactl) command for Linux and [setProcessAffinityMask](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setprocessaffinitymask) API for Windows. 

Here is an Linux example on how you can run your workload on P-Cores only:
Get the CPU id's for P-Cores (check for cores with hyper threading, easy tell is max frequency):
`$ lscpu --all --extended`

![image](https://github.com/oneapi-src/oneDNN/assets/111955825/3da8cc3f-a3cd-4b29-9e5b-a5f8775e8f66)

Use `numactl --physcpubind with P-Core` IDs found from step above:
```
$ export OMP_NUM_THREADS=16 # <--- Num of P-Cores
$ numactl --physcpubind=0-15 ./workload_script
```
