### ISSUE TITLE
Getting configuration error on RiscV Qemu: Only Sequential Runtime is now supported for a Risc-V CPU

### ISSUE THREAD

**Issue by anuphalarnkar** [oneapi-src/oneDNN#1848]
# Summary
I am using Risc-V Qemu running a Ubuntu 22.04.3 SiFive RiscV image. When I try to build with CMAKE, I am getting configuration error **Only Sequential Runtime is now supported for a Risc-V CPU**

# Version
Commit ID: 253af34a1700d8bd8e0025385c8953a354a22e05

# Environment
Qemu running Ubuntu 22.0.4.3 version of SiFive RiscV image
**Qemu Version: **
QEMU emulator version 6.2.0 (Debian 1:6.2+dfsg-2ubuntu6.17)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

**lscpu** 
Architecture:          riscv64
  Byte Order:          Little Endian
CPU(s):                8
  On-line CPU(s) list: 0-7
NUMA:
  NUMA node(s):        1
  NUMA node0 CPU(s):   0-7

**uname -a**
Linux ubuntu 6.5.0-26-generic #26.1~22.04.1-Ubuntu SMP Thu Mar 14 04:00:07 UTC 2024 riscv64 riscv64 riscv64 GNU/Linux

**gcc --version**
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

cmake --version
cmake version 3.22.1

**CMake Output Log:**

ubuntu@ubuntu:~/oneDNN/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/home/ubuntu/onednn_bins -DCMAKE_BUILD_TYPE=Release -DONEDNN_LIBRARY_TYPE=STATIC -DONEDNN_BUILD_DOC=OFF -DONEDNN_GPU_VENDOR=AMD

-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: RV64
-- DNNL compat: set DNNL_LIBRARY_TYPE to ONEDNN_LIBRARY_TYPE with value `STATIC`
-- DNNL compat: set DNNL_GPU_VENDOR to ONEDNN_GPU_VENDOR with value `AMD`
-- DNNL_LIBRARY_NAME: dnnl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Performing Test CAN_COMPILE_RVV_INTRINSICS
-- Performing Test CAN_COMPILE_RVV_INTRINSICS - Failed
-- Can compile RVV Intrinsics: FALSE
-- DNNL_RISCV_USE_RVV_INTRINSICS: FALSE
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE)
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2.7")
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Found Git: /usr/bin/git (found version "2.34.1")
-- Enabled testing coverage: CI
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Enabled GeMM kernels ISA: ALL
-- Primitive cache is enabled
CMake Error at src/cpu/rv64/CMakeLists.txt:36 (message):
  Only sequential runtime is now supported for a RISC-V CPU

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/oneDNN/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/oneDNN/build/CMakeFiles/CMakeError.log".

# Steps to reproduce
$> git clone  https://github.com/oneapi-src/oneDNN.git
$> cd oneDNN && git reset --hard 253af34a1700d8bd8e0025385c8953a354a22e05
$> mkdir build && cd build
$> cmake .. -DCMAKE_INSTALL_PREFIX=/home/ubuntu/onednn_bins -DCMAKE_BUILD_TYPE=Release -DONEDNN_LIBRARY_TYPE=STATIC -DONEDNN_BUILD_DOC=OFF -DONEDNN_GPU_VENDOR=AMD

**Comment by vpirogov** [comment]
Default value for [`ONEDNN_CPU_RUNTIME`](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html) build option is `OMP`. RISC-V implementation restricts supported runtime values to `SEQ`, so you should be able to build oneDNN with `ONEDNN_CPU_RUNTIME=SEQ`.

I don't know why this restriction exists, unfortunately. Maybe @pazamelin can provide some insights.

**Comment by vpirogov** [comment]
If OpenMP is a viable option for RISC-V feel free to open a PR to relax this restriction.

**Comment by anuphalarnkar** [comment]
Thanks for your support. I was able to compile and also run the tests under benchdnn.
