### ISSUE TITLE
can support  the fp16 or bf16 for cpu with 3.3.6 version?

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1849]
when i test the example of cnn-train-bf16 on the Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz, it prompts  "No bf16 convolution implementation is available for this platform". it shows the cpu only runs f32? 
thanks.
fei.

**Comment by shu1chen** [comment]
Hi, that's possibly because bf16 is not supported on the hardware. The [hardware limitations](https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html#hardware-limitations) session in oneDNN developer guide lists the minimal supported instruction set extension (ISA) for the data types. You may find the supported ISA in the [specification of Intel(R) Core(TM) i7-10700 CPU](https://ark.intel.com/content/www/us/en/ark/products/199316/intel-core-i7-10700-processor-16m-cache-up-to-4-80-ghz.html#tab-blade-1-0-7).

**Comment by feixuedudiao** [comment]
@shu1chen, i have a question, for [Intel(R) Core(TM) i7-10700 CPU], rumtime is how select with omp, tbb and seq? i test the performance with seq. but i feel th performance is not good.

**Comment by feixuedudiao** [comment]
@shu1chen i'm to try. thanks.

**Comment by feixuedudiao** [comment]
@shu1chen There have a question for omp_num_threads = 4, why set it to 4?

**Comment by shu1chen** [comment]
> There have a question for omp_num_threads = 4, why set it to 4?

@feixuedudiao It's an example. You may set the desired number of cores to use

**Comment by feixuedudiao** [comment]
oh, thanks. But how i can set the omp_nump_thread with the api in code. I find a function with get_num_cores, but don't fin set_num_cores.

**Comment by shu1chen** [comment]
> oh, thanks. But how i can set the omp_nump_thread with the api in code. I find a function with get_num_cores, but don't fin set_num_cores.

It might be omp_set_num_threads that you're looking for. Please see the [OpenMP Functions in the doc](https://learn.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-functions?view=msvc-170).

**Comment by feixuedudiao** [comment]
@shu1chen 
The function of omp_set_num_threads(4) is same to "set OMP_NUM_THREADS=4" for onednn?

**Comment by shu1chen** [comment]
> The function of omp_set_num_threads(4) is same to "set OMP_NUM_THREADS=4" for onednn?

Yes, oneDNN CPU relies on OpenMP threading in this case. Both `OMP_NUM_THREADS` and `omp_set_num_threads` are from OMP and they are supposed to be the same as shown in the [OpenMP Environment Variables](https://learn.microsoft.com/en-us/cpp/parallel/openmp/reference/openmp-environment-variables?view=msvc-170) link.

**Comment by feixuedudiao** [comment]
@shu1chen 
thanks. I look it as soon.
