### ISSUE TITLE
how can i close the verbose when running

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1853]
when i run the app of onednn program , it print  above inforamtion of verbose. I have close the ONEDNN_VERBOSE through the command of "set ONEDNN_VERBOSE=OFF" environment variable.

onednn_verbose,primitive,exec,cpu,binary,jit:uni,undef,src_f32::blocked:abcd::f0 src_f32::blocked:abcd::f0 dst_f32::blocked:abcd::f0,attr-post-ops:eltwise_hardswish:0.166667:0.5 ,alg:binary_add,1x32x56x96:1x32x56x96,0.0827
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcd::f0 dst_f32::blocked:acdb::f0,,,1x32x56x96,0.0749

**Comment by yehudaorel** [comment]
Hi @feixuedudiao, this seems to be an environment issue, could be the case that your code calls on [dnnl_set_verbose(int level)](https://oneapi-src.github.io/oneDNN/group_dnnl_api_service.html#doxid-group-dnnl-api-service-1ga14cc3b56337322e1e5132c5ee0c84856) which overrides `ONEDNN_VERBOSE` environment variable, can you verify that?

**Comment by feixuedudiao** [comment]
@yehudaorel . I have verified that my code can't call the dnn_set_verbose function, but i only close the environment variable.

**Comment by shu1chen** [comment]
@feixuedudiao Please try `set ONEDNN_VERBOSE=none` or `set ONEDNN_VERBOSE=0`. As shown in the [doc of verbose mode](https://oneapi-src.github.io/oneDNN/dev_guide_verbose.html#verbose-mode), `ONEDNN_VERBOSE=OFF` is for build-time control and `ONEDNN_VERBOSE=none` is for run-time control.

**Comment by yehudaorel** [comment]
Hi @feixuedudiao, were you able to get the issue resolved?
