### ISSUE TITLE
MSVC doesn't support -fsycl flag.

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1865]
when i compile the oneDnn with dpc++,  used the vs2022, Intel oneAPI DPC++/C++ 2024.0, and win10 system, it hapens this error at above, but i don't know why.
CALL "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat";
CALL "D:\Program Files (x86)\Intel\oneAPI\setvars.bat"
mkdir "cpu_cache_sycl_release_x64"
cd "cpu_cache_sycl_release_x64"
:: Set C and C++ compilers
set CC=icx
set CXX=icx
cmake -A x64 -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=release -DBUILD_SHARED_LIBS=OFF -DONEDNN_BUILD_GRAPH=OFF -DDNNL_CPU_RUNTIME=SYCL -DDNNL_GPU_RUNTIME=SYCL -DONEDNN_ENABLE_PRIMITIVE_CACHE=ON ..

cmake --build . --config Release

CALL "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat";                                                      
**********************************************************************                                                                               
** Visual Studio 2022 Developer Command Prompt v17.9.5                                                                                               
** Copyright (c) 2022 Microsoft Corporation                                                                                                          
**********************************************************************                                                                               
[vcvarsall.bat] Environment initialized for: 'x64'                                                                                                   
-- Building for: Visual Studio 17 2022                                                                                                               
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19042.                                                                          
-- The C compiler identification is MSVC 19.39.33523.0                                                                                               
-- The CXX compiler identification is MSVC 19.39.33523.0                                                                                             
-- Detecting C compiler ABI info                                                                                                                     
-- Detecting C compiler ABI info - done                                                                                                              
-- Check for working C compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped  
-- Detecting C compile features                                                                                                                      
-- Detecting C compile features - done                                                                                                               
-- Detecting CXX compiler ABI info                                                                                                                   
-- Detecting CXX compiler ABI info - done                                                                                                            
-- Check for working CXX compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features                                                                                                                    
-- Detecting CXX compile features - done                                                                                                             
-- DNNL_TARGET_ARCH: X64                                                                                                                             
-- DNNL compat: set DNNL_ENABLE_PRIMITIVE_CACHE to ONEDNN_ENABLE_PRIMITIVE_CACHE with value `ON`                                                     
-- DNNL_LIBRARY_NAME: dnnl                                                                                                                           
-- Performing Test SYCL_FLAG_SUPPORTED                                                                                                               
-- Performing Test SYCL_FLAG_SUPPORTED - Failed                                                                                                      
CMake Error at cmake/dpcpp_driver_check.cmake:36 (message):                                                                                          
  MSVC doesn't support -fsycl flag.                                                                                                                  
Call Stack (most recent call first):                                                                                                                 
  cmake/dpcpp_driver_check.cmake:60 (CHECK_COMPILER_DRIVER)                                                                                          
  cmake/SYCL.cmake:30 (include)                                                                                                                      
  CMakeLists.txt:118 (include)

**Comment by feixuedudiao** [comment]
This problem have been solved with above compile parmeter, it can compile sucessfully with vs2022, i reference this issue(https://community.intel.com/t5/Intel-oneAPI-Data-Parallel-C/Using-Intel-Compiler-2022-as-a-toolset-in-cmake-not-working/m-p/1415673?profile.language=zh-TW)
CALL "D:\Program Files (x86)\Intel\oneAPI\setvars.bat"
mkdir "cpu_cache_sycl_release_x64"
cd "cpu_cache_sycl_release_x64"
cmake -G "Visual Studio 17 2022" -T "Intel C++ Compiler 2024" -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DCMAKE_BUILD_TYPE=Debug -DDNNL_CPU_RUNTIME=SYCL -DDNNL_GPU_RUNTIME=SYCL -DDNNL_WITH_LEVEL_ZERO=1 ..
cmake --build . --config Release

**Comment by rupakroyintel** [comment]
@feixuedudiao Can we close this issue?

**Comment by feixuedudiao** [comment]
@rupakroyintel. Of course. Thanks.
