### ISSUE TITLE
Is this based opencl or intel dpc++ 

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1866]
Hi Mahler,

Thanks for your interest.

We developed GPU support in MKL-DNN in close cooperation with clDNN team. Due to our experiments, MKL-DNN demonstrate on par or better performance comparing to clDNN on Intel Graphics.

For example, we were able to run and validate accuracy of fp16 inference for ResNet-50 and Inception-V3 models using our internal version of IntelCaffe framework with experimental GPU support. On the Intel Iris Pro Graphics P580 (GT4e) GPUs, for batch sizes 32/64, we saw up to 180 fps on ResNet-50 (similar to clDNN-based inference) and up to 120 fps on Inception-V3 (~1.5x faster than clDNN).

Intel will be adding new optimizations for future CPU and GPU platforms into MKL-DNN, while clDNN library support will be limited to maintaining existing users.

Regards,
Konstantin

_Originally posted by @karturov in https://github.com/oneapi-src/oneDNN/issues/520#issuecomment-515523310_

**Comment by rupakroyintel** [comment]
@feixuedudiao It mostly depends on the specific hardware and the type of workload. Can you share some more details?

**Comment by feixuedudiao** [comment]
@rupakroyintel , thank you to answer. if i user it with gpu on i7-10700 cpu，which is great, opencl or dpc++?

**Comment by vpirogov** [comment]
@feixuedudiao,

Recommended GPU programming model for oneDNN is DPC++. However the choice between OpenCL or DPC++ is primarily defined by application needs and if you are enabling an application that runs with OpenCL you have an option to use oneDNN with OpenCL API and runtime for better interoperability. There's no material differences in performance between OpenCL and DPC++.

**Comment by feixuedudiao** [comment]
@vpirogov thanks.

**Comment by rupakroyintel** [comment]
Closing the issue for now.
