### ISSUE TITLE
undefined symbol: void __cdecl __itt_pt_mark_event(unsigned char) and error : undefined symbol: void __cdecl __itt_pt_mark(unsigned char)

### ISSUE THREAD

**Issue by feixuedudiao** [oneapi-src/oneDNN#1868]
When i build the oneDNN library with vs2022 for windows，it report "error : undefined symbol: void __cdecl __itt_pt_mark(unsigned char), undefined symbol: void __cdecl __itt_pt_mark_event". From the error message, we can find that the libraries of these two functions can not be linked,The cpu is Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90, and i have installed the tbb and opencl on pc . I don't know why. The cpu is the compile paramater is above:
mkdir "cpu_gpu_sycl_debug_x64"
cd "cpu_gpu_sycl_debug_x64"
cmake -G "Visual Studio 17 2022" -T "Intel C++ Compiler 2024" -DCMAKE_BUILD_TYPE=debug  -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DDNNL_CPU_RUNTIME=SYCL -DDNNL_GPU_RUNTIME=SYCL -DDNNL_WITH_LEVEL_ZERO=1 -DONEDNN_BUILD_GRAPH=OFF -DONEDNN_ENABLE_WORKLOAD=INFERENCE ..
cmake --build . --config Debug
cd ..
 

Fei . All best.

**Comment by vpirogov** [comment]
@feixuedudiao, Intel C++\DPC++ Compiler [does not support](https://www.intel.com/content/www/us/en/docs/dpcpp-cpp-compiler/developer-guide-reference/2024-1/use-cmake-with-the-compiler.html) CMake MSVS generator. This scenario works perfectly well with `-GNinja`. This is documented in [Build from Source](https://oneapi-src.github.io/oneDNN/dev_guide_build.html#id1) section of oneDNN Developer Guide.

**Comment by feixuedudiao** [comment]
@vpirogov Thanks. I'm to try it.
