### ISSUE TITLE
Security.md: replace incorrect email address

### ISSUE THREAD

**Issue by rozhukov** [oneapi-src/oneDNN#1876]
# Summary
In the Security.md file there is an incorrect email for Security reports: security@lists.uxlfoundation.org
Should be replaced by: **security@uxlfoundation.org**

# URLs
https://github.com/oneapi-src/oneDNN/blob/5476baec67b0d0a4fca41719000049a578341e4d/SECURITY.md?plain=1#L22

**Comment by vpirogov** [comment]
Thanks, @rozhukov! Fixed by 872062aa7c2bc71f8b64692b3d31f3708c41db67.
