### ISSUE TITLE
Build failure on AArch64 due to brgemm_matmul_t

### ISSUE THREAD

**Issue by jondea** [oneapi-src/oneDNN#1877]
# Summary
AArch64 build fails on 26ec08d60169fca60fb4d3b34dcb65c7328c7854 (succeeds on commit before 06331766d4f2638e35da3ba98aba6e2df3462401) with or without ACL. This should happen on on AArch64 core, although we have seen it on Neoverse N1 and V1 (AWS 6g and 7g).

```
/code/oneDNN/src/cpu/aarch64/matmul/brgemm_matmul.cpp:240:28: error: no matching function for call to 'precompute_scales'

    const float *oscales = precompute_scales(

                           ^~~~~~~~~~~~~~~~~

/code/oneDNN/src/cpu/aarch64/matmul/brgemm_matmul.cpp:1435:17: note: in instantiation of member function 'dnnl::impl::cpu::aarch64::matmul::brgemm_matmul_t<dnnl::impl::cpu::aarch64::sve_512>::execute_body' requested here

template struct brgemm_matmul_t<sve_512>;

                ^

/code/oneDNN/src/cpu/scale_utils.hpp:41:14: note: candidate function not viable: requires at least 8 arguments, but 5 were provided

const float *precompute_scales(const memory_tracking::grantor_t &scratchpad,
```

**Comment by igorsafo** [comment]
Hi @jondea , thank you for reporting the issue. We made some changes to a function that is used for Aarch64 as well

**Comment by igorsafo** [comment]
Hi @jondea , please try the latest version of `main`. The 41901a5 should fix the issue.

**Comment by jondea** [comment]
Yes, that works, thanks for the quick fix!
