### ISSUE TITLE
question about matmul_perf example

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneDNN#1922]
In oneDNN/main/examples/matmul_perf.cpp,  why is the type of a_in_md and b_in_md dt::f32 ?   

Thanks 

```
    // Create memory descriptors and memory objects for src, weights, bias, and
    // dst.
    auto a_md = memory::desc(a_dims, type, tag::any);
    auto b_md = memory::desc(b_dims, type, tag::any);
    auto c_md = memory::desc(c_dims, type, tag::any);

    auto a_in_md = memory::desc(a_dims, dt::f32, tag::ab);
    auto b_in_md = memory::desc(b_dims, dt::f32, tag::ab);
```

**Comment by zjin-lcf** [comment]
Is it good for the following function to return a boolean function (fail/success) ? 

    void execute(const stream& astream, const std::unordered_map<int, memory>& args) const;

**Comment by rupakroyintel** [comment]
@zjin-lcf a_in_md and b_in_md are the input memory descriptor whereas a_md, b_md are src memory descriptor and c_md is the destination/target memory descriptor. The src and dst memory descriptors will change based on the 'type' but the input memory descriptor will remain the same. The input memory descriptor has been set to f32 in this case just as an example. 
The data type of the input memory descriptor can also be f16/bf16/s8 if you modify the example for other data types. More details on the data types can be found here: https://oneapi-src.github.io/oneDNN/dev_guide_reorder.html#data-types-support
