### ISSUE TITLE
Can't create engine in amd backend.

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1965]
The error is like this :
```sh
gpu_utils::device_id_t dnnl::impl::gpu::intel::sycl::device_id(const ::sycl::device &): Assertion `!"unreachable"' failed.
```
Here is the code I used to create a engine(amd backend) :
```c++
dnnl::engine engine(engine_kind, 0);
```

This happened when I update my local oneDNN local repository to the latest commit of your main branch last week(06.15.2024), I noticed you have change the machenism the initiate a engine, at `src/sycl/sycl_engine_base.hpp:182`. 

So, is there any other ways to init a engine?

**Comment by vpirogov** [comment]
@MOLOjl, this is correct way to initialize the engine. We were in the middle of GPU codebase refactoring last few weeks, so this may be a bug. Currently I do not see anything similar in our validation.

+@densamoilov for additional thoughts

**Comment by vpirogov** [comment]
Could you please share how you build oneDNN? Instruction for AMD GPU builds are available [here](https://github.com/oneapi-src/oneDNN/blob/main/src/gpu/amd/README.md).

**Comment by densamoilov** [comment]
@MOLOjl, I pushed the latest changes that affects the AMD GPU vendor to main, please give it a try and let us know if the issue persists.

**Comment by MOLOjl** [comment]
@densamoilov @vpirogov problem solved after I update my branch to the latest commit, thanks for your helping.
