### ISSUE TITLE
Heuristics for operations workload distribution for matrix multiplication based on number of threads

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#1970]
Hello,
Is there any heuristics for workload distribution of matrix multiplication operation based on number of threads i.e if no of threads are 32, how is the matrix multiplication work is divided among the threads based on matrix size and shape(small or big)? If yes, can you show the file location for the same?

**Comment by dzarukin** [comment]
Hi @vineel96, you may refer to this location: https://github.com/oneapi-src/oneDNN/tree/main/src/cpu/x64/matmul
It contains an implementation for matrix multiplication depending on a huge space of parameters.

This is an entry point for execution: https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/matmul/brgemm_matmul.cpp#L276. At line 312 the parallel section starts. You may inspect what tasks per thread look like.

Adjusting based on shapes happening at the init stage and usually referred as blocking setup. It generally happens inside this call: https://github.com/oneapi-src/oneDNN/blob/main/src/cpu/x64/matmul/brgemm_matmul.cpp#L122. It is about filling an internal structure that would be responsible for generating relevant kernels at the next stage.

**Comment by vineel96** [comment]
@dzarukin  Thanks for information
