### ISSUE TITLE
Does oneDNN support int64?

### ISSUE THREAD

**Issue by MOLOjl** [oneapi-src/oneDNN#1978]
I noticed that the enum `dnnl_data_type_t` does not include the `int64` or `long long` types. Does this mean you do not support int64 data type in oneDNN? If so, will this feature be supported in a future update?

**Comment by vpirogov** [comment]
oneDNN does not support int64 tensors and we do not have plans to enable these. The datatype is used to represent tensor dimensions though.

Any particular functionality that you are interested in? What is the intended use?

**Comment by MOLOjl** [comment]
We were trying to introduce some operators from PyTorch, such as `gather` and `mask`. Some of them use int64 tensors as inputs. I understand that these operators are not intended to be supported by oneDNN, but our team is trying to support them. Maybe I can use f64 and type cast as an alternative.
