### ISSUE TITLE
AMD oneDNN Build Error

### ISSUE THREAD

**Issue by Moltres-Galar** [oneapi-src/oneDNN#1994]
# Summary
Hi there.
According to [https://github.com/oneapi-src/oneDNN/blob/main/src/gpu/amd/README.md](url), I recently attempted to build oneDNN on the AMD GPU platforms MI300X and MI250X. After installing the complete Intel toolkit version 2024.2, the system operated smoothly.

root@3f63eb29cf23:~/oneDNN/build# cmake -DrocBLAS_INCLUDE_DIR=/opt/rocm-5.3.0/include/rocblas -DrocBLAS_LIBRARY=/opt/rocm-5.3.0/lib/librocblas.so -DDNNL_CPU_RUNTIME=SYCL -DDNNL_GPU_RUNTIME=SYCL -DDNNL_GPU_VENDOR=AMD -DONEDNN_BUILD_GRAPH=OFF -G Ninja  ..
-- CMAKE_BUILD_TYPE is unset, defaulting to Release
-- The C compiler identification is IntelLLVM 2024.2.0
-- The CXX compiler identification is IntelLLVM 2024.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/intel/oneapi/2024.2/bin/icx - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/intel/oneapi/2024.2/bin/icpx - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: X64
-- DNNL_LIBRARY_NAME: dnnl
-- Performing Test SYCL_FLAG_SUPPORTED
-- Performing Test SYCL_FLAG_SUPPORTED - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found HIP: /opt/rocm/lib/libamdhip64.so (found version "5.3.22061") 
-- Found rocBLAS: /opt/rocm-5.3.0/lib/librocblas.so (found version "2.45.0") 
-- Found MIOpen: /opt/rocm/lib/libMIOpen.so (found version "2.18.0") 
-- DPC++ support is enabled (HIP)
-- Found OpenMP_C: -fiopenmp  
-- Found OpenMP_CXX: -fiopenmp  
-- Found OpenMP: TRUE   
-- TBB: /opt/intel/oneapi/tbb/2021.13
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.1") found components: doxygen missing components: dot
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE) 
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2.7")
-- Found Sphinx: /usr/bin/sphinx-build (found version "sphinx-build 4.3.2") 
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Enabled testing coverage: CI
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Enabled GeMM kernels ISA: ALL
-- Primitive cache is enabled
-- The ASM compiler identification is IntelLLVM
-- Found assembler: /opt/intel/oneapi/2024.2/bin/icx
-- Performing Test COMPILER_ALLOWS_ALIAS_ATTRIBUTES
-- Performing Test COMPILER_ALLOWS_ALIAS_ATTRIBUTES - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/oneDNN/build

I then followed the guidance to try using ROCm 5.3 and also tested the latest version, ROCm 6.1.3. However, both attempts resulted in the following error

# Version
oneDNN: git 0a477d2dc2ded7e5065f1e0f01d237a6cb8a6c91

# Observed behavior
FAILED: src/common/CMakeFiles/dnnl_common.dir/engine.cpp.o 
/opt/intel/oneapi/2024.2/bin/icpx -DCL_TARGET_OPENCL_VERSION=300 -DDNNL_DLL -DDNNL_DLL_EXPORTS -DDNNL_ENABLE_CPU_ISA_HINTS -DDNNL_ENABLE_ITT_TASKS -DDNNL_ENABLE_MAX_CPU_ISA -DDNNL_X64=1 -DTBB_PREVIEW_TASK_ARENA_CONSTRAINTS_EXTENSION=1 -D__HIP_PLATFORM_AMD__=1 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/root/oneDNN/build/include -I/root/oneDNN/include -I/opt/intel/oneapi/tbb/2021.13/include -I/root/oneDNN/src -idirafter/opt/rocm/include -idirafter/opt/rocm-5.3.0/include/rocblas -Wno-#pragma-messages -fsycl -fiopenmp -fvisibility-inlines-hidden  -ffp-model=precise -fno-reciprocal-math -Wno-unknown-warning-option -Wall -Wno-unknown-pragmas -fvisibility=internal   -fPIC -Wformat -Wformat-security   -Wno-pass-failed -Wno-tautological-compare -Wno-pass-failed -Wno-recommended-option  -DITT_API_IPT_SUPPORT -O3 -DNDEBUG -D_FORTIFY_SOURCE=2 -MD -MT src/common/CMakeFiles/dnnl_common.dir/engine.cpp.o -MF src/common/CMakeFiles/dnnl_common.dir/engine.cpp.o.d -o src/common/CMakeFiles/dnnl_common.dir/engine.cpp.o -c /root/oneDNN/src/common/engine.cpp
In file included from /root/oneDNN/src/common/engine.cpp:37:
In file included from /root/oneDNN/src/xpu/sycl/engine_factory.hpp:30:
In file included from /root/oneDNN/src/xpu/sycl/utils.hpp:26:
In file included from /opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/sycl.hpp:30:
/opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/backend.hpp:76:3: error: implicit instantiation of undefined template 'sycl::detail::BackendReturn<sycl::backend::ext_oneapi_hip, sycl::device>'
   76 |   using return_type = typename detail::BackendReturn<Backend, T>::type;
      |   ^
/opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/backend.hpp:86:1: note: in instantiation of template type alias 'return_type' requested here
   86 | using backend_return_t =
      | ^
/opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/ext/oneapi/backend/hip.hpp:17:8: note: in instantiation of template type alias 'backend_return_t' requested here
   17 | inline backend_return_t<backend::ext_oneapi_hip, device>
      |        ^
/opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/detail/backend_traits.hpp:21:47: note: template is declared here
   21 | template <backend Backend, typename T> struct BackendReturn;
      |                                               ^
In file included from /root/oneDNN/src/common/engine.cpp:37:
In file included from /root/oneDNN/src/xpu/sycl/engine_factory.hpp:30:
In file included from /root/oneDNN/src/xpu/sycl/utils.hpp:26:
In file included from /opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/sycl.hpp:30:
/opt/intel/oneapi/compiler/2024.2/bin/compiler/../../include/sycl/backend.hpp:76:3: error: implicit instantiation of undefined template 'sycl::detail::BackendReturn<sycl::backend::ext_oneapi_hip, sycl::device>'
   76 |   using return_type = typename detail::BackendReturn<Backend, T>::type;
      |   ^
and more

# Expected behavior
The build should complete successfully.

Thank you.

**Comment by shu1chen** [comment]
Hello @Moltres-Galar, did you download the [oneAPI for AMD GPUs](https://developer.codeplay.com/products/oneapi/amd/home) and use the SYCL compiler there with DPC++ HIP plugin version 2024.2.0?

**Comment by Moltres-Galar** [comment]
Thank you for pointing out the issue. I tried installing this version of oneAPI and it worked; it seems I had downloaded the wrong version previously. 
Thank you for your help.
