### ISSUE TITLE
Fix compilation of oneDNN with C++20 on Windows

### ISSUE THREAD

**Issue by ilya-lavrenov** [oneapi-src/oneDNN#2028]
# Summary
oneDNN and some software which uses it (e.g. OpenVINO), are distributed as source code. 
And some users may want to compile it with their own C++ standard and compile flags.

# Problem statement
oneDNN with GPU backend enabled cannot be compiled with C++ 20 with MSVC compiler.
Build logs are https://github.com/openvinotoolkit/openvino/actions/runs/10289707118/job/28478073165

Problematic place https://github.com/oneapi-src/oneDNN/blob/main/src/gpu/intel/jit/gemm/include/internal/utils.hpp#L22 - __cplusplus  is defined to 1997 value for MSVC compiler.

# Preferred solution
Please, enable C++20 support om compilation level.

**Comment by vpirogov** [comment]
oneDNN should be buildable with C++ 20, so this looks like a bug.

+@rjoursler, @petercad

**Comment by petercad** [comment]
@rjoursler Looks like [this line](https://github.com/oneapi-src/oneDNN/blob/2e7b691217ff17497aebd7e565fa1701f8a42396/src/gpu/intel/jit/gemm/include/internal/utils.hpp#L97) needs to take into account `__cplusplus`.

**Comment by ilya-lavrenov** [comment]
> @rjoursler Looks like [this line](https://github.com/oneapi-src/oneDNN/blob/2e7b691217ff17497aebd7e565fa1701f8a42396/src/gpu/intel/jit/gemm/include/internal/utils.hpp#L97) needs to take into account `__cplusplus`.

No, as I stated in the description:

> Problematic place https://github.com/oneapi-src/oneDNN/blob/main/src/gpu/intel/jit/gemm/include/internal/utils.hpp#L22 - __cplusplus is defined to 1997 value for MSVC compiler.

You need to rely on _MSVC_LANG for SMVC compiler instead of __cplusplus

WA on OpenVINO side is to use https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170, but we want to avoid it.

**Comment by rjoursler** [comment]
This should be fixed by commit ece6802e6f166ef19978205ca10dd5760eafbd3b, @ilya-lavrenov could you please confirm this issue is fully resolved?
