### ISSUE TITLE
[ACL] non-constant depthwise convolution weights leads to performance degradation

### ISSUE THREAD

**Issue by alvoron** [oneapi-src/oneDNN#2033]
Making depthwise convolution weights non-constant leads to performance degradation:
https://github.com/oneapi-src/oneDNN/blob/84ce605c44fb6f1bbe4a4dd487d8678a2e5a6d7e/src/cpu/aarch64/acl_convolution_utils.cpp#L187

The following benchdnn test gives me 1.15 ms if `set_are_values_constant` is not called (line 187 is commented) and 1.3 ms if it's called:
```
--max-ms-per-prb=4e3 --mode=P --conv --reset --allow-enum-tags-only=0 --engine=cpu --dir=FWD_I --alg=direct --dt=f32:f32:f32  --stag=acdb --wtag=any --dtag=acdb  --attr-scratchpad=user g512mb1_ic512oc512_ih64oh64kh87sh1dh1ph86_iw1ow1kw1sw1dw0pw0
```

@milpuz01 I've seen you added this call as part of depthwise convolution enablement in oneDNN:
https://github.com/oneapi-src/oneDNN/pull/1655

Could you please comment the purpose of this call? I haven't found in-place weights modification.
I reproduced the issue on OpenVINO fork https://github.com/openvinotoolkit/oneDNN - oneDNN 3.5 is used there.

**Comment by vpirogov** [comment]
+@oneapi-src/onednn-cpu-aarch64

**Comment by theComputeKid** [comment]
I just came across this issue. Coincidentally, my next upstream PR will be on depthwise convolution via ACL. I have already fixed this issue downstream. I will reference this issue when I get the PR up.
