### ISSUE TITLE
OneDNN 2.7.3 Compilation Error in TensorFlow on RISC-V

### ISSUE THREAD

**Issue by helloworld-star** [oneapi-src/oneDNN#2042]
# Summary
This issue pertains to the compilation of OneDNN 2.7.3 on RISC-V. The compilation process encountered an error related to the isa member of a struct, which is not recognized in the context of the RISC-V architecture. The expected behavior is that the MKL acceleration library should be disabled for RISC-V, but it appears to have been included unintentionally.

# Version
OneDNN 2.7.3

# Environment
* CPU make and model (qemu9.0.0(RISC-V))
* OS version (`oprnEuler-24.03-riscv`)
* Compiler version (`gcc --12.3.1`)
* Bazel version (`Bazel--5.3.0`)
* Bazel output log
external/mkl_dnn_v1/src/cpu/x64/rnn/brgemm_cell_common_bwd.cpp:102:37: error: 'const struct dnnl::impl::cpu::rnn_utils::diff_src_brgemm_conf_t' has no member named 'isa'
102 | && rnn_.diff_src_brgemm.isa == x64::avx512_core_bf16_amx_bf16) {
| ^~~

# Steps to reproduce
https://build.tarsier-infra.isrc.ac.cn/package/show/home:Kaguya/tensorflow-gitee

# Observed behavior
According to the information gathered, OneDNN 2.7.3 is Intel's acceleration library, and it should be disabled when compiling on the RISC-V. The TensorFlow manual indicates that the MKL acceleration library should be enabled by setting --config=mkl. However, this option was not set during compilation, but the output indicates that the library still entered the compilation process.

The compile command:
bazel --output_user_root=pwd/../output_user_root build --subcommands --host_copt=-Wno-stringop-truncation //tensorflow/tools/pip_package:build_pip_package --verbose_failures --experimental_local_memory_estimate --jobs=16

# Expected behavior
The MKL acceleration library should be disabled for RISC-V to prevent such compilation errors.

**Comment by shu1chen** [comment]
Hi @helloworld-star, the compilation options are set by TensorFlow when building oneDNN. I see that you have already submitted this same issue in TensorFlow repo: tensorflow/tensorflow#74015. How do you think oneDNN can support you?

**Comment by shu1chen** [comment]
Closing as stale. Please feel free to reopen it with additional info.
