### ISSUE TITLE
submemory_desc() throws exception 

### ISSUE THREAD

**Issue by uapconvnet** [oneapi-src/oneDNN#2045]
Hi,

If I want to split a memory region channelwise in two equal parts I can use:
```
n = 1;
c = 160;
h = 8;
w = 8;

auto BlockedFmt = dnnl::memory::format_tag::nChw16c;
auto DataType = dnnl::memory::data_type::f32;

memory::desc input_md({n, c, h, w}, DataType, BlockedFmt); // md for memory desc
memory input(input_md, ...);

// create submemory descriptors for the slices
memory::desc slice1_md = input_md.submemory_desc({n, c/2, h, w}, offset={0,   0, 0, 0});
memory::desc slice2_md = input_md.submemory_desc({n, c/2, h, w}, offset={0, c/2, 0, 0});
```

The above (pseudo)code works perfectly. But when I set c = 2 it raises an exception when creating the submemory slices.
Is this by design? How do I channelwise split a memory in the case when c = 2 ?
(the exception is raised on the second slice)

thanks

**Comment by rafael-lago** [comment]
@uapconvnet
As @dzarukin explained, you're using nChw16, a blocked format that splits the memory into blocks of fixed dimension (this is to facilitate the usage of AVX512 instructions). More specifically, C has to be a multiple of 16 for nChw16 and a multiple of 8 for nChw8. Please refer to the following link for an example (including information on zero-padding):
https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html#blocked-layout

**Comment by uapconvnet** [comment]
Thanks for the clarification!
