### ISSUE TITLE
Regarding Winograd Convolution

### ISSUE THREAD

**Issue by vineel96** [oneapi-src/oneDNN#2083]
Hello,
Some questions regarding winograd convolution:

1. why there is no jit implementation for winograd, I see only ACL winograd implementation
2. Why winograd convolution is not used compared to normal convolution? is it because of the accuracy issue?
3. Any plans to improve the accuracy issue in winograd convolution?

**Comment by theComputeKid** [comment]
I believe the winograd accuracy issue you are referring to is the one you mention in: https://github.com/ARM-software/ComputeLibrary/issues/1138

**Comment by vpirogov** [comment]
Closing as the question is addressed in https://github.com/ARM-software/ComputeLibrary/issues/1138.
