### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by AnonymousYWL** [oneapi-src/oneDNN#2090]
Hello.
Are there any benchmark results evaluating the performance of AMX-enabled processors for DNN operators, such as convolution and matrix multiplication?

**Comment by asirvaiy** [comment]
Hi,
You can use Benchdnn to check the performance of each operator. https://github.com/oneapi-src/oneDNN/tree/main/tests/benchdnn 
To enable AMX, you need to use data type int8 or bf16.

**Comment by asirvaiy** [comment]
> Hi, You can use Benchdnn to check the performance of each operator. https://github.com/oneapi-src/oneDNN/tree/main/tests/benchdnn To enable AMX, you need to use data type int8 or bf16.

Hope you were able to benchmark. Closing the issue now.
