### ISSUE TITLE
Build failure when using MingW/GCC on Windows

### ISSUE THREAD

**Issue by MichaelFroelich** [oneapi-src/oneDNN#2092]
When building with MingW and GNU GCC 14.2 on Windows, then the SDL.cmake file will use the DEPENDENTLOADFLAG:0x2000 flag that does not exit on GCC. This breaks the build.

This results in the following error:

[build] C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find /DEPENDENTLOADFLAG:0x2000: No such file or directory
[build] collect2.exe: error: ld returned 1 exit status

This error was found on both the main branch of OneDNN as well as the rls-v3.6 branch

Intel CPU
Windows 10
GCC 14.2.0
CMake 3.30.2

The expected behaviour should be that this flag is not used if the compiler is "GNU" or that a similar flag is used instead

**Comment by shu1chen** [comment]
Thanks for reporting this issue.
Hello @avmanerikar, this "/DEPENDENTLOADFLAG:0x2000" flag was introduced by https://github.com/oneapi-src/oneDNN/commit/a2bbbf1e556fde960495ad756ca154be628dfaf0 2 days ago and it seems that the "GNU" case was ignored. Could you please take a look at it?

**Comment by MichaelFroelich** [comment]
Yes, the error still persists when I use "GNU" for the build option ONEDNN_DPCPP_HOST_COMPILER. The code that needs to change is as follows:

```
if(WIN32)
    if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        # add Clang++ specific flags
        append(CMAKE_EXE_LINKER_FLAGS "-Xlinker /DEPENDENTLOADFLAG:0x2000")
        append(CMAKE_SHARED_LINKER_FLAGS "-Xlinker /DEPENDENTLOADFLAG:0x2000")
    else()
        # Default to MSVC-style definition
        append(CMAKE_EXE_LINKER_FLAGS "/DEPENDENTLOADFLAG:0x2000")
        append(CMAKE_SHARED_LINKER_FLAGS "/DEPENDENTLOADFLAG:0x2000")
    endif()
endif()
```

This can be found in the file build onednn-src\cmake\SDL.cmake

There is no option for GNU here and will fall into the else statement regardless.
