### ISSUE TITLE
How to modify oneDNN to enable GEMM operation acceleration on your own hardware

### ISSUE THREAD

**Issue by nanzh-19** [oneapi-src/oneDNN#2114]
My use case is inference acceleration on a CPU using TensorFlow Serving, and my hardware architecture is AArch64 (ARMv8). Currently, I've noticed that with oneDNN enabled, the performance bottleneck is in GEMM. I want to create a fused operator for GEMM and ReLU. Which parts of the code should I modify to improve performance? Thank you for your assistance!

**Comment by mgouicem** [comment]
Hi @nanzh-19 you can fuse relu with matmul operator at the oneDNN API level by using post-ops. You can find a full example of Matmul + ReLU [here](https://github.com/oneapi-src/oneDNN/blob/0185923d2732d3f82d122aacec7d66221b4ed1ec/examples/primitives/matmul.cpp#L106).

Tagging @milpuz01 @cfRod @jondea for guidance on Tensorflow integration.

**Comment by theComputeKid** [comment]
@nanzh-19 : as @mgouicem mentioned, oneDNN can pass down a fused GEMM and ReLU to ACL, where it can execute an optimised operation. 

In addition to his example, you can pass activation info in GEMMInfo here: https://github.com/ARM-software/ComputeLibrary/blob/de7288cb71e6b9190f52e50a44ed68c309e4a041/arm_compute/function_info/GEMMInfo.h#L86

And then specify ReLU as here: https://github.com/ARM-software/ComputeLibrary/blob/de7288cb71e6b9190f52e50a44ed68c309e4a041/arm_compute/function_info/ActivationLayerInfo.h#L49

Even if you have unreleased hardware, it is important to note that we optimise for architectural features such as SVE/NEON/SME etc, rather than the machine description or vendor. So I believe that you should get good performance.

Hope that helps, feel free to inquire more.

**Comment by nanzh-19** [comment]
Thank you for your comment. I have the following questions:

We believe that OneDNN has not been thoroughly optimized for our machine. For example, OneDNN is not aware of our machine's memory structure, which may lead to suboptimal matrix blocking for GEMM. Therefore, we would like to optimize based on OneDNN's code.

The reason for the lack of optimization of OneDNN for our machine is that we compared x86 servers with our own servers. When observing inference performance on a single NUMA node, we found that our machine's performance significantly degraded after using OneDNN.

![image](https://github.com/user-attachments/assets/76a7325c-14a2-45a9-bd4a-1555897ba7c7)
The data in the figure represents the inference throughput.

**Comment by mgouicem** [comment]
@nanzh-19 there could multiple things at play here and log files might be helpful (if you can share any).
In general here are a few things:
- did you build oneDNN with acl? Or did you use oneDNN as part of a framework (and if the latter, which one)?
- your OS might have to include support for your custom hardware. In particular, aarch64 jitted implementations get the system topology using a mix of hwcap and system files, see Linux [code here](https://github.com/fujitsu/xbyak_aarch64/blob/main/src/util_impl_linux.h#L62).
- which threading runtime did you use ?

**Comment by nanzh-19** [comment]
Thank you for mgouicem's comment. I've identified the reason for the performance discrepancy: on the ARM architecture, the ACL's arm_gemm is being called, while on the x86 architecture, brgemm is used. My current issue is how to modify TensorFlow's calls so that brgemm can be used on the ARM architecture as well.

**Comment by theComputeKid** [comment]
Depending on how you got/built tensorflow, I believe aarch64 has a much older version of oneDNN than x86. If you want to investigate further, you could also try using benchdnn directly on the latest oneDNN from main and see the difference for your use case.

**Comment by Serenagirl** [comment]
> Thank you for [@mgouicem](https://github.com/mgouicem) 's comment. I've identified the reason for the performance discrepancy: on the ARM architecture, the ACL's arm_gemm is being called, while on the x86 architecture, brgemm is used. My current issue is how to modify TensorFlow's calls so that brgemm can be used on the ARM architecture as well.
arm_gemm is for the ARM architecture, and brgemm is for the x86 architecture. There are many internal optimizations to adapt to the x86 architecture. If the data is directly migrated to the ARM architecture, the effect may not be good.
