### ISSUE TITLE
benchdnn matmul with --wtag=acbd correctness test failure on CPU

### ISSUE THREAD

**Issue by shu1chen** [oneapi-src/oneDNN#2180]
# Summary
When working on #2175, it's found that there is also a bug on x86_64. After the commit 3877097d6c535e323a98bb8dacf194dfaa5b3660 on main branch, benchdnn correctness check fails after adding --wtag=acbd. It's good on the previous commit 6bfb6a8debbf9bfde4e478d11acbae4ba07c2f69.

# Version
onednn_verbose,v1,info,oneDNN v3.7.0 (commit 3877097d6c535e323a98bb8dacf194dfaa5b3660)
onednn_verbose,v1,info,cpu,runtime:OpenMP,nthr:64
onednn_verbose,v1,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support and Intel AMX with bfloat16 and 8-bit integer support

# Environment
* CPU: Intel (R) Xeon (R) CPU Max 9462
* OS version: Ubuntu 22.04
* Compiler version: gcc 11.4.0

# Steps to reproduce
```
$ ./tests/benchdnn/benchdnn --engine=cpu --matmul --wtag=acbd --dtag=abcd 1x1x2x3:3x1x3x3
```

# Observed behavior
```
[   6][DST][1:0:0:0] exp_f32:        7186 exp:        7186 got:        -nan diff:     nan rdiff:     nan
[   7][DST][1:0:0:1] exp_f32:       -5487 exp:       -5487 got:        -nan diff:     nan rdiff:     nan
[   8][DST][1:0:0:2] exp_f32:       -5549 exp:       -5549 got:        -nan diff:     nan rdiff:     nan
[   9][DST][1:0:1:0] exp_f32:       -3131 exp:       -3131 got:        -nan diff:     nan rdiff:     nan
[  10][DST][1:0:1:1] exp_f32:        2511 exp:        2511 got:        -nan diff:     nan rdiff:     nan
[  11][DST][1:0:1:2] exp_f32:        -240 exp:        -240 got:        -nan diff:     nan rdiff:     nan
[  12][DST][2:0:0:0] exp_f32:       -1727 exp:       -1727 got:        -nan diff:     nan rdiff:     nan
[  13][DST][2:0:0:1] exp_f32:       -9256 exp:       -9256 got:        -nan diff:     nan rdiff:     nan
[  14][DST][2:0:0:2] exp_f32:        2826 exp:        2826 got:        -nan diff:     nan rdiff:     nan
[  15][DST][2:0:1:0] exp_f32:        1391 exp:        1391 got:        -nan diff:     nan rdiff:     nan
[COMPARE_STATS][DST]: trh=0 err_max_diff:     nan err_max_rdiff:     nan all_max_diff:     nan all_max_rdiff:     nan
0:FAILED (errors:12 total:18) __REPRO: --matmul --wtag=acbd --dtag=abcd 1x1x2x3:3x1x3x3
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 invalid_arguments:0 failed:1 listed:0
total: 0.01s; fill: 0.01s (48%); compute_ref: 0.00s (24%); compare: 0.00s (7%);
```

# Expected behavior
Test pass. It's better to add a test for this use case.

**Comment by dzarukin** [comment]
Must be fixed by [6be35fd4](https://github.com/oneapi-src/oneDNN/commit/6be35fd41278dc12e21117e5f21dee5274b4d6e8).
