### ISSUE TITLE
3.6.1: please stop running benchmarking with parallelisation

### ISSUE THREAD

**Issue by kloczek** [oneapi-src/oneDNN#2200]
# Summary
Running benchmarking as part of the test suite on multicore box causes total clogging box.
![image](https://github.com/user-attachments/assets/800f6623-5102-4c53-a666-df6dab8afcbc)

**Comment by vpirogov** [comment]
Benchdnn follows default library behavior, which is in turn defined by threading runtime used in your build. If you want to run several benchmarks in parallel you can limit the number of threads using threading controls. For OpenMP this could be done by setting environment variable `OMP_NUM_THREADS=1`. See [Configuring oneDNN for Benchmarking](https://oneapi-src.github.io/oneDNN/dev_guide_performance_settings.html) section of the user guide for details.

**Comment by kloczek** [comment]
This issue ticket has nothing to do with numer of threads. It is about facts that all benchmark tests are not serialized but they all executed together.
Please read https://www.scivision.dev/cmake-resource-lock-ctest/  about how to do that.

Other thing is that all these benchmark tests are used unconditionally.
It would be goo to have cmake option to disable execute benchmark tests as part of the test suite.

**Comment by shu1chen** [comment]
Hello @kloczek, depending on the platform being tested, running the benchdnn tests in parallel can be appropriate. As documented in [benchdnn_general_info.md](https://github.com/oneapi-src/oneDNN/blob/main/tests/benchdnn/doc/benchdnn_general_info.md#running-tests), the benchdnn tests are enabled through CMake. Users can utilize `ctest` options to specify which tests to run and control the parallel execution level. 
This issue seems more related to `ctest` configuration rather than a specific oneDNN issue.
- To serialize the benchdnn tests, you can run:
```
ctest -R ".*benchdnn.*" --parallel 1
```
- For more information, please refer to the [ctest documentation](https://cmake.org/cmake/help/latest/envvar/CTEST_PARALLEL_LEVEL.html).
- To disable execute benchmark tests as part of the test suite, you can use:
```
ctest -E ".*benchdnn.*"
```

**Comment by vpirogov** [comment]
> This issue ticket has nothing to do with numer of threads. It is about facts that all benchmark tests are not serialized but they all executed together. 

oneDNN does not run performance benchmarks in default build. Could you please share cmake and ctest commands you use?

**Comment by kloczek** [comment]
> oneDNN does not run performance benchmarks in default build. Could you please share cmake and ctest commands you use?

Are you sure?
https://github.com/oneapi-src/oneDNN/blob/34c28a11d657c4999aef2e11987c223ca90c40d4/tests/CMakeLists.txt#L107C1-L110C1

and nothing in tests/benchdnn/CMakeLists.txt allows to disable benchmarks.

Here are cmake params and ooutput
```console
+ /usr/bin/cmake -B x86_64-redhat-linux-gnu -D BUILD_SHARED_LIBS=ON -D CMAKE_AR=/usr/bin/gcc-ar -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D CMAKE_C_FLAGS_RELEASE=-DNDEBUG -D CMAKE_EXPORT_COMPILE_COMMANDS=ON -D CMAKE_Fortran_FLAGS_RELEASE=-DNDEBUG -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_NM=/usr/bin/gcc-nm -D CMAKE_RANLIB=/usr/bin/gcc-ranlib -D CMAKE_VERBOSE_MAKEFILE=ON -D ENABLE_BSYMBOLICFUNCTIONS=ON -D INCLUDE_INSTALL_DIR=/usr/include -D LIB_INSTALL_DIR=/usr/lib64 -D LIB_SUFFIX=64 -D SHARE_INSTALL_PREFIX=/usr/share -D SYSCONF_INSTALL_DIR=/etc -S .
CMake Deprecation Warning at CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DNNL_TARGET_ARCH: X64
-- DNNL_LIBRARY_NAME: dnnl
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found Doxygen: /usr/bin/doxygen (found version "1.12.0") found components: doxygen missing components: dot
-- Could NOT find Doxyrest (missing: DOXYREST_EXECUTABLE)
CMake Warning (dev) at cmake/Sphinx.cmake:25 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  cmake/doc.cmake:28 (include)
  CMakeLists.txt:127 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /usr/bin/python (found suitable version "3.10.14", minimum required is "2.7")
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Could NOT find Git (missing: GIT_EXECUTABLE)
-- Enabled testing coverage: CI
-- Enabled workload: TRAINING
-- Enabled primitives: ALL
-- Enabled primitive CPU ISA: ALL
-- Enabled primitive GPU ISA: ALL
-- Enabled GeMM kernels ISA: ALL
-- Primitive cache is enabled
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
-- Graph component is enabled
-- Graph compiler backend is disabled.
-- Configuring done (2.9s)
-- Generating done (0.7s)
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_Fortran_FLAGS_RELEASE
    ENABLE_BSYMBOLICFUNCTIONS
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR


-- Build files have been written to: /home/tkloczko/rpmbuild/BUILD/oneDNN-3.5.3/x86_64-redhat-linux-gnu
```

**Comment by vpirogov** [comment]
> Are you sure?
> and nothing in tests/benchdnn/CMakeLists.txt allows to disable benchmarks.

Benchdnn is a framework for accuracy and performance validation. Specific test coverage `ctest` will execute is managed by [`ONEDNN_TEST_SET`](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html#onednn-test-set) option. None of these options include performance validation. 

From the logs you shared I see that you are running default test coverage, which includes limited set of accuracy tests. These are not fundamentally different from gtests in terms of CPU utilization. Considering that underlying functionality is threaded the best option to deal with resource utilization would be using `--parallel N` option to meet restrictions of your environment as @shu1chen suggested. Technically we can slap 'RUN_SERIAL' on all the tests, but this would unnecessarily restrict parallel execution capabilities of `ctest`.

**Comment by kloczek** [comment]
> Benchdnn is a framework for accuracy and performance validation. Specific test coverage `ctest` will execute is managed by [`ONEDNN_TEST_SET`](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html#onednn-test-set) option. None of these options include performance validation.

With full respect .. that was not about what I've asked ..
Could you please read one more time my question?

> These are not fundamentally different from gtests in terms of CPU utilization

Please look one more time on quoted CMakeLists.txt file.
gtest based tests are separated in own directory.

One more time: this ticket is about running **all benchmark units in parallel**. Each one is saturating possible number to run threads and by thus it does not make sense to run them with parallelisation. They should be executed sequentially.
I gave you already cmake documentation link in which is described how to tune that.

**Comment by densamoilov** [comment]
@kloczek, based on the screenshot that you've shared you run multiple instances of benchdnn. Each instance utilizes the default number of threads that is the number of threads available in the system. So if you want to control the utilization of available resources you will need to adjust the number of threads you want each instance to use. Have you tried that?

Using `RESOURCE_LOCK` will force the instances to run in a sequential manner, which will perhaps solve the problem you are seeing but making such behavior default will introduce unnecessary limitations for the users who want to control the number of threads per instance.

**Comment by kloczek** [comment]
> @kloczek, based on the screenshot that you've shared you run multiple instances of benchdnn. Each instance utilizes the default number of threads that is the number of threads available in the system. So if you want to control the utilization of available resources you will need to adjust the number of threads you want each instance to use. Have you tried that?

I did nothing special. This is result of running ctest with `-j48` which saturated user time (99.6%) on 24/48 dual CPU box casing that in running queue in peak was +1k processes/threads.

**Comment by densamoilov** [comment]
>  ctest with -j48 
This command launches 48 processes and each of the them runs benchdnn for a certain part of the test dataset.
For example process #1 runs `benchdnn --conv ...`, process #2 runs `benchdnn --matmul ...` and so on. Since you don't set a limit on how many threads each process is allowed to use (e.g. via `OMP_NUM_THREADS=1`) they use all of them (I assume it should be 48 threads per process). If we enable `RESOURCE_LOCK` then the `ctest -j48` will become equivalent of `ctest` as all the process will be run in order.

**Comment by kloczek** [comment]
> This command launches 48 processes and each of the them runs benchdnn for a certain part of the test dataset.

Yes and that is intentional and this why cmake, GNU autotools, meson and other frameworks provides possibility serialize or run tests in parallel.
Running benchmarks in parallel **by definition** is wrong especially on systems with bigger number of CPUs. Benchmarks should be serialized because it make running such tests susceptible to slight changes for example under additional pressure of other system processes. Running those tests serialised allows maximise reproducible results of those benchmarks.

Non-benchmark tests produces only single bool value metric like 1/0, yes/no, success/fail.
Benchmarks produces metrics like speed, utilisation of some resources like memory or CPU time or real time which are not bool results values. By this they are much more susceptible to env properties. Such property could be and in this case is "what else is running on test env system?". In this case results of those benchmarks will be different when you will run them with and without parallelisation. To make those results reproducible best is to run those tests .. sequentially.
It is only coincidence that in this case that in this case those benchmarks if running without parallelisation will be running minutes and executed with parallelization will take HOURS .. all on the same physical box.

**Comment by densamoilov** [comment]
@kloczek,
By running `ctest` you don't start performance benchmarking, you start correctness validation as @vpirogov has already mentioned. So it is absolutely fine to run correctness validation in parallel. Running performance benchmarking with ctest is not supported.
> Benchdnn is a framework for accuracy and performance validation. Specific test coverage ctest will execute is managed by [ONEDNN_TEST_SET](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html#onednn-test-set) option. None of these options include performance validation.
