### ISSUE TITLE
questions about fpmath mode

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDNN#2230]
Could you please clarify the application of the fpmath mode (e.g. FP32 GEMM only) ?

Does the library select one of the conversions when the mode is dnnl_fpmath_mode_any ?
dnnl_fpmath_mode_any: 
Implicit f32->f16, f32->tf32 or f32->bf16 conversions allowed.

**Comment by rupakroyintel** [comment]
@jinz2014 Thanks for reaching out. The [dnnl::fpmath_mode](https://oneapi-src.github.io/oneDNN/enum_dnnl_fpmath_mode.html#doxid-group-dnnl-api-fpmath-mode-1ga0ad94cbef13dce222933422bfdcfa725) primitive attribute specifies which implicit down-conversions are allowed for that a certain primitive. In case of an FP32 GEMM operation with dnnl_fpmath_mode_any  ,on an Intel CPU with BF16 support, the computation will use  BF16 arithmetic for performance gains. If no mixed-precision formats are supported, the computation will default to FP32.

**Comment by jinz2014** [comment]
Thanks.  Is the mode specific to the FP32 GEMM ?  What about FP64 GEMM operation with dnnl_fpmath_mode_any ?

In https://docs.nvidia.com/cuda/cublas/index.html#cublasltmatmul

CUBLAS_COMPUTE_32F_FAST_16F or

CUBLAS_COMPUTE_32F_FAST_16BF or

CUBLAS_COMPUTE_32F_FAST_TF32

**Comment by rupakroyintel** [comment]
In case of FP64 GEMM operation, dnnl_fpmath_mode_any does not perform any implicit precision conversion (lowering). The operation will be performed with the same precision as the input data.
