### ISSUE TITLE
amax question 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDNN#2231]
Is the absolute max (amax) operation available in oneDNN ?

**Comment by mgouicem** [comment]
Hi @jinz2014 oneDNN does not currently support amax reduction algorithm, only max reduction (see [documentation](https://oneapi-src.github.io/oneDNN/dev_guide_reduction.html)).

**Comment by rupakroyintel** [comment]
@jinz2014 Thanks for reaching out. For a better understanding of the difference between amax and max primitive, You can have a look at PyTorch's [amax](https://pytorch.org/docs/stable/generated/torch.amax.html) and [max](https://pytorch.org/docs/stable/generated/torch.max.html) documentation.
