### ISSUE TITLE
undefined reference to `dnnl::impl::gpu::intel::ocl::vectorized_lnorm_fused_kernel'

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDNN#2238]
To reproduce:

git clone https://github.com/oneapi-src/oneDNN.git

cd oneDNN

mkdir -p build
cd build

export CC=icx
export CXX=icpx

cmake .. \
          -DDNNL_CPU_RUNTIME=SYCL \
          -DDNNL_GPU_RUNTIME=SYCL

make -j

[ 89%] Linking CXX executable matmul-perf-cpp
/usr/bin/ld: ../src/libdnnl.so.3.7: undefined reference to `dnnl::impl::gpu::intel::ocl::vectorized_lnorm_fused_kernel'
icpx: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rcao8** [comment]
Looks it works well with the latest oneDNN version in my end.
```
# make -j10
.....
[100%] Building CXX object tests/benchdnn/CMakeFiles/benchdnn.dir/zeropad/zeropad_aux.cpp.o
[100%] Building CXX object tests/benchdnn/CMakeFiles/benchdnn.dir/__/test_thread.cpp.o
[100%] Linking CXX executable benchdnn
[100%] Built target benchdnn

# git log
commit 6efa272e3aeda5ce3c5e456d85f1fd822ee6d0bc (HEAD -> main, origin/main, origin/HEAD)
Author: Peter Caday <peter.caday@intel.com>
Date:   Tue Nov 26 12:16:14 2024 -0800

    xe: jit: gemm: scattered x remainder logic fix
```

Please try **make -j10** for example for desktop CPUs instead of **make -j**
If the issue still exists in your environment, please you tell us which icx/icpx version that you are using? and which CPU platform that you are compiling?

**Comment by jinz2014** [comment]
Thanks for the suggestion. If this issue is common, the install guide may include your suggestion.
