### ISSUE TITLE
AArch64 compilers support

### ISSUE THREAD

**Issue by spalicki** [oneapi-src/oneDNN#2294]
Recently, we started a cleanup of old and no longer supported tools. One of the tasks that I am working on right now includes updating our build system and documentation to remove dependencies and hacks for old compilers, specifically GCC < 8 and Clang < 11.
In the AArch64 section, the [documentation](https://github.com/oneapi-src/oneDNN/blob/main/README.md#validated-configurations) states that it is validated on GCC 7 and Clang 9 (the AArch64 CI runs on GCC 13). Is this correct, or can we safely move to newer compilers?

**Comment by vpirogov** [comment]
+@oneapi-src/onednn-cpu-aarch64

**Comment by theComputeKid** [comment]
At the lower end, ACL officially supports [gcc-10](https://artificial-intelligence.sites.arm.com/computelibrary/v24.12/index.xhtml), though that doc is a bit out of date. You are correct that we test gcc-14.2 and clang-17 for the public oneDNN repo. We also have internal testing for gcc-10, but that hasn't yet been ported out yet.

I think it should be safe for you to remove gcc-8, clang-11 but let me check to see if anyone still uses it, and I'll get back to you.

cc: @Sqvid

**Comment by theComputeKid** [comment]
Feel free to remove gcc-8 and clang-11.
