### ISSUE TITLE
Filter dilation for pooling layer and how to set the output size

### ISSUE THREAD

**Issue by XiaobingSuper** [oneapi-src/oneDNN#325]
Hi, I have some questions about mkldnn pooling, mainly about max_pooling.

1.  Is there support filter dilation for max_pooling ?

2.  What is the model used when setting the output size, ceil model or floor model?  for example,  we can chose the model by the parameter **ceil_model**  in  [pytorch-maxpool2d](https://pytorch.org/docs/master/nn.html#maxpool2d), which can get different output size using different mode. But in mkldnn, there will be error when using floor model and ceil model is ok.

Thanks.

**Comment by vpirogov** [comment]
Intel MKL-DNN supports dilation in convolutions only, not in pooling. We are also not aware of any cases where dilation is used in pooling layers. Do you have any example models or a paper that describes how it's used?

The output shape for pooling in Intel MKL-DNN can be controlled using padding parameters. The library does not have ceil or floor flags, so I'm not exactly sure what errors you are referring to.

**Comment by vpirogov** [comment]
Thanks! I'm adding 'enhancement' label to track the dilated pooling request.

**Comment by jignparm** [comment]
Any update or ETA on supporting dilations in the pooling operations? 

The latest version of the ONNX operators have added **ceil_mode** and **dilations** to the MaxPool operator (see below)

https://github.com/onnx/onnx/blob/master/docs/Operators.md#MaxPool

**Comment by XiaobingSuper** [comment]
@jignparm, the ceil model can be support by changing the [padding size](https://github.com/intel/caffe/blob/362a3b375e8f5bc64f5338d18f1742448cfb8fb7/src/caffe/layers/mkldnn_pooling_layer.cpp#L148) of MKLDNN MaxPooling padding to get the given output size. The dilations to MaxPool is not supported now. Thanks！

**Comment by XiaobingSuper** [comment]
@vpirogov,  Any progress? PyTorch Community https://github.com/pytorch/pytorch/issues/34675 said Max_pool2d is slow in native CPU path, so I think if MKLDNN can support it, may be can get a good performance.

**Comment by vpirogov** [comment]
Hi @XiaobingSuper,

We did not get to evaluation of this functionality yet. Considering that there's interest from Pytorch community I'm bumping priority of this request.

**Comment by vpirogov** [comment]
Filter dilation for pooling is introduced in dc68611fd0710224fa3d474e14c5043679ced288.
