### ISSUE TITLE
why not support caffe prelu (channel_shared = false )

### ISSUE THREAD

**Issue by longriyao** [oneapi-src/oneDNN#419]

**Comment by vpirogov** [comment]
This is just a question of time. PReLU has a learnable parameter and does not fit into existing eltwise API, so we need to design new function to accomodate it. As it's not particularly widely used we did not get there yet.

Note though, that PReLU is required only for training. For inference PReLU is ReLU with non-zero negative slope.

**Comment by longriyao** [comment]
Thanks!

**Comment by mika-fischer** [comment]
> Note though, that PReLU is required only for training. For inference PReLU is ReLU with non-zero negative slope.

@vpirogov Could you please elaborate on that? We're only interested in inference, but usually (and in our case too), PReLU has a different non-zero negative slope for each channel. I don't see how that could be represented in the current elementwise relu...

**Comment by vpirogov** [comment]
PreLU support is added in 192a058d9c0c158a4be4a0f5ec386aabdeede065.
