### ISSUE TITLE
benchdnn help CLI

### ISSUE THREAD

**Issue by WilliamTambellini** [oneapi-src/oneDNN#509]
Just a suggestion to add a "--help" support to benchdnn.
As today benchdnn does nt seem to have a --help support, the doc being only available online on this page:  
https://github.com/intel/mkl-dnn/tree/master/tests/benchdnn
the proposal is to add a minimum of "print usage" to the benchdnn CLI tool.

-----------------------------------------------------------------------------

### Environment
* OS version (`uname -a`) : Linux
* git hash (`git log -1 --format=%H`) :  038c9c7e58311b414452b89b3f3bbc9566e8b7df

### Steps to reproduce
./benchdnn --help

### Actual behavior
$ tests/benchdnn/benchdnn --help
conv driver: unknown option: `--help`, exiting...

### Expected behavior
./benchdnn --help
Usage:
benchdnn --DRIVER 
 [--engine=ENGINE_KIND] 
 [--mode=MODE] [--reset]
 [--max-ms-per-prb=INT] [--fix-times-per-prb=INT] 
 [-vINT|--verbose=INT] 
 [--skip-impl=SKIP_IMPL]
 [--allow-unimpl=BOOL] 
 [--perf-template=PERF_TEMPLATE] 
 [DRIVER-OPTS] PROBLEM-DESCRIPTION 
 [--batch=FILE]
...

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

Yeah, I think that makes perfect sense.
You can make a PR if you want to or may leave it to us (in which we will add the `--help` later).
