### ISSUE TITLE
Pooling and BN fallback to ref implementation

### ISSUE THREAD

**Issue by pinzhenx** [oneapi-src/oneDNN#588]
The following ops come from resnext50_32x4d

0.18.1 v.s. 1.1.1

```
mkldnn_verbose,exec,pooling,jit:avx512_common,forward_training,fdata:nChw16c fws:nChw16c,alg:pooling_max,mb1ic64_ih112oh56kh3sh2ph1_iw112ow56kw3sw2pw1,0.0529785
dnnl_verbose,exec,cpu,pooling,ref:any,forward_training,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:abcd:f0 ws_u8::blocked:abcd:f0,,alg:pooling_max,mb1ic64_ih112oh56kh3sh2ph1_iw112ow56kw3sw2pw1,12.4121


mkldnn_verbose,exec,pooling,jit:avx512_common,forward_training,fdata:nChw16c fws:undef,alg:pooling_avg_exclude_padding,mb1ic2048_ih7oh1kh7sh7ph0_iw7ow1kw7sw7pw0,0.0129395
dnnl_verbose,exec,cpu,pooling,ref:any,forward_training,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:abcd:f0 ws_undef::undef::f0,,alg:pooling_avg_exclude_padding,mb1ic2048_ih7oh1kh7sh7ph0_iw7ow1kw7sw7pw0,0.473877


mkldnn_verbose,exec,batch_normalization,ncsp_bnorm:any,forward_inference,fdata:nchw fdiff:undef,flags:3,mb1ic128ih56iw56,0.0861816
dnnl_verbose,exec,cpu,batch_normalization,bnorm_ref:any,forward_inference,data_f32::blocked:aBcd4b:f0 diff_undef::undef::f0,,flags:3,mb1ic128ih56iw56,2.198
```

**Comment by emfomenk** [comment]
For pooling it seems like you force dst to use plain memory format (`abcd`, same as `nchw`). Could you please pass format that `any` instead?

The batch normalization case is interesting. we don't have an optimized version of bnorm for `nChw4c`, that typically shouldn't happen. does the topology have grouped convolution just before this batch norm?

**Comment by pinzhenx** [comment]
> Could you please pass format tag any instead?
It uses JIT implementation now.

> does the topology have grouped convolution just before this batch norm?
Yes. It's preceded by such a conv
```
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_training,src_f32::blocked:aBcd4b:f0 wei_f32::blocked:aBCde4c4b:f0 bia_f32::blocked:a:f0 
```

**Comment by emfomenk** [comment]
Hi @pinzhenx,

> It uses JIT implementation now.

Good, that's aligned with the [DevGuide](https://intel.github.io/mkl-dnn/dev_guide_pooling.html) (2nd bullet in General Notes).

> Re slow batch normalization... 

Yeah, we use `nChw4c` memory format to make such convolutions fast. But other primitives are not quite ready for that yet 😕
We need to add the corresponding implementations. Reassign the issue to @tprimak.

For now, the quick workaround I can suggest is to use the function `is_4c_blocked_format()` (see below) to check if the memory format is `nChw4c` and explicitly reorder data to either plain (`nchw`) or blocked (`nChw16c`). This workaround code should be added to batch norm, layer norm, pooling, and lrn primitives.

``` cpp
bool is_4c_blocked_format(const dnnl::memory::desc &md) {
    return md.data.format_kind == dnnl_blocked
        && md.data.format_desc.blocking.inner_nblks == 1
        && md.data.format_desc.blocking.inner_idxs[0] == 1
        && md.data.format_desc.blocking.inner_blks[0] == 4;
}

// in your implementation
if (is_4c_blocked_format(bnorm_src_md) {
    // reorder bnorm_src --> bnorm_src_nChw16c (assuming you are on avx512)
}
```

---

Slightly unrelated, but still. It seems you have `conv -> batch norm` pattern and you do inference. In this case it is beneficial to embed the batch normalization parameters to the convolution weights. This should significantly improve overall performance.

**Comment by pinzhenx** [comment]
Hi @emfomenk 

Thank you for the detailed scope for fixing and the solution.

Unfortunately, I'm not dealing with graph based inference so there's no way to implement conv-bn fusion in my scenario. Anyway, thanks for the suggestion and look forward to seeing this resolved.

**Comment by vpirogov** [comment]
Closing as stale.
