### ISSUE TITLE
Public API to check if igemm is optimized for the current platform

### ISSUE THREAD

**Issue by guillaumekln** [oneapi-src/oneDNN#620]
# Summary

When specific conditions are not met, igemm functions could run a slow [reference implementation](https://github.com/intel/mkl-dnn/blob/master/src/cpu/gemm/s8x8s32/ref_gemm_s8x8s32.cpp). The library should expose a public function to check whether the fast execution will be chosen at runtime so that library users can act accordingly.

# Problem statement

Currently, there is no good way to know if igemm function will select an optimized code path. This could be problematic when building a single binary for multiple target platforms: depending on the current CPU, igemm could be slower than a basic sgemm.

For this reason, the function described above could help library users to choose a different code path, e.g. falling back to sgemm or using a igemm from another library. 

# Preferred solution

A simple function that returns a boolean could be enough (e.g. `dnnl_has_fast_int8_gemm`).

Alternatively, exposing a function similar to [`mayiuse`](https://github.com/intel/mkl-dnn/blob/077d70363b026036ab08f838841ce464e60c42f2/src/cpu/cpu_isa_traits.hpp#L153) could be helpful to get started: this would enable developers to implement this runtime check while assuming some implementation details.

**Comment by rsdubtso** [comment]
Hi @guillaumekln. 

First, beg your pardon for neglecting this for over a month. The question is not an easy one...

It probably would have been better for DNNL to not fall back to a reference implementation, but it is not always possible. A potential change that I think may works for the library is to add a flag that would be to allow gemm-like functions to return an error status instead of calling reference implementation, but that would require DNNL to introduce new entry points to preserve backwards compatibility.

Can you please share more information on how you would handle such conditions? What 'other library' would you call?

**Comment by guillaumekln** [comment]
Thanks for the update.

> Can you please share more information on how you would handle such conditions? What 'other library' would you call?

Sure. For the context, we are building a single binary to execute neural machine translation models. Models are typically released in reduced precision (e.g. int8 or int16) to save on storage and bandwidth and possibly have a faster runtime. At this point the target compute platform is unknown as we offer on-premise deployment.

Now when loading the model, we have to check if the current platform can run the reduced precision in an optimized way. Assuming we are using the latest DNNL version and we somehow detect that `dnnl_gemm_s8s8s32` will not run fast, we would requantize the weights to int16 and fallback to `cblas_gemm_s16s16s32` from Intel MKL. The fallback logic gets more complicated if we also consider AMD (where Intel MKL should be avoided) and GPU.

The main point is that we want to offer the best performance, whether the input weights are in int8, int16, or float.

**Comment by rsdubtso** [comment]
Understood. Is there a particular combination of GEMM parameters that you need to *not* fall back to the reference implementation? I'll discuss our options regarding GEMM with the team. 

PS. I would be surprised if the int16 variant would be faster than SGEMM on Intel CPUs for all practical purposes.

**Comment by guillaumekln** [comment]
> Is there a particular combination of GEMM parameters that you need to not fall back to the reference implementation?

We are using the s8s8 variant with all offsets set to 0. Is that what you were asking?

> PS. I would be surprised if the int16 variant would be faster than SGEMM on Intel CPUs for all practical purposes.

Our models are up to 35% faster on AVX2 with int16 weights compared to float32 (with similar outputs).

**Comment by rsdubtso** [comment]
> We are using the s8s8 variant with all offsets set to 0. Is that what you were asking?

Sorry for confusion. I was asking about cases that are useful to you and that you observe to fall back to reference and hence you need this function.

**Comment by guillaumekln** [comment]
I'm mostly interested in cases where `mayiuse(avx2)` is false.

**Comment by kruus** [comment]
Suggestion: Perhaps the info string is enough? For a couple of other primitives :ref, :jit, or :blas suffixes are added to the name.  Searching for ":ref" in the `primitive_descriptor::info()` string could be introduced for other primitives, as the need arises, without adding new functions.

**Comment by vpirogov** [comment]
Starting from v1.2 we should have all the int8 functionality optimized for Intel AVX2, including GEMM. Is there anything still missing?

**Comment by guillaumekln** [comment]
This issue discusses a way for library users to detect when int8 GEMM is not optimized, e.g. on pre-AVX2 hardware. Currently it silently falls back to a slow reference implementation.

The change proposed by @rsdubtso could be a solution:

> A potential change that I think may works for the library is to add a flag that would be to allow gemm-like functions to return an error status instead of calling reference implementation

**Comment by kruus** [comment]
@guillaumekln I'm suggesting that int8 igemm can use a _hack_, in the meantime, to detect ref impls. What do your "dnnl_verbose,create," info strings look like?  Do they mirror the suggestive string value of [IGEMM_S8U8S32_ISA_STR](https://github.com/necla-ml/gen-dnn/blob/e0f6b9d2dcca1375b7bbcb2c9bcb516a3bddc973/src/cpu/gemm/gemm.hpp#L68) ?  Looking at the code, I guess you might see an ":any" suffix, instead of ":avx512_core_vnni" or ":avx512_core" suffixes.  So you might be able to write a hacky igemm ref impl detector today.

@rsdubtso's proposal certainly solves your issue.  On the other hand, if other jit primitives potentially might also want to forbid fallback/ref impls, might an attribute be in order?

**Comment by guillaumekln** [comment]
@kruus Thanks for the suggestion. However, `dnnl_gemm_s8s8s32` is not a primitive and does not trigger any verbose logs. So it does not seem like we have access to such information.

**Comment by kruus** [comment]
Gotcha.  BTW, while improving the "gemm API", consider gathering gemm DNNL_API declarations in (maybe renamed) `gemm/os_blas.h`, which could be included via `cpu_isa_traits.hpp`.  This would get rid of some annoying 'extern' code duplication in gtests that want, like @guillaumekln, direct access to the "gemm API" functions.  All the gtests include cpu_isa_traits already, I think.

**Comment by rsdubtso** [comment]
Hi @guillaumekln, just to keep you updated: it may take a while until this will be worked on and it will probably miss the 1.3 timeframe. Feel free to post a PR if this is blocking you...

**Comment by guillaumekln** [comment]
Thanks for the update! This is not a blocking issue.

**Comment by vpirogov** [comment]
@guillaumekln, we are currently working on int8 GEMM optimizations for SSE4.1 ISA. Will this cover your needs or you are targeting even older systems?

**Comment by guillaumekln** [comment]
Yes, this is enough to cover most usages.

**Comment by vpirogov** [comment]
int8 GEMM optimizations for SSE4.1 and AVX are promoted to master and will be released in v1.4.
