### ISSUE TITLE
CPU dispatch and VANILLA build

### ISSUE THREAD

**Issue by kruus** [oneapi-src/oneDNN#664]
# Summary
Two related features are support for cross-compiling and CPU dispatch to VANILLA.  Both involve making a more precise code boundary between JIT and non-JIT code, as well as touching (eventually) hundreds of files.  Rather than a monolithic merge, here is a proposal for how to proceed.

Already, the Intel team has improved the ref impls to a point that I no longer notice a huge time difference running all examples and gtests in a VANILLA build compared to a JIT build.  So here's some ideas on how to move in the direction of having the Intel master code harmonize better with a cross-platform VANILLA build.  Note that the reference impls seem to all be there already. It's just that they are mixed in with jit optimizations, for expediency.

I address two questions:

1. How the public API changes.
1. How to proceed in baby steps toward the ultimate goal.

Please provide alternate ideas about sub-goals, non-goals, priorities, potential pitfalls, etc.

# Problem statement
Currently, many layers require a little bit of work to compile and pass all tests without xbyak or jit_\* impls.  All non-jit src/*.hpp files, src/cpu/gemm/ and src/cpu/rnn/ can provide portable reference impls with fairly non-intrusive changes.
Preparing for CPU dispatch to VANILLA and a VANILLA-only libdnnl build involves some internal header changes, introducing a few API changes.  We need to agree on some changes in semantics of terms used in public and internal APIs.

Long-term desired behaviour is to add and fiddle with cmake toolchain file[s] on a fork of mkl-dnn and build VANILLA on a fork, passing all tests.  I expect clang-based cross-compilers should "just work" doing this.

# Preferred solution

## api
The main API change centers about 3 terms that can define how a cross-platform build goes.  My current thinking is that a _cross-platform view can support 3 abstractions_ of ISA: **VANILLA, ANY, and ALL**.  For x86 the only 2 important ones are the default build [ALL bells and whistles], as usual], and VANILLA ("cross-platform" ref impls only).  ANY is more of a semantic issue, where the generic meaning is "lowest common denominator" -- differing from VANILLA only by lacking the _cross-platform_ requirement. For x86 ANY might alias to SSE41 (I didn't, because the semantic meaning of ANY is technically different).

#### dnnl.h, dnnl.hpp, dnnl_config
Internally, I would like dnnl_cpu_isa_t to add a "vanilla" value (and maybe an "any" value).  "All" can retain its value.  Assigned values are arbitrary, mapped to bitmasks (now sometimes cpu-specific by extending cpu_isa_traits.  Fairly early, dnnl_config.h provides a DNNL_BUILD_STRING so log files can clearer mark any deviations from a default build.  Prefer to pass "-Dxxx" compiler options via dnnl_config.h so they leave a permanent record of the build target.
Should dnnl_version also record the DNNL_CPU and DNNL_ISA build? (These can be uninterpreted int values, whose meaning is in dnnl_config.h).

## PRs might be organized into a number of "preparatory" steps.
a) internals consult "src/common/cpu_target.h" to set up 0/1 preprocessor symbols with a standard naming scheme:  I currently use TARGET_cpu[_subtype] values:  TARGET_X86, TARGET_X86_JIT, and as an initial cross-compile example TARGET_VE. cpu_target.h at this point is a stub, that towards final stages can get set up via cmake.
How  TARGET_xxx values come from 'cpu' and 'subtype' info:
  -  cpu_target.h also sets a value of DNNL_CPU to a constant DNNL_CPU_X86 (anything capable of using xbyak) and DNNL_CPU_VE (for testing a non-xbyak build)
  - cpu_target.h fixes values of DNNL_ISA to one of 3 values: DNNL_ISA_VANILLA, DNNL_ISA_ANY, or DNNL_ISA_ALL
  - when finally "ready for prime time", we add support for auto-determining DNNL_CPU from CMAKE_SYSTEM_PROCESSOR, and add the option to control DNNL_ISA.
    - Values passed via dnnl_config.h.in, which also sets up a DNNL_BUILD_STRING that is printed near beginning of benchdnn and gtests (must avoid confusion once multiple builds are possible).
    - cpu_target.h translates various DNNL_xxx from dnnl_config.h to the more readable TARGET_xxx things that will end up sprinkled in src/.
    - ... and into tests/benchdnn/ and tests/gtests/  (later, may clean up skips or unimplemented with appropriate SKIP clauses).

b) Individual layer PRs retain always use default build settings for cpu_target.h; i.e. DNNL_CPU=DNNL_CPU_X86, TARGET_X86_JIT=1, so PR execution can be auto-tested.  Values in cpu_target.h can be hand-modified to !TARGET_X86_JIT to generate a compiler error if any jit headers get pulled in, or to !TARGET_X86 to verify that a VANILLA reference-only compilation is possible.
  - *Note:* As soon as a cpu-dispatch-to-VANILLA PR is done, one could at least hand-test execution of the particular PR layer in gtests and benchdnn, even though the full test battery will naturally fail (until all layers actually have a cross-platform ref impl).  cpu-dispatch-to-VANILLA is lies mostly in cpu_isa_traits and its cpu_isa_xxx gtests.
  - I also guarantee that some final full-ish set of layers are working in a full VANILLA build in one of my gen-dnn branches;

c) Finally cmake is configured to allow a `DNNL_ISA=VANILLA` option, after all layers have individually been tested.  Such a *baseline cross-platform build* has no xbyak/jit, yet still provide a reasonably complete set of portable impls (examples, tests, gtests and benchdnn run)
  - We are OK if some are missing (ex. a vanilla build is ok without packed-int gemm and many bfloat16 operations).  Ref gemm is OK as it is (a wee bit slower) since the USE_CBLAS option is the expected cross-platform speedup.  We are OK if some run slowly (various int8 things). Ref rnn is see is sometimes many times slower (have not investigated) and this is OK too.

## Moving on to cross-compile friendliness:
d) On Intel master cross-compilation cmake files support DNNL_ISA targets VANILLA, ANY and ALL.  Internally, the 3 cases are distinguishable, but only vanilla impls are provided.  Functioning support for whatever the ANY...ALL spectrum might mean and do "*belongs-on-fork*".
e) a couple(?) of headers get added for optimization macros that can vary widely between compilers, and can always default to "expand-to-nothing"  (openmp pragmas, peculiar optimization hints).
f) Above PRs should choose between TARGET_X86...|VE booleans so that TARGET_X86 code version is the one that is used by default (on a new target cpu)
  - The mkl-dnn master code base makes no promises about a VANILLA build, except that *it ran OK on an x86 not too long ago*.  (I reject a very large number of my own customizations as "too intrusive").
  - Some code reorganization may be useful to better localize and provide support functions for common or foreseeable cross-platform issues.
  - It's OK for vanilla TARGET_mycpu code blocks that severely impact code readability to be rejected as "*belongs on cpu-specific fork*" (can document issue as a comment).
  - Adding optimization macros for cross-compilations is OK. They are likely short one liners and typically multiple pragmas can be bunched on the line before the 'for' loop.  The eye-clutter of maintaining the macros gets punted into separate optimization headers.
  - I suggest a decent general rule is to accept `TARGET_other` code blocks if they address an execution bug or localizable compiler bugs.  Changes just to avoid cross-compilation warnings should be avoided.  (Oops.  I don't quite follow my own suggestion)

### VANILLA capabilities (todo items)

I'm not sure about alternate reference layers (ex. lrn loop order gives me vector length 5 on VE, not great with up to 512 floats per register).  Separate file? Same file? Perhaps "belongs on fork" is best, until x86 benchdnn comparisons can prove a need.

Comments about how AARCH64, ARM64, [insert your cpu here] fit into this are also welcome -- I know little about today's more popular chipsets :)

**Comment by rsdubtso** [comment]
I would suggest using `DNNL_CPU=<foo>` as the way to control this. (`DNNL_CPU=VANILLA|x86_64|...`)

**Comment by rsdubtso** [comment]
Tagging @nSircombe

**Comment by kruus** [comment]
> I would suggest using `DNNL_CPU=<foo>` as the way to control this. (`DNNL_CPU=VANILLA|x86_64|...`)

At what level (cmake, public headers or internal)? It looks like you are suggesting a cmake option.

There are 2 build concepts needed: (i) a simplified cpu type (x86-jit-capable vs. other archs) and this is set _automatically_ from whatever cmake[+toolchain] says; and (ii) feature level (vanillla, [any,] all), which is _user-controlled_.  Using VANILLA and x86_64 together mixes an "feature" spec (user-controllable) with a "cpu" target, which I'd like to avoid at cmake level.

@nSirCombe Might there be a future need to distinguish src/cpu/ code blocks for aarch64 or arm64 from my proposed catch-all DNNL_CPU==DNNL_CPU_X86? TARGET_AARCH64 remains as is, I think, to serve its (2?) other purposes. The other likely xbyak-related consideration is that if xbyak use and immintrin.h availability are synonymous, the internal DNNL_X86_64 can be deprecated.

**At cmake level** the user-specifiable simplest-case feature spec (instead) offers 2 choices: `DNNL_ISA=VANILLA | ALL(default)`.  VANILLA is CPU-agnostic.  'ALL' does the right thing, regardless of auto-determined x86_64 or MYCPU. The build variables are passed via include/dnnl_config.h, retaining a DNNL\_ prefix (cpu tests like DNNL_CPU==DNNL_CPU_MYCPU, and feature tests like DNNL_ISA==DNNL_ISA_VANILLA|ALL). non-x86 cross-compilations may enjoy having an 'ANY' case available, although x86 builds do not need to expose it.

**Internally** (in src/common/cpu_target.h)  TARGET_xxx booleans **do** sometimes cover combination-cases.  Initially, only a few seem useful: *TARGET_X86* (DNNL_CPU==DNNL_CPU_X86),  *TARGET_X86_JIT* (TARGET_X86 && DNNL_ISA!=DNNL_ISA_VANILLA), and *TARGET_MYCPU*. I suggest such booleans because few seem to be needed and it keeps '#if's short and sweet.

**Comment by nSircombe** [comment]
Thanks for the heads-up, this is really interesting. 

> Might there be a future need to distinguish src/cpu/ code blocks for aarch64

Yes, indeed there might! with a further distinction between Neon and SVE ISAs.

**Comment by kruus** [comment]
The closed PR has the general approach, but you might get by only looking at cmake/options.cmake and include/dnnl_config.h.in and imagining what you might need.  My working branch for VANILLA dispatch and non-jit build is at https://github.com/necla-ml/gen-dnn/tree/vanilla-pull.  Today I looked at vanilla-build rnn and got it passing tests :)

**Comment by rsdubtso** [comment]
I think we may need some more dramatic code reorganization to accommodate non-x86 CPUs better. This would make it less intrusive, but we need to be very careful about the code that is on one hand generic and can be used across multiple CPUs, and, on the other hand, may require some platform-specific features (like a function to get a number of the cores in the system).

**Comment by kruus** [comment]
@rsdubtso  please add to list of cross-platform necessities that routinely get handled:
- cache-line, and page-alignment (several locations),
- cache sizings (for gemm), and
- simd vector length (no influence on ref impls iirc).
So far I've assumed OpenMP would be sufficiently cross-platform to handle any number of CPUs.  What chipsets or layers might benefit from an internal number-of-cores function?

**Comment by emfomenk** [comment]
Hi @kruus,

Sorry for the long pause in the discussion.

I would like to understand a little better the motivation behind this dispatch idea. I do understand the desire of splitting jit (read non-portable) vs non-jit (portable) implementations -- this makes total sense to me.
But I don't follow on why VANILLA 'isa' would be of any help here. 

Say, tomorrow (if only that could be true), we will reorganize the `src/cpu` directory in to `src/cpu/x64/` (for x64-specific implementations, read jit) and `src/cpu/*.*` with the portable  implementations -- wouldn't it be exactly what you are looking for? In this case, the current definition of `isa` (e.g. `DNNL_MAX_CPU_ISA`) will be indeed vague, except for `all`. But this shouldn't be a big deal. If other architectures will want to add their own ISA control, we could add that to the `dnnl_cpu_isa_t` too (we only need to understand how to separate x64 / arm / ... isa to avoid confusion).

**Comment by kruus** [comment]
No problem taking time to think through the design carefully.

I think of cpu dispatch to vanilla as a first step in getting code organized.  It introduces the concept of something that can compile without xbyak. A second easy benefit is the a full vanilla libdnnl, a suitable baseline for cross-compiling.

In principle `src/cpu/x64` is a nice goal, but currently many impls share standard boilerplate code with the ref impl. To avoid duplicating this common scaffolding, which changes periodically, a few `#if`s often *can* do the trick [for now].  I.e. VANILLA code is [sometimes] a *messy subset* of the current codebase, rather than a nice clean file-based partitioning.

Going for a clean partitioning (while somehow reusing the common scaffolding code) seems a great eventual goal, though, and the number of cases with invasive changes is not enormous.  The `ifdef` approach only hints at how to work towards a clean separation, buto-invasive chanages.`ifdef`s (eventually 'skip' tests) in `tests` for unsupported vanilla things need doing either way.

Once satisfied with code *partitioned* for vanilla dispatch or build, forks adding a `src/cpu/mycpu/` (to provide an optimized `all` isa targets for `mycpu`) still may get stuck with some copy-paste issues to provide optimized variants of kernels in the `#if` approach ... **Oh**, *quite possibly this too might benefit from delineating between jit/ref kernels and the common scaffolding code* --- I'm once again finding your design idea to have merit :)

Do you prefer to properly partition a `src/cpu/x64` first, rather than beginning with a simple delineation of the various code / struct boundaries?

**Comment by emfomenk** [comment]
> Do you prefer to properly partition a src/cpu/x64 first, rather than beginning with a simple delineation of the various code / struct boundaries?

Yeah, I think it shouldn't take much time and effort, but would make the code much cleaner and more manageable. I created an RFC for this restructure. Please take a look and let me know if I miss anything there. The plan is to separate x64-specific (read jit) code, but keep the generic things in `cpu/`. The `#if` are inevitable, but I expect them in very few cases actually (covered in RFC).

**Comment by kruus** [comment]
Sorry for delays, I missed the merge into master... quick initial comments as I check things.

- Is it true that to compile on x86 without jit you must configure with `cmake -DDNNL_TARGET_ARCH=ARCH_GENERIC` *and nothing else*?  `platform.hpp` admits only 3 magic string values.  My first expectation was that anything unrecognized would turn off jit.

- DNNL_ENABLE_PRIMITIVE_CACHE is unused.  I have often implemented the OFF option to simplify code for debugging.  Should the option description state it is deprecated and ignored?

- `test_iface_primitive_cache` FAILED.  Is *vanilla* cache missing some initialization for the generic build?

Many thanks for commit dcffcf9b90c2d66f89f43f57dca23d336e67fc02 :)

**Comment by emfomenk** [comment]
Hi @kruus,

> - Is it true that to compile on x86 without jit you must configure with cmake `-DDNNL_TARGET_ARCH=ARCH_GENERIC` and nothing else? 

Yes and (a little bit) no:
- Yes, because currently specifying anything else through CMake will make `platform.hpp` to try to auto-detect the architecture ([link](https://github.com/oneapi-src/oneDNN/blob/57eb97d882c292e54d150fc3cbf765e48dc808fb/src/cpu/platform.hpp#L32-L38)), which will be detected as x64 (assuming you are on such system) and this in tern will lead to `#include "xbyak.h"` and other headers;
- No, because if you pass to cmake anything but `X64` the `src/cpu/x64` won't be included ([link](https://github.com/oneapi-src/oneDNN/blob/57eb97d882c292e54d150fc3cbf765e48dc808fb/src/cpu/CMakeLists.txt#L65-L67)).

Summary: this would lead to a broken build. So, the stock version must be built with `cmake -DDNNL_TARGET_ARCH=ARCH_GENERIC`. The expectation is that new architectures would extend the corresponding part of `platform.hpp` and cmake.

> with DNNL_ENABLE_PRIMITIVE_CACHE=0, test_iface_primitive_cache fails. (Probably for normal build too, although I see it for the vanilla build)

Looks like a bug, thanks! Will look into that. Maybe the test should be simply skipped in this case.

>  A tricky bit is that if disabled, `primitive_hashing.[hc]pp` are still used within jit convolutions.

IIRC, this is a lazy way to compare two primitive descriptors. Probably, there is a better way to implement the comparison...

**Comment by kruus** [comment]
Yes, should skip the test.  Reusing the hashing key code is just good **"code reuse"**, not laziness. I only discovered it when making `src/common/primitive_cache.[hc]pp` empty during preprocessing for my ports.  The current short-circuiting of cache function is fine.

I haven't looked at CPU dispatch, but having been able to build and test vanilla on x86, I'm happy to close this enhancement.  I'll need some weeks to fit the VE port into the new, nice organization.

**Comment by emfomenk** [comment]
I am glad to hear the refactoring works (or seems to work) for you, @kruus.
Please let us know if something is missing.
Looking forward for future RFCs! :)
