### ISSUE TITLE
Addition of basic AArch64 validation.

### ISSUE THREAD

**Issue by nSircombe** [oneapi-src/oneDNN#679]
# Summary
https://github.com/intel/mkl-dnn/pull/658 made minimal changes to the build system to enable a DNNL build on AArch64.
This request is to consider the inclusion of AArch64 validation.

# Problem statement
As of https://github.com/intel/mkl-dnn/pull/658, DNNL builds natively with GCC on AArch64 systems. This provides a basis for the development of AArch64 specific code - it would be beneficial to defend this position in DNNL's CI.

Full cross-platform support may require more substantial changes (c.f. https://github.com/intel/mkl-dnn/issues/664), and in-depth validation will be required at some point to cover AArch64 specific code. These issues are not addressed here.

# Preferred solution
Drone CI (https://drone.io/) provides free cloud based CI for OS projects, support for AArch64, and integration with GitHub.

The ['feature/aarch64_ci' branch in this fork](https://github.com/nSircombe/mkl-dnn/tree/feature/aarch64_ci) contains a basic drone CI [config](https://github.com/nSircombe/mkl-dnn/blob/feature/aarch64_ci/.github/automation/.drone.yml). The results of a series of breaking/fixing commits can be found [here](https://cloud.drone.io/nSircombe/mkl-dnn/).

Note: 
- https://github.com/nSircombe/mkl-dnn/tree/feature/aarch64_ci reverts https://github.com/intel/mkl-dnn/commit/5bc2f6090b6bebb186715abd7a907cdd380c42d2 to make sure the tests ignore the unimplemented packed sgemm kernel (see https://github.com/intel/mkl-dnn/issues/678).
- It was necessary to relax `-Werror`.
- Only targets arm64 (AArch64) architecture, and Windows and MacOS variants are not included (Note: Drone CI Cloud does not appear to offer MacOS, but does provide x86 linux and Windows flavours).
- There is no Ubuntu 16.04 clang variant, as there is no pre-built clang-9 package available for Ubuntu 16.04.

**Comment by emfomenk** [comment]
Hi @nSircombe,

Thanks for this proposal and prepared branch!
LGTM 👍 

I have one quick question:
- You said there was a need to relax `-Werror`. I couldn't find this in you branch, though.
    - Also, what went wrong? Does it make sense to fix those warnings/errors?

Regarding the procedure.
Currently the workflow on our side looks as following:
- Develop in the internal repo with internal CI (that runs on a variety of different HW-configurations and compilers)
- Once CI is green -- promote the most recent changes to GitHub

The CI that we have here, on GitHub, was mostly designed for the external PRs to make some light validation. Before the final merge we typically run those PRs through our internal CI.

With this being said, I wonder what should be the protocol on our side to validate arm64 builds. In the short term the simplest way is to keep the current scheme as is, but monitor that non of our updates break the arm64 validation. If this happens -- fix as soon as possible.
@nSircombe, are you fine with this for time being?

But we probably can work with our Infra team, so that before promoting our changes to GitHub we push a special branch (say, `master-validate`) and run CI here. Once green too, do the final promotion to `github/master`.

Summoning @vpirogov for his opinion.

**Comment by nSircombe** [comment]
Hi @emfomenk,

Thanks for taking at look at my CI demo.

> You said there was a need to relax -Werror. I couldn't find this in you branch, though.

I added "-Wno-error=attributes" with the other AArch64 specific flags in platform.cmake here: https://github.com/nSircombe/mkl-dnn/blob/34117d43a2a4c17987e230495952dbeea7f86b80/cmake/platform.cmake#L144.

The warning comes from over-aligned types in `/src/cpu/jit_avx512_common_convolution_winograd.cpp`

```
src/cpu/jit_avx512_common_convolution_winograd.cpp: In function ‘void dnnl::impl::cpu::input_transform_data(int, const dnnl::impl::cpu::jit_conv_winograd_conf_t&, float*, float*, bool)’:
src/cpu/jit_avx512_common_convolution_winograd.cpp:434:46: warning: requested alignment 64 is larger than 16 [-Wattributes]
  434 |     alignas(64) float Iw[alpha][alpha][simd_w];
      |                                              ^
```

Thanks for the background on your approach to CI and validation. @vpirogov was also kind enough to take me through the basics. Clearly we will need to setup our own AArch64 CI to do more exhaustive validation of AArch64 specific code, and help us defend against performance regressions. 

However, in the short-term (with no _real_ AArch64 specific code to defend!) just having your patches run through the 'light touch' CI would be extremely useful. Your suggestion sounds ideal to me, if it's practical for you.

**Comment by vpirogov** [comment]
Hi @nSircombe,

We will be happy to have Drone CI running on this repository to cover aarch64 alongside with existing Azure CI. @sakulish, who supports our infrastructure, is reviewing the configuration and may have some suggestions.

**Comment by sakulish** [comment]
Hi @nSircombe, sorry for late response. Please remove clang format check, just to not duplicate one from Azure. Regarding everything else I do not have any objections

off-topic: DroneCI have really good plugins for AWS, but it is a pity that OSX is not supported

**Comment by nSircombe** [comment]
Hi @sakulish,

> Please remove clang format check, just to not duplicate one from Azure. 

Yep, no problem. I'll make that change in my fork.

...before I forget, one other tweak I had to make that's I forgot to highlight explicitly above - I had to alter the [test.sh](.github/automation/test.sh) to return the return from the `ctest` line as it was the simplest way to hook it up to Drone. I don't think this will cause a problem for the Azure CI?

Should I put in a PR once I've disabled the clang-format test?

**Comment by sakulish** [comment]
@nSircombe it definitely should not affect, we are handling errors in clang format check right the same way
Yes, please remove clang format check firstly

**Comment by nSircombe** [comment]
Ok, I've updated https://github.com/nSircombe/mkl-dnn/tree/feature/aarch64_ci

**Comment by sakulish** [comment]
@nSircombe , I checked changes in your fork and there are a couple of things that should be done before we merge this
1) Align commit messages with our format <scope>: <short description>(for example "ci: added opensource ci")
2) Create PR with DroneCI configuration only (I see code changes in you PR)

**Comment by nSircombe** [comment]
Hi @sakulish 
Of course, no problem. I think the code changes have now been resolved in other PRs. I'll tidy up and put the Drone CI changes in a clean PR.

**Comment by nSircombe** [comment]
Hi @sakulish, 
I've raised a PR now - #694.
This is dependent on both #693 and #685.

**Comment by vpirogov** [comment]
While the changes were merged in repository we still need to configure Drone CI. Reopening this issue until configuration is complete.

**Comment by vpirogov** [comment]
aarch64 CI is [up and running](https://cloud.drone.io/oneapi-src/oneDNN).

**Comment by nSircombe** [comment]
Great news! @vpirogov, @sakulish, @emfomenk - thanks for all your help with this.

@emfomenk suggested a workflow whereby Intel commits were first pushed to a staging branch ("master-validate") to run the CI before final promotion to github/master - I that still an option being considered?

**Comment by emfomenk** [comment]
@nSircombe,

On second thought and after a talk with @vpirogov, I think that extra staging step is probably not a good idea. I suggest we do the following:
1. Short term:
    - Keep the procedural things as they are now. Once our internal CI is green we promote the changes to GitHub directly. We will monitor the CI of the `github/master` and if we accidentally break it, we will fix that ASAP.
    - We promote #698, and will turn the light validation of the non-x64 build (see **Way to test / x64** in the description) in our internal CI
        - As this flow is almost the same for ARM AArch64, this light validation should significantly reduce the possibility of breaking ARM AArch64 CI
2. Middle term:
    - We enable ARM AArch64 build in our internal CI (using cross compilation, hopefully it is not that difficult). This should almost eliminate the chance of breaking ARM AArch64.
3. Long term:
    - We are working on migrating the main development on GitHub.

The timeline:
1. 1-2 weeks.
2. Depends. I need to check how hard it is to setup the environment on x64 platform (if it is possible at all). Your guidance would be very helpful. Also, summoning @sakulish, if he sees any major issues with this approach.
3. Who knows? :) I think this will happen sooner than later, maybe towards the EoY. Cannot really estimate right now. But we are pretty seriously considering this option.
