### ISSUE TITLE
file problem creating directory: /usr/local/lib/cmake/mkldnn

### ISSUE THREAD

**Issue by yurivict** [oneapi-src/oneDNN#683]
The version 1.3 fails during the```install``` target:

```
-- Installing: /usr/ports/math/onednn/work/stage/usr/local/lib/cmake/dnnl/dnnl-targets-release.cmake
CMake Error at /usr/ports/math/onednn/work/oneDNN-1.3/cmake/gen_mkldnn_compat_cmakes.cmake:25 (file):
  file problem creating directory: /usr/local/lib/cmake/mkldnn


-- Installing: /usr/ports/math/onednn/work/stage/usr/local/lib/libmkldnn.so
```

FreeBSD 12

**Comment by rsdubtso** [comment]
Hi @yurivict . I cannot reproduce this. You need to provide complete info. It would be also nice if you could provide exact source code modifications made to the package as DNNL won't build on FreeBSD out of the box.

**Comment by yurivict** [comment]
I can't reproduce this myself now.
