### ISSUE TITLE
GRU Primitive Creation Error.

### ISSUE THREAD

**Issue by redhairdragon** [oneapi-src/oneDNN#688]
Hi, I am creating a really simple GRU function. It keeps showing
 "terminate called after throwing an instance of 'dnnl::error'
  what():  could not create a descriptor for an LBR GRU forward propagation primitive
Aborted (core dumped) "
Can anyone help me? I know this can be stupid. But I just cannot figure out why.

```
#include <algorithm>
#include <cmath>
#include <cstring>
#include <iostream>
#include <numeric>
#include <string>
#include <vector>
#include "dnnl.hpp"

using namespace dnnl;
using std::cout;
using std::endl;

using tag = memory::format_tag;
using dt = memory::data_type;
using dim_t = dnnl::memory::dim;

const memory::dim N = CHUNK_SIZE,  // batch size
    T = 1,                   // time steps
    C = 600,                         // channels
    G = 3,                         // gates (GRU has 6->3 U, 3 W)
    L = 1,                 // layers
    D = 1;                         // directions

int main(int argc, char** argv) {
    // Create execution dnnl::engine.
    engine engine(engine::kind::cpu, 0);
    // Create dnnl::stream.
    stream engine_stream(engine);

    memory::dims src_dims = {T, N, 2 * C};
    memory::dims hx_dims = {L, D, N, C};
    memory::dims w_dims = {L, D, 2 * C, G, C};
    memory::dims u_dims = {L, D, C, G, C};
    memory::dims dst_dims = {T, N, C};

    auto src_layer_md = memory::desc(src_dims, dt::f32, tag::any);
    auto src_iter_md = memory::desc();
    // auto src_iter_md = memory::desc(hx_dims, dt::f32, tag::ldnc);
    auto gru_weights_layer_md = memory::desc(w_dims, dt::f32, tag::any);
    auto gru_weights_iter_md = memory::desc(u_dims, dt::f32, tag::any);
    auto bias_md = memory::desc();
    auto dst_layer_md = memory::desc(dst_dims, dt::f32, tag::any);
    auto dst_iter_md = memory::desc();
    // auto dst_iter_md = memory::desc(hx_dims, dt::f32, tag::any);


    auto gru_desc = gru_forward::desc(
        prop_kind::forward_training, 
        rnn_direction::unidirectional_left2right,
        src_layer_md, 
        src_iter_md, 
        gru_weights_layer_md, 
        gru_weights_iter_md,
        bias_md, 
        dst_layer_md, 
        dst_iter_md);

    // Create primitive descriptor.
    auto gru_pd = gru_forward::primitive_desc(gru_desc, engine);
}
```

**Comment by emfomenk** [comment]
Hi @redhairdragon,

It seems we have a bug in the documentation: the bias is not expected to be zero. The fix is the following:

``` patch
-    auto bias_md = memory::desc();
+    auto bias_md = memory::desc({L, D, G, C}, dt::f32, tag::ldgo);
```

I tend to think this is a bug in the documentation and not in the implementation, as for training we assume that bias is a mandatory learnable parameter. However, from the usability perspective, I think nothing prevents us to make bias an optional parameter. @redhairdragon, could you please comment on what is your use-case? In the final application do you need bias or as in the example here you want it to be zero? Is it inference or training?

**Comment by redhairdragon** [comment]
> Hi @redhairdragon,
> 
> It seems we have a bug in the documentation: the bias is not expected to be zero. The fix is the following:
> 
> ```diff
> -    auto bias_md = memory::desc();
> +    auto bias_md = memory::desc({L, D, G, C}, dt::f32, tag::ldgo);
> ```
> 
> I tend to think this is a bug in the documentation and not in the implementation, as for training we assume that bias is a mandatory learnable parameter. However, from the usability perspective, I think nothing prevents us to make bias an optional parameter. @redhairdragon, could you please comment on what is your use-case? In the final application do you need bias or as in the example here you want it to be zero? Is it inference or training?

Thank you very much. I was just experimenting with the API and I saw bias is optional so I just ignored it.
