### ISSUE TITLE
Make documentation building optional, as it can clash when the project is used as submodule

### ISSUE THREAD

**Issue by XapaJIaMnu** [oneapi-src/oneDNN#689]
# Summary
At the moment, Documentation is built by default if Doxygen is found and the target is named the generic `doc`: https://github.com/oneapi-src/oneDNN/blob/master/cmake/Doxygen.cmake#L63

This causes issues such as:
`CMake Error at CMakeLists.txt:437 (add_custom_target):
  add_custom_target cannot create target "doc" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory`
When using OneDNN as a submodule in another project.

Instead, there should be an option such as DNNL_BUILD_DOC, or change the target to `dnnl_doc`, so that it doesn't clash with another generic custom target name.

**Comment by rsdubtso** [comment]
Thanks for the report. This makes sense.

**Comment by rsdubtso** [comment]
A PR would be welcome. Otherwise, this will be done when someone on the team has bandwidth.

**Comment by XapaJIaMnu** [comment]
Done.
