### ISSUE TITLE
binary primitive crashes in the newer version

### ISSUE THREAD

**Issue by nabroyan** [oneapi-src/oneDNN#692]
# Summary
`binary` primitive causes heap corruption/memory access violation after upgrading from 1.1.2 to 1.3.

# Version
DNNL 1.3

# Environment
* CPU Intel i7 9750H
* OS version Windows 10 and Windows WSL Ubuntu 18.04
* Compiler Visual Studio 2019 and WSL gcc 7.4
* CMake version 3.17

# Steps to reproduce
Here is the code, which causes the problem.
```
auto src0_md = src0_memory.get_desc();
auto src1_md = src1_memory.get_desc();
auto binary_desc = dnnl::binary::desc(dnnl::algorithm::binary_mul, src0_md, src1_md, src0_md);

dnnl::binary::primitive_desc binary_pd = dnnl::binary::primitive_desc(binary_desc, eng);
dnnl::binary bin(binary_pd);
bin.execute(strm,
{
	{DNNL_ARG_SRC_0, src0_memory},
	{DNNL_ARG_SRC_1, src1_memory},
	{DNNL_ARG_DST, src0_memory}
});
strm.wait();
```

# Observed behavior
This code was working fine with the 1.1.2 version, but with 1.3 version it either crashes on `bin.execute` or causing `Access violation reading location 0x0000080FFFFFFFFC.` exception while the scope ends.
I have also tried to use a new memory for destination (instead of in-place), but results were the same.

# Expected behavior
Not to crash.

**Comment by vpirogov** [comment]
Hi @nabroyan,

Could you please run the code with environment variable `DNNL_VERBOSE=1` and post the resulting log here?

Vadim

**Comment by nabroyan** [comment]
Hi @vpirogov 

Thank you for quick reply.
Here is the log of my test:

> dnnl_verbose,info,DNNL v1.3.0 (commit 07579e6c0c6839a390a6f3040e05a2b2c71e628a)
> dnnl_verbose,info,cpu,runtime:OpenMP
> dnnl_verbose,info,cpu,isa:Intel AVX2
> dnnl_verbose,info,gpu,runtime:none
> dnnl_verbose,exec,cpu,inner_product,gemm:jit,forward_inference,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:a:f0 dst_f32::blocked:ab:f0,,,mb1ic12oc12,16.2939
> dnnl_verbose,exec,cpu,binary,jit:uni,undef,src_f32::blocked:ab:f0 src_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,alg:binary_mul,12x12:1x12 12x12,0.0389

It seems, that there is undefined behavior, as it crashes on different statements on each runs.

**Comment by vpirogov** [comment]
Thanks, @nabroyan. I can reproduce segfault with benchdnn on v1.3 and master.

**Comment by dzarukin** [comment]
Hi! This is indeed a mistake in how spatial was computed.

@nabroyan, could you try [this patch](https://gist.github.com/dzarukin/c4fc3d41e3dcb28b01b557c59e7bb887) to check if it fixes for you?

**Comment by nabroyan** [comment]
@dzarukin , yes the patch fixes for me. Thank you for prompt reply and fix!
