### ISSUE TITLE
Different performance between framework and Benchdnn

### ISSUE THREAD

**Issue by mangoliu1992** [oneapi-src/oneDNN#695]
Hi, I am doing some profiling of oneDNN.
Take this shape of convolution for example: _mb28_ic1oc32_ih28oh28kh5sh1dh0ph2_iw28ow28kw5sw1dw0pw2_

When I set dnnl_verbose, from the framework level I see the execution time is 0.8ms.
However, when I run the it with benchdnn, I see the execution time is 0.14ms.

Since this execution  time is printed by oneDNN from the verbose mode. Why there are difference on the same system?  Do you have any suggestion for me to debug?

**Comment by rsdubtso** [comment]
Hi @mangoliu1992 . This difference may be explained by the fact that benchdnn benchmarks a single operation in a tight loop which means that, for example, the caches are hot, TLB is fully populated, etc. When running a full topology it is typical that only convolutions input is in cache (probably LLC), while the weights are not. This may substantially affect performance. Hope this helps.

**Comment by emfomenk** [comment]
A minor addition / question -- are the version of the library in the application and benchdnn the same?

**Comment by mangoliu1992** [comment]
@emfomenk yes, I use the same dnnl version

**Comment by mangoliu1992** [comment]
> Hi @mangoliu1992 . This difference may be explained by the fact that benchdnn benchmarks a single operation in a tight loop which means that, for example, the caches are hot, TLB is fully populated, etc. When running a full topology it is typical that only convolutions input is in cache (probably LLC), while the weights are not. This may substantially affect performance. Hope this helps.

Thanks for the reply.  That may be the explanation. Do you have any ideas to design some experiments to prove that...

**Comment by mangoliu1992** [comment]
Thanks for the reply. It should be difference between benchdnn and application.

**Comment by dzarukin** [comment]
Hi @mangoliu1992 , to see the influence of cold caches you may try to use benchdnn with `--fix-times-per-prb=1` option and see performance result. It makes a loop iterator over compute function equal to one. This would be somewhat close to what happens in the framework assuming all the data is taken from memory.
