### ISSUE TITLE
INT8 Support for ReLu on GPU

### ISSUE THREAD

**Issue by LeicongLi** [oneapi-src/oneDNN#699]
Hi dnnler, do we have int8 support for ReLu (element-wise) on GPU?
Thanks!

**Comment by emfomenk** [comment]
Hi @LeicongLi,

Yes, we do. In general, GPU and CPU are aligned in terms of functionality (modulo HW data type support [matrix](https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html)). Supported eltwise algorithms could be found in the documentation [here](https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html).

**Comment by LeicongLi** [comment]
Thanks.
