### ISSUE TITLE
Data formats on AVX2 and AVX512

### ISSUE THREAD

**Issue by pranathibl** [oneapi-src/oneDNN#702]
Hi,

I am using a network which has a convolution and Depth-Concatenation on AVX2 and AVX512 machines. 
On AVX512 machine convolution is picking up the data format as  nChw16c, but not on AVX2.
When will nChw16c and nChw8c are choosen?

I am using MKLDNN version v1.0

Thanks,
Pranathi

**Comment by vpirogov** [comment]
@pranathibl,

Memory formats are in general ISA-specific and nChw16c is used for activations on Intel AVX-512 systems. On Intel AVX2 systems you should expect nChw8c instead. We have detailed article on [memory formats](https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html) in the developer guide.

Hope this helps.

**Comment by vpirogov** [comment]
Closing as the question seems to be addressed. Feel free to reopen or submit a new issue if you have any further questions.
