### ISSUE TITLE
In GEMM,what is the function of the variable addr_off_?

### ISSUE THREAD

**Issue by lingweiyang** [oneapi-src/oneDNN#703]

**Comment by vpirogov** [comment]
Tagging @aaraujom.

**Comment by lingweiyang** [comment]
What is the difference between JIT_avx_ gemm_f32.cpp and jit_avx2_kernel_sgemm_kern.cpp?
 Why does the former have an unroll_N = 6 and the latter has an unroll_N = 4?

**Comment by aaraujom** [comment]
Hi @lingweiyang – We use offsets (`addr_off_`) for A and B matrices such that instruction length be smaller. In regards unroll factors, we choose them such that we utilize hardware as best as possible. You can try to change them and check performance. The files `jit_avx_gemm_f32.cpp` and `jit_avx2_kernel_sgemm_kern.cpp` are different sgemm kernels. Please check `src/cpu/gemm/gemm_info.cpp` and `src/cpu/gemm/gemm_driver.cpp` for better understanding.

**Comment by lingweiyang** [comment]
Thanks for your answer. What is the difference between copy and nocopy?

**Comment by lingweiyang** [comment]
What does "pack" mean?

**Comment by aaraujom** [comment]
"copy" means we use copy kernels while "nocopy" we don't. For "pack" it typically means matrix is packed.

Could I ask the purpose of those questions? Are you planning to make a pull request with modified version?

**Comment by lingweiyang** [comment]
I want to study GEMM

**Comment by vpirogov** [comment]
Closing as the question is addressed. Feel free to reopen and submit a new one if you have any further questions.
