### ISSUE TITLE
permute_axes for lstm weight tensor

### ISSUE THREAD

**Issue by affranchi** [oneapi-src/oneDNN#705]
Hi,

I'm trying to use axes permuted weight tensor for lstm but it's not working with message:
"could not permute axes of a memory descriptor"

My code is:

=======================================================

    const memory::dim N = 1, // batch size
            T = 1, // time steps
            C = 2, // channels - hidden_size
            P = 3, // Feature_size
            G = 4, // gates
            L = 1, // layers
            D = 1; // directions

    memory::dims src_dims = {T, N, P};
    memory::dims weights_dims = {L, D, P, G, C};
    memory::dims weights_iter_dims = {L, D, C, G, C};
    memory::dims bias_dims = {L, D, G, C};
    memory::dims dst_dims = {T, N, C};

    auto src_layer_md = memory::desc(src_dims, dt::f32, tag::abc);
    auto bias_md = memory::desc(bias_dims, dt::f32, tag::ldgo);
    auto dst_layer_md = memory::desc(dst_dims, dt::f32, tag::tnc);
    auto src_layer_mem = memory(src_layer_md, engine);
    auto bias_mem = memory(bias_md, engine);
    auto dst_layer_mem = memory(dst_layer_md, engine);

    auto lstm_weights_md = memory::desc({D, G*C, P}, dt::f32, tag::abc);
    auto lstm_weights_iter_md = memory::desc(weights_iter_dims, dt::f32, tag::ldigo);

    auto lstm_desc = lstm_forward::desc(prop_kind::forward_inference,
            rnn_direction::unidirectional_left2right, src_layer_md, memory::desc(),
            memory::desc(),lstm_weights_md.permute_axes({0,2,1}).reshape({L, D, P, G, C}), lstm_weights_iter_md, bias_md,
            dst_layer_md, memory::desc(), memory::desc());
    // Create primitive descriptor.
    auto lstm_pd = lstm_forward::primitive_desc(lstm_desc, engine);

=======================================================

*. Interesting observation here is that src_layer_md with permute_axes doesn't have a problem like the below:

=======================================================

    auto src_layer_md = memory::desc({T,P,N}, dt::f32, tag::abc);
    auto lstm_weights_md = memory::desc(weights_dims, dt::f32, tag::ldigo);

    auto lstm_desc = lstm_forward::desc(prop_kind::forward_inference,
            rnn_direction::unidirectional_left2right, src_layer_md.permute_axes({0,2,1}),
            memory::desc(), memory::desc(), lstm_weights_md, lstm_weights_iter_md, bias_md,
           dst_layer_md, memory::desc(), memory::desc());
    auto lstm_pd = lstm_forward::primitive_desc(lstm_desc, engine); // No error
=======================================================

Can't we use permute axes for LSTM weight tensor?
Please, let me know if I missed something here.

Thanks,
Kenny

**Comment by emfomenk** [comment]
Hi @affranchi,

There are few things here.

First of all the `permute_axes` requires the permutation vector to have the same length as the number of dimensions in the tensor (as it permutes the axes). For the first snippet the `lstm_weights_md` has 5 dimensions, but you pass only 3 values to permute.

Next, the reshape that applied afterwards is basically a way to re-think the memory descriptor, according to the shapes you provided to the reshape function. For instance:

``` cpp
memory_desc md_4D({A, B, C, D}, data_type::f32, format_tag::abcd);
// note that B, C, D that were collapse physically were in the same order
// hence the reshape is a safe operation
memory_desc md_2D = md_4D.reshape({A, B*C*D}); // format aka ab

// however...
memory_desc bad_md_2D = md_4D.reshape({A*C, B*D}); // fails
// because you cannot reinterpret this memory descriptor that
// way, as physically C comes after B, and not after A
```

For the RNN snippet you showed above I don't think it would be a safe operation.

The reshape and permute_axes do not change the data, they operate on memory descriptors only. If you store your data in other than oneDNN physical format, what you need to do is specify the format you have, e.g.:

``` cpp
// note that DNNL requires L, D, P, G, C logical order
memory::dims user_weights_dims = {L, P, D, G, C}; 
// physical axis order corresponds to the logical ones L, then P, then D, then G, then C
auto user_weights_md = memory::desc(user_weights_iter_dims, dt::f32, tag::abcde);

// swap first and second axes
auto lstm_weights_md = user_weights_md.permute_axes({0, 2, 1, 3, 4});

if (check) {
    memory::dims lstm_weights_dims = {L, D, P, G, C}; // this is what DNNL expects
    // note that the format tag is a_cb_de and not a_bc_de, as physically axes are ordered that way
    auto validate_lstm_weights_md = memory::desc(lstm_weights_dims, dt::f32, tag::acbde);
    assert(validate_lstm_weights_md == lstm_weights_md);
}

auto lstm_desc = lstm_forward::desc(..., lstm_weights_md, ...);
```

This would define the correct semantics, but will most likely fail due to oneDNN not supporting this memory format for weights. You should create the weights with format tag `any`, and then reorder the data from the format you have to the one the implementation chooses. Something along the lines:

``` cpp
memory::dims user_weights_dims = {L, P, D, G, C}; 
auto user_weights_md = memory::desc(user_weights_dims, dt::f32, tag::abcde)
         .permute_axes({0, 2, 1, 3, 4}); // the logical dims are {L, D, P, G, C}

memory::dims lstm_weights_md({L, D, P, G, C}, dt::f32, format_tag::any);
auto lstm_desc = lstm_forward::desc(..., lstm_weights_md, ...);

lstm_weights_md = lstm_desc.weights_layer_desc(); // query what the implementation wants
if (lstm_weights_md != user_weights_md) {
    // perform a reorder of data
}
```

**Comment by affranchi** [comment]
Thank you so much for your info. It's very helpful to understand DNNL more.
