### ISSUE TITLE
Perf of sgemm vs matmul primitive

### ISSUE THREAD

**Issue by WilliamTambellini** [oneapi-src/oneDNN#706]
Hello
This is just a call to verify that the perf I see on AWS C5 2xlarge is the expected one.
This is obtained with (slightly modified) examples/tutorials/matmul/cpu_sgemm_and_matmul.cpp :

ubuntu@awsc5:~$ OMP_NUM_THREADS=1 ./cpu_sgemm_and_matmul 
DNNL version: 1.3.0 07579e6c0c6839a390a6f3040e05a2b2c71e628a
               M               N               K           sgemm           dynmm          statmm               
           37682             512             512         1.5e+05       1.496e+05       1.496e+05               
               1             512             512           22.22           24.68           24.69               
               1            2048             512           204.7           327.9             327               
               1             512            2048           177.1           179.1           177.6 

sgemm reports dnnl_sgemm(...)
TIME(dnnl_sgemm(transA, transB, M, N, K, alpha, A.data(), lda, B.data(), ldb, beta, C_sgemm.data(), ldc);)

dynmm reports the dynamic matmul prim using  DNNL_RUNTIME_DIM_VAL : 
TIME(matmul_p.execute(s, {{DNNL_ARG_SRC, A_m}, {DNNL_ARG_WEIGHTS, B_m},{DNNL_ARG_DST, C_m}}); s.wait();)

statmm refers to the execution part of static_matmul_create_and_execute() : 
TIME(matmul_p.execute(s, {{DNNL_ARG_SRC, A_m}, {DNNL_ARG_WEIGHTS, B_m}, {DNNL_ARG_DST, C_m}, {DNNL_ARG_ATTR_OUTPUT_SCALES, alpha_m}}); s.wait();)

According to the doc, the static mm should be the fastest one but here dnnl_sgemm seems actually even sometimes faster. 

Modifications: just wrapping the executions (not creation) in a macro measuring time : 
#define BENCH(X)   std::cout << std::setw(16) << std::setprecision(4) << X; 
#define REPEAT 100
using ct=std::chrono::high_resolution_clock;
ct::time_point start, end;
#define TIME(EXPRESSION)                                                       \
  {                                                                            \
    double total = 0;                                                          \
    for (unsigned jjj = 0; jjj < REPEAT; ++jjj) {                              \
      start = ct::now();                                \
      EXPRESSION                                                               \
      end = ct::now();                                  \
      total += std::chrono::duration<double, std::micro>(end - start).count(); \
    }                                                                          \
    BENCH((total / (double)REPEAT));                                           \
  }

dnnl built with: 
cmake .. -DCMAKE_CXX_COMPILER=$gccdir/bin/g++ -DCMAKE_C_COMPILER=$gccdir/bin/gcc \
 -DCMAKE_BUILD_TYPE=RELEASE \
 -DDNNL_VERBOSE=ON \
 -DDNNL_CPU_RUNTIME=OMP \
 -DDNNL_ENABLE_CONCURRENT_EXEC=ON \
 -DDNNL_ENABLE_JIT_PROFILING=OFF \
 -DDNNL_ARCH_OPT_FLAGS="" 

Note: the input memory buffers are (just) std vectors, how do you guarantee for it to be well mem aligned for the local running cpu ?

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

The fact that matmul shows the same performance for static and dynamic shapes now is expected. 

Currently we just call `dnnl_sgemm` underneath. In the long term, if the shapes are known at primitive creation time we can utilize jit approach to generate a more specific kernel. This could be especially advantageous for the small matrices.

Also, it is worth mentioning, that if we know the shape we will natively support packed gemm through matmul interface, that will allow users to pre-pack one of the matrices and reuse it across different calls. See [this](https://github.com/oneapi-src/oneDNN/blob/9788d45b886c7ff300c786df73da30a66f0b768f/examples/tutorials/matmul/inference_int8_matmul.cpp#L207-L216). Though, this is not implemented yet.

One thing that bothers me in your numbers is the difference between sgemm and matmul. Specifically, this line:
```
1 2048 512 204.7 327.9 327
```

I would expect no significant performance difference between sgemm and matmul. I tried your code but got the following numbers:
```
   37682     512     512        1.457e+05       1.447e+05        1.45e+05
       1     512     512            26.61           28.64           28.36
       1    2048     512            174.9           176.8           176.7
       1     512    2048            174.7           176.6           176.4
```

Parameters: `transa=N', 'transb=T`, `alpha=1.0`. I used the latest v1.4 version (though I don't remember we changed anything related to f32 matmul compared to v1.3).

So to me it looks like an accidental interference happened in your run. Please let us know if this is a reproducible behavior on your side. This might be a bug then.

**Comment by emfomenk** [comment]
The modified example I used:
https://gist.github.com/emfomenk/605469f4a0049fb2656267bbecfe138c

**Comment by WilliamTambellini** [comment]
Hi @emfomenk 
Tks. Perhaps dont trust the perf of this example atm, the IO vectors are not guarantee to be mem aligned. I m retouching it right now to memalign the input/output vectors.
Tks
W.

**Comment by WilliamTambellini** [comment]
Hi @emfomenk 
Here are the new results using mem aligned vectors 
template <typename T>
using aligned_vector = std::vector<T, boost::alignment::aligned_allocator<T, 64>>;
on AWS C5 :

`
DNNL version: 1.3.0 07579e6
ubuntu@awsc5:~$ OMP_NUM_THREADS=1 ./cpu_sgemm_and_matmul 
               M               N               K           sgemm           dynmm          statmm               
           37682             512             512       1.181e+05       1.167e+05       1.163e+05               
               1             512             512           28.23           30.55           30.35               
               1            2048             512           195.2           277.4           275.1               
               1             512            2048           195.9             196           193.9 
`

sgemm 
Do these measures make sens ?

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

No, the numbers do not make sense to me. The last but one line is really weird -- matmul should have the same performance as gemm, while in your case it is 1.42x slower.
I checked out the same revision as you, but still get comparable numbers:

``` bash
$ git log -n1
commit 07579e6c0c6839a390a6f3040e05a2b2c71e628a (HEAD, tag: v1.3, origin/rls-v1.3)
Author: Arthur Mitrano <arthur.araujo.mitrano@intel.com>
Date:   Fri Mar 27 16:12:45 2020 -0700

    benchdnn: ip: add DLRM training sizes

$ OMP_NUM_THREADS=1 ./examples/cpu-tutorials-matmul-sgemm-and-matmul-cpp

   37682     512     512        1.536e+05       1.459e+05       1.451e+05
       1     512     512            25.54           27.63           27.23
       1    2048     512            174.9           177.1           176.9
       1     512    2048            174.3           176.6           176.3
Example passed on CPU.
```

Could you please try using the [modified example](https://gist.github.com/emfomenk/605469f4a0049fb2656267bbecfe138c) that I shared? Maybe we benchmark something different. Because otherwise I don't have any ideas what could go wrong...

**Comment by WilliamTambellini** [comment]
Hi @emfomenk 
Tks. I ve compared my example and yours and they were the same except I was including 
    s.wait();
in the timing macro whereas you are not:
    TIME(matmul_p.execute(s, {{DNNL_ARG_SRC, A_m}, {DNNL_ARG_WEIGHTS, B_m},{DNNL_ARG_DST, C_m}}); )
vs
    TIME(matmul_p.execute(s, {{DNNL_ARG_SRC, A_m}, {DNNL_ARG_WEIGHTS, B_m},{DNNL_ARG_DST, C_m}}); s.wait();)

I ve moved the stream wait outside the timing loop and it does nt seem to change the speed so that's probably not the root cause. 
I also notice that the speed variations differ from run to run.
We are sure to use the same commit (final 1.3) and same CPU (AWS C5) so:
- are you sure you re building dnnl the same way I do ?
- which gcc version are you using ?

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

Yeah, `stream` and `steam::wait()` are nothing for CPU. So that shouldn't be the reason indeed.

I am not using AWS C5, but SKX 8180. Though I don't expect any significant difference in behavior.  The compiler is gcc 4.8, that comes with RHEL 7.

The code is pretty trivial ([link](https://github.com/oneapi-src/oneDNN/blob/07579e6c0c6839a390a6f3040e05a2b2c71e628a/src/cpu/matmul/gemm_f32_matmul.cpp#L191)), as you can see we simply call gemm and that's it. I am really dumbfounded where the difference come from.

Could you please run this one since example only with DNNL_VERBOSE=1 to confirm that the time the library reports matches what the benchmark says?

Also, do you have a chance to check the benchmark on another system? I run it on few different machines on my side, but the behavior is still same: sgemm ~ matmul...

**Comment by WilliamTambellini** [comment]
Here is the output with verbose on:

               M               N               K           sgemm           dynmm          statmm               
           37682             512             512       1.184e+05
dnnl_verbose,info,DNNL v1.3.0 (commit 07579e6c0c6839a390a6f3040e05a2b2c71e628a)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,116.865
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,117.519
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,117.133
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,116.911
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,117.559
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,116.503
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,117.354
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,117.55
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,oscale:0:nan;,,m-9223372036854775808n-9223372036854775808k-9223372036854775808,117.264
...
On other CPUs, the behavior is also strange : sgemm being sometimes slower sometimes faster than the mm prims.

**Comment by emfomenk** [comment]
The output here is ok: verbose for matmul matches the sgemm time. That was also oK in the original output. I am confused by this line:
```
 1            2048             512           195.2           277.4           275.1  
```
where matmul is 42% slower than sgemm.

> On other CPUs, the behavior is also strange : sgemm being sometimes slower sometimes faster than the mm prims.

Looks like some instability in the environment. Maybe this a vcpu and there other people running stuff on the same instance?

**Comment by WilliamTambellini** [comment]
Hi @emfomenk 
I guess we can say that the default AWS C5 instance is technically a VM:
[centos@awsc5 ~]$ hostnamectl
   Static hostname: xxxxxxxxxxxxxxxxxxxxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 05cb8c7b39fe0f70e3ce97e5beab809d
           Boot ID: 7c6c2b33b20a471284babe73fcacdd17
    Virtualization: kvm

W.

**Comment by WilliamTambellini** [comment]
I ve repro on a baremetal reserved machine and run the 512 gemv a 2nd time at the end : the 2nd time, the timings are steady meaning the bug seems to happen only at the 1st exec of small sgemm:   

               M               N               K           sgemm           dynmm          statmm               
           37682             512             512       1.613e+05       1.628e+05       1.612e+05               
               1             512             512           152.1           24.28           19.62               
               1            2048             512           92.49           88.69           87.64               
               1             512            2048           87.62              73           73.33               
               1             512             512           21.65           19.43           19.36

**Comment by emfomenk** [comment]
Hi @WilliamTambellini,

I think the first call requires of gemv requires generating the kernels, that is very expensive (but should be done only once per program).
Could you please changes the example to ignore the very first iteration during the benchmark (somewhere [here](https://gist.github.com/emfomenk/605469f4a0049fb2656267bbecfe138c#file-cpu_sgemm_and_matmul-cpp-L77-L83))?

``` patch
 #define TIME(EXPRESSION) \
 { \
     double total = 0; \
+    EXPRESSION; /* warm up run */ \
     for (int jjj = 0; jjj < REPEAT; ++jjj) { \
         start = ct::now(); \
         EXPRESSION; \
         end = ct::now(); \
         total += std::chrono::duration<double, std::micro>(end - start).count(); \
     } \
     BENCH((total / (double)REPEAT)); \
```

**Comment by WilliamTambellini** [comment]
I ve repro on a baremetal reserved machine and run the 512 gemv a 2nd time at the end : the 2nd time, the timings are steady meaning the 'bug' seems to happen only at the 1st exec of small sgemm:   

               M               N               K           sgemm           dynmm          statmm               
           37682             512             512       1.613e+05       1.628e+05       1.612e+05               
               1             512             512           152.1           24.28           19.62               
               1            2048             512           92.49           88.69           87.64               
               1             512            2048           87.62              73           73.33               
               1             512             512           21.65           19.43           19.36            

Retouching the TIME macro in order to 'warmup' sgemm... Tks.

**Comment by rsdubtso** [comment]
> 'bug' seems to happen only at the 1st exec of small sgemm:

Not sure I'm reading the test code correctly, but are you running multiple cases in the same benchmark and is the small sgemm the first computation overall? Does the 'bad' case change if you run computations in the different order?

**Comment by WilliamTambellini** [comment]
That s it: on an avx2 CPU :

               M               N               K           sgemm           dynmm          statmm               
           37682             512             512       1.639e+05       1.691e+05       1.649e+05               
               1             512             512            23.7           19.65            23.5               
               1            2048             512            90.5           96.89           93.49               
               1             512            2048           89.91           76.57           76.97      

Tks.

**Comment by emfomenk** [comment]
This looks better. The difference seems to be negligible (well, strictly speaking 89 <-> 76 is not that negligible difference, but I guess here the problem is that the system noise has much more noticeable effect on smaller problems that on a bigger ones).
