### ISSUE TITLE
Website on package renaming is out of date

### ISSUE THREAD

**Issue by bhipple** [oneapi-src/oneDNN#708]
https://01.org/dnnl

> The project was initially launched as Intel Math Kernel Library for Deep Neural Networks (Intel MKL-DNN) and renamed to DNNL with v1.1 release.

It looks like the website could use an update for the latest rename to `oneDNN`.

**Comment by vpirogov** [comment]
Hi @bhipple,

Thank you for the report. Most of the content was updated today and remaining changes will propagate in a few days.

**Comment by vpirogov** [comment]
Finally the 01.org was updated.
