### ISSUE TITLE
Issue "make file" #47

### ISSUE THREAD

**Issue by raialonso8** [oneapi-src/oneDNN#715]
Hi,
I am using Ubuntu 18.04 and ros eloquent
I am trying to install catkind. First I tried with sudo apt-get install ros-eloquent-catkin however it looks that ros eloquent does not have a catkin package to install as it uses ament instead so I then followed the next tutorial:
https://index.ros.org/doc/ros2/Tutorials/catment/#combining-all-of-ros-and-ros-2-in-one-workspace-and-building-it-todo
It has a chapter called "Variation: Using the catkin API in a ROS 2 package" where tells you how to install catkin for ros2 as  follows:
```
# install catkin_pkg
git clone https://github.com/ros-infrastructure/catkin_pkg.git
cd catkin_pkg
git checkout ament
python3 setup.py install --prefix $HOME/catkin --single-version-externally-managed --record foo --install-layout deb
# install catkin
git clone https://github.com/ros/catkin.git
cd catkin
git checkout ament
mkdir build
cd build
PYTHONPATH=$HOME/catkin/lib/python3/dist-packages/ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/catkin -DPYTHON_EXECUTABLE=/usr/bin/python3
make install
```
However after following all the steps with succes when it comes to the last command "make install" it comes out with the following error:

CMake Error at gtest/cmake_install.cmake:47 (file):
  file INSTALL cannot find
  "/home/cpsr/catkin_pkg/catkin/build/gtest/libgtest.so".
Call Stack (most recent call first):
  cmake_install.cmake:159 (include)

Makefile:94: recipe for target 'install' failed
make: *** [install] Error 1

Any clue or any help?
Thanks for your time,

**Comment by emfomenk** [comment]
Hi @raialonso8,

Why do you file the issue against this project?
Probably, the proper place is https://github.com/ros/catkin/issues.

Closed as unrelated.
