### ISSUE TITLE
Why should the bias of matmul primitive be the same size as dst?

### ISSUE THREAD

**Issue by springkim** [oneapi-src/oneDNN#718]
Fully-connected operations are defined as below when inference.
![](https://i.imgur.com/7e8jNjC.png)
Now, if consider the mini-batch in the training stage, the formula can be used as below. 
![](https://i.imgur.com/qAW0d1h.png)
(where m is mini-batch size)
Here, the size of weights does not change. However, the bias must be resized in order to use matmul primitive.
**To use matmul primitive, we need to re-adjust the bias tensor every epoch, is there a greater advantage than the method below?**
```cpp
fwd.execute(stream, {       //matmul
	{DNNL_ARG_SRC,mem_i},
	{DNNL_ARG_WEIGHTS,mem_w},
	{DNNL_ARG_DST,mem_o}
	});
stream.wait();
if (bias) {
	float *pbias = static_cast<float *>(mem_b.get_data_handle());
	float *pout = static_cast<float *>(mem_o.get_data_handle());
	for (int i = 0; i < mini_batch; i++) {
		float* p = pout + fc_out_size * i;
		vsAdd(fc_out_size, p, pbias, p);
	}
}
```
Or is there a better way to calculate bias?

**Comment by rsdubtso** [comment]
From the [matmul documentation](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html):
> The bias tensor is optional and supports implicit broadcast semantics: any of its dimensions can be 1 and the same value would be used across the corresponding dimension. However, 
bias must have the same number of dimensions as the dst.
.

**Comment by hholst80** [comment]
Strictly speaking, the operation of the form

Y := X W + B

In order for the algebra to make sense the shape of X, Y and the product X W has to be equal. How to implement this efficient is by using a outer product formulation for C

C = e b^T      C(i,j) = b(j)      1 <= i <= m,1 <= j <= n.

where e is a column vector of dimension m with all 1:s and b^T is a row vector of dimension m. This is what we mean by "broadcast". It is a transformation from R^n to R^m ⨯ R^n with the property that the bias vector b will be added to each column.

**Comment by vpirogov** [comment]
Thank you for clarification, @hholst80!

I'm closing the issue as the question is addressed. Feel free to reopen or submit a new one if you have any further questions.
