### ISSUE TITLE
Warm-up operator?

### ISSUE THREAD

**Issue by affranchi** [oneapi-src/oneDNN#720]
Hello,

I'm running two operators LSTM and MatMul. First running for both operators are ridiculously slow.  For example, with 2x2 matrix, MatMul takes more than 50 ms. (Please, see below test code result and logs.)

I know there was similar question and answer: https://github.com/oneapi-src/oneDNN/issues/242
Although, it needs sometime to arrange for the first place, still it's unreasonably slow (2x2 matrix MatMul takes more than 50 ms.) Can I avoid or reduce this time?

I attached my MatMul code. Please, let me know if I did something wrong.

**MatMul test code**
```
    using Clock = std::chrono::steady_clock;
    using ClockDur = decltype(Clock::now() - Clock::now());
    using OutputDur = std::chrono::microseconds;
    using std::chrono::duration_cast;

    const auto pre_all_ts = Clock::now();

    dnnl::engine engine(dnnl::engine::kind::cpu, 0);
    dnnl::stream engine_stream(engine);
    dnnl::memory::dims bias_dims{1,2};

    const auto src_md = dnnl::memory::desc({2,2},
                                           dnnl::memory::data_type::f32,
                                           dnnl::memory::format_tag::ab);
    const auto weights_md = dnnl::memory::desc({2,2},
                                               dnnl::memory::data_type::f32,
                                               dnnl::memory::format_tag::ab);
    auto dst_md = dnnl::memory::desc({2,2},
                                     dnnl::memory::data_type::f32,
                                     dnnl::memory::format_tag::ab);
    auto bias_md = dnnl::memory::desc(bias_dims,
                                      dnnl::memory::data_type::f32,
                                      dnnl::memory::format_tag::ab);

    const auto src_mem = dnnl::memory(src_md, engine);
    const auto weights_mem = dnnl::memory(weights_md, engine);
    auto dst_mem = dnnl::memory(dst_md, engine);

    float* src_mem_data = static_cast<float*>(src_mem.get_data_handle());
    float* weight_mem_data = static_cast<float*>(weights_mem.get_data_handle());
    src_mem_data[0] = 1;
    src_mem_data[1] = 2;
    src_mem_data[2] = 3;
    src_mem_data[3] = 4;
    weight_mem_data[0] = 4;
    weight_mem_data[1] = 3;
    weight_mem_data[2] = 2;
    weight_mem_data[3] = 1;

    dnnl::primitive_attr matmul_attr;

    const auto pre_opdesc_ts = Clock::now();
    auto matmul_d = dnnl::matmul::desc(src_md, weights_md, bias_md, dst_md);
    const auto post_opdesc_ts = Clock::now();

    const auto pre_pd_ts = Clock::now();
    auto matmul_pd = dnnl::matmul::primitive_desc(matmul_d, matmul_attr, engine);
    const auto post_pd_ts = Clock::now();

    auto bias_mem = dnnl::memory(bias_md, engine);
    auto* bias_data = static_cast<float*>(bias_mem.get_data_handle());
    std::fill(bias_data, bias_data + 2, 0);

    // Create the primitive.
    const auto pre_prim_ts = Clock::now();
    auto matmul_prim = dnnl::matmul(matmul_pd);
    const auto post_prim_ts = Clock::now();

    std::unordered_map<int, dnnl::memory> matmul_args;
    matmul_args.insert({DNNL_ARG_SRC, src_mem});
    matmul_args.insert({DNNL_ARG_WEIGHTS, weights_mem});
    matmul_args.insert({DNNL_ARG_BIAS, bias_mem});
    matmul_args.insert({DNNL_ARG_DST, dst_mem});

    // Primitive execution: matrix multiplication with ReLU.
    const auto pre_exec_ts = Clock::now();
    matmul_prim.execute(engine_stream, matmul_args);
    const auto post_exec_ts = Clock::now();

    // Wait for the computation to finalize.
    const auto pre_wait_ts = Clock::now();
    engine_stream.wait();
    const auto post_wait_ts = Clock::now();

    const auto post_all_ts = Clock::now();
    const auto all_time = post_all_ts - pre_all_ts;
    const auto opdesc_time = post_opdesc_ts - pre_opdesc_ts;
    const auto primdesc_time = post_pd_ts - pre_pd_ts;
    const auto prim_time = post_prim_ts - pre_prim_ts;
    const auto exec_time = post_exec_ts - pre_exec_ts;
    const auto wait_time = post_wait_ts - pre_wait_ts;

    std::ofstream timefile;
    timefile.open ("./time.txt",std::ios::app);
    timefile << "==============================================\n";
    timefile << "[MatMul All Time] : " << duration_cast<OutputDur>(all_time).count() <<"\n";
    timefile << "[MatMul op desc Time] : " << duration_cast<OutputDur>(opdesc_time).count() <<"\n";
    timefile << "[MatMul primitive desc Time] : " << duration_cast<OutputDur>(primdesc_time).count() <<"\n";
    timefile << "[MatMul primitive Time] : " << duration_cast<OutputDur>(prim_time).count() <<"\n";
    timefile << "[MatMul execute Time] : " << duration_cast<OutputDur>(exec_time).count() <<"\n";
    timefile << "[MatMul wait Time] : " << duration_cast<OutputDur>(wait_time).count() <<"\n";
    timefile.close();
```
**MKLDNN_VERBOSE log:**

--- First Run
dnnl_verbose,info,oneDNN v1.4.0 (commit N/A)
dnnl_verbose,info,cpu,runtime:TBB
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,m2n2k2,51.135
--- Second Run
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,m2n2k2,0.0290527
--- Third Run with 150x150 matrix
dnnl_verbose,exec,cpu,matmul,gemm:jit,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 bia_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,m150n150k150,0.102051

**Time result(micro second scale):**

--- First run
[MatMul All Time] : 50846
[MatMul op desc Time] : 2
[MatMul primitive desc Time] : 36
[MatMul primitive Time] : 165
[MatMul execute Time] : 50583
[MatMul wait Time] : 11
--- Second run
[MatMul All Time] : 95
[MatMul op desc Time] : 0
[MatMul primitive desc Time] : 9
[MatMul primitive Time] : 49
[MatMul execute Time] : 25
[MatMul wait Time] : 0
--- Third run with 150x150 matrix
[MatMul All Time] : 151
[MatMul op desc Time] : 0
[MatMul primitive desc Time] : 7
[MatMul primitive Time] : 56
[MatMul execute Time] : 81
[MatMul wait Time] : 0

FYI, LSTM has similar issue.

--- First run
[All LSTM Time] : 51507
[MEM Time] : 3
[Prim Time] : 270
[Exec Time] : 51033
--- Second run
[All LSTM Time] : 399
[MEM Time] : 1
[Prim Time] : 141
[Exec Time] : 33

**LSTM MKLDNN_VERBOSE Log**
--- First Run
dnnl_verbose,info,oneDNN v1.4.0 (commit N/A)
dnnl_verbose,info,cpu,runtime:TBB
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,1x1x3x4x2,0.000976562
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,1x1x2x4x2,0
dnnl_verbose,exec,cpu,rnn,ref:any,forward_inference,src_layer_f32::blocked:abc:f0 src_iter_undef::undef::f0 wei_layer_f32::blocked:abcde:f0 wei_layer_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0 dst_iter_f32::blocked:abcd:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l1t2mb1sic2slc3dhc2dlc2,52.009

--- Second Run
dnnl_verbose,exec,cpu,reorder,rnn_weights_reorder,undef,src_f32::blocked:abcde:f0 dst_f32::rnn_packed::f0,,,1x1x3x4x2,0.0310059
dnnl_verbose,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde:f0 dst_f32::blocked:abcde:f0,,,1x1x2x4x2,0.000976562
dnnl_verbose,exec,cpu,rnn,ref:any,forward_inference,src_layer_f32::blocked:abc:f0 src_iter_undef::undef::f0 wei_layer_f32::rnn_packed::f0 wei_layer_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0 dst_iter_f32::blocked:abcd:f0,,alg:vanilla_lstm direction:unidirectional_left2right activation:undef,l1t1mb1sic2slc3dhc2dlc2,0.0222168

Thanks!

**Comment by emfomenk** [comment]
Hi @affranchi,

Both LSTM and MatMul rely on `dnnl_sgemm()` functionality underneath. And the peculiarity of `dnnl_sgemm()` is that it jits the kernels at a first call. The jitting should happen only once per program run per data types (matrices A, B, and C). The overhead is constant in a sense that it doesn't depend on the shape and is currently unavoidable.
In theory, we could jit the gemm kernels at library load or application start up, instead of generating them lazily. However:
1. This will slow down the load regardless of whether gemm is used or not. This also would consume memory resources (not much though) regardless of whethere gemm is used or not.
2. Doesn't remove the overhead per se. Just moves it to another place.

If you want predictable run-time for, say, inference, the best suggestion for now is to call a dummy `sgemm` (with meaningful shapes, say, 2x2x2) to make the library initialize it.

Is this workaround acceptable for you?

On our side, we probably could initialize gemm at MatMul and RNN primitive creation time, as we know users are going to run them. This doesn't solve the issue of the pure gemm API though...

**Comment by emfomenk** [comment]
> And the peculiarity of `dnnl_sgemm()` is that it jits the kernels at a first call. The jitting should happen only once per program run per data types (matrices A, B, and C). The overhead is constant in a sense that it doesn't depend on the shape and is currently unavoidable.

Correction. Actually, the shape might be important too. We have copy and no-copy gemm kernels, that are dispatched (optimally) depending on a complicated logic that takes shapes, transA, transB, and leading dimensions into account. So if one set of kernels is initialized the other may be uninitialized yet. When gemm is called with another set of parameters that involves the other set of kernels, that first call will be slow too.

**Comment by affranchi** [comment]
Thank you for your answer.
Adding dnnl_sgemm for warming up works! :)

First run and same micro second scale:

[MatMul All Time] : 155
[MatMul op desc Time] : 1
[MatMul primitive desc Time] : 36
[MatMul primitive Time] : 62
[MatMul execute Time] : 34
[MatMul wait Time] : 0
[MatMul gemm Time] : 50687 <-- Measured warm-up dnnl_sgemm

[All LSTM Time] : 473
[MEM Time] : 1
[Prim Time] : 163
[Exec Time] : 81
[Gemm Time] : 50681 <-- Measured warm-up dnnl_sgemm
