### ISSUE TITLE
memory_format_propagation.cpp weights_mem format explanation needed

### ISSUE THREAD

**Issue by jnorwood** [oneapi-src/oneDNN#725]
# Summary

need explanation why format_tag oihw differs from {IC,OC,KH,KW} order at line 180 in the cpp file, which appears in the " Create source and destination memory objects" topic of the "memory_format_propagation() function" documentation

auto weights_mem = memory({{IC, OC, KH, KW}, memory::data_type::f32,
                                      memory::format_tag::oihw},

# URLs
https://github.com/oneapi-src/oneDNN/blob/master/examples/memory_format_propagation.cpp
https://oneapi-src.github.io/oneDNN/memory_format_propagation_cpp.html
# Additional details

**Comment by emfomenk** [comment]
Hi @jnorwood,

This is a typo. The sequence should be `{OC, IC, KH, KW}`. We missed it because (coincidentally) `OC` is equal to `IC`, hence oneDNN could not identify this is the inconsistent configuration. Will fix that.
Thank you for thorough documentation reading and the report!
