### ISSUE TITLE
Need a good description of the padding dims of the convolution_forward primitives

### ISSUE THREAD

**Issue by jnorwood** [oneapi-src/oneDNN#726]
# Summary
The dnnl_8hpp_source.html padding_l and padding_r dims need some better description

 3583             memory::validate_dims(padding_l, src_desc.data.ndims - 2);
 3584             memory::validate_dims(padding_r, src_desc.data.ndims - 2);

The deeplearning.net example below for theano has an animated diagram  showing padding  for the left, right, top and bottom boundaries of the image.

Without further documentation, I would guess that the example padding_l dim values refers to the left and top image borders  and padding_r dim values would refer to the right and bottom image borders  of that theano animated diagram.

I think the oneDNN documentation could use an example similar to the theano animated diagram, but with an image and filter that result in different left, right, top and bottom padding.  That way it could be made clear with an example how the padding_l and padding_r dim values relate to the image boundary padding. 

The other inference examples don't help, since they use the same values for the two padding parameters.

cnn_inference_f32_8c-example.html

    CHECK(dnnl_convolution_forward_desc_init(&conv_any_desc, dnnl_forward,
            dnnl_convolution_direct, &conv_src_md, &conv_weights_md,
            &conv_bias_md, &conv_dst_md, conv_strides, conv_padding,
            conv_padding));

cnn_inference_int8_8cpp-example.html

    auto conv_desc = convolution_forward::desc(prop_kind::forward,
            algorithm::convolution_direct, conv_src_md, conv_weights_md,
            conv_bias_md, conv_dst_md, conv_strides, conv_padding,
            conv_padding);

The pooling example does help explain the expected padding parameters, which were not clear from the convolution examples and documentation.   I presume they are the same.
 
            PH_L = 0, // height padding: left
            PH_R = 0, // height padding: right
            PW_L = 0, // width padding: left
            PW_R = 0, // width padding: right

    memory::dims padding_dims_l = {PH_L, PW_L};
    memory::dims padding_dims_r = {PH_R, PW_R};

# URLs
https://oneapi-src.github.io/oneDNN/dnnl_8hpp_source.html
http://deeplearning.net/software/theano/tutorial/conv_arithmetic.html
https://oneapi-src.github.io/oneDNN/cnn_inference_int8_8cpp-example.html
https://oneapi-src.github.io/oneDNN/cnn_inference_f32_8c-example.html
https://oneapi-src.github.io/oneDNN/pooling_8cpp-example.html

# Additional details

**Comment by emfomenk** [comment]
Hi @jnorwood,

Thanks for you feedback!

First off, your understanding is correct: _left_ padding stands for front (Depth), top (Height), and left (Width) padding, and _right_ padding stands for back (Depth), bottom (Height), and right (Widht) padding.

For convolution we tried to explain the notion of `_L` and `_R` paddings in the parameters table in the user's guide [here](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html). Probably, the picture is more illustrative, but I think the text there should be fine too.

However, the API reference manual and examples could mention this aspect one more time, I agree.

**Comment by jnorwood** [comment]
The table seems more related to the processing formula, but doesn't help much to describe exactly what goes in the dim parameters and which order.  For example, from the table, one might assume that PD_L and PD_R are required in the padding parameters.  So is {1,y,x}  equivalent to {y,x} for padding dim parameter?

This link was helpful for the convolutions, but the other convolution examples were not so helpful, on their own, due to the less explicit configuration of the padding parameters.  

https://oneapi-src.github.io/oneDNN/convolution_example_cpp.html

            PH_L = 1, // height padding: left
            PH_R = 1, // height padding: right
            PW_L = 1, // width padding: left
            PW_R = 1, // width padding: right

    memory::dims padding_dims_l = {PH_L, PW_L};
    memory::dims padding_dims_r = {PH_R, PW_R};

    auto conv_desc = convolution_forward::desc(prop_kind::forward_training,
            algorithm::convolution_direct, conv_src_md, conv_weights_md,
            user_bias_md, conv_dst_md, strides_dims, padding_dims_l,
            padding_dims_r);

**Comment by emfomenk** [comment]
> The table seems more related to the processing formula, but doesn't help much to describe exactly what goes in the dim parameters and which order.

Yeah, you are right. I mostly referred to the comment part of the table (`In the API we use padding_l to indicate the corresponding vector of paddings (_l in the name stands for left)` that explains the purpose and the meaning of the `padding_l` and `padding_r` arrays in the API.

The reference manual should clarify these aspect, I agree.

> So is {1,y,x} equivalent to {y,x} for padding dim parameter?

This isn't stated clear in the reference manual, but `padding_l` and `padding_r` arrays are expected to be of size `ndims - 2`, i.e. contain only spatial dimensions. For 2D convolution, the paddings should contain only the values related to height and width (and not depth).

**Comment by emfomenk** [comment]
Actually, the reference manual does mention what is expected for the padding arrays ([link](https://oneapi-src.github.io/oneDNN/group__dnnl__api__convolution.html#ga9699a81a0e3341014447e4da0cdd7e18)):

>   Parameters   | .
> --- | ---
> **strides** | Array of strides for spatial dimension.
> **padding_l** | Array of padding values for low indices for each spatial dimension (front, top, left).
> **padding_r** | Array of padding values  for high indices for each spatial dimension (back, bottom, right). Can  be NULL in which case padding is considered to be symmetrical.

The only missing part is that `(front, top, left)` is actually:
- `(front, top, left)` in case of 3D convolution,
- `(top, left)` in case of 2D convolution,
- `(left)` in case of 1D convolution.

**Comment by jnorwood** [comment]
https://oneapi-src.github.io/oneDNN/structdnnl_1_1convolution__forward_1_1desc.html
yes, these class descriptions are ok.  
One of the convolution examples is ok, also.
I'll close this.
