### ISSUE TITLE
undefined reference to `cblas_gemm_s8u8s32_pack_get_size' persists...

### ISSUE THREAD

**Issue by jiapei100** [oneapi-src/oneDNN#732]
Hmmm, I'm using **master of today**, but built with the following **ERROR** message if I enable **EXAMPLES**...

```console
../../src/libdnnl.so.1.4: undefined reference to `cblas_gemm_s8u8s32_pack_get_size'
../../src/libdnnl.so.1.4: undefined reference to `cblas_sgemm_pack_get_size'
../../src/libdnnl.so.1.4: undefined reference to `cblas_sgemm_compute'
../../src/libdnnl.so.1.4: undefined reference to `cblas_gemm_s8u8s32_pack'
../../src/libdnnl.so.1.4: undefined reference to `cblas_sgemm'
../../src/libdnnl.so.1.4: undefined reference to `cblas_gemm_s8u8s32'
../../src/libdnnl.so.1.4: undefined reference to `cblas_gemm_s8u8s32_compute'
../../src/libdnnl.so.1.4: undefined reference to `cblas_sgemm_pack'
../../src/libdnnl.so.1.4: undefined reference to `cblas_saxpy'
```

Any suggestions?? Thankn you ...

**Comment by emfomenk** [comment]
Hi @jiapei100,

Intel MKL-DNN v1.0 and DNNL v1.1+ do not depend on Intel MKL (that has these `cblas_*` symbols) by default, unless you explicitly pass special building options to the library. This is not recommended for end users and unsupported; the ability to build the library with Intel MKL is kept solely for development and debugging purposes.

How did you build the library? Did you pass `-DUSE_MKL` compiler flags (say, using `CMAKE_CXX_FLAGS`) or use `-D_DNNL_USE_MKL` cmake option?

**Comment by jiapei100** [comment]
Hi, @emfomenk 

Final page of my configuration is:

```console
...
 MKLINC                           /opt/intel/mkl/include
 MKLLIB                           /opt/intel/mkl/lib/intel64/libmkl_core.so
 OPENCLROOT        
 OpenMP_CXX_FLAGS                 -fopenmp
 OpenMP_CXX_LIB_NAMES             gomp;pthread
 OpenMP_C_FLAGS                   -fopenmp
 OpenMP_C_LIB_NAMES               gomp;pthread
 OpenMP_gomp_LIBRARY              /usr/lib/gcc/x86_64-linux-gnu/7/libgomp.so
 OpenMP_pthread_LIBRARY           /usr/lib/x86_64-linux-gnu/libpthread.so
 TBBROOT                          /opt/intel/tbb          
 _DNNL_TEST_THREADPOOL_IMPL       STANDALONE     
 _DNNL_USE_MKL                    ON
```

I'm possibly using MKL of 2020.1, my license seems to be expired **ALREADY**....
Anyway, I just installed **Intel® Math Kernel Library**  directly and trying to compile it with oneDNN ???

Any further suggestions?

Cheers

**Comment by rsdubtso** [comment]
The short answer is that you should not be using MKL to build oneDNN. The longer one is that this option was left in as a debug developer-only feature (hence the leading underscore in `_DNN_USE_MKL`). If you really must, you should set  `MKLLIB=libmkl_rt.so`.

**Comment by jiapei100** [comment]
@rsdubtso 
Thank you .... **libmkl-rt.so** solved my problem. Thank you.
