### ISSUE TITLE
What is the best version to upgrade to

### ISSUE THREAD

**Issue by UtsavAgrawal14** [oneapi-src/oneDNN#734]
I want to upgrade my code from MKL to oneDNN. Which version is the best to upgrade to?
I want to know the best version in terms of stability and performance.

**Comment by emfomenk** [comment]
Hi @UtsavAgrawal14,

In general, the answer on you question is -- the latest stable release, which is currently [v1.4](https://github.com/oneapi-src/oneDNN/releases/tag/v1.4).

What functionality do you use from Intel MKL?
The current intersection between the library is only single precision floating point and integer gemms: `sgemm` / `gemm_s8u8s32` in Intel MKL and `dnnl_sgemm` / `dnnl_gemm_u8s8s32` in oneDNN.
If you use older Intel MKL, it also had a DNN component which was evolved into this open source project few years ago. Please note, that the API is considerably different, though the ideas are the same. Also oneDNN has much bigger coverage (in terms of DNN primitives) than what Intel MKL had.

**Comment by UtsavAgrawal14** [comment]
Thanks for the response. I have a few more queries before I can upgrade:
1. What exactly is the reason for migrating to OneDNN from MKL-DNN?
2. Is the 0.x version going to be deprecated? If so, when is that going to happen as I see 0.x also is currently receiving updates.
3. If I decide to continue with MKL-DNN, is that going to be a problem in the future?
4. What is the difference between the latest 0.x version and the latest 1.x version? Are they equivalent to each other?

**Comment by emfomenk** [comment]
Hi @UtsavAgrawal14,

> What exactly is the reason for migrating to OneDNN from MKL-DNN?

// _assuming you meant indeed Intel MKL-DNN (this project) and not [Intel MKL](https://software.intel.com/content/www/us/en/develop/tools/math-kernel-library.html)_

oneDNN and Intel MKL-DNN are just the names of the same library. Before v1.1 it was Intel MKL-DNN, then it was renamed to DNNL, and now the project is called oneDNN. No semantic difference, just name :)

> Is the 0.x version going to be deprecated? If so, when is that going to happen as I see 0.x also is currently receiving updates.

v0.x **is** deprecated. The last fixes were very specific and narrow. We haven't added any new functionality and optimizations into v0.x branch almost a year now. It is highly recommended to use the latest version.

> If I decide to continue with MKL-DNN, is that going to be a problem in the future?

The problems are:
1. no bug fixes for older versions (we typically backport critical issues to 1 or 2 previous releases)
2. limited support (cause most of the recommendations will -- update the version :))
3. more time to switch to the newer version once you decide to do that, as there are some API differences

> What is the difference between the latest 0.x version and the latest 1.x version? Are they equivalent to each other?

By the time we released v1.0 the difference between 0.x and 1.0 was mostly API. No (significant) conceptual differences. There is a [Version 1.0 Transition Guide ](https://oneapi-src.github.io/oneDNN/dev_guide_transition_to_v1.html). You can go over it to see those differences.

Needless to say that today, the latest v1.x version has many more new primitives, features, and performance improvements, and bug fixes. You can compare the documentation for [v1.0](https://oneapi-src.github.io/oneDNN/v1.0/index.html) and the current version [v1.4](https://oneapi-src.github.io/oneDNN/v1.4/index.html). You could also go over [release notes](https://github.com/oneapi-src/oneDNN/releases) for each versions to see what was added.

**Comment by UtsavAgrawal14** [comment]
I see there's a compatibility header "include/mkldnn_dnnl_mangling.h" that's mapping Intel MKL-DNN symbols to DNNL ones. Is that going to be maintained or removed at some time in future releases?

**Comment by emfomenk** [comment]
This is about the transition from Intel MKL-DNN v1.0 to DNNL v1.1, where we only changed the name of the library + replaced all symbols with `mkldnn_` prefix to `dnnl_`.
More on that here: https://oneapi-src.github.io/oneDNN/dev_guide_transition_to_dnnl.html

**Comment by uu-praveeng** [comment]
Hi @emfomenk ,

Sorry repeated queries :

We are using mkldnn v1.0 with mkldnn namespace apis

Over all our intention is to upgrade to v1.4 but do we have to rename the mkldnn to dnnls and upgrade from v1.0 to v1.4 or can we upgrade with mkldnn namespace apis. 

What is reason behind maintaining the mangling header and how many releases will it be maintained? What happens if we upgrade to v1.4 with same mkldnn namespace apis?

Thank you,
Praveen.

**Comment by emfomenk** [comment]
Hi @uu-praveeng,

We keep `mkldnn` compat-headers for backwards compatibility. When we made the rename `mkldnn` -> `dnnl`, we didn't bump the major version, only increased the minor one: 1.0 -> 1.1. These headers are our burden and price for claiming the compliance with the semantic versioning.

Please note, that any new symbols added after v1.1 in `dnnl` namespace are not back-ported to the corresponding `mkldnn` namespace. So, if you don't plan to use any new features (like layer normalization or binary primitive), you could continue using `mkldnn` namespace. The namespace will be supported at least till the end of this year.

With the next major release we will likely drop the compatibility headers as they will become very outdated + there is enough time to switch to the new naming scheme.

**Comment by uu-praveeng** [comment]
Thanks , this clarification really helps us .
