### ISSUE TITLE
How to set scales of int8convrelu

### ISSUE THREAD

**Issue by lisa0314** [oneapi-src/oneDNN#735]
As I know, if I want to implement int8 conv for ONE-DNN，I need to set the `output_scale = (input_scale * weights_scale) / dst_scale` (when mask =0) using `dnnl_primitive_attr_set_output_scales `. However, I am quite confused when I need to implement int8 conv with fusion post op relu6. 
The function `dnnl_post_ops_append_eltwise` has one parammeter named `scale`, how to set the value of this scale? and what's the relation between the scale of `dnnl_post_ops_append_eltwise` and the scale of `dnnl_primitive_attr_set_output_scales ` when I implement a int8convrelu?

**Comment by emfomenk** [comment]
Hi @lisa0314,

Please check Example 2 [here](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_quantization.html).

> The function dnnl_post_ops_append_eltwise has one parameter named scale, how to set the value of this scale?

What do you mean by saying "how to set the value"? It is passed as the first argument of the corresponding [method](https://oneapi-src.github.io/oneDNN/structdnnl_1_1post__ops.html#a66606f08467b19091e696b52a2f789e6). BTW, the documentation also shows the relation between the arguments and formula being computed.

For relu6 I would expect the following sequence:
```
// pseudo-code

src_s8 <-- 1/src_scale * src_f32
wei_s8 <-- 1/wei_scale * wei_f32

// dst_f32 <-- relu6(conv(src_f32, wei_f32)
// dst_s8 <-- 1/dst_scale * dst_f32

dst_s8 <-- 
    conv(src_s8, wei_s8)
    .attr_output_scale(src_scale * wei_scale)
    .attr_post_op(eltwise=clip, scale=1/dst_scale, alpha = 0, beta = 6)
```

**Comment by lisa0314** [comment]
@emfomenk Thanks for your detailed comments! I got it!
