### ISSUE TITLE
How to set the value of scale for Int8Conv with post op sum+relu6?

### ISSUE THREAD

**Issue by lisa0314** [oneapi-src/oneDNN#738]
When I define a int8 conv with two chain post ops sum+relu6 and I know the value of scale for weights, scale for  source and scale for dst, I am confused about how to deal with the value of scales for append_sum and append_eltwise.
As[ this link](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html#dev_guide_attributes_post_ops_with_scales) says, I still can't find out what's the relation between scale of dst and scale of append_sum or append_eltwise.

**Comment by emfomenk** [comment]
Hi @lisa0314,

The scale for append_sum scales the previous destination. I.e. before appending the result of convolution (multiplied by output_scale) to the previous destination that previous destination will be scaled by the value from append_sum function.

The scale for append_eltwise is how the result of the eltwise will be scaled. If this is the final post op, then typically that scale should be equal to `1/dst_scale`.

Pseudo example:
``` c++
// F32 computations:
//     dst_f32 = ReLU6( prev_dst_f32 + conv(src_f32, wei_f32) )

// Assumptions:
// x_s8 <-- 1/x_scale * x_f32, where x = {src, wei, prev_dst, dst}

// Int8 computations:
conv(src_s8, wei_s8)
    .set_output_scale(src_scale * wei_scale) // this will make the result of 
                                             // conv-kernel to return real f32 value
    .append_sum(prev_dst_scale) // this is to translate prev_dst_s8 to real
                                // f32 value too, to make both expressions from
                                // left and right from + be of the same "nature"
    .append_eltwise(scale=1/dst, alg=clip, alpha=0, beta=6) // scale here translates real 
                                                            // f32 value to s8 range
```

It is worth mentioning that oneDNN doesn't put any semantics into the scales and values, but simply applies the scales at the certain (documented) places. So the actual semantics is set by a user. What I showed abowe is just one way of doing int8 computations (though, probably the most natural: all post operations are done using the real (non-scaled) f32 values). You could adapt oneDNN computations for your own needs.

For instance, if it happen that `prev_dst_scale = dst_scale`, the following computations would lead to the same result (though, semantically it would be harder to comprehend):

``` cpp
conv(src_s8, wei_s8)
    .set_output_scale(src_scale * wei_scale / dst_scale)
    .append_sum(1.)
    .append_eltwise(scale=1, alg=clip, alpha=0, beta=6 / dst_scale)

// note, this trick works, because:
// a * clip(x, min, max) = clip(a * x, a * min, a * max)
```

**Comment by lisa0314** [comment]
@emfomenk Thanks for your comments!
