### ISSUE TITLE
How to handle Bias-data if i want to perform convolution without bias

### ISSUE THREAD

**Issue by Alok-Ranjan23** [oneapi-src/oneDNN#739]
I want to perform convolution without bias. I do not want to pass bias as an array filled with 0. I want to pass bias as an array pointing to 'NULL'. Am I allowed to do pass bias data as NULL?

**Comment by rsdubtso** [comment]
If you are using C++ API, then you can create convolution descriptor without specifying bias term like this:

https://github.com/oneapi-src/oneDNN/blob/86b9a0534e1e39042be7ecfc0eda8a20c5b57f5a/examples/memory_format_propagation.cpp#L154-L160

In the C API, the bias memory descriptor can be set NULL to indicate the absence of the bias term.
