### ISSUE TITLE
objdump jit.bin file failed

### ISSUE THREAD

**Issue by Danliran** [oneapi-src/oneDNN#740]
Hi,
Dump the code reference to https://oneapi-src.github.io/oneDNN/dev_guide_inspecting_jit.html, but report file format not recongnized.

command:
DNNL_JIT_DUMP=1 ./primitives-convolution-cpp

objdump -D  -b dnnl_dump_jit_uni_reorder_kernel_f32.0.bin
objdump: dnnl_dump_jit_uni_reorder_kernel_f32.0.bin: File format not recognized

**Comment by rsdubtso** [comment]
Hi @Danliran. It is important to specify the machine architecture (`-mi386:x86-64`) as the dumps are just raw bytes:
```bash
objdump -D -b binary -mi386:x86-64 dnnl_dump_jit_uni_reorder_kernel_f32.0.bin
```
