### ISSUE TITLE
Query AVX2 or AVX512

### ISSUE THREAD

**Issue by pranathibl** [oneapi-src/oneDNN#749]
Hi,

Is there any API to query if the machine supports AVX2 or AVX512 instructions from MKLDNN V1.0?

Thanks,
Pranathi.

**Comment by rsdubtso** [comment]
The latest master has this:

https://github.com/oneapi-src/oneDNN/blob/ad368f4848240c16efc09ec805f6966cb0bb005f/include/dnnl.h#L3930-L3938

https://github.com/oneapi-src/oneDNN/blob/ad368f4848240c16efc09ec805f6966cb0bb005f/include/dnnl.hpp#L10694-L10697

This feature will be available in 1.6.
