### ISSUE TITLE
FPGAs

### ISSUE THREAD

**Issue by RuoshArora** [oneapi-src/oneDNN#751]
Hello,

Is it possible to run any of the oneDNN code on an FPGA? I couldn't find any FPGA code samples.

Thank you!

**Comment by igorsafo** [comment]
Hello @RuoshArora , oneDNN doesn't support FPGA devices.

**Comment by igorsafo** [comment]
Closing as the question seems to be addressed. Feel free to open a new issue if you have any other questions.
