### ISSUE TITLE
how can I disable DL_boost (VNNI) to evaluate generic int8 performance on Cascadelake ? 

### ISSUE THREAD

**Issue by vesslanjin** [oneapi-src/oneDNN#752]
is there a way to do that in oneDNN ?

**Comment by emfomenk** [comment]
[DNNL_MAX_CPU_ISA](https://oneapi-src.github.io/oneDNN/dev_guide_cpu_dispatcher_control.html)=AVX512_CORE (as opposite to AVX512_CORE_VNNI)
You might also want to set `DNNL_MAX_CPU_ISA=AVX2`, to dispatch avx2 only.

**Comment by vpirogov** [comment]
I updated documentation with the full list of supported values for DNN_MAX_CPU_ISA. Hope this helps.

**Comment by vesslanjin** [comment]
got it, thanks.
