### ISSUE TITLE
How to create/access scratchpad memory? 

### ISSUE THREAD

**Issue by avinashcpandey** [oneapi-src/oneDNN#754]
Hi,
I have gone through below link which talks about scratchpad memory 
https://oneapi-src.github.io/oneDNN/dev_guide_attributes_scratchpad.html

I am looking for some documentation where i can create/access scratchpad memory which is independent of primitive.  
Basically I want to create one scratch memory and use it for multiple primitive execution. Two cases are:
1. Running primitive one by one, create scratchpad and use the same for running those.
2. If two primitive are executing together, then by checking some flag we can get the status of scratchpad memory, If its in use by other primitive and no space is left which can be used by other primitive, then create other scratchpad memory and return the pointer. 

Idea is eliminate the buffer allocation happens multiple times, allocate once and keep on using the same(based on space availability in it), If space not available at some point of time, create another.

oneDNN use the scratchpad in some different way which is tightly coupled with particular primitive,, wondering Do we have such things in oneDNN?  

I am running some experiments with gemm kernels, for that i need this info.

**Comment by rsdubtso** [comment]
Closing as inactive. Feel free to reopen.
