### ISSUE TITLE
How to run CPU-only tests in CI when building with -DNNL_GPU_RUNTIME=OCL?

### ISSUE THREAD

**Issue by krupenik** [oneapi-src/oneDNN#763]
Hello, our CI setup doesn't have a GPU, how do we run CPU-only part of the test suite?

I tried to use `.github/automation/test.sh --test-kind gtest --build-dir $builddir --gtest_filter=*:-*_CPU*`, but to no avail.

Thanks!

**Comment by rsdubtso** [comment]
In my experience, running `ctest -E '(gpu|cross-engine)'` should be sufficient.

**Comment by krupenik** [comment]
> In my experience, running `ctest -E '(gpu|cross-engine)'` should be sufficient.

thanks, that worked.
