### ISSUE TITLE
fuction of xbyak

### ISSUE THREAD

**Issue by chauncyyoung** [oneapi-src/oneDNN#766]
I have a question about the function of xbyak:

Does it make function when the C++code translated to assembler(for example, it translates some specific codes to x86 instructions) or when translated assembler to machine language?

**Comment by rsdubtso** [comment]
The Xbyak library is used to write functions that generate x86_64 binary code. There is no [assembler](https://en.wikipedia.org/wiki/Assembler#Computing) involved. The resulting code is usually a function that follows the host platform ABI. Such functions are called when executing primitives.

**Comment by chauncyyoung** [comment]
thank you! Another question is that how can i use openblas/mkldnn_cblas in gemm? I don't know how to modify the cmakelist...

**Comment by nSircombe** [comment]
Hi @chauncyyoung there's some existing support for using a BLAS interface (including MKL), but for development / debug purposes.
`FindBLAS.cmake` was recently added (see https://github.com/oneapi-src/oneDNN/pull/741) to make this a little easier to access, particularly in the case of ArmPL on AArch64 and OpenBLAS. This change should be heading into the 1.6 release I believe.
Also, some changes to the documentation on this are currently under review as part of https://github.com/oneapi-src/oneDNN/pull/770.
Hope that helps.

**Comment by vpirogov** [comment]
@chauncyyoung, 

oneDNN has JIT implementation of GEMM for Intel64/AMD64 architecture, so there's no need to use OpenBLAS or Intel MKL.
