### ISSUE TITLE
ref_eltwise backward may miss some opportunities to run dense impl.

### ISSUE THREAD

**Issue by kruus** [oneapi-src/oneDNN#769]
# Summary
Please review [ref_elwise.hpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_eltwise.hpp) for consistency of `use_dense` condition within forward and backward init to reduce execution of *generic* impl.

# Version
oneDNN v1.4.0 (commit c2770a75f842c9dab8a42bb203c40061e4cb3462)

# Environment
VE Aurora version, but code same on master today.

# Steps to reproduce
1. Change `inputs/eltwise/test_eltwise_all` (perhaps recompiling without jit impls) so **only**
the `ref::any` impls are executed for the benchdnn tests.

1. add printf to see when generic ref_eltwise impl is used.

1. Run some benchmarks.  You will see that sometimes the fwd uses dense where the "same" backward
test runs the generic impl.

Then compare forward `use_dense` test
https://github.com/oneapi-src/oneDNN/blob/f5997b5e6726de82d19ae9b86b08d80aea4af82e/src/cpu/ref_eltwise.hpp#L62-L63

with backward
https://github.com/oneapi-src/oneDNN/blob/f5997b5e6726de82d19ae9b86b08d80aea4af82e/src/cpu/ref_eltwise.hpp#L127-L128

After changing the backward to use `is_dense` *"just like"* the forward
```
            use_dense_ = same_fmt_ &&
                    ( diff_dst_d.is_dense()
                      || diff_dst_d.is_dense(true) && is_zero_preserved() )
                    && !has_zero_dim_memory();
```
, verify that benchdnn sometimes avoids the generic impl, while still running ref:any benchdnn tests without error.

# Observed behavior
generic bwd ref_eltwise runs in cases where dense impl was expected.

# Expected behavior
Use dense bwd ref_elwise wherever possible.

**Comment by emfomenk** [comment]
Hi @kruus,

Agree, seems like the root of the inconsistency comes from far a6152fa0697ff044bc6a533de8ea734ae2764cf5 commit. Will test your suggestion and fix.
Thank you!

**Comment by kruus** [comment]
A related thought is how benchdnn eltwise tests might have some code coverage of the `generic` impls.  Naturally, I'm lazy and happily limiting my nc++ eltwise vectorization work to the `dense` routines.  (x86 dense impls compile nicely, but nc++ needed some help).

**Comment by dzarukin** [comment]
Hi @kruus, we have a plan to extend coverage by iterating over all implementations available in the library for a single problem, but no ETA when it is going to be delivered.

**Comment by kruus** [comment]
@dzarukin I had extended benchdnn to use the iterator api for gen-dnn circa v0.10, but quickly let it slide because of too-large diffs during upstream ports. IIRC, back then the main correctness issue was re-init of various memories as iterating to the next impl.
