### ISSUE TITLE
Next release schedule?

### ISSUE THREAD

**Issue by blueberry** [oneapi-src/oneDNN#772]
Hi, 

When is the next release (1.5.1 or 1.6) scheduled (at least approximately)?

Thank you.

**Comment by nSircombe** [comment]
@vpirogov created a 'Milestones' page recently: https://github.com/oneapi-src/oneDNN/milestones

Which has timescales for upcoming releases if that's of any help? (No mention of a 1.5.1 though).

**Comment by blueberry** [comment]
Thank you, that's great!
