### ISSUE TITLE
Fortran support?

### ISSUE THREAD

**Issue by peterukk** [oneapi-src/oneDNN#773]
Seeing that oneMKL already has Fortran interfaces, I was wondering if are you planning on adding Fortran support to oneDNN in the future? I'd love to try out the inner product primitive in my Fortran program. While Fortran is not the first language one may think of using for deep learning, it's king in my own field (climate/weather modelling) which has started to explore machine learning.

**Comment by vpirogov** [comment]
Hi @peterukk,

We currently do not have plans to introduce Fortran API for oneDNN. The library provides C API that can be used to interoperate with other languages, including Fortran.

**Comment by vpirogov** [comment]
Closing the issue as there's no plan to implement Fortran support by the core team.
