### ISSUE TITLE
assertion failure during benchdnn rnn test with -DUSE_CBLAS

### ISSUE THREAD

**Issue by kruus** [oneapi-src/oneDNN#774]
# Summary
assertion failure for rnn call to gemm with dimension N == 0, when compiled with -DUSE_CBLAS.
Is it expected that rnn issue gemm calls with a matrix dimension of zero?

# Version
oneDNN v1.4.0 (commit 30203a2a9a60bb0c1f45b09d33025ca86977a8eb)

# Environment
VE Aurora compiler (nc++) but responsible code looks the same in master.

# Steps to reproduce
- Compile with -DUSE_CBLAS and assertions enabled
- Run `benchdnn --mode=C --rnn --alg=VANILLA_GRU --activation=TANH --trivial-strides=true l2t1mb4sic2slc2dhc2dic2`
- The 4th call to extended_sgemm occured with N==0
  - debug printf --> `gemm: C@0x601000f6cb80 M=6 N=0 ldc=16`
- Then msan_unpoison_matrix gets called:
  https://github.com/oneapi-src/oneDNN/blob/4155bb46d44d6139a08130cc8498ebf2ba06d46e/src/cpu/gemm/gemm.cpp#L121
- This triggers an assertion within `msan_unpoison_matrix`
  - https://github.com/oneapi-src/oneDNN/blob/4155bb46d44d6139a08130cc8498ebf2ba06d46e/src/cpu/gemm/gemm_msan_unpoison.hpp#L26

# Observed behavior
rnn code may issue a gemm call with matrix dimension zero, which can trigger an assertion when libcblas is used.

# Expected behavior
No assertion failure.

**Comment by mgouicem** [comment]
Hi @kruus ,
Indeed, we have an early out in the [x64 path ](https://github.com/oneapi-src/oneDNN/blob/f47ffe9a549a28537e95fefadbcdb2ceb3e7bcd6/src/cpu/x64/gemm/gemm_driver.cpp#L1628) for {n,m} = 0, and which causes the unpoisoning to never get called there (as unpoisoning happens later [in the kernel](https://github.com/oneapi-src/oneDNN/blob/f47ffe9a549a28537e95fefadbcdb2ceb3e7bcd6/src/cpu/x64/gemm/gemm_driver.cpp#L513)).

Unfortunately, we do not have that when we call CBLAS (here we rely on the cblas implementation for any early out). Fixing in an upcoming commit.

**Comment by kruus** [comment]
While confirming *sightings*, @mgouicem, please also look at another case of suspicious code.  If *not a bug*, perhaps use an assertion.

The third argument to `ker` in https://github.com/oneapi-src/oneDNN/blob/f47ffe9a549a28537e95fefadbcdb2ceb3e7bcd6/src/cpu/simple_reorder.hpp#L330-L372

apparently does an unprotect store to `c[oc]`, yet
the invocation (last line of snippet) **suggests** that third argument `c` possibly is `nullptr`.

Unfortunately, I've no idea how to craft a test case to try and exercise the `c==nullptr` case.

**Comment by kruus** [comment]
More random **sightings** A, B, C.  (Well, maybe C is more like "doesn't work as intended"?)

#### A
https://github.com/oneapi-src/oneDNN/blob/49dcdb1d76bc43c058380f5697b75e2f7f2552a6/src/cpu/cpu_reorder.cpp#L76-L77
https://github.com/oneapi-src/oneDNN/blob/49dcdb1d76bc43c058380f5697b75e2f7f2552a6/src/cpu/cpu_reorder.cpp#L87-L89
Since no non-x86 targets support jit (afaik), consider using `#if !DNNL_X64 || (...)` might be more appropriate.  I stumbled on this when wondering why many VE reorders (used extensively in benchdnn) were taking an inordinately long time, and found out they were not using direct_copy.

#### B
Also the `name()` of each simple_reorder.hpp template is `"simple:any"`, and I found it useful to distinguish them (ex. return `"simple:any:direct_copy"` or `"simple:any:generic"`, etc. (can just point name() -->  impl_name() per-template static)).

#### C
Also, the ignored check return value (nilpotent code line) in https://github.com/oneapi-src/oneDNN/blob/49dcdb1d76bc43c058380f5697b75e2f7f2552a6/src/cpu/simple_reorder.hpp#L114 might more usefully express the potential restriction to a unique `sum` post-op if written as something like
```
if (sum_support) if(!simple_po_check(attr)) return false;
else if(attr->post_ops_.len() != 0) return false;
```

**Comment by kruus** [comment]
Please also look at this line https://github.com/oneapi-src/oneDNN/blob/e9d161985e5c734a603c09dbe83aa95eff3220d2/src/cpu/ref_pooling.cpp#L191

I think `data_t{0}` would avoid type conversion warnings.

**Comment by vpirogov** [comment]
Reopened the issue to keep track of remaining sightings.
