### ISSUE TITLE
Explaining convolution_backward_weights and convolution_backward_data

### ISSUE THREAD

**Issue by yuehniu** [oneapi-src/oneDNN#781]
For convolution_backward_weights and convolution_backward_data, which one is for calculating gradients on weights and which one is for gradients on activations? 

I read through the sample code cnn training in 'SampleDNNL', it seems only convolution_backward_weights is used. Should both of them be used in a complete backward iteration?

**Comment by emfomenk** [comment]
Hi @yuehniu,

It might happen that in the samples you looked at that was the first convolution layer, which doesn't need to propagate the activations gradient (as there are no other layers before the first one).

- `convolution_backward_data` computes activations gradient (`diff_src` in terms on oneDNN) based on weights (`weights`) and activation gradients from the subsequent layer (`diff_dst`).
- `convolution_backward_weights` computes weights gradient (`diff_weights` in terms on oneDNN) based on original activations from the forward pass (`src`) and activation gradients from the subsequent layer (`diff_dst`).
    - The same primitive may compute bias gradient (`diff_bias`) if the convolution was configured to use bias.

**Comment by yuehniu** [comment]
Yeah. Thanks. It is the first convolution layers, which makes so much sense.
