### ISSUE TITLE
DNNL for AARCH64

### ISSUE THREAD

**Issue by guol-fnst** [oneapi-src/oneDNN#785]
Is implement of DNNL fro AARCH64 still in progress? I didn't find any source code in the master branch.
But the readme.md said it supports "Arm 64-bit Architecture (AArch64)".

**Comment by vpirogov** [comment]
Hi @guol-fnst,

oneDNN v1.6 builds and passess validation on AArch64-based platforms. Master has an option to use ArmPL to improve performance on GEMM-based functionality. There's no JIT code targeting AArch64 at this point though.

+@nSircombe to comment on plans.

**Comment by guol-fnst** [comment]
Hi @vpirogov Thanks for your response.
JIT code targeting AARCH64 is exactly what I concern about.

Hi @nSircombe  Is there any possibility  or plan of adding  JIT code targeting AARCH64 support to oneDNN?

**Comment by nSircombe** [comment]
Hi @guol-fnst

As @vpirogov noted, at preset oneDNN builds on Aarch64 and passes the CI test suite. But we're relying on the fallback c++ reference implementations. 
The option to build against Arm Performance Libraries for BLAS calls has recently been exposed in master. There are some notes on this in the build docs and 'cmake/options.cmake'. We are planning an RFC soon to outline plans for implementing Aarch64 specific kernels, but this (and the ArmPL BLAS option) will not make use of "JITed" kernels. 

You may be interested in this Fujitsu oneDNN project: https://github.com/fujitsu/dnnl_aarch64 although I'm not aware of any firm plans to 
upstream into the main oneDNN repo. 

Hope this helps.

**Comment by guol-fnst** [comment]
Hi @vpirogov 
Really appreciated for your patience!
So are there any reasons why mkl-dnn for AARCH64 will not make use of "JITed" kernels. After all,  mkl-dnn itself takes use of "JITed kernels" for x64 to produce highly optimized code.
Thanks!

**Comment by vpirogov** [comment]
@guol-fnst,

JIT kernels are specific to instruction set architecture (ISA), so every new ISA requires a separate implementation. These kernels were not implemented for Aarch64 yet. JIT optimizations will be available if and when someone takes time to develop and contribute these to oneDNN.

**Comment by guol-fnst** [comment]
> @guol-fnst,
> 
> JIT kernels are specific to instruction set architecture (ISA), so every new ISA requires a separate implementation. These kernels were not implemented for Aarch64 yet. JIT optimizations will be available if and when someone takes time to develop and contribute these to oneDNN.

Thanks for your reply! 

@nSircombe Also much appreciated!

**Comment by kawakami-k** [comment]
Fujitsu plans to upstream JIT kernels for aarch64 to oneDNN v1.6.
In the next few days, I will be putting out an RFC regarding the implementation of AArch64.

**Comment by emfomenk** [comment]
> Fujitsu plans to upstream JIT kernels for aarch64 to oneDNN v1.6.
> In the next few days, I will be putting out an RFC regarding the implementation of AArch64.

@kawakami-k, it is exciting! Thank you! Looking forward for the RFC.
A minor comment: oneDNN v1.6 has already been [released](https://github.com/oneapi-src/oneDNN/releases/tag/v1.6), so the upstream could happen for v1.7+ only.

**Comment by kosaki** [comment]
Just offtopic notice: Fujitsu formed a single team to upstream our JITed DNN code, which @kawakami-k and @guol-fnst join. We will show you our RFC soon. :-)

**Comment by emfomenk** [comment]
Thanks @kosaki! Looking forward to the RFC! :)

@guol-fnst, I assume the original question is answered, so I am closing the issues. 
Please, feel free to reopen this issue or open a new one if you have further questions.

**Comment by amitdo** [comment]
>**WARNING**

>    Arm 64-bit Architecture (AArch64), Power ISA (PPC64) and IBMz (s390x) support is **experimental** with limited testing validation.

Is there a plan to have full (non-experimental) support for Arm 64 in the near future?
