### ISSUE TITLE
MKL Optimisations in Python

### ISSUE THREAD

**Issue by RuoshArora** [oneapi-src/oneDNN#791]
I was wondering, how do I turn off the MKL optimisations in **TensorFlow and PyTorch**?

I want to disable it to measure my gain in performance when using mkldnn.

Thank you!!!

**Comment by dzarukin** [comment]
Hi @RuoshArora,
Please refer to TF [build documentation](https://www.tensorflow.org/install/source#configure_the_build) to switch on/off oneDNN.
For PyTorch I haven't found any related documentation for the request. @Jianhui-Li, @mingfeima could you help with a request, please?
Thanks.

**Comment by pinzhenx** [comment]
Hi @RuoshArora,

For pytorch, you could disable mkldnn at both compile-time and runtime.

* Disable at compile-time

As per [this instructions](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#build-only-what-you-need), you just need to prepend `USE_MKLDNN=0` before `python setup.py install`.

* Disable at runtime

wrap your code in a `with` context

```
import torch.backends.mkldnn

m = YourModel()
x = torch.rand(1,2,3,4)

with torch.backends.mkldnn.flags(enabled=False):
    # wrap you code here
    y = m(x)
```

**Comment by RuoshArora** [comment]
That was very very helpful! Thank you so much

**Comment by vpirogov** [comment]
Closing as the question is addressed.
