### ISSUE TITLE
Different activation functions for lstm

### ISSUE THREAD

**Issue by pranathibl** [oneapi-src/oneDNN#792]
Hi,

Is there any option to use different activation for gates in lstm layer?
For example, instead of sigmoid using hard-sigmoid activation for input gate.

Thanks,
Pranathi

**Comment by dzarukin** [comment]
Hi @pranathibl,
OneDNN doesn't provide an API extension to specify any other activations for LSTM cell kind. Moreover, oneDNN doesn't support hard-sigmoid activation function.
The best shot I may suggest is to create a fork of oneDNN, get down to the place where activation function is applied and modify the source code to support it if this is desired.
Another option would be to provide a justification why this is important for the library to support such extension and either to make a contribution with preliminary RFC posted for the team review or create a request which may be implemented in future with the correspondent priority.
Thanks.

**Comment by vpirogov** [comment]
Closing as the question is addressed.
