### ISSUE TITLE
cant found libmklml_intel.so

### ISSUE THREAD

**Issue by 652994331** [oneapi-src/oneDNN#810]
Hi, i am using tensorflow-1.13.1, however, it seems it built with mkl by default. So i followed this https://github.com/mind/wheels#mkl.

But there's no prepare_mkl.sh in latest version mkl_dnn, and i also cant find libmklml_intel.so after i installed it. Please help !

**Comment by ahuizxc** [comment]
> Hi, i am using tensorflow-1.13.1, however, it seems it built with mkl by default. So i followed this https://github.com/mind/wheels#mkl.
> 
> But there's no prepare_mkl.sh in latest version mkl_dnn, and i also cant find libmklml_intel.so after i installed it. Please help !

```
source /opt/intel/mkl/source /opt/intel/mkl/bin/mklvars.sh
```
will help you.

**Comment by vpirogov** [comment]
Hi @652994331,

Tensorflow 1.13 was released more than a year ago and is not compatible with oneDNN v1.7, which is currently developed in master branch. To build TF 1.13 you need previous version of this library, [Intel MKL-DNN v0.17](https://github.com/oneapi-src/oneDNN/releases/tag/v0.17):
```
git clone -b rls-v0.17 https://github.com/01org/mkl-dnn.git
```

**Comment by 652994331** [comment]
@vpirogov  got u, thanks so much
