### ISSUE TITLE
Could you tell me if there is anything else we need to agree with?

### ISSUE THREAD

**Issue by YukihiroKomura** [oneapi-src/oneDNN#825]
Hi, I'm Yukihiro Komura from Fujitsu.

Currently, we are taking internal procedures to post "https://github.com/oneapi-src/oneDNN/pull/811".
In posting, I saw the following "Contributing Guidelines" and " LICENSE ".
https://github.com/oneapi-src/oneDNN/blob/master/CONTRIBUTING.md
https://github.com/oneapi-src/oneDNN/blob/master/LICENSE
Could you tell me if there is anything else we need to agree with?

**Comment by vpirogov** [comment]
Hi Komura-san,

Contributions to oneDNN project are governed by [Apache License 2.0](https://github.com/oneapi-src/oneDNN/blob/master/LICENSE). Please make sure your code complies with it's terms and conditions. We do not require any additional paperwork.

Contributing guidelines are not a legal document. These outline key technical and style requirements to the code in oneDNN project. The guidelines are not exhaustive and you may expect to get feedback or requests to modify the contribution code from other onedNN contributors.

Hope this helps,
Vadim

**Comment by YukihiroKomura** [comment]
Hi Vadim-san,

Thank you for your precise reply to what I wanted to hear.
Now we can proceed with the internal procedures.
Thank you for your reply.
