### ISSUE TITLE
Embedding Layer

### ISSUE THREAD

**Issue by marsupialtail** [oneapi-src/oneDNN#827]
Is there a primitive in the works for an embedding layer for NLP models like LSTMs and Transformers?

**Comment by vpirogov** [comment]
Hi @marsupialtail,

There is no embedding functionality in oneDNN currently. This is a part of the workload that is expected to be implemented in the application using native programming model.

**Comment by WilliamTambellini** [comment]
Dont know if @marsupialtail is speaking about such layer but here are for instance the doc of the embedding algo 
from pytorch:
https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html
from TF:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding
a way to extract a tensor from indices, basically a memory op more than a computation op.

**Comment by marsupialtail** [comment]
That's right I was looking for that op. Since you guys don't have it then I guess it must be implemented.
