### ISSUE TITLE
Question: Using oneDNN in a multhreaded application

### ISSUE THREAD

**Issue by pratikfegade** [oneapi-src/oneDNN#828]
I'm running a multi-threaded application which spawns 8 threads (to occupy all the physical cores in my machine) using OpenMP (I'm using libomp.so). I wish to invoke oneDNN in a single threaded manner within each of the 8 outer application threads. Currently, when I try to do this the program deadlocks within opnMP after making calls to oneDNN. Disabling nested parallelism in OpenMP leads to the same behavior. Is what I wish to do a possible usage scenario for oneDNN. If so, what knobs do I need to set?

**Comment by vpirogov** [comment]
Hi @pratikfegade,

Could you please elaborate on what oneDNN functions you call from OpenMP parallel sections?

**Comment by vpirogov** [comment]
oneDNN primitives are not thread safe by default. See [developer guide section on scratchpad](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_scratchpad.html) for details.

**Comment by vpirogov** [comment]
Closing this as we do not have enough information to investigate further. Feel free to reopen or submit a new one with additional data.
