### ISSUE TITLE
Is AVX-512 enabled automatically?

### ISSUE THREAD

**Issue by blueberry** [oneapi-src/oneDNN#829]
Hi,

I'm running DNNL on i9-9900X, which, by specification has two AVX512 units. I have a few questions:
- Does DNNL automatically use AVX512 hardware, or I have to enable it explicitly (through some environment variable for example)?
- What operations should benefit the most from AVX512 (so I can test that) and what speedup should be normally expected comparing to processors with AVX2?
- The third question is related to MKL. I know it's another Intel's library, but I'll try anyway :) Does MKL use AVX512 when I don't enable it explicitly through MKL_ENABLE_AVX512? I've compared big fgemm and there seems to be no difference with or without this env variable.

**Comment by emfomenk** [comment]
Hi @blueberry,

> Does DNNL automatically use AVX512 hardware, or I have to enable it explicitly (through some environment variable for example)?

The library picks the most appropriate ISA on its own, no need for special actions. You can verify what ISA is used by looking at `DNNL_VERBOSE=1` and finding something like `jit:avx512_core` as opposite to `jit:avx2`.

You can also use `DNNL_MAX_CPU_ISA` to play with dispatching different ISAs.

> What operations should benefit the most from AVX512 (so I can test that) and what speedup should be normally expected comparing to processors with AVX2?

Compute bound operations are mostly the ones that would gain a lot from wider registers. That is: convolution, inner product, gemm, RNN, matmul, deconvolution. The speed-up compared to AVX2 depends on the operating CPU frequency, algorithm efficiency, and other things, but typically it is in the ballpark from 1.5 to 2x (assuming the same CPU frequency and algorithm efficiency the ideal scaling should be around 2x for solely compute-bound problems like big gemm).

Memory bandwidth limited functions like reorder, pooling, eltwise won't benefit much, especially if the data processed doesn't fit into caches.

> The third question is related to MKL. I know it's another Intel's library, but I'll try anyway :) Does MKL use AVX512 when I don't enable it explicitly through `MKL_ENABLE_AVX512`? 

Intel MKL behaves similarly to DNNL -- dispatches to the most appropriate ISA. You don't need to set any special environment variables (unless you use very-very old Intel MKL, from 2015 or so). Moreover, there is no such thing as `MKL_ENABLE_AVX512`. There is [`MKL_ENABLE_INSTRUCTION=AVX512`](https://software.intel.com/content/www/us/en/develop/documentation/mkl-linux-developer-guide/top/managing-behavior-of-the-intel-math-kernel-library-with-environment-variables/instruction-set-specific-dispatching-on-intel-architectures.html), but this is probably what you meant.

**Comment by blueberry** [comment]
Thank you! I enabled verbose output, and can see that avx512 is emitted.

(Regarding MKL, I've found that MKL_ENABLE_AVX512 setting in the docs, but since the highest available performance capability is used by default, that's good enough for me :)

**Comment by emfomenk** [comment]
> Regarding MKL, I've found that MKL_ENABLE_AVX512 setting in the docs

Actually, this is my mistake. Intel MKL has `MKL_ENABLE_AVX512`, but as a part of function call, not environment variable that I think you referred to. So, a user can either do
``` cpp
// cpp
int main()
    mkl_enable_instructions(MKL_ENABLE_AVX512)
    mkl_foo();
    ...
}
```
or just
``` bash
$ export MKL_ENABLE_INSTRUCTION=AVX512
$ ./app
```

But neither is required in your case. BTW, you could validate that Intel MKL dispatches correctly by looking at the output when you set `MKL_VERBOSE=1`, which is a counterpart of `DNNL_VERBOSE=1`, but for Intel MKL.

**Comment by emfomenk** [comment]
P.S.

I would suggest using [`benchdnn`](https://github.com/oneapi-src/oneDNN/tree/master/tests/benchdnn#benchdnn) -- a performance and correctness benchmark for oneDNN -- to play and see the performance aspects of different convolutions and different ISAs being used (controlled by `DNNL_MAX_CPU_ISA`).

``` bash
$ export OMP_NUM_THREADS=8 KMP_AFFINITY=granularity=fine,compact
$ DNNL_MAX_CPU_ISA=AVX2 ./tests/benchdnn/benchdnn --conv --mode=P mb50_ic256oc256_ih13kh3ph1
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,jit:avx2,,--conv mb50ic256ih13oc256oh13kh3ph1,8.97188,0,21.2268,422.667,21.2741,421.728
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):21.2268 avg(ms):21.2741

$ ./tests/benchdnn/benchdnn --conv --mode=P mb50_ic256oc256_ih13kh3ph1
Output template: perf,%engine%,%impl%,%name%,%prb%,%Gops%,%Gfreq%,%-time%,%-Gflops%,%0time%,%0Gflops%
perf,cpu,jit:avx512_common,,--conv mb50ic256ih13oc256oh13kh3ph1,8.97188,0,10.522,852.68,10.561,849.531
tests:1 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
total perf: min(ms):10.522 avg(ms):10.561
```

So, for this particular convolution problem AVX512 gives 2.01x speed up (852 GFlops / 422 GFlops).

Some more information on how to properly measure performance could be found here: https://oneapi-src.github.io/oneDNN/dev_guide_performance_settings.html.
