### ISSUE TITLE
Regarding Matmul Operations

### ISSUE THREAD

**Issue by Alok-Ranjan23** [oneapi-src/oneDNN#835]
When I have run matmul.cpp available in examples/primitives for two sizes.
Case 1:  M=1 K=379 N=110,  src_matrix is transposed here.
              i.e.  transa=CblasTrans, transb=CblasNoTrans

Case 2:   M=321 K=1 N=943, filter_matrix is transposed here.
              i.e. transa=CblasNoTrans transb=CblasTrans

--- In src/cpu/matmul/gemm_f32_matmul.cpp, the following logic is used to decide whether we need to transpose or not.

 `const char *transA
            = src_strides[1] == 1 && src_d.dims()[batched + 0] > 1 ? "N" : "T";`
`const char *transB
            = weights_strides[1] == 1 && weights_d.dims()[batched + 0] > 1
            ? "N"
            : "T";
`

Can you please elaborate when we need to transpose_input and transpose filter? What are constraints on the M,K, and N for the transpose of input and filter?

**Comment by emfomenk** [comment]
Hi @Alok-Ranjan23,

Sorry for delay with response.

> Can you please elaborate when we need to transpose_input and transpose filter?

I am not sure I understand the question.
It is up to a user to decide if they want src and filter to be transposed or not. Typically, `src_matrix` comes from some other operations, and it is difficult to control its layout. However, `filter_matrix` can be prepared in advance, so it is possible to pre-transpose it if this helps performance.
For the former case a user just provides the proper memory format to oneDNN, and the library complies. For the latter case, a user can pass memory format `any` to allow a primitive decide what the most performant layout is. Then the user needs to query the required format back from a primitive, and reorder the matrix if necessary.
- Documentation [link](https://oneapi-src.github.io/oneDNN/memory_format_propagation_cpp.html).
- Matmul tutorial for inference: [link](https://github.com/oneapi-src/oneDNN/blob/a39781dc400fa7e352ade999c057a80d1f025186/examples/tutorials/matmul/inference_int8_matmul.cpp#L109-L110). Note that src format is fixed, but the weights format is created with `any`. 

> What are constraints on the M,K, and N for the transpose of input and filter?

No constrains as far as I know.

> In `src/cpu/matmul/gemm_f32_matmul.cpp`, the following logic is used to decide whether we need to transpose or not.
>
> ``` cpp
> const char *transA = src_strides[1] == 1 && src_d.dims()[batched + 0] > 1 ? "N" : "T";
> const char *transB = weights_strides[1] == 1 && weights_d.dims()[batched + 0] > 1 ? "N" : "T";
> ```

The code translates the strides from memory descriptors that oneDNN uses to "gemm-language": `CblasNoTrans` / `CblasTrans`, as matmul primitive relies on gemm.

**Comment by Alok-Ranjan23** [comment]
Hi @emfomenk ,

Thanks for your reply.

In src/cpu/matmul/gemm_f32_matmul.cpp, the following logic is used to translate the strides from memory descriptors that oneDNN uses to "gemm-language": CblasNoTrans / CblasTrans, as matmul primitive relies on gemm.

`const char *transA = src_strides[1] == 1 && src_d.dims()[batched + 0] > 1 ? "N" : "T";`

`const char *transB = weights_strides[1] == 1 && weights_d.dims()[batched + 0] > 1 ? "N" : "T";`

What is **src_strides[1]**, **weights_strides[1]**, **src_d.dims()** and **batched** in above lines?

**Comment by emfomenk** [comment]
- `src_strides[1]` is a stride that corresponds to `src_md.dims[batched + 1]`, the `K` dimension of matrix A;
- `src_d.dims()` is an alies to `src_md.dims`, i.e. the logical dimensions of src tensor: `{[batch], M, K}`;
- `batched == 0` if src/weights/dst are 2D tensors, and `1` if if src/weights/dst are 3D tensors;

For simplicity I will assume the matmul is not batched, i.e. `batched == 0`.

The `src_strides[1]` corresponds to the stride for "K" dimension of matrix A. BLAS case `transA == NoTrans` is when matrix A is laid out as `M x K` in C notation, that is where K is the innermost dimension. In other words, when the stride for K dimension is `1`, and stride for `M` dimension is K. That's the check: 
``` cpp
src_stride[1] == 1 // i.e. stride of the K dim == 1
```
There is a corner case when `M` is 1. In this case even if matrix is `K x M`, the stride for K would still be `1`. That's why we have an additional check:
``` cpp
src_d.dims()[0] > 1 // i.e. M dim > 1
```

In any case, these all checks are the implementation details.
May I know the reason you want to dive into these details?

**Comment by Alok-Ranjan23** [comment]
Does trans_input and trans_filter has any effect on matmul operation except the performance of the matmul operation?

**Comment by emfomenk** [comment]
> Does trans_input and trans_filter has any effect on matmul operation except the performance of the matmul operation?

Trans input and filter correspond to the data layout on the user side.
There are no changes to the semantic of the operation (leaving memory layout aside). Feature coverage is the same too, i.e. no matter if you matrix A (src) is transposed or not, the matmul primitive supports tanh, sigmoid and other post operations, supports s8 * s8 computations, etc.

**Comment by Alok-Ranjan23** [comment]
Does input_transpose and filter_transpose alter the result?

**Comment by emfomenk** [comment]
Seems the question is addressed. Closing the issue.
Feel free to re-open or to create a new one.
