### ISSUE TITLE
Compiling and running on Aarch64 server

### ISSUE THREAD

**Issue by GalMoore** [oneapi-src/oneDNN#836]
Hey,

Great to see oneDNN will soon support Aarch64. Is there some example demonstrating how to build, compile and run an exec on aarch64? Also, what exactly is the meaning of JIT? Does that mean I will not have a stand alone executable to run?

Thanks!

Gal

**Comment by vpirogov** [comment]
Hi @GalMoore,

You can find instructions on building and testing oneDNN in the [developer guide](https://oneapi-src.github.io/oneDNN/dev_guide_build.html). The only AArch64 specific option that oneDNN has is [`DNNL_BLAS_VENDOR=ARMPL`](https://oneapi-src.github.io/oneDNN/dev_guide_build_options.html).

oneDNN is a library, not an executable program. It's typically used as part of an application like Pytorch or Tensorflow. The distribution includes several executable programs: [examples and tutorials](https://github.com/oneapi-src/oneDNN/tree/master/examples) and [benchdnn](https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/README.md), a comprehensive functional and performance validation tool for the library.

JIT stands for just-in-time code generation. This is a technology oneDNN uses to specialize implementations of critical functions to platform instruction set (ISA) and generate optimized implementations of some functions at runtime.

**Comment by vpirogov** [comment]
+@nSircombe for additional insights on Aarch64.

**Comment by nSircombe** [comment]
Hi @GalMoore,

As it stands, oneDNN will build 'out of the box' on AArch64, as @vpirogov points out, it is also possible to link against [Arm Performance Libraries](https://developer.arm.com/tools-and-software/server-and-hpc/compile/arm-compiler-for-linux/arm-performance-libraries) which provides improved performance for some fp32 operations (such as convolutions) by leveraging the optimised AArch64 BLAS kernels developed (originally) for scientific computing and HPC applications.

There's a PR under review at the moment (#820) that would start to integrate operators from [Arm Compute Library](https://www.mlplatform.org). Compute Library, unlike Arm Performance Libraries, is targeted at ML workloads and provides support for features and functionality common in ML.

In terms of building frameworks using oneDNN, there are Docker recipes available as part of [Arm's 'Tool-Solutions' repo](https://github.com/ARM-software/Tool-Solutions) - see: https://github.com/ARM-software/Tool-Solutions/tree/master/docker/tensorflow-aarch64

These can be used to build a Docker image with TensorFlow 2.3 and dependencies, with options to use to oneDNN and ArmPL. The option to build with oneDNN and Compute Library will naturally become a part of this build, assuming #820 is accepted.

Currently the PyTorch build here: https://github.com/ARM-software/Tool-Solutions/tree/master/docker/pytorch-aarch64 does not currently provide an option to build with a oneDNN backend, but this should be available in the future.

...these Docker builds will be incrementally updated to capture improvements across the whole stack. At the moment they're ideal for getting a 'first look' at common ML stacks on AArch64 servers, and should be a valuable resource for anyone trying to build part of the stack outside of Docker (see, for example, the build-scripts that the Dockerfile uses here: https://github.com/ARM-software/Tool-Solutions/tree/master/docker/tensorflow-aarch64/scripts.

Hope that helps.
Cheers,
Nathan.

**Comment by GalMoore** [comment]
Dear nSircombe,

Many thanks to you and @vpirogov for your responses. 

I’ve created a small project to demonstrate how we achieve 300microsecond inference on single core x86 [here](https://github.com/GalMoore/Two_Layer_Convnet_MKLDNN/blob/master/README.MD). It would be great if you could run this and see how this same project could be restructured to run on aarch64.

From our measurements; the first run (which I assume loads the params) takes about 70milliseconds and the following 10k runs take 300microsecods each. I can add that building this network directly using ACL to run on a single core ARM server was orders of magnitude slower.

I look forward to hearing from you.
Many thanks,

Gal

**Comment by GalMoore** [comment]
@vpirogov @nSircombe Did you guys have a chance to take a look?

**Comment by nSircombe** [comment]
Hi @GalMoore 

I have to confess, I missed the reply above, so I've not looked into it yet. I'll take a look and let you know.

**Comment by nSircombe** [comment]
> building this network directly using ACL to run on a single core ARM server 
Could you clarify - slower than oneDNN without ACL on AArch64, or slower than the x86 build with oneDNN? Or are you comparing [this](https://github.com/GalMoore/Two_Layer_Convnet_MKLDNN/blob/master/README.MD) x86 build with an unpublished, oneDNN-free AArch64 version? 

Do you have the AArch64 version of https://github.com/GalMoore/Two_Layer_Convnet_MKLDNN?

**Comment by vpirogov** [comment]
Closing the issue as discussion stalled. Feel free to reopen or submit a new one with additional data.
