### ISSUE TITLE
LSTM enhancement for batch size 1

### ISSUE THREAD

**Issue by affranchi** [oneapi-src/oneDNN#837]
# Summary
LSTM with single batch and multiple time steps doesn't work fast in oneDNN.

# Problem statement
My customer uses single batch with multiple sequence. It's usual in speech models.
lstm_forward and lstm_prim.execute take some time from my analysis. FYI, one customer model includes 

`
batch size = 1
time steps = 63
input size = 24
channel size 32
gates = 4
Layer = 1
Direction 2
`
`
batch size = 1
time steps = 31
input size = 48
channel size 32
gates = 4
Layer = 1
Direction 2
`
`
batch size = 1
time steps = 15
input size = 96
channel size 32
gates = 4
Layer = 1
Direction 2
`
`
batch size = 1
time steps = 31
input size = 48
channel size 32
gates = 4
Layer = 1
Direction 2
`

As shown above, the  LSTMs have small feature(channel) size and input size.
I tested the above cases using the below source code based on example:

```
    void LSTM(memory::dim N, memory::dim T, memory::dim I, memory::dim C, memory::dim G, memory::dim L, memory::dim D)
    {
        using Clock = std::chrono::steady_clock;
        using OutputDur = std::chrono::microseconds;
        using std::chrono::duration_cast;

        // Create execution dnnl::engine.
        dnnl::engine engine(dnnl::engine::kind::cpu, 0);
        // Create dnnl::stream.
        dnnl::stream engine_stream(engine);

        // Source (src), weights, bias, and destination (dst) tensors
        // dimensions.
        memory::dims src_dims = {T, N, I};
        memory::dims weights_dims = {L, D, I, G, C};
        memory::dims weights_iter_dims = {L, D, C, G, C};
        memory::dims bias_dims = {L, D, G, C};
        memory::dims dst_dims = {T, N, D*C};
        // Allocate buffers.
        std::vector<float> src_layer_data(product(src_dims));
        std::vector<float> weights_layer_data(product(weights_dims));
        std::vector<float> weights_iter_data(product(weights_iter_dims));
        std::vector<float> dst_layer_data(product(dst_dims));
        std::vector<float> bias_data(product(bias_dims));
        // Initialize src, weights, and bias tensors.
        std::generate(src_layer_data.begin(), src_layer_data.end(), []() {
            static int i = 0;
            return std::cos(i++ / 10.f);
        });
        std::generate(weights_layer_data.begin(), weights_layer_data.end(), []() {
            static int i = 0;
            return std::sin(i++ * 2.f);
        });
        std::generate(bias_data.begin(), bias_data.end(), []() {
            static int i = 0;
            return std::tanh(i++);
        });
        // Create memory descriptors and memory objects for src, bias, and dst.
        auto src_layer_md = memory::desc(src_dims, dt::f32, tag::tnc);
        auto bias_md = memory::desc(bias_dims, dt::f32, tag::ldgo);
        auto dst_layer_md = memory::desc(dst_dims, dt::f32, tag::tnc);
        auto src_layer_mem = memory(src_layer_md, engine);
        auto bias_mem = memory(bias_md, engine);
        auto dst_layer_mem = memory(dst_layer_md, engine);
        // Create memory objects for weights using user's memory layout. In this
        // example, LDIGO is assumed.
        auto user_weights_layer_mem
                = memory({weights_dims, dt::f32, tag::ldigo}, engine);
        auto user_weights_iter_mem
                = memory({weights_iter_dims, dt::f32, tag::ldigo}, engine);
        // Write data to memory object's handle.
        write_to_dnnl_memory(src_layer_data.data(), src_layer_mem);
        write_to_dnnl_memory(bias_data.data(), bias_mem);
        write_to_dnnl_memory(weights_layer_data.data(), user_weights_layer_mem);
        write_to_dnnl_memory(weights_iter_data.data(), user_weights_iter_mem);
        // Create memory descriptors for weights with format_tag::any. This enables
        // the LSTM primitive to choose the optimized memory layout.
        auto lstm_weights_layer_md = memory::desc(weights_dims, dt::f32, tag::any);
        auto lstm_weights_iter_md = memory::desc(weights_iter_dims, dt::f32, tag::any);
        // Optional memory descriptors for recurrent data.
        auto src_iter_md = memory::desc();
        auto src_iter_c_md = memory::desc();
        auto dst_iter_md = memory::desc();
        auto dst_iter_c_md = memory::desc();

        // Create operation descriptor.
        auto lstm_desc = lstm_forward::desc(prop_kind::forward_training,
                D > 1 ? rnn_direction::bidirectional_concat : 
                rnn_direction::unidirectional_left2right, src_layer_md, src_iter_md,
                src_iter_c_md, lstm_weights_layer_md, lstm_weights_iter_md, bias_md,
                dst_layer_md, dst_iter_md, dst_iter_c_md);
        // Create primitive descriptor.
        auto lstm_pd = lstm_forward::primitive_desc(lstm_desc, engine);
        // For now, assume that the weights memory layout generated by the primitive
        // and the ones provided by the user are identical.
        auto lstm_weights_layer_mem = user_weights_layer_mem;
        auto lstm_weights_iter_mem = user_weights_iter_mem;
        // Reorder the data in case the weights memory layout generated by the
        // primitive and the one provided by the user are different. In this case,
        // we create additional memory objects with internal buffers that will
        // contain the reordered data.
        if (lstm_pd.weights_desc() != user_weights_layer_mem.get_desc()) {
            lstm_weights_layer_mem = memory(lstm_pd.weights_desc(), engine);
            reorder(user_weights_layer_mem, lstm_weights_layer_mem)
                    .execute(engine_stream, user_weights_layer_mem,
                            lstm_weights_layer_mem);
        }
        if (lstm_pd.weights_iter_desc() != user_weights_iter_mem.get_desc()) {
            lstm_weights_iter_mem = memory(lstm_pd.weights_iter_desc(), engine);
            reorder(user_weights_iter_mem, lstm_weights_iter_mem)
                    .execute(engine_stream, user_weights_iter_mem,
                            lstm_weights_iter_mem);
        }
        // Create the memory objects from the primitive descriptor. A workspace is
        // also required for LSTM.
        // NOTE: Here, the workspace is required for later usage in backward
        // propagation mode.
        auto src_iter_mem = memory(lstm_pd.src_iter_desc(), engine);
        auto src_iter_c_mem = memory(lstm_pd.src_iter_c_desc(), engine);
        auto weights_iter_mem = memory(lstm_pd.weights_iter_desc(), engine);
        auto dst_iter_mem = memory(lstm_pd.dst_iter_desc(), engine);
        auto dst_iter_c_mem = memory(lstm_pd.dst_iter_c_desc(), engine);
        auto workspace_mem = memory(lstm_pd.workspace_desc(), engine);
        // Create the primitive.
        const auto pdf_time1 = Clock::now();
        auto lstm_prim = lstm_forward(lstm_pd);
        const auto pdf_time2 = Clock::now();
        // Primitive arguments
        std::unordered_map<int, memory> lstm_args;
        lstm_args.insert({DNNL_ARG_SRC_LAYER, src_layer_mem});
        lstm_args.insert({DNNL_ARG_WEIGHTS_LAYER, lstm_weights_layer_mem});
        lstm_args.insert({DNNL_ARG_WEIGHTS_ITER, lstm_weights_iter_mem});
        lstm_args.insert({DNNL_ARG_BIAS, bias_mem});
        lstm_args.insert({DNNL_ARG_DST_LAYER, dst_layer_mem});
        lstm_args.insert({DNNL_ARG_SRC_ITER, src_iter_mem});
        lstm_args.insert({DNNL_ARG_SRC_ITER_C, src_iter_c_mem});
        lstm_args.insert({DNNL_ARG_DST_ITER, dst_iter_mem});
        lstm_args.insert({DNNL_ARG_DST_ITER_C, dst_iter_c_mem});
        lstm_args.insert({DNNL_ARG_WORKSPACE, workspace_mem});
        // Primitive execution: LSTM.
        const auto exe_time1 = Clock::now();
        lstm_prim.execute(engine_stream, lstm_args);
        // Wait for the computation to finalize.
        engine_stream.wait();
        const auto exe_time2 = Clock::now();

        const auto pdf_time = pdf_time2-pdf_time1;
        const auto exe_time = exe_time2-exe_time1;
        std::ofstream f;
        f.open ("/home/oneDNN/workspace/lstm_result.txt",std::ios::app);
        f << "[Batch: " << N << "] [Seq: " << T << "] [InputSize: " << I << "] [FeatureSize: " << C << "] [Directions: " << D << " ] "
                << duration_cast<OutputDur>(pdf_time).count() << ", " <<  duration_cast<OutputDur>(exe_time).count() << "\n";
        myfile.close();
    }
```

Results(microseconds):
[Batch: 1] [Seq: 63] [InputSize: 24] [FeatureSize: 32] [Directions: 2 ] 17, 1075
[Batch: 1] [Seq: 31] [InputSize: 48] [FeatureSize: 32] [Directions: 2 ] 166, 595
[Batch: 1] [Seq: 15] [InputSize: 96] [FeatureSize: 32] [Directions: 2 ] 187, 348

Verbose echo:
dnnl_verbose,info,oneDNN v1.6.0 (commit N/A)
dnnl_verbose,info,cpu,runtime:TBB
dnnl_verbose,info,cpu,isa:Intel AVX-512 with AVX512BW, AVX512VL, and AVX512DQ extensions
dnnl_verbose,info,gpu,runtime:none

dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 src_iter_undef::undef::f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0 dst_iter_undef::undef::f0,,alg:vanilla_lstm direction:bidirectional_concat activation:undef,l1t63mb1sic32slc24dhc32dlc64,1.05591

dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 src_iter_undef::undef::f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0 dst_iter_undef::undef::f0,,alg:vanilla_lstm direction:bidirectional_concat activation:undef,l1t31mb1sic32slc48dhc32dlc64,0.533936

dnnl_verbose,exec,cpu,rnn,ref:any,forward_training,src_layer_f32::blocked:abc:f0 src_iter_undef::undef::f0 wei_layer_f32::blocked:abcde:f0 wei_iter_f32::blocked:abcde:f0 bias_f32::blocked:abcd:f0 dst_layer_f32::blocked:abc:f0 dst_iter_undef::undef::f0,,alg:vanilla_lstm direction:bidirectional_concat activation:undef,l1t15mb1sic32slc96dhc32dlc64,0.3059081

# Preferred solution
Would be nice if oneDNN provides well-optimized LSTM for single batch case.

**Comment by emfomenk** [comment]
Hi @affranchi,

Could you please share the HW (for the aforementioned numbers, and what you target in general), any expectations if you have, the importance (e.g. what is the contribution of these LSTM to overall workload time), etc?

These LSTM seem to be very small. It seems we still trying to use all available threads, and this actually plays against us:

| Skylake Server 8180 | (default) OMP=28 | OMP=8 | OMP=1 |
| :-- | :-- | :-- | :-- |
| `l1t63mb1sic32slc24dhc32dic32` | 1.97 ms | 0.74 ms | 0.18 ms |
| `l1t31mb1sic32slc48dhc32dic32` | 1.01 ms | 0.37 ms | 0.10 ms |
| `l1t15mb1sic32slc96dhc32dic32` | 0.51 ms | 0.19 ms | 0.06 ms |

Command line:
``` bash
$ OMP_NUM_THREADS=$omp numactl -m0 -N0 \
    ./benchdnn.rls-v1.6-5250726a5.gcc483.omp \
    --mode=P --rnn --alg=VANILLA_LSTM --direction=concat \
    l1t63mb1sic32slc24dhc32 \
    l1t31mb1sic32slc48dhc32 \
    l1t15mb1sic32slc96dhc32
```

So it seems at least some speed up could be obtained from running oneDNN in one thread. Could you please check? You can use `taskset` or `numactl` to limit the number of threads used for the TBB threading runtime.

**Comment by affranchi** [comment]
Hi @emfomenk ,

my test machine is AWS m5 (Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz / 16 vCPU / 64GB memory)
You're right.
The performance for LSTMs is getting better with less threads.

numactl -C 0 ./test
```
[Batch: 1] [Seq: 63] [InputSize: 24] [FeatureSize: 32] [Directions: 2 ] 14, 223
[Batch: 1] [Seq: 31] [InputSize: 48] [FeatureSize: 32] [Directions: 2 ] 141, 147
[Batch: 1] [Seq: 15] [InputSize: 96] [FeatureSize: 32] [Directions: 2 ] 128, 133
```

numactl -C 0,1 ./test
```
[Batch: 1] [Seq: 63] [InputSize: 24] [FeatureSize: 32] [Directions: 2 ] 15, 422
[Batch: 1] [Seq: 31] [InputSize: 48] [FeatureSize: 32] [Directions: 2 ] 161, 233
[Batch: 1] [Seq: 15] [InputSize: 96] [FeatureSize: 32] [Directions: 2 ] 145, 194
```

For other operator performance, I need to use threads. Do you have any recommendation in this case which has a model mixed with better performance operators in threads and worse performance operators in threads?

**Comment by emfomenk** [comment]
Hi @affranchi,

We don't have a specific recommendation for such mixed cases. The library doesn't have nice handles to switch the number of threads it uses. But in general you can do the following:
``` c
void create_primitive_one_thread() {
    omp_set_num_threads(1); // limit the number of threads
    prim = ...; // create primitive that will use only one thread
    omp_set_num_threads(restore_number);  // restore to allow an application use all threads
}
void execute_primitive_one_thread() {
    omp_set_num_threads(1); // limit the number of threads
    prim.execute(....); // execute in one thread
    omp_set_num_threads(restore_number); // restore to allow an application use all threads
}
```

TBB "analogues" for `omp_set_num_threads` is [task_arena](https://www.threadingbuildingblocks.org/docs/doxygen/a00144.html#abe92eac81ca849b110de69e6efd0e5aa) interface.

Please note, that for OMP it is important to create and execute primitive in the same environment. If you create a primitive when `omp_get_max_threads()` return one number, but at execution you get another number -- this could lead different issues. 

For TBB, this is not the case, you could use arena interface to limit number of threads used right before the execution. However, for performance reasons it is still recommended to create and execute a primitive under the same arena (so that at creation time the primitive used the proper decomposition that depends on number of threads/workers available).

Finally, if you only use one primitive from the whole oneDNN library you may consider using the sequential version.

In long term, however, I think we need to fix this negative scaling: at least make sure that when run on the whole system the performance is not worse than if run on a single thread.

> The performance for LSTMs is getting better with less threads.

Does performance on one thread meet you expectation? I understand the faster the better, but it would be nice to understand if this level of performance would be sufficient or insufficient.

**Comment by affranchi** [comment]
Thank you for your info. It's very helpful to enhance performance. Yes, faster is better but with this thread number control, I achieved my target performance. I have other issue for single batch LSTM case but will ask it on the other thread.
