### ISSUE TITLE
Fail to create convolution_forward descriptor

### ISSUE THREAD

**Issue by etom42** [oneapi-src/oneDNN#839]
Hi,
I am trying to create a convolution_forward descriptor but get dnnl_invalid_argument error.
I am trying to use the optimized memory layout as described in the documentation
(https://spec.oneapi.com/versions/latest/elements/oneDNN/source/primitives/convolution.html)

**Failing** configuration for 2D int8 convolution, taken from the documentation:
Src: data type s8, layout NHWC = {1, 11, 11, 32}
Wgt: data type s8, layout HWIO = {3, 3, 32, 1}
Dst: data type s32, layout NHWC = {1, 9, 9, 1}
Stride = {1, 1}
Pad (left and right) = {0, 0}

No bias, no other stuff.

**Passing** configuration (from example):
Src: data type s8, layout NCHW = {1, 32, 11, 11}
Wgt: data type s8, layout OIHW = {1, 32, 3, 3}
Dst: data type s32, layout NCHW = {1, 1, 9, 9}
Stride = {1, 1}
Pad (left and right) = {0, 0}

Any ideas?
Thanks
Eli

**Comment by emfomenk** [comment]
Hi @etom42,

I guess the problem in the failing case is the order of dimensions. Please note, that the dimensions should always be passed in the fixed (for each primitive, specified in the "data representation" section of the guide that you mentioned) order, regardless of the memory format. For convolution activations that is {N, C H, W}, even if the format is nhwc.  The weights: {O, I, H, W}.

**Comment by etom42** [comment]
Hi @emfomenk ,
Thank you very much - it solved it.

I re-read the the "data-representation" section and it wasn't clear about that.

Once again, thanks.
