### ISSUE TITLE
How does int8 winograd convolution use avx512_vnni instructions?

### ISSUE THREAD

**Issue by Gxllii** [oneapi-src/oneDNN#840]
I found that u8s8s32x_wino_convolution has been supported in oneDNN. The operands need to be u8 and s8 in the VPDPBUSD vnni instruction according to the documentation. However, the transformed input (activation) in Winograd convolution is not guaranteed to be non-negative values. How does oneDNN resolve and implement it? Thanks.

**Comment by kwiersch** [comment]
Hi @Gxllii ,

I believe that during the src transform, the potentially signed values are shifted by 128 (see [this line](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx512_core_u8s8s32x_wino_convolution.cpp#L232) in the src transform kernel). But that changes the meaning of the resulting GeMM from tsrc * twei to (tsrc + 128) * twei, so to get back the intended result the extra factor of 128 * twei must removed (this is typically called the "compensation" and is calculated at [this line](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/wino_reorder.hpp#L297) during the weights reorder).

Thanks,
Keola

**Comment by Gxllii** [comment]
Thanks! @kwiersch.

**Comment by Gxllii** [comment]
Hi @kwiersch,
I'm a little confused about the weights reorder operation. Was it done before int8 GEMM?

**Comment by emfomenk** [comment]
Yes, a reorder happens before executing the convolution.
It applies the winograd transform ([G_2x2_3x3](https://github.com/oneapi-src/oneDNN/blob/6bbc076ad32be82dae23cc1cd37da6323a305544/src/cpu/x64/wino_reorder.hpp#L174-L176)) and quantizes the weights (see [this line](https://github.com/oneapi-src/oneDNN/blob/6bbc076ad32be82dae23cc1cd37da6323a305544/src/cpu/x64/wino_reorder.hpp#L252-L254)).

**Comment by Gxllii** [comment]
So the result of gemm is initial by -128 * twei?

**Comment by emfomenk** [comment]
If I read the code correctly (@kwiersch please correct me if I am wrong) the registers [are initialized](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/x64/jit_avx512_core_u8s8s32x_wino_convolution.cpp#L622-L623) with `-128 * twei` (in the pointed code `reg_aux_dst_b` contains the address of [these values](https://github.com/oneapi-src/oneDNN/blob/6bbc076ad32be82dae23cc1cd37da6323a305544/src/cpu/x64/wino_reorder.hpp#L297-L298)) from the very beginning, and then gemm adds the result of `(tsrc + 128) * twei` to them.
