### ISSUE TITLE
Reduction primitive release?

### ISSUE THREAD

**Issue by affranchi** [oneapi-src/oneDNN#846]
Hi folks,

could you let me know which official version will include "Reduction" and when the version(or rc version) will be released? I'm using 1.6.1 now and looks 1.6.3 also doesn't include this Reduction. I have one model which needs reduction_sum so would be great for me if you guys can release this "Reduction" as soon as possible.

Thanks,
Kyungsoo

**Comment by igorsafo** [comment]
Hi @affranchi ,

Reduction functionality will be included in v1.7.  Release is targeting ww43 this year. Source code related to reduction primitive is already available in master so there is possibility to try this functionality by building oneDNN from source code.

**Comment by affranchi** [comment]
Thank you for the info. Does ww43 mean 43rd week in this year(Oct 19-Oct25)?
Yeah, I'll try to build from source code to check.

**Comment by igorsafo** [comment]
Yes, ww43 means 43rd work week. Sorry for the confusion.

**Comment by emfomenk** [comment]
Shameless hijacking the thread.
The release schedule can be found here: https://github.com/oneapi-src/oneDNN/milestones

**Comment by affranchi** [comment]
Thank you so much for all the info!
