### ISSUE TITLE
How to determine weight format for depthwise post-op?

### ISSUE THREAD

**Issue by FedyuninV** [oneapi-src/oneDNN#849]
I've been trying to fuse conv1x1 (via `convPostOps.append_dw_k3s*p1`) with depthwiseConv and I've faced the next problem.

In order to use it I should allocate memory for depthwise weights and bias. And I can't find out which format is required for them.

```c++
using namespace dnnl;

memory dwWeightMemory( { { 32, 1, 1, 3, 3 }, memory::data_type::f32, /* Which format should I use here? */ memory::format_tag::goihw }, eng );
memory dwBiasMemory( { { 32 }, memory::data_type::f32, /* Which format should I use here? */ memory::format_tag::x }, eng );

/*
 * Here dwWeightMemory and dwBiasMemory are filled with initial values
 */

// Adding primitive with args
fwd.push_back( convolution_forward( convPd ) );
fwdArgs.push_back( { { DNNL_ARG_SRC, srcMemory }, { DNNL_ARG_WEIGHTS, weightMemory }, { DNNL_ARG_DST, dstMemory },
    { DNNL_ARG_ATTR_POST_OP_DW | DNNL_ARG_WEIGHTS, dwWeightMemory }, { DNNL_ARG_ATTR_POST_OP_DW | DNNL_ARG_BIAS, dwBiasMemory }  } );
```

What I've managed to find out:
- `memory::format_tag::goihw` doesn't work (number mismatch with the similar net, where depthwise isn't fused with conv1x1)
- I can't use any info from `convPd.weight_desc()` because of mismatch between sizes ( `{C, 1, 1, 3, 3}` and `{OC, IC, 1, 1}` )
- A little dive into the code didn't help to find out :(

**Comment by vpirogov** [comment]
Hi @FedyuninV,

oneDNN developer guide has a section on [depthwise post-op](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html) that might be helpful. Depthwise convolution has `g = ic = oc` , so the weights shape should be `{32, 32, 32, 3, 3}`. To get fast implementation of the operation you need to [query memory formats](https://oneapi-src.github.io/oneDNN/memory_format_propagation_cpp.html) for destinaion and weight tensors with `format::any` and reorder the weights.

Adding @tprimak, @nivas-x86 for additional comments.

**Comment by nivas-x86** [comment]
@FedyuninV  the [document](https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html) @vpirogov referred has an example "**Relu -> Depthwise -> Relu**". The last two lines of this example, particularly shows how to query memory formats for depthwise.

**Comment by FedyuninV** [comment]
@vpirogov @nivas-x86 Thanks a lot! I've overlooked this example. Now it works!
