### ISSUE TITLE
Compiling oneDNN for AARCH64 cross compile 

### ISSUE THREAD

**Issue by GalMoore** [oneapi-src/oneDNN#851]
Hey, I'm trying to compile oneDNN for cross compile; from x86 to aarch64 server. I'm using the 1.7-RC tag and the following command to generate makefile:

![image](https://user-images.githubusercontent.com/14869708/95973902-e9d73380-0e1c-11eb-8630-357a26934ac4.png)

** I can't copy paste the exact command so please ignore typos.

The error I'm getting during "make" is:

![image](https://user-images.githubusercontent.com/14869708/95973916-ee9be780-0e1c-11eb-9166-79fce1a7b5f7.png)

EDIT:
And when using the correct compiler I get: 

`aarch64-linux-gnu-g++:` error: unrecognized command line option ‘-msse4.1’

Thanks for your help!
Gal

**Comment by emfomenk** [comment]
Seems you already found a solution, but just for the future reference.
Seems like `-DDNNL_TARGET_ARCH=AARCH64` cmake option is missing.
