### ISSUE TITLE
The algorithm to calculate the exponent of a vector

### ISSUE THREAD

**Issue by benjamim93** [oneapi-src/oneDNN#854]
Can anyone tell me the algorithm onednn follows to calculate the exponent of a vector? The part of code is in jit_uni_eltwise_injector.cpp:  exp_compute_vector()

**Comment by dzarukin** [comment]
Hi @benjamim93, thanks for the question. Please consider using `eltwise` primitive with `alg_kind` set to `dnnl_eltwise_exp`. Here is the developer guide doc link: https://oneapi-src.github.io/oneDNN/dev_guide_eltwise.html. Thanks.

**Comment by benjamim93** [comment]
Hi @dzarukin Thank you for answering. I am curious about the algorithm onednn uses. Looks like it uses some approximation approach to do the calculation of exp. Is it possible to tell?

**Comment by mgouicem** [comment]
Hi @benjamim93, we use a classical algorithm that does a range reduction followed by a polynomial evaluation.
You can find a description [here](https://www.pseudorandom.com/implementing-exp#section-11).

**Comment by benjamim93** [comment]
Hi @mgouicem Thanks!
