### ISSUE TITLE
AVX-512 detected incorrectly on macOS, compile error on older macOS versions

### ISSUE THREAD

**Issue by atafra** [oneapi-src/oneDNN#859]
AVX-512 is detected incorrectly on macOS by the included version of Xbyak (typically it detects only AVX2 but it depends on whether any AVX-512 instructions were executed before, outside of oneDNN). Compilation also fails on some older macOS versions. I fixed these bugs upstream:

https://github.com/herumi/xbyak/commit/a0c49fa2e7b0f6ff2baf7b94363304b382151cbf
https://github.com/herumi/xbyak/commit/70777a69937b1ddd588e0c24091c0fd1781c0897

Upgrading Xbyak to the latest master will fix these issues.

**Comment by emfomenk** [comment]
Thanks for the heads up, @atafra! We try keeping Xbyak up-to-date, so will pick the improved version soon.
Is this more a FYI or you have a specific oneDNN version you want to have a fix?

**Comment by atafra** [comment]
We already fixed this in our fork for Open Image Denoise but it would great if this could be fixed in the next v1.x version of oneDNN (ideally v1.7). Thanks!

**Comment by emfomenk** [comment]
I see, thank you!
Unfortunately, v1.7 is right around the corner.
So, if there is no explicit need for that we probably will pull that in v1.8 release.

\<off-topic>we need to add GitHub milestone for v1.8 release\</off-topic>

**Comment by atafra** [comment]
OK, thanks. It's not critical to have the fix in v1.7 for **us** because we use our own fork but v1.7 will be still broken on macOS systems with AVX-512 (latest MacBook Pro 13 and Mac Pro).

**Comment by emfomenk** [comment]
Partially addressed in d58524e (future v1.8).
A promotion to v1.7 is WIP.

**Comment by emfomenk** [comment]
Promoted to v1.7 and master branches.
@atafra, thank you!
