### ISSUE TITLE
onednn support on mac silicon

### ISSUE THREAD

**Issue by uu-praveeng** [oneapi-src/oneDNN#862]
Hi,

 In the near future mac is shifting towards to mac silicon and mac PCs will not have any intel based processors.  How relevant is the dnnl library for mac silicon based PC's. Is this going to be deprecated for mac?

If not , what are plans to make it work on mac silicon based PCs ? Does dnnl works under rosetta 2?

Thanks,
Praveen.

**Comment by vpirogov** [comment]
Hi @uu-praveeng,

[According to Apple](https://www.apple.com/newsroom/2020/06/apple-announces-mac-transition-to-apple-silicon/) transition to Apple silicon will take at least 2 years. After transition is complete Apple will continue to support and release new versions of macOS for Intel-based Macs. 

We will continue to support optimizations for Intel processors on macOS until Apple removes this support from operating system completely. 

I would expect that oneDNN will work with Rosetta 2 based on [Apple's description](https://developer.apple.com/documentation/apple_silicon/about_the_rosetta_translation_environment) of the technology. This requires validation on actual silicon though.

oneDNN has native support for Aarch64 starting from [v1.5](https://github.com/oneapi-src/oneDNN/releases/tag/v1.5) with additional optimizations coming in v1.7 and v1.8. Adding @nSircombe for additional comments on Aarch64 optimizations roadmap.

**Comment by nSircombe** [comment]
Hi @uu-praveeng,

It's relatively early days for Aarch64 support in oneDNN - to date we've focussed on basic enablement and testing / CI, and, more recently, leveraging Arm Compute Library to provide Aarch64 optimised primitives. 

There are some more outline details about the roadmap for ML on Aarch64 servers (where servers in this context means, primarily, non-edge) here: https://connect.linaro.org/resources/lvc20/lvc20-216/
