### ISSUE TITLE
Question about the calculation of gemm convolution efficiency.

### ISSUE THREAD

**Issue by CaoZhongZ** [oneapi-src/oneDNN#866]
https://github.com/oneapi-src/oneDNN/blob/d58524e696bb960c051eb78da103252412ea7a80/src/cpu/gemm_convolution_utils.cpp#L1669

Is this a typo or deliberately doing so.

**Comment by vpirogov** [comment]
Summoning @tprimak and @ankalinin to comment.

**Comment by ankalinin** [comment]
Oh, that's a typo. Thank you for revealing! This will be fixed.

**Comment by CaoZhongZ** [comment]
👌I see, thank you.
