### ISSUE TITLE
Is there any way to specify the tile size for Winograd convolution?

### ISSUE THREAD

**Issue by Gxllii** [oneapi-src/oneDNN#868]
For Winograd convolution, oneDNN supports F(2x2,3x3) and F(4x4,3x3).
Is there any way to specify which tile size to be used?
Thank you.

**Comment by vpirogov** [comment]
Specific Winograd algorithm is chosen automatically based on the activation and weight tensors shape. There's no API that allows to choose specific Winograd algorithm in oneDNN.
