### ISSUE TITLE
Clang build failure on Aarch64

### ISSUE THREAD

**Issue by nSircombe** [oneapi-src/oneDNN#870]
# Summary
The master branch build is currently failing with Clang-9 on Aarch64. This appears to be due to recent changes in /code/oneDNN/src/cpu/cpu_shuffle_list.cpp, [this commit](https://github.com/oneapi-src/oneDNN/commit/e1c9a4ef992728779bb4bb5ec3bfbe6dc4da69b4#diff-5ca49a660c696f117969949450524e128b0a2c2ef9044983f789696102babba1)

```
/code/oneDNN/src/cpu/cpu_shuffle_list.cpp:33:22: error: unused variable 'bf16_size_bytes' [-Werror,-Wunused-const-variable]
static constexpr int bf16_size_bytes = sizeof(bfloat16_t);
                     ^
/code/oneDNN/src/cpu/cpu_shuffle_list.cpp:34:22: error: unused variable 'f32_size_bytes' [-Werror,-Wunused-const-variable]
static constexpr int f32_size_bytes = sizeof(float);
                     ^
2 errors generated.
```

The commit simply removes unnecessary templates from `cpu_shuffle_list.cpp`. However, on Aarch64, this means there is then nothing in `impl_list` using `bf16_size_bytes` and `f32_size_bytes`, since the only uses are guarded by `CPU_INSTANCE_X64`. The result is the unused variable warning, which leads to a failure with `-Werror` set.

A simple solution might just be to put the definitions of `bf16_size_bytes` and `f32_size_bytes` behind the `DNNL_X64_ONLY` macro? 
Something like:

```
diff --git a/src/cpu/cpu_shuffle_list.cpp b/src/cpu/cpu_shuffle_list.cpp
index bca8d8111..678adfbc1 100644
--- a/src/cpu/cpu_shuffle_list.cpp
+++ b/src/cpu/cpu_shuffle_list.cpp
@@ -30,8 +30,8 @@ namespace cpu {
 
 using pd_create_f = engine_t::primitive_desc_create_f;
 
-static constexpr int bf16_size_bytes = sizeof(bfloat16_t);
-static constexpr int f32_size_bytes = sizeof(float);
+DNNL_X64_ONLY(static constexpr int bf16_size_bytes = sizeof(bfloat16_t);)
+DNNL_X64_ONLY(static constexpr int f32_size_bytes = sizeof(float);)
 
 namespace {
 using namespace dnnl::impl::data_type;
```

# Version
oneDNN v1.7.0 (commit 3db1ff5e012817fe9e41f503f027009dc5e26a53)

# Environment
Marvell ThunderX2 (Aarch64) CentOS 8, clang-9

# Steps to reproduce
Any build with clang on Aarch64 should reproduce the issue. Building with -Werror will result in a failure, otherwise build will succeed with warnings.

# Observed behavior
Build (`cmake -DDNNL_BUILD_FOR_CI=ON .. && make -j`) generates the following error:
```
/code/oneDNN/src/cpu/cpu_shuffle_list.cpp:33:22: error: unused variable 'bf16_size_bytes' [-Werror,-Wunused-const-variable]
static constexpr int bf16_size_bytes = sizeof(bfloat16_t);
                     ^
/code/oneDNN/src/cpu/cpu_shuffle_list.cpp:34:22: error: unused variable 'f32_size_bytes' [-Werror,-Wunused-const-variable]
static constexpr int f32_size_bytes = sizeof(float);
                     ^
2 errors generated.
```

# Expected behavior
Successful, build culminating in:
```
...
[100%] Linking CXX executable benchdnn
[100%] Built target benchdnn
[100%] Linking CXX executable test_eltwise
[100%] Built target test_eltwise
```

**Comment by vpirogov** [comment]
Thank you for the report, @nSircombe. This issue is should be fixed by bffc76f7a6a287b78e031bc903a593fc74e04650.

**Comment by vpirogov** [comment]
Aarch64 CI passed on master.

**Comment by nSircombe** [comment]
Hi @vamironov,

Great stuff - just re-ran our clang-nightly pipeline, all green again now too.

Cheers.
