### ISSUE TITLE
Implementation choice for BWD_D deconvolution

### ISSUE THREAD

**Issue by alenik01** [oneapi-src/oneDNN#872]
Good afternoon, dear colleagues.

I have a question about primitive descriptors created within the following setup:
`./benchdnn --deconv --dir=BWD_D ic16ih5oc3oh5kh3ph1n"2d_conv:1st"`
Deconvolution with `backward_data` regime is created here, and it employs [gemm_convolution_fwd_t ](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/cpu_convolution_list.cpp#L105) like it is a usual forward convolution (this probably makes sense, if deconvolution brings transposition and `BWD_D` applies another transposition).

May you please point out, at what stage of the call stack this deconvolution pd starts to search in the list of forward implementations of [cpu_convolution_list.cpp](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/cpu_convolution_list.cpp#L91-L109)? I wish to tune launch checks for `acl_gemm_convolution_fwd_t` in such a setup.

Best regards,
Aleksandr Nikolaev

**Comment by igorsafo** [comment]
Hi @alenik01 ,
As you mentioned there is a deconvolution implementation which is based on convolution implementations. This deconvolution is called `ref_deconvolution_bwd_data_t` and is chosen if other implementations are not applicable. The same idea is used for other propagation kinds.

In `ref_deconvolution_bwd_data_t` there is a [method](https://github.com/oneapi-src/oneDNN/blob/master/src/cpu/ref_deconvolution.hpp#L300) called `init_convolution`, which does the following:
1. Creates a convolution descriptor based on deconvolution one;
2. Iterates through convolution implementations until an applicable implementation is found;

During execution deconvolution executes the following:
1. Convolution primitive
2. Bias kernel (if needed and not supported by convolution)

To launch `acl_gemm_convolution_fwd_t` you need to make sure that `ref_deconvolution_bwd_data_t` is chosen and `acl_gemm_convolution_fwd_t` implementation is chosen in `init_convolution`.

**Comment by alenik01** [comment]
Good morning, @igorsafo .

Many thanks for explaining, it is indeed in the [ref_deconvolution.hpp](https://github.com/oneapi-src/oneDNN/blob/27cb0e4b4a2fa6160d275d82774ed998cc455de4/src/cpu/ref_deconvolution.hpp#L49-L89).

Best wishes,
Aleksandr
