### ISSUE TITLE
Tests for DNNL_CPU_RUNTIME=THREADPOOL _DNNL_TEST_THREADPOOL_IMPL=STANDALONE freeze

### ISSUE THREAD

**Issue by yurivict** [oneapi-src/oneDNN#877]
When oneDNN is built with ```DNNL_CPU_RUNTIME=THREADPOOL _DNNL_TEST_THREADPOOL_IMPL=STANDALONE``` tests freeze:

```
Test project /usr/ports/math/onednn/work/.build
      Start  1: api-c
 1/71 Test  #1: api-c .............................................   Passed    0.03 sec
      Start  2: test_c_symbols-c
 2/71 Test  #2: test_c_symbols-c ..................................   Passed    0.01 sec
      Start  3: test_batch_normalization_f32
```

Version: 1.7
OS: FreeBSD 12.2
clang-10

**Comment by emfomenk** [comment]
Hi @yurivict,

I wasn't able to reproduce the issue locally (using Linux though).
Tried 1, 2, 4, 8, and 16 threads in the thread-pool. Compiler: clang10.

Could you please run the test manually (`DNNL_VERBOSE=2 ./tests/gtests/test_batch_normalization_f32`) and share:
1. on which test case it hangs,
2. what is the call stack for at least one of the threads (hopefully it hangs in debug build as well),
3. the verbose log as well.

Is the hang sporadic or persistent?

**Comment by vpirogov** [comment]
Closing as we don't have enough information to reproduce the issue. Feel free to reopen with additional data.
