### ISSUE TITLE
Which branch should I send pull requests for v2.x?

### ISSUE THREAD

**Issue by kawakami-k** [oneapi-src/oneDNN#884]
The JIT implementation of AArch64's reordering process has been incorporated into the master branch on October 23 (Thank you so much!). We'd like to send pull requests, these are planned to a few weeks later, for the other implementations for oneDNN v2.x. 
Which branch should I send pull requests, the master branch or the dev-v2 branch?

**Comment by vpirogov** [comment]
@kawakami-k,

Thank you for the contributions. Please continue submitting pull requests to master branch. Note, that after v1.8 code cutoff (Nov 18) we plan to merge changes from dev-v2 into master and stop adding new features to v1.x line.

**Comment by vpirogov** [comment]
We just promoted v2.0 features to `master` and stopped development on `dev-v2` Here's the list of current active branches and corresponding target releases: 
| Branch | New planned release | Purpose
| :- | :- | :-
| `master` | v2.1 | Default development branch for new features.
| `mnt-v1` | N/A | Potential v1.9 release if the need to deliver features and/or optimizations API compatible with v1.x arises.
| `rls-v1.8` | v1.8.1 | Bug fixes for v1.8 release.
