### ISSUE TITLE
More nuances of int8 computation

### ISSUE THREAD

**Issue by marsupialtail** [oneapi-src/oneDNN#891]
I read this page: https://oneapi-src.github.io/oneDNN/dev_guide_int8_computations.html but am still confused about the i32 accumulation that happens implicitly. Does this mean that when I create a primitive with s8 or u8 src and dst memories, i32 accumulation is automatically done and then the destination converted back to u8/s8? Do I need to specify an option to enable this behavior? 

Alternatively, if I want to do the accumulation in s8/u8, is this even possible?

**Comment by densamoilov** [comment]
Hi @marsupialtail, the flow is performed automatically, you don't have to specify an option to enable it, we described it in the article just to let people know what's going on inside.

oneDNN doesn't provide an API to specify accumulation type, the type is initialized automatically for each primitive that supports it.
On the other hand, what would be benefit of that? Typically, s8/u8 is not enough for accumulating results of multiplication s8/u8 data types, which may lead to overflow.

There is a [related issue](https://github.com/oneapi-src/oneDNN/issues/476) which was motivation for writing the article.

**Comment by alokbakshi** [comment]
Hi @marsupialtail 

Just wanted to add that using the identities below 

<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{align*}&space;(a&space;\mod&space;N)&space;&plus;&space;(b&space;\mod&space;N)&space;&\equiv&space;(a&space;&plus;&space;b)&space;\mod&space;N&space;\\&space;(a&space;\mod&space;N)&space;\cdot&space;(b&space;\mod&space;N)&space;&\equiv&space;(a&space;\cdot&space;b&space;)&space;\mod&space;N&space;\end{align*}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\begin{align*}&space;(a&space;\mod&space;N)&space;&plus;&space;(b&space;\mod&space;N)&space;&\equiv&space;(a&space;&plus;&space;b)&space;\mod&space;N&space;\\&space;(a&space;\mod&space;N)&space;\cdot&space;(b&space;\mod&space;N)&space;&\equiv&space;(a&space;\cdot&space;b&space;)&space;\mod&space;N&space;\end{align*}" title="\begin{align*} (a \mod N) + (b \mod N) &\equiv (a + b) \mod N \\ (a \mod N) \cdot (b \mod N) &\equiv (a \cdot b ) \mod N \end{align*}" /></a>

one can see that -- as long as the intermediate accumulator is wide enough to represent destination type -- the outcome of convolution operation will not depend upon the choice of accumulator. In particular, for pure convolution (i.e. without bias, and post--ops) following two operations are equivalent (similarly for `s8` destination type)

- accumulator type: `f32`    -----> destination type: `u8`
- accumulator type: `u8`     -----> destination type: `u8`
