### ISSUE TITLE
Packed GEMM

### ISSUE THREAD

**Issue by CosimoRulli** [oneapi-src/oneDNN#898]
Hello developers, I am interested in understanding how the packing works in the single-threaded version of sgemm (fp32). In particular, I would like to manually pack the B matrix, which I have in fragmented format.

**Comment by mgouicem** [comment]
Hi @CosimoRulli for computing sgemm we provide 2 public APIs:
- a primitive based API, named [Matmul](https://oneapi-src.github.io/oneDNN/dev_guide_matmul.html) 
- a function based API, named [dnnl_sgemm](https://github.com/oneapi-src/oneDNN/blob/7bd73fb5297425e3d38a80a49559f55fdbad2d8c/include/oneapi/dnnl/dnnl.h#L3576)

None of those support pre-packed matrices as of now. Matmul supports it API wise but not implementation-wise. dnnl_sgemm does not support it API-wise.

If you want to use the Matmul primitive, the reordering of the B matrix from fragmented buffers can be achieved with the concat primtive (it will concatenate all the fragments in plain layout into one dnnl_memory object with blocked/packed layout).

Sidenote: there is an internal pack sgemm API for the x64 backend, but it is neither public nor documented, and can change without notice, so we discourage users from relying on it.

**Comment by mgouicem** [comment]
I am closing this issue since it seems it is addressed. Feel free to reopen or open a new issue if you have more questions.
