### ISSUE TITLE
how to implement the deconv operation?

### ISSUE THREAD

**Issue by yuqj1991** [oneapi-src/oneDNN#901]
hi, could you please provide the deconv example?

tnanks!

**Comment by densamoilov** [comment]
Hi @yuqj1991, we already had the similar questions, please take a look into #143, #228, #193 and let us know if they helped you.

If you are looking for an example that demonstrates how to use oneDNN API to create and run deconvolution primitive then you can use [example of convolution](https://github.com/oneapi-src/oneDNN/blob/master/examples/primitives/convolution.cpp) and the [documentation](https://oneapi-src.github.io/oneDNN/v2/group__dnnl__api__deconvolution.html) to turn the convolution example into deconvolution one.
