### ISSUE TITLE
benchdnn subtest '5:SKIPPED (SKIP_IMPL_HIT) __REPRO: --conv --dir=BWD_WB -- cfg=f32_full' hanging

### ISSUE THREAD

**Issue by jainsang** [oneapi-src/oneDNN#912]
# Summary
We are using onednn with Yocto Project thru a recipe in meta-intel layer.
Among other tests we are running "./benchdnn --conv --batch=inputs/conv/test_conv_3d"
5th subtest of this test is hanging on intel NUC7-KBL.

# Version
git hash = "570ab9c2ea0915b048279438aebb063b8769149c"
version = v1.6 

# Environment
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
Stepping:                        9
CPU MHz:                         3974.583
CPU max MHz:                     4000.0000
CPU min MHz:                     400.0000
BogoMIPS:                        6999.82
Virtualization:                  VT-x
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        4 MiB
Vulnerability Itlb multihit:     Processor vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RS
                                 B filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts
                                 acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art ar
                                 ch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulq
                                 dq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_
                                 2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnow
                                 prefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi fle
                                 xpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx r
                                 dseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pl
                                 n pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

# Steps to reproduce
Run following test on target device :
"./benchdnn --conv --batch=inputs/conv/test_conv_3d" .

# Observed behavior
Test run until 5th subtest and then hangs indefinitely,

0:PASSED __REPRO: --conv  --cfg=f32_full
 ic16id10ih13iw50oc16od10oh13ow50kd3kh3kw3pd1ph1pw1n"3d_conv_pad:1"
 1:PASSED __REPRO: --conv --dir=BWD_D --cfg=f32_full
 ic16id10ih13iw50oc16od10oh13ow50kd3kh3kw3pd1ph1pw1n"3d_conv_pad:1"
2:SKIPPED (SKIP_IMPL_HIT) __REPRO: --conv --dir=BWD_WB --  cfg=f32_full
ic16id10ih13iw50oc16od10oh13ow50kd3kh3kw3pd1ph1pw1n"3d_conv_pad:1"
3:PASSED __REPRO: --conv --cfg=f32_full
 ic64id15ih10iw20oc64od15oh10ow20kd3kh3kw3pd1ph1pw1n"3d_conv_pad:2"
4:PASSED __REPRO: --conv --dir=BWD_D --cfg=f32_full
 ic64id15ih10iw20oc64od15oh10ow20kd3kh3kw3pd1ph1pw1n"3d_conv_pad:2"
5:SKIPPED (SKIP_IMPL_HIT) __REPRO: --conv --dir=BWD_WB --  cfg=f32_full

# Expected behavior

All subtests should execute successfully (pass or fail or skip)
Sample output from other device:
tests:13314 passed:7996 skipped:5290 mistrusted:28 unimplemented:0 failed:0 listed:0

**Comment by mgouicem** [comment]
Hi @jainsang , this issue should be fixed by now, since the 1.6.5 patch release (a84360ed7e6db37b0147b874b1cdd9ec765e4682).
Could you please give it a try?

**Comment by mgouicem** [comment]
I am closing this issue given the lack of activity. Feel free to reopen or open a new issue if you have more questions.
