### ISSUE TITLE
could not execute a primitive

### ISSUE THREAD

**Issue by yuqj1991** [oneapi-src/oneDNN#914]
hi, guys
i am implementing a convolution op based on dnnl, but when i run a simple exec, it gave the log as the title said:
could not execute a primitive. could you give some reasons about  this log

thanks

**Comment by sbogusev** [comment]
Hi @yuqj1991 . Could you please execute your code with `DNNL_VERBOSE=2` and provide the detailed log here?

**Comment by yuqj1991** [comment]
> Hi @yuqj1991 . Could you please execute your code with `DNNL_VERBOSE=2` and provide the detailed log here?

HI @sbogusev .because i used the onednn releases-version(1.7), so where i should do with the DNNL_VERBOSE=2? or maybe in the step of cmake .., or in the step of make. and even in the code.

thanks

**Comment by yuqj1991** [comment]
> Hi @yuqj1991 . Could you please execute your code with `DNNL_VERBOSE=2` and provide the detailed log 

Hi, i have export the DNNL_VERBOSE=2, but got nothing about the error (could not execute a primitive)

**Comment by sbogusev** [comment]
Hi @yuqj1991 . Using the DNNL_VERBOSE=2 environment variable enables oneDNN to produce verbose output for various execution and creation steps. It will not contain anything about the error, but it may help understand what the error is caused by.

Do you get no output at all when you use `export DNNL_VERBOSE=2`?

**Comment by sbogusev** [comment]
Just to let you know that the `could not execute a primitive` error may be caused by out-of-memory situations, or providing incorrect memory objects for execution, or maybe something else.

**Comment by yuqj1991** [comment]
@sbogusev 
thanks, i got it. and i find the bug of my code.
thanks very much

**Comment by sbogusev** [comment]
@yuqj1991 Great to hear it works! Ping us if you have any other questions.

**Comment by ShubhamZoop** [comment]
Hey @yuqj1991 can I know how you solved the error mentioned above?
