### ISSUE TITLE
tensorflow tflite padding_some/ padding_valid

### ISSUE THREAD

**Issue by yuqj1991** [oneapi-src/oneDNN#916]
hello, guys
i want to implement the convolution op with onednn, but the weights come from the tflite model. in the operator of convolution from tflite model, there are to methods of padding ,padding_same, padding_valid. as you know, when it was the padding_valid, i can set the phl, phr, pwl,pwr was 0. so what should i do to configure when the padding is padding_same.

**Comment by kwiersch** [comment]
hi @yuqj1991 ,

in oneDNN, convolution "shape" must satisfy [this equation](https://oneapi-src.github.io/oneDNN/dev_guide_convolution.html):

> OW = floor((IW - KW + PW_L + PW_R) / SW) + 1

while in TensorFlow the output dimension for "SAME" padding is determined by [this equation](https://www.tensorflow.org/api_docs/python/tf/nn/convolution):

> OW = ceil(IW / SW)

let's take the easy case where SW = 1. then from oneDNN definition we have

> OW = IW - KW + PW_L + PW_R + 1

while from TensorFlow definition we have

> OW = IW

and thus

> PW_L + PW_R = KW - 1

now all that is left is to determine PW_L and PW_R. let's assume we have KW odd, as that is the typical case. then it's quite natural to choose

> PW_L = PW_R = (KW - 1) / 2

**Comment by kwiersch** [comment]
also, you can take a look at the tensorflow source code. [GetOutputAndPadSizeInMklOrder()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/mkl/mkl_conv_ops.h#L325) appears to calculate the output and padding size required for oneDNN convolution primitive by calling [GetWindowedOutputSizeVerboseV2()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/kernel_shape_util.cc#L20), which in turn calculates the "SAME" padding like so:

> OW = ceil(IW / SW)

> PW = PW_L + PW_R = (OW - 1) * SW + KW - IW

> PW_L = PW / 2

> PW_R = PW - PW_L

**Comment by yuqj1991** [comment]
@kwiersch  thanks for your detailed explanation. i will take a look at the tensorflow source code which you mentioned
