### ISSUE TITLE
test_gemm_s8s8s32 failure on AzureDevOps OSX CI

### ISSUE THREAD

**Issue by kawakami-k** [oneapi-src/oneDNN#921]
# Summary

Azure DevOps CI of the current master branch are passed as shown in
https://dev.azure.com/mkldnn/dnnl/_build/results?buildId=311&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=48834338-8603-52b5-7d02-e967904bd6ed
, but I can't pass the CI for the same commit in my fork as shown in
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=12&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=7fa14b02-7776-5964-c2fd-5874e324208b

The test pattern below failed.
```
 ./test_gemm_s8s8s32 --gtest_filter="TestGEMM_heavy_s8s8s32_CPU/gemm_test.TestGEMM/4
```

# Version

`7bd73fb5297425e3d38a80a49559f55fdbad2d8c` of Master branch

# Environment
Azure DevOps OSX_10_14

# Steps to reproduce
- Fork https://github.com/oneapi-src/oneDNN into my own GitHub account 
- Enable Azure DevOps CI of my fork and start Azure DevOps CI

# Observed behavior

One of `test_gemm_s8s8s32` failed.
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=99&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=7fa14b02-7776-5964-c2fd-5874e324208b&l=878

I added some debug dump code 
https://github.com/kawakami-k/oneDNN/commits/TestGEMM_heavy_s8s8s32_CPU/gemm_test.TestGEMM/4
, then I ran Azure DevOps CI. The below is the log.
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=100&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=d42aab22-229f-5bc6-1d14-17661990413c

As for (row=0, col=0) element, 
the difference between the got value and the reference value is 11, which is beyond the allowable difference of 9.
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=100&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=d42aab22-229f-5bc6-1d14-17661990413c&l=54197

The got value is compensated by `add_results()` in `gemm_driver.cpp`,
https://github.com/kawakami-k/oneDNN/blob/TestGEMM_heavy_s8s8s32_CPU/gemm_test.TestGEMM/4/src/cpu/gemm/s8x8s32/simple_gemm_s8s8s32.cpp#L141
and the compensation values are calculated in `compensation_compute()` in `simple_gemm_s8s8s32.cpp`.

In `compensation_compute()`, oneDNN on Azure DevOps OSX_10_14 received 87381 as `L2_cache_size`.
https://github.com/kawakami-k/oneDNN/blob/TestGEMM_heavy_s8s8s32_CPU/gemm_test.TestGEMM/4/src/cpu/gemm/s8x8s32/simple_gemm_s8s8s32.cpp#L62
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=100&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=d42aab22-229f-5bc6-1d14-17661990413c&l=29
`87381` seems to be reasonable, because `machdep.cpu.cache.size` is 256 and `machdep.cpu.core_count` is 3 (37381 * 3 = 256K).
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=100&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=067cd3d2-91f1-5961-4dce-c25f5665f287&l=63
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=100&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=067cd3d2-91f1-5961-4dce-c25f5665f287&l=70

`87381` results in `blocking_factor` of 30, 

From the following code and log, is 256 used as `blocking _factor`?
https://github.com/kawakami-k/oneDNN/blob/TestGEMM_heavy_s8s8s32_CPU/gemm_test.TestGEMM/4/src/cpu/x64/gemm/gemm_driver.cpp#L622
https://github.com/kawakami-k/oneDNN/blob/TestGEMM_heavy_s8s8s32_CPU/gemm_test.TestGEMM/4/src/cpu/x64/gemm/gemm_driver.cpp#L800
https://dev.azure.com/kawakamik/oneDNN/_build/results?buildId=100&view=logs&j=b12a3ddb-6e56-5025-2dba-bfa0589f86b9&t=d42aab22-229f-5bc6-1d14-17661990413c&l=41

If 256 is used, there is `blocking_factor` mismatch between compensation and matrix calculation.

**Comment by vpirogov** [comment]
@kawakami-k, thank you for the report. The same test fails in the latest run on master as well.

**Comment by mgouicem** [comment]
This issue is now fixed in master. Thanks.
