### ISSUE TITLE
"test_conv_all" with benchdnn does not work correctly

### ISSUE THREAD

**Issue by m-ymzk** [oneapi-src/oneDNN#923]
The "inputs/conv/test_conv_all" uses these files.
 - test_conv_f32
 - test_conv_f32_nxc
 - test_conv_gemm_f32
 - test_conv_gemm_f32_nxc

[In the commit, ](https://github.com/oneapi-src/oneDNN/commit/fd70df1202ecc4ef1499db3e442c67a37c83e768)
```
commit fd70df1202ecc4ef1499db3e442c67a37c83e768
    benchdnn: inputs: conv: include bf16 testing in nightly scope
```
these files were renamed with "_dt".

# Version
- v1.8-rc
- master, dev-v2 branches

# Steps to reproduce
```command: "./benchdnn --conv --batch=inputs/conv/test_conv_all```
returns
```cannot open file test_conv_f32```

**Comment by kwiersch** [comment]
Hi @m-ymzk, thanks for pointing this out! Indeed the commit fd70df12 did not properly update `test_conv_all` (this test file is a special case that is kept mostly for developer convenience, meaning it is not run during CI). I will prepare a patch internally to fix it, sorry for the inconvenience!

PS The dev-v2 branch is now obsolete as v2.x development has been moved to the master branch.

**Comment by m-ymzk** [comment]
Thank you for your reply to correct it.

**Comment by kwiersch** [comment]
You are very welcome! Though I should warn you that there are over 300k tests in that all-inclusive test suite:
```bash
$ ./benchdnn --mode=L --conv --batch=test_conv_all | tail -n1
tests:305764 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:305764
```

**Comment by dzarukin** [comment]
> You are very welcome! Though I should warn you that there are over 300k tests in that all-inclusive test suite:
> 
> ```shell
> $ ./benchdnn --mode=L --conv --batch=test_conv_all | tail -n1
> tests:305764 passed:0 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:305764
> ```

Just in case, in hours it takes infinity and beyond!
