### ISSUE TITLE
Blocked Format with Duplicated Dimensions?

### ISSUE THREAD

**Issue by alexandrelimassantana** [oneapi-src/oneDNN#927]
Hello,

I found the format **OIhw_4i16o4i** while reading the [dnnl_types header](https://github.com/oneapi-src/oneDNN/blob/master/include/dnnl_types.h) (line 1097).

I am struggling to visualize how data is organized in memory for formats where a dimension is blocked more than once.
I would appreciate a lot if someone could verify if my reasoning over this shape makes sense.

I am trying to think about the format with regards to the indices (o,i,h,w) of an element in a plain-memory format.
As such the element with indices (0,0,0,1) would be 2nd element in the oihw plain-memory format.
For the **OIhw_4i16o** format, the element (0,0,0,1) is the 64th element in memory.
I envision that the **OIhw_4i16o4i** and **OIhw_4i16o** formats have the same 64 initial elements.
I also imagine that the element (0,0,0,1) is located at the 256th position in the **OIhw_4i16o4i** format.
If my logic makes sense, my question is: are the indices 0-255 occupied by 4 **4i16o** blocks shifted in the i-axis?

**Comment by dzarukin** [comment]
Hi @alexandrelimassantana, thanks for the question.
I see pretty same way you do. The only visualization I may suggest is this:
1) There's a cell of 4i elements.
2) There's a macro-cell of 4*4i element in a row and 4 such row creating a square 4x4 with 4i cells.
3) There's a 3D stack of 4 such squares, which forms a single 4i16o4i block for a single spatial point.
4) Now imaging such "cube" as a single point, create a plain of h times w dimensions. This will respond to a single block of I.
5) The final step is to imaging such spatial plains as a stack of O (o/16) times I (i/16).
That's the best I may propose how to visualize it.

Just in case, such complex blocking formats are only needed to obtain performance from VNNI instruction on int8 data type, in fp32 those are not used.

Hope it helps. Thank you.

**Comment by alexandrelimassantana** [comment]
Thanks a lot for the explanation!
The information about the use case for this format is also much appreciated
