### ISSUE TITLE
No performance improvement with convolution_auto

### ISSUE THREAD

**Issue by pranathibl** [oneapi-src/oneDNN#929]
Hi,

I have used convolution_auto for convolution_algorithm instead of convolution_direct for VGG16 network. I do not see any performance difference between the two. Whereas, If convolution_winograd is used , There is a performance improvement.

convolution_auto is not picking winograd, it is picking direct convolution instead. I am using v1.4 on AVX512 machine.

below is the output when MKLDNN_VERBOSE is set to 1 with convolution_auto.

dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:abcd:f0 wei_f32::blocked:Acdb16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic3oc64_ih224oh224kh3sh1dh0ph1_iw224ow224kw3sw1dw0pw1,14.905
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic64oc64_ih224oh224kh3sh1dh0ph1_iw224ow224kw3sw1dw0pw1,20.436
dnnl_verbose,exec,cpu,pooling,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:aBcd16b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic64_ih224oh112kh2sh2ph0_iw224ow112kw2sw2pw0,0.48291
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic64oc128_ih112oh112kh3sh1dh0ph1_iw112ow112kw3sw1dw0pw1,1.9729
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic128oc128_ih112oh112kh3sh1dh0ph1_iw112ow112kw3sw1dw0pw1,5.09399
dnnl_verbose,exec,cpu,pooling,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:aBcd16b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic128_ih112oh56kh2sh2ph0_iw112ow56kw2sw2pw0,6.31396
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic128oc256_ih56oh56kh3sh1dh0ph1_iw56ow56kw3sw1dw0pw1,2.17505
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic256oc256_ih56oh56kh3sh1dh0ph1_iw56ow56kw3sw1dw0pw1,16.407
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic256oc256_ih56oh56kh3sh1dh0ph1_iw56ow56kw3sw1dw0pw1,8.72607
dnnl_verbose,exec,cpu,pooling,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:aBcd16b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic256_ih56oh28kh2sh2ph0_iw56ow28kw2sw2pw0,0.0771484
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic256oc512_ih28oh28kh3sh1dh0ph1_iw28ow28kw3sw1dw0pw1,2.09399
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic512oc512_ih28oh28kh3sh1dh0ph1_iw28ow28kw3sw1dw0pw1,3.79712
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic512oc512_ih28oh28kh3sh1dh0ph1_iw28ow28kw3sw1dw0pw1,3.68701
dnnl_verbose,exec,cpu,pooling,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 dst_f32::blocked:aBcd16b:f0 ws_undef::undef::f0,,alg:pooling_max,mb1ic512_ih28oh14kh2sh2ph0_iw28ow14kw2sw2pw0,0.0180664
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic512oc512_ih14oh14kh3sh1dh0ph1_iw14ow14kw3sw1dw0pw1,0.879883
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic512oc512_ih14oh14kh3sh1dh0ph1_iw14ow14kw3sw1dw0pw1,4.83887
dnnl_verbose,exec,cpu,convolution,jit:avx512_common,forward_inference,src_f32::blocked:aBcd16b:f0 wei_f32::blocked:ABcd16b16a:f0 bia_f32::blocked:a:f0 dst_f32::blocked:aBcd16b:f0,post_ops:'eltwise_relu:0:1;';,alg:convolution_direct,mb1_ic512oc512_ih14oh14kh3sh1dh0ph1_iw14ow14kw3sw1dw0pw1,0.966064

Thanks
Pranathi

**Comment by mgouicem** [comment]
Hi @pranathibl and thank you for the report!
For `convolution__auto`, we rely on heuristics to pick between `direct` and `winograd` algorithm. It is possible that the dispatching is currently suboptimal. @kwiersch @alokbakshi, could you take a look at this issue?

**Comment by kwiersch** [comment]
Hi @pranathibl, the main goal for `auto` algorithm is to provide performance benefit without causing any degradations. For small minibatch sizes, some topologies (such as googlenet) are slower with winograd than direct convolution. For this reason, the current heuristic chooses direct convolution is such cases.

If you are interested, relevant bits of heuristic are scattered here and there in the codebase:

- choosing 2x3 wino or direct:
https://github.com/oneapi-src/oneDNN/blob/rls-v1.4/src/cpu/jit_avx512_core_f32_wino_conv_2x3.cpp#L553
- choosing 2x3 wino or 4x3 wino:
https://github.com/oneapi-src/oneDNN/blob/rls-v1.4/src/cpu/jit_avx512_core_f32_wino_conv_2x3.cpp#L650
- choosing 4x3 wino or direct:
https://github.com/oneapi-src/oneDNN/blob/rls-v1.4/src/cpu/jit_avx512_core_f32_wino_conv_4x3_kernel.cpp#L62

**Comment by vpirogov** [comment]
Closing the issue as the question is addressed. Feel free to reopen or submit a new one with additional information.
