### ISSUE TITLE
Issues in using dnnl libraries on different cross platforms

### ISSUE THREAD

**Issue by nhkrishna** [oneapi-src/oneDNN#942]
Hi,

I have built dnnl libraries on one `Linux platform1` which has g++ version 8.3.0. 
I'm using these same shared libraries on different `Linux platform2` which has g++ version 9.3.0. This resulted in below linker errors:
`/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: libdnnl.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
`

If I built dnnl libraries on `Linux Platform2` then it was working without any issues. It seems `std::string` implementation was changing for C++ version to version. Is there anyway to built dnnl libraries that are independent of cross platforms. Like specifying C++ version while building the dnnl libraries so that same version can be used on different cross platforms.

Regards,
Hari

**Comment by WilliamTambellini** [comment]
perhaps try 
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by mgouicem** [comment]
Hi @nhkrishna , as pointed out by William, this looks like incompatible version of libstdc++ on both systems.
Did you manage to solve your issue?

**Comment by mgouicem** [comment]
Closing this issue since it seems resolved. If not, feel free to reopen it. Thanks!
