### ISSUE TITLE
benchdnn ip doc references file that doesn't exist `inputs/ip/ip_all`

### ISSUE THREAD

**Issue by sfraczek** [oneapi-src/oneDNN#945]
# Summary
File referenced in doc `ip_all` probably changed name.

# URLs
https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/doc/driver_ip.md
in Examples first example.

# Additional details
./benchdnn --ip --batch=inputs/ip/**ip_all**.

**Comment by sbogusev** [comment]
Thanks for noticing @sfraczek , will fix this shortly.

**Comment by mgouicem** [comment]
This is now fixed in master (commit fe837a367700455114c51703154fcd1b0ecb21c9). 
Thank you for the report!
