### ISSUE TITLE
No binaries for v1.8.1

### ISSUE THREAD

**Issue by nietras** [oneapi-src/oneDNN#946]
Why does the 1.8.1 release not have any binaries for downloading?

**Comment by vpirogov** [comment]
Hi @nietras,

Most users build oneDNN from source, so we do not publish binaries for patch releses. If you find these useful though I would be happy to get these out for v1.8.1.

**Comment by vpirogov** [comment]
@nietras, oneDNN distribution on [conda-forge](https://github.com/conda-forge/onednn-feedstock) recently became available, which builds for every patch release. Hope this helps.
