### ISSUE TITLE
[win32][openmp][static link] cannot find libiomp5mt.lib in v0.20-rc release assets

### ISSUE THREAD

**Issue by zhaoyang-star** [oneapi-src/oneDNN#962]
# Summary
v0.20-rc requires Dynamic Link openmp lib(`libiomp5md.lib, libiomp5md.dll`). Project [Paddle-Lite](https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/cmake/external/mklml.cmake#L37) will build a static library based on MKLML. The build files are as follows:
```
D:\Paddle-Lite>dir build.lite.x86\inference_lite_lib\cxx\lib
2020/10/15  14:33        82,861,956 libpaddle_api_light_bundled.lib
D:\Paddle-Lite>dir build.lite.x86\inference_lite_lib\third_party\mklml\lib
2020/10/15  14:33         1,677,560 libiomp5md.dll
2020/10/15  14:33           231,558 libiomp5md.lib
```

# Problem statement
I try to let Paddle-Lite build a static library using Static Link openmp(`libiomp5mt.lib`) or not using openmp library.
But I found that there is no file called `libiomp5mt.lib` in v0.20-rc. 
The latest oneAPI and Intel Compile Toolkit don't have this file either.  How to get this static library file or how to using MKLML in a thread-sequential way?

**Comment by vpirogov** [comment]
Hi @zhaoyang-star,

You can find static OpenMP runtime as part of [Intel C++ Compiler](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/dpc-compiler.html) distribution or [Intel oneMKL](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html).

Linking to static OpenMP runtime is generally not recommended as it may cause problems when linking to other applications.  Another consideration related to OpenMP runtime is that you might want to stick to the runtime that comes with your compiler. oneDNN is compatible with OpenMP runtime from GCC or Clang.

**Comment by zhaoyang-star** [comment]
Hi @vpirogov ,

I tried install the latest Intel C++ Compiler or Inte oneMKL. But `libiomp5mt.lib` is NOT in the installed directory( libiomp5md.lib and libiomp5md.dll can be found). So how to get `libiomp5mt.lib`?

I know static linking to OpenMP is not recommended. But I have no choice because the project need this way.

**Comment by vpirogov** [comment]
Sorry for misleading you, I missed the fact that the question is Windows-specific. On Windows static linking to Intel OpenMP runtime is not supported and only dynamic OpenMP runtime is provided with Intel MKL or Intel C++ Compiler.

It looks like the only way to avoid dependency on dynamic OpenMP runtime on Windows is building oneDNN without threading and without `mklml.so`. Here're the options for v0.20:
> cmake .. -DMKLDNN_THREADING=SEQ -DMKLDNN_USE_MKL=NONE
