### ISSUE TITLE
Does benchdnn support several post-ops?

### ISSUE THREAD

**Issue by alenik01** [oneapi-src/oneDNN#971]
Good morning.

When I am running `benchdnn` in oneDNN v1.8 release with the following settings:
`./tests/benchdnn/benchdnn --engine=cpu --conv --cfg=f32 --attr-post-ops="'sum;relu'" ic64ih56oc256oh56kh1ph0`

it for some reason fails (gemm:ref is called as convolution implementation):
> [   0][DST][0,0,0,0,0,0] fp:          62 fp0:          62 dt:           0 diff:      62 rdiff:       1
[   2][DST][0,0,0,0,0,2] fp:         281 fp0:         281 dt:           0 diff:     281 rdiff:       1
[   7][DST][0,0,0,0,0,7] fp:         805 fp0:         805 dt:           0 diff:     805 rdiff:       1
[   8][DST][0,0,0,0,0,8] fp:          -0 fp0:          -0 dt:         994 diff:     994 rdiff:     994
[   9][DST][0,0,0,0,0,9] fp:          -0 fp0:          -0 dt:         612 diff:     612 rdiff:     612
[  10][DST][0,0,0,0,0,10] fp:         342 fp0:         342 dt:           0 diff:     342 rdiff:       1
[  11][DST][0,0,0,0,0,11] fp:        1339 fp0:        1339 dt:           0 diff:    1339 rdiff:       1
[  14][DST][0,0,0,0,0,14] fp:          68 fp0:          68 dt:           0 diff:      68 rdiff:       1
[  15][DST][0,0,0,0,0,15] fp:         890 fp0:         890 dt:           0 diff:     890 rdiff:       1
@@@ [DST] final: diff: err:1179791, l0(``4603``) l1:(7.27466e+08,7.31901e+08,9.84484e+08,``1.35331``) l2:(980119,1.05865e+06,1.14522e+06,``1.16845``) l8:(4242,4622,4603,``1.0851``)
@@@ error [int conv::doit(const conv::prb_t*, res_t*):829]: 'compare_dst(prb, dst, dst_fp, res, true)' -> 1

With single `--attr-post-ops` everything works fine. May you please comment, are several post-ops supported for the `--conv` driver? Or the behaviour above should be considered as a bug?

Best regards,
Aleksandr

**Comment by mgouicem** [comment]
Hi @alenik01, Yes benchdnn supports multiple postops. The above failure looks like a bug.
Could you share the verbose output and how you built the library to rootcause it?

**Comment by igorsafo** [comment]
Hi @alenik01 ,
I tried to reproduce this issues, but this test passes on my side (Intel Broadwell server CPU (with AVX2 support)).
I used -DDNNL_TARGET_ARCH=ARCH_GENERIC to disable all JIT code and ran this test:
```
DNNL_VERBOSE=1 ./build/tests/benchdnn/benchdnn --engine=cpu --conv --cfg=f32 --attr-post-ops="'sum;relu'" ic64ih56oc256oh56kh1ph0
dnnl_verbose,info,oneDNN v1.8.0 (commit 2c8d20640d5068e2d85e378b266644fe86220e84)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:Generic
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x64x56x56,0.213867
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,256x64x1x1,0.0390625
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x256x56x56,0.391113
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:a:f0 dst_f32::blocked:a:f0,,,256,0.0310059
dnnl_verbose,exec,cpu,convolution,gemm:ref,forward_training,src_f32::blocked:abcd:f0 wei_f32::blocked:abcd:f0 bia_f32::blocked:a:f0 dst_f32::blocked:abcd:f0,post_ops:'sum;eltwise_relu;';,alg:convolution_direct,mb2_ic64oc256_ih56oh56kh1sh1dh0ph0_iw56ow56kw1sw1dw0pw0,13.312
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x256x56x56,0.658936
0:PASSED __REPRO: --conv --attr-post-ops="'sum;relu'" ic64ih56oc256oh56kh1ph0
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
```

Could you please provide more details about your environment?

**Comment by alenik01** [comment]
Good afternoon, @mgouicem @igorsafo .

Thank you for clarification. I am on AArch64 Ubuntu 18, I have made a clean build, tried both GCC 9.3.0 and 10.2.0 with and without `-DDNNL_AARCH64_USE_ACL=ON -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_EXTENSIONS=OFF` and in all the cases it works fine now (see below). Sorry for disturbance.

>DNNL_VERBOSE=2 ./tests/benchdnn/benchdnn --engine=cpu --conv --cfg=f32 --attr-post-ops="'sum;relu'" ic64ih56oc256oh56kh1ph0
dnnl_verbose,info,oneDNN v1.8.0 (commit 2c8d20640d5068e2d85e378b266644fe86220e84)
dnnl_verbose,info,cpu,runtime:OpenMP
dnnl_verbose,info,cpu,isa:AArch64 (with Advadnced SIMD & floating-point)
dnnl_verbose,info,gpu,runtime:none
dnnl_verbose,create:cache_miss,cpu,convolution,gemm:ref,forward_training,src_f32::blocked:abcd:f0 wei_f32::blocked:abcd:f0 bia_f32::blocked:a:f0 dst_f32::blocked:abcd:f0,post_ops:'sum;eltwise_relu;';,alg:convolution_direct,mb2_ic64oc256_ih56oh56kh1sh1dh0ph0_iw56ow56kw1sw1dw0pw0,0.0429688
dnnl_verbose,create:cache_hit,cpu,convolution,gemm:ref,forward_training,src_f32::blocked:abcd:f0 wei_f32::blocked:abcd:f0 bia_f32::blocked:a:f0 dst_f32::blocked:abcd:f0,post_ops:'sum;eltwise_relu;';,alg:convolution_direct,mb2_ic64oc256_ih56oh56kh1sh1dh0ph0_iw56ow56kw1sw1dw0pw0,0.0371094
dnnl_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x64x56x56,0.0239258
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x64x56x56,2.02393
dnnl_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,256x64x1x1,0.0100098
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,256x64x1x1,2.2561
dnnl_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x256x56x56,0.00805664
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x256x56x56,1.6709
dnnl_verbose,create:cache_miss,cpu,reorder,simple:any,undef,src_f32::blocked:a:f0 dst_f32::blocked:a:f0,,,256,0.0219727
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:a:f0 dst_f32::blocked:a:f0,,,256,1.44507
dnnl_verbose,exec,cpu,convolution,gemm:ref,forward_training,src_f32::blocked:abcd:f0 wei_f32::blocked:abcd:f0 bia_f32::blocked:a:f0 dst_f32::blocked:abcd:f0,post_ops:'sum;eltwise_relu;';,alg:convolution_direct,mb2_ic64oc256_ih56oh56kh1sh1dh0ph0_iw56ow56kw1sw1dw0pw0,9.61084
dnnl_verbose,create:cache_hit,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x256x56x56,0.0151367
dnnl_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:abcd:f0 dst_f32::blocked:abcd:f0,,,2x256x56x56,2.427
0:PASSED __REPRO: --conv --attr-post-ops="'sum;relu'" ic64ih56oc256oh56kh1ph0
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
