### ISSUE TITLE
performance comparison for refcode vs optimised code

### ISSUE THREAD

**Issue by uu-praveeng** [oneapi-src/oneDNN#972]
Hi,

Is there a way to build the oneDNN library on Intel platforms disabling the  optimization kernels. So that library only includes ref c implementations of all the layers.

We want to do performance analysis, how much we have gained by enabling optimizations wrt ref C implementation of Layers code.

Thanks,
Praveen.

**Comment by nSircombe** [comment]
Hi @uu-praveeng,

As it happens, there is! @diaena was trying to to the same thing just recently - https://github.com/oneapi-src/oneDNN/issues/957

I think you need to set `DNNL_TARGET_ARCH=ARCH_GENERIC`.

**Comment by sergiomatiz1986** [comment]
Hi @nSircombe,

I was wondering if DNNL_TARGET_ARCH=ARCH_GENERIC would also disable BLAS. In my application, I would like to benchmark the performance of MKL-DNN without the use of SIMD (but without deactivating BLAS/GEMM for instance)

**Comment by nSircombe** [comment]
As far as I'm aware, if you've chosen to build and link with an external BLAS lib, this will still be the case if you choose ARCH_GENERIC. But you might want to double-check with an `ldd` of the final `.so`?
