### ISSUE TITLE
"test_conv_regression" fails

### ISSUE THREAD

**Issue by m-ymzk** [oneapi-src/oneDNN#974]
# Summary
If more than one post operations is specified, a run-time error occurs.

# Version
master branch: 822a802

# Environment
- intel/xeon
- fx700/A64FX

# Steps to reproduce
```
NG: benchdnn --conv --batch=test_conv_regression
NG: benchdnn --conv --skip-impl="ref_fused_convolution" --cfg=f32 --attr-post-ops="'relu;dw_k3s1p1;sqrt'" ic256oc256_ih60oh20kh3ph0sh3_iw50ow25kw3pw0sw2n
OK: benchdnn --conv --skip-impl="ref_fused_convolution" --cfg=f32 --attr-post-ops="'relu'" ic256oc256_ih60oh20kh3ph0sh3_iw50ow25kw3pw0sw2n
```

# Observed behavior
```
% ./tests/benchdnn/benchdnn --conv --skip-impl="ref_fused_convolution" --cfg=f32 --attr-post-ops="'relu;dw_k3s1p1;sqrt'" ic256oc256_ih60oh20kh3ph0sh3_iw50ow25kw3pw0sw2n
error [int execute_reorder(const dnn_mem_t&, dnn_mem_t&, const_dnnl_primitive_attr_t):82]: 'dnnl_reorder_primitive_desc_create(&r_pd, &src.md_, src.engine(), &dst.md_, dst.engine(), attr)' -> invalid_arguments(2)
zsh: exit 2     ./tests/benchdnn/benchdnn --conv --skip-impl="ref_fused_convolution" --cfg=f3
```

**Comment by igorsafo** [comment]
Hi @m-ymzk , thanks for your report. Indeed this is an issue in the library, I reproduced behavior and found one of root causes (gemm convolution shouldn't dispatch here, there is an issue in method `post_ops_ok()` . Also please take a look into restrictions which apply to dw_conv post operation: https://oneapi-src.github.io/oneDNN/dev_guide_attributes_post_ops.html
This post-operation can be applied only to 1x1 convolutions and has some additional limitations on post-ops which can be combined with it:
- Currently only supported for 2D 1x1 convolution.
- Only eltwise post-op can be part of post-op chain (i.e., sum post-op is not supported)
- The dst_1x1, wei_dw and dst_dw are assumed to be dnnl_format_tag_any.

Regards,
Igor Safonov

**Comment by nSircombe** [comment]
@igorsafo - what's the issue with `post_ops_ok()`? I've very recently spotted a failure in our downstream CI which appeared with this commit: https://github.com/oneapi-src/oneDNN/commit/822a80201b317fe03093ace8fb3df4d1b4d2c6d5

I'm seeing a failure (which I haven't raised an issue for yet, as I was still looking at it).

```
The following tests FAILED:
	 95 - test_benchdnn_conv_ci_cpu (Failed)
Errors while running CTest
```
...which doesn't appear to have occurred on the recent DroneCI runs (which is confusing!)
And wondered if it might be related?

**Comment by igorsafo** [comment]
Hi @nSircombe , sorry for the late response. The problem is that the commit you mentioned (822a802) breaks check for the first post operation and allows user to pass any post op even if it is not supported by primitive:
```cpp
            for (int idx = 0; idx < po.len(); idx++)
                if (( /* should be an implication if is_sum(idx) then idx == 0 */ is_sum(idx) && idx != 0) && !is_binary(idx)
                        && !is_eltwise(idx))
                    return false;
``` 

The changes are already in the internal repository and will be upstreamed soon within regular PRs merge procedure.

**Comment by nSircombe** [comment]
Hi @igorsafo,

Thanks for the clarification - a quick change to the logic, closer to what was implemented prior to https://github.com/oneapi-src/oneDNN/commit/822a80201b317fe03093ace8fb3df4d1b4d2c6d5 fixes it for me. I'll not worry about it anymore and wait for the fix to get pushed up!

**Comment by nSircombe** [comment]
@igorsafo - just to let you know, it looks like all our downstream CI went green again when we picked up https://github.com/oneapi-src/oneDNN/commit/7779f24c10ae502f50abe52903a2c619dec62c7c 

Cheers,
Nathan.

**Comment by m-ymzk** [comment]
Hi @igorsafo @nSircombe ,
Thanks, I have confirmed that this problem has been resolved on two different servers(Xeon and A64FX).
