### ISSUE TITLE
Vanilla LSTM cell state data type issue

### ISSUE THREAD

**Issue by tkrupa-intel** [oneapi-src/oneDNN#976]
# Summary
The documentation for RNN states that for LSTM, the cell state datatype is always f32 (Implementation details/Data Type Support/table adnotation 1.). However, when running f16 case (third table row), I needed to use an f16 cell state buffer for the results to be correct (when using f32 for cell state and f16 for other buffers, the outputs were mostly NaNs).

# URLs
https://oneapi-src.github.io/oneDNN/dev_guide_rnn.html

# Additional details
N/A

**Comment by mgouicem** [comment]
Hi @tkrupa-intel , are you using RNN on CPU or GPU? As of now, only the GPU engines support fp16. The CPU engines should return `unimplemented` (and it seems that we are currently not checking that).

**Comment by tkrupa-intel** [comment]
Hi @mgouicem,
sorry for not specifying; I've only used it on GPU.

**Comment by mgouicem** [comment]
Thanks @tkrupa-intel . Indeed, on CPU, the cell state is always f32, but on GPU it is f16 for the configuration you mentioned. Will update the doc and adjust pd creation to better reflect that. Thanks!

**Comment by tkrupa-intel** [comment]
Happy to help!
