### ISSUE TITLE
Difference between BAcd16a16b and BAcd16b16a tensor formats

### ISSUE THREAD

**Issue by alexandrelimassantana** [oneapi-src/oneDNN#983]
Hello,

I was wondering what is the difference between weight tensor formats BAcd16**a**16**b** and BAcd16**b**16**a**.
The only difference I could find is that the inner_blk values for the memory descriptor are swapped (from {0,1} to {1,0}).
However, I don't understand how this changes the data organization to the point that it is considered another format tag.
Could someone clarify the difference?

**Comment by igorsafo** [comment]
Hi @alexandrelimassantana ,
The difference between BAcd16a16b and BAcd16b16a is that the innermost 16x16 2D-matrix is transposed in the first case.
For more details about oneDNN memory formats please review the following article: [Understanding Memory Formats](https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html)

Regards,
Igor Safonov

**Comment by alexandrelimassantana** [comment]
I understand, seems a bit obvious after some thinking really :)
Thanks for the comment!
