### ISSUE TITLE
Binary primitive limitation

### ISSUE THREAD

**Issue by tkrupa-intel** [oneapi-src/oneDNN#985]
# Summary
Binary primitive is supposed to support broadcasting primitive for both inputs. However, although it always works with source 1, it only seems to work with source 0 on CPU. This is the conclusion I've come to after trying to run different broadcasting variants with GPU engine. To confirm this, I checked if this can be reproduced in benchdnn and it does - benchdnn output indicates that this case is valid only on CPU. 'Implementation Limitations' section lacks this information.

# URLs
https://oneapi-src.github.io/oneDNN/dev_guide_binary.html
https://github.com/oneapi-src/oneDNN/blob/master/tests/benchdnn/binary/binary.cpp#L170

# Additional details
Benchdnn calls I used to check this and their outputs:
```
benchdnn --binary --mode=c --engine=cpu --sdt=f32:f32 --ddt=f32 --stag=nchw:nchw --alg=MUL 1x3x4x4:2x1x4x4
0:PASSED __REPRO: --binary --stag=nchw:nchw --alg=mul 1x3x4x4:2x1x4x4
tests:1 passed:1 skipped:0 mistrusted:0 unimplemented:0 failed:0 listed:0
```
```
benchdnn --binary --mode=c --engine=gpu --sdt=f32:f32 --ddt=f32 --stag=nchw:nchw --alg=MUL 1x3x4x4:2x1x4x4
0:SKIPPED (INVALID_CASE) __REPRO: --binary --engine=gpu --stag=nchw:nchw --alg=mul 1x3x4x4:2x1x4x4
tests:1 passed:0 skipped:1 mistrusted:0 unimplemented:0 failed:0 listed:0
```

**Comment by vpirogov** [comment]
Thank you for the report, @tkrupa-intel!
