### ISSUE TITLE
NVIDIA gpus support using oneDNN

### ISSUE THREAD

**Issue by uu-praveeng** [oneapi-src/oneDNN#989]
Hi,

Its really great to see the deployment to NVIDIA using oneDNN.
Curious to know the motivation behind adding the cudnn API calls as part of oneDNN. 
Is this  to unify oneDNN library for deploying to multuiplle hardwares. 

Previously our assumption was oneDNN was based mainly for intel based targets.
This is really good stuff that is going in. 

Thanks,
Praveen.

**Comment by vpirogov** [comment]
Hi @uu-praveeng,

Your assumption is correct. oneDNN is a component of [oneAPI](https://www.oneapi.com/), a cross-industry, open, standards-based unified programming model. While the core development team at Intel is focusing on Intel-based harware targets we welcome contributions targeting other platforms in an effort to deliver common developer experience across architectures.
