### ISSUE TITLE
Disable multithreading  while building onednn library for Intel

### ISSUE THREAD

**Issue by uu-praveeng** [oneapi-src/oneDNN#996]
Hi,

Is there a way to disable the multithreading/openmp while building oneDNN library for Intel.?
I see that there is hack mentioned in [issue](https://github.com/oneapi-src/oneDNN/issues/166). 

Can this(DNNL_CPU_RUNTIME) option be extended to take NONE as a value. 
We know that this degrades performance .But, we want to address a customer use case here.

Thanks,
Praveen.

**Comment by uu-praveeng** [comment]
Minor update . I tried passing the option to SEQ. But it got overridden and library is using openmp on linux.

**Comment by igorsafo** [comment]
Hi @uu-praveeng ,
Could you please try to clean your build directory and build oneDNN again?
I tried to reproduce the issue using GCC compiler, but with no success:
```sh
$ (mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DDNNL_CPU_RUNTIME=SEQ .. && make -j)
$ ldd ./build/src/libdnnl.so
        linux-vdso.so.1 =>  (0x00007ffe46b56000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efeaae95000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007efeaac91000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007efeaa988000)
        libm.so.6 => /lib64/libm.so.6 (0x00007efeaa686000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007efeaa470000)
        libc.so.6 => /lib64/libc.so.6 (0x00007efeaa0af000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efeae767000)
```

Regards,
Igor Safonov

**Comment by uu-praveeng** [comment]
Thanks Igor for replying  back quickly. I have used oneDNN 1.4 where I have seen this issue. With the latest one I don't see this issue. 

Thanks,
Praveen.

**Comment by uu-praveeng** [comment]
Could you check with g++ once in linux.

**Comment by igorsafo** [comment]
Sure.

```sh
$ (mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=DEBUG -DDNNL_CPU_RUNTIME=SEQ .. && make -j8)
$ ldd ./build/src/libdnnl.so
        linux-vdso.so.1 =>  (0x00007ffc141a0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff1e0130000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff1dff2c000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff1dfc23000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff1df921000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff1df70b000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff1df34a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff1e25a2000)
```

Is it possible that you have a typo in the build command?

Regards,
Igor Safonov
