### ISSUE TITLE
oneDNN Graph Visual Studio 2019 support

### ISSUE THREAD

**Issue by jeyblu** [oneapi-src/oneDNN#997]
# Summary
Support Visual Studio 2019 as a compiler for oneDNN Graph

# Problem statement
Tried to build oneDNN Graph on Windows 10:

`cmake .. -DDNNL_GRAPH_BUILD_TESTS=1 -DDNNL_GRAPH_BUILD_EXAMPLES=1 -G "Visual Studio 16 2019" -A x64`

Got an error:

CMake Error at CMakeLists.txt:101 (message):
  oneDNN Graph doesn't support MSVC at this moment.

# Preferred solution
Support Visual Studio 2019 as a compiler for oneDNN Graph

**Comment by igorsafo** [comment]
Hi @jeyblu ,
Thank you for your report.

@TaoLv @Jianhui-Li Could you please comment on plans for Visual studio support?

Regards,
Igor Safonov

**Comment by TaoLv** [comment]
Hi @jeyblu, thank you for the issue report. Yes, as stated in the error message, MSVC is not supported by the existing build system of oneDNN Graph. Recently, team is working on the definition of support matrix for different platforms. Will get back to you with the plan if we have any decision.

**Comment by TaoLv** [comment]
MSVC build support has been enabled in 544e60a44428a277211d27d7001c17d8fe76614e.

Build instructions can be found at https://github.com/oneapi-src/oneDNN/blob/dev-graph/doc/build/build.md#windows.
